### PR TITLE
Fix packaging issues for native Debian packages

### PR DESCRIPTION
**Pull request by usaleem-ix**
### Motivation and Context
https://github.com/openzfs/zfs/issues/16513

### Description
Fixes:
https://github.com/openzfs/zfs/issues/15586
https://github.com/openzfs/zfs/issues/15404
https://github.com/openzfs/zfs/issues/14736
https://github.com/openzfs/zfs/issues/15638

### How Has This Been Tested?

- Manually tested by building and installing packages prepared from release tarballs generated via `make dist` and other similar targets.
- Manual invocation `make -j native deb` or `make -j native-deb-utils native-deb-kmod` does not break.
- zfs-zed.service runs correctly after installing the package.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by satmandu** [comment]
Would it make sense to synchonize with what debian uses downstream?

i.e., https://salsa.debian.org/zfsonlinux-team/zfs/-/tree/master/debian?ref_type=heads

**Comment by usaleem-ix** [comment]
> Would it make sense to synchronize with what Debian uses downstream?
> 
> i.e., https://salsa.debian.org/zfsonlinux-team/zfs/-/tree/master/debian?ref_type=heads

This can be a topic of another PR, since it would require more testing and would take some time to validate all the bits. The purpose of this PR is to fix packaging issues that are currently open. Hopefully, before zfs-2.3 branch out.

**Comment by behlendorf** [comment]
Thanks for fixing up these issues with the packaging for everyone.  I'll pull them in once the CI looks good and let you know if I see any other reports of problems.

**Review by behlendorf — APPROVED** [review]

**Comment by behlendorf** [comment]
Merged as:

45addf7605 Update path for zed in zfs-zed.service for native debian packages
cc9e36a42e Disable parallel build for native-deb* targets
c204c3f340 Fix missing packaging files from release tarballs

**Pull request closed without merging**
