### PR TITLE
Fix memory allocation for the checksum benchmark - variant 2

### PR DESCRIPTION
**Pull request by mcmilk**
Allocation via kmem_cache_alloc() is limited to less the 4m for
some architectures.

This commit limits the benchmarks to 1m on 32bit architectures and
adds 4m + 16m benchmarks to the 64bit ones.

Signed-off-by: Tino Reichardt <milky-zfs@mcmilk.de>
Fixes: #13669

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by amotin — APPROVED** [review]

**Comment by mcmilk** [comment]
> You don't need to drop the column from results in comment in this case.

Yes, I just noticed... I will re-add... ;)

**Comment by mcmilk** [comment]
@BrainSlayer mentions that 16m will fail on some 64bit archs... so this one must be changed, when we want 4m and 16m to be benchmarked also. Does it make sense to investigate more work on this... or is PR `variant 1` okay?

**Comment by amotin** [comment]
To me any variant is OK, but as I've written I'd prefer to know the limitations.  ZFS already assumes 16MB maximum recordsize/volblocksize, and if it is not realistic, it should probably corrected/documented.

**Comment by BrainSlayer** [comment]
i have a better solution. use adb_alloc instead of adb_alloc_linear. it will just work fine for insane allocation sizes on any platform

**Comment by mcmilk** [comment]
> i have a better solution. use adb_alloc instead of adb_alloc_linear. it will just work fine for insane allocation sizes on any platform

okay, I will do so...

**Comment by mcmilk** [comment]
This one can be closed, I have updated the PR #13670

**Pull request closed without merging**
