### PR TITLE
Linux 5.15 compat: standalone <linux/stdarg.h>

### PR DESCRIPTION
**Pull request by solbjorn**
### Motivation and Context
Commits

```
39f75da7bcc8 ("isystem: trim/fixup stdarg.h and other headers")
c0891ac15f04 ("isystem: ship and use stdarg.h")
564f963eabd1 ("isystem: delete global -isystem compile option")
```

(for now can be found in linux-next.git tree, will land into the Linus' tree during the ongoing 5.15 cycle with one of akpm merges)

removed the -isystem flag and disallowed the inclusion of any compiler header files. They also introduced a minimal <linux/stdarg.h> as a replacement for <stdarg.h>.
include/os/linux/spl/sys/cmn_err.h in the ZFS source tree includes <stdarg.h> unconditionally. Introduce a test for <linux/stdarg.h> and include it instead of the compiler's one to prevent module build breakage.

### How Has This Been Tested?
A configuration and then build of ZFS module were run, for a kernel tree containing changes from the mentioned commits.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
@ckane would you mind taking a look at this too.

**Review by tonynguien — APPROVED** [review]
Looks good to me.

**Comment by solbjorn** [comment]
Could someone please explain what "indirect subtype changes" is?

**Comment by behlendorf** [comment]
That's an unrelated infrastructure change on our part.  You should be able to resolve it be rebasing on the latest master source and then force updating the PR.

**Comment by solbjorn** [comment]
It's up to date with the master currently. I took a look on the functions and seems CheckABI doesn't like that `va_list` may be altered depending on which stdarg.h (compiler's one or shipped with the kernel) is used. Still unclear for me as CheckABI tests only userspace part while this PR's code is guarded with `_KERNEL`.

**Comment by behlendorf** [comment]
@solbjorn it looks like this PR is just a few commits behind the master branch.  The critical commits missing were from the #12529 PR which effectively bumped the minimum version of libabigail required and generated new ABI reference file for that version.  After I rebased this PR locally on to those changes it resolved the CheckABI failure as expected.  If you can rebase this PR on to at least 3eb3e4d14cf008045b79afbbe9d24812d56917be from the master branch that should sort it out.

**Comment by solbjorn** [comment]
Ah, forgot to fetch master to my fork, sorry. All is fine now, thanks!

**Pull request merged**
