### PR TITLE
FreeBSD: use zero_region instead of allocating a dedicated page

### PR DESCRIPTION
**Pull request by mjguzik**
Signed-off-by: Mateusz Guzik <mjguzik@gmail.com>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by amotin — APPROVED** [review]
Makes sense after the chunk size was fixed to PAGE_SIZE.  I was thinking whether it still worth accounting that page in statistics, since the page is not allocated, but I see Linux does the same, so I'm fine with it.

@mjguzik You could ask for the review before committing it to FreeBSD. ;)

**Review by amotin — COMMENTED** [review]
Linux actually has two versions of abd_alloc_zero_scatter() -- one for kernel and one for user-space. I guess this version won't build in user-space.

**Comment by bwatkinson** [comment]
> Linux actually has two versions of abd_alloc_zero_scatter() -- one for kernel and one for user-space. I guess this version won't build in user-space.

This does seem pretty reasonable to me, but @amotin brings up a good point. Would this work with user-space as well? The reason we have both kernel and user-space versions of this in Linux is because `abd_get_zeros()` is called in `vdev_queue_aggregate()` for constructing gang ABDs.

**Comment by behlendorf** [comment]
Currently we always use the Linux version when building in user space.  So at least for the moment this not working in user space shouldn't be a problem.

**Review by behlendorf — APPROVED** [review]

**Review by bwatkinson — APPROVED** [review]

**Review by bwatkinson — APPROVED** [review]

**Pull request merged**
