### PR TITLE
module: zstd: check we don't leak symbols; regenerate symbol map

### LINKED ISSUE #12988: multiple definition of `HIST_isError' compiling against linux-5.16.1-gentoo kernel
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	|  Gentoo Base System release 2.8
Kernel Version	|  linux-5.16.1-gentoo
Architecture	| x86_64
OpenZFS Version	| HEAD

### Describe the problem you're observing
Compiling zfs HEAD inline against linux-5.16.1-gentoo gives the following build fail on make:
```bash
... SNIP ...
  AR      fs/zfs/zfs/built-in.a
  AR      fs/zfs/built-in.a
  AR      net/netfilter/built-in.a
  AR      fs/built-in.a
  AR      net/built-in.a
  AR      drivers/md/built-in.a
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
ld: lib/zstd/compress/hist.o: in function `ERR_isError':
/usr/src/linux/lib/zstd/compress/../common/error_private.h:45: multiple definition of `HIST_isError'; fs/zfs/zstd/lib/zstd.o:/usr/src/linux/fs/zfs/zstd/lib/zstd.c:8103: first defined here
make: *** [Makefile:1161: vmlinux] Error 1
```

### Describe how to reproduce the problem
ZFS build script located at:
* https://gist.github.com/thehaven/6946427

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
#12988

### Description
This both (a) fixes #12988 and (b) ensures we'll actually catch errors like these on CI in future.

CC: @rincebrain 

### How Has This Been Tested?
Builds. The new generated compat wrapper included. I reverted it for verification in this checkstyle job: https://github.com/nabijaczleweli/zfs/runs/5528159177?check_suite_focus=true#step:5:34

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by rincebrain — APPROVED** [review]

**Comment by behlendorf** [comment]
When testing this locally, I got a slightly different ordering of the `#define`'s in `zstd_compat_wrapper.h` when regenerating.  Of course that's not an issue, but just for reference here's the diff from generating on a RHEL 8.5 system.

```diff
diff --git a/module/zstd/include/zstd_compat_wrapper.h b/module/zstd/include/zstd_compat_wrapper.h
index 4f81e1c59..ae762f043 100644
--- a/module/zstd/include/zstd_compat_wrapper.h
+++ b/module/zstd/include/zstd_compat_wrapper.h
@@ -172,8 +172,8 @@
 #define        ZSTD_CCtxParams_init zfs_ZSTD_CCtxParams_init
 #define        ZSTD_CCtxParams_init_advanced zfs_ZSTD_CCtxParams_init_advanced
 #define        ZSTD_cParam_getBounds zfs_ZSTD_cParam_getBounds
-#define        ZSTD_CCtxParams_setParameter zfs_ZSTD_CCtxParams_setParameter
 #define        ZSTD_CCtx_setParameter zfs_ZSTD_CCtx_setParameter
+#define        ZSTD_CCtxParams_setParameter zfs_ZSTD_CCtxParams_setParameter
 #define        ZSTD_CCtx_getParameter zfs_ZSTD_CCtx_getParameter
 #define        ZSTD_CCtxParams_getParameter zfs_ZSTD_CCtxParams_getParameter
 #define        ZSTD_CCtx_setParametersUsingCCtxParams zfs_ZSTD_CCtx_setParametersUsingCCtxParams
@@ -219,13 +219,13 @@
 #define        ZSTD_getSequences zfs_ZSTD_getSequences
 #define        ZSTD_createCDict_byReference zfs_ZSTD_createCDict_byReference
 #define        ZSTD_createCDict zfs_ZSTD_createCDict
-#define        ZSTD_compress zfs_ZSTD_compress
 #define        ZSTD_CCtx_refCDict zfs_ZSTD_CCtx_refCDict
-#define        ZSTD_CCtx_refPrefix zfs_ZSTD_CCtx_refPrefix
 #define        ZSTD_CCtx_refPrefix_advanced zfs_ZSTD_CCtx_refPrefix_advanced
+#define        ZSTD_CCtx_refPrefix zfs_ZSTD_CCtx_refPrefix
 #define        ZSTD_CCtx_loadDictionary_byReference zfs_ZSTD_CCtx_loadDictionary_byReference
-#define        ZSTD_freeCCtx zfs_ZSTD_freeCCtx
 #define        ZSTD_CCtx_loadDictionary zfs_ZSTD_CCtx_loadDictionary
+#define        ZSTD_freeCCtx zfs_ZSTD_freeCCtx
+#define        ZSTD_compress zfs_ZSTD_compress
 #define        ZSTD_CCtx_loadDictionary_advanced zfs_ZSTD_CCtx_loadDictionary_advanced
 #define        ZSTD_createCCtx zfs_ZSTD_createCCtx
 #define        ZSTD_createCCtx_advanced zfs_ZSTD_createCCtx_advanced
@@ -308,8 +308,8 @@
 #define        ZSTD_compressBlock_btultra_extDict zfs_ZSTD_compressBlock_btultra_extDict
 
 /* lib/decompress/huf_decompress.o: */
-#define        HUF_readDTableX1_wksp zfs_HUF_readDTableX1_wksp
 #define        HUF_decompress4X1 zfs_HUF_decompress4X1
+#define        HUF_readDTableX1_wksp zfs_HUF_readDTableX1_wksp
 #define        HUF_readDTableX1 zfs_HUF_readDTableX1
 #define        HUF_decompress1X1_usingDTable zfs_HUF_decompress1X1_usingDTable
 #define        HUF_decompress1X1_DCtx_wksp zfs_HUF_decompress1X1_DCtx_wksp
@@ -379,10 +379,10 @@
 #define        ZSTD_loadDEntropy zfs_ZSTD_loadDEntropy
 #define        ZSTD_decompressBegin zfs_ZSTD_decompressBegin
 #define        ZSTD_decompressBegin_usingDict zfs_ZSTD_decompressBegin_usingDict
-#define        ZSTD_decompressBegin_usingDDict zfs_ZSTD_decompressBegin_usingDDict
 #define        ZSTD_decompress_usingDict zfs_ZSTD_decompress_usingDict
 #define        ZSTD_decompressDCtx zfs_ZSTD_decompressDCtx
 #define        ZSTD_decompress zfs_ZSTD_decompress
+#define        ZSTD_decompressBegin_usingDDict zfs_ZSTD_decompressBegin_usingDDict
 #define        ZSTD_getDictID_fromDict zfs_ZSTD_getDictID_fromDict
 #define        ZSTD_getDictID_fromFrame zfs_ZSTD_getDictID_fromFrame
 #define        ZSTD_decompress_usingDDict zfs_ZSTD_decompress_usingDDict
```

**Comment by nabijaczleweli** [comment]
Fair cop, made `gensymbols` sort symbols for each file, so it should be idempotent now.

**Comment by nabijaczleweli** [comment]
Fair cop, made `gensymbols` sort symbols for each file, so it should be idempotent now.

**Comment by Ornias1993** [comment]
> ### Motivation and Context
> #12988
> 
> ### Description
> This both (a) fixes #12988 and (b) ensures we'll actually catch errors like these on CI in future.
> 
> CC: @rincebrain
> 
> ### How Has This Been Tested?
> Builds. The new generated compat wrapper included. I reverted it for verification in this checkstyle job: https://github.com/nabijaczleweli/zfs/runs/5528159177?check_suite_focus=true#step:5:34
> 
> ### Types of changes
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Performance enhancement (non-breaking change which improves efficiency)
> * [x]  Code cleanup (non-breaking change which makes code smaller or more readable)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> * [ ]  Library ABI change (libzfs, libzfs_core, libnvpair, libuutil and libzfsbootenv)
> * [ ]  Documentation (a change to man pages or other documentation)
> 
> ### Checklist:
> * [x]  My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
> * [x]  I have updated the documentation accordingly.
> * [x]  I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
> * [x]  I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
> * [ ]  I have run the ZFS Test Suite with this change applied. – CI take my hand
> * [x]  All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

As a note, it might be handy to also CC @BrainSlayer (that other brain), as he made this code back-in-the-day ;-)

**Comment by BrainSlayer** [comment]
@Ornias1993 thx for info. i already discovered this feature and used it in my git tree for more recent zstd revisions

**Pull request merged**
