### PR TITLE
Fix zdb_dump_block for little endian

### PR DESCRIPTION
**Pull request by tuxoko**
### Motivation and Context

The endian macros were changed but zdb_dump_block wasn't updated accordingly.

### How Has This Been Tested?

Before the change
```
$ sudo zdb -R pp 0:20000c000:200
Found vdev: /dev/sdb1

0:20000c000:200
          0 1 2 3 4 5 6 7   8 9 a b c d e f  0123456789abcdef
000000:  00cc0403002f505a  0000000000000101  ZP/.............
```
After the change
```
$ sudo zdb -R pp 0:20000c000:200
Found vdev: /dev/sdb1

0:20000c000:200
          0 1 2 3 4 5 6 7   8 9 a b c d e f  0123456789abcdef
000000:  5a502f000304cc00  0101000000000000  ZP/.............
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by tonyhutter — APPROVED** [review]

**Review by mcmilk — APPROVED** [review]

**Comment by mcmilk** [comment]
Maybe we can remove one of the two newlines in the beginning of the function also?

```
diff --git a/cmd/zdb/zdb.c b/cmd/zdb/zdb.c
index 0d2f0b1da..c79be1f9f 100644
--- a/cmd/zdb/zdb.c
+++ b/cmd/zdb/zdb.c
@@ -8328,7 +8328,6 @@ zdb_dump_block(char *label, void *buf, uint64_t size, int flags)
        const char *hdr;
        char *c;
 
-
        if (do_bswap)
                hdr = " 7 6 5 4 3 2 1 0   f e d c b a 9 8";
        else

```

**Comment by tuxoko** [comment]
> Maybe we can remove one of the two newlines in the beginning of the function also?

You mean the hdr? But that is need to indicate the byte sequence in case you do byte swap.

**Comment by mcmilk** [comment]
> char *c;

No, the double newline right after variable declaration: `char *c;\n\n`. It's just a small cosmetic change - there is no real need for it.

**Comment by tonyhutter** [comment]
@mcmilk we can probably fix those in a separate cleanup PR.  My guess is that there are other minor cleanups we could include as well.  I think this PR is ready to go as-is, and I'll pull it in tomorrow unless I hear otherwise.

**Review by allanjude — APPROVED** [review]

**Pull request merged**
