### PR TITLE
zfs-2.1.12 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Support 6.3 kernel + other fixes

### Description
Proposed patchset for zfs-2.1.12 release

### How Has This Been Tested?
Buildbot will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rincebrain** [comment]
Suggest #14924 and whatever we decide about #14931 so that the CI stops panicking on every FBSD run for 2.1?

**Comment by behlendorf** [comment]
@tonyhutter I've merged https://github.com/openzfs/zfs/pull/14924 in to the staging branch can you apply it to this PR as well.

**Comment by tonyhutter** [comment]
Thanks https://github.com/openzfs/zfs/pull/14924 is in my latest push.  We'll keep an eye on https://github.com/openzfs/zfs/pull/14931

**Comment by tonyhutter** [comment]
Released: https://github.com/openzfs/zfs/releases/tag/zfs-2.1.12

**Pull request merged**
