### PR TITLE
ZTS: Remove bashisms from zfs-tests.sh

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

Avoid a build dependency on bash.

### Description

Convert zfs-tests.sh to /bin/sh.

### How Has This Been Tested?

Tested running a particular tag with -T, full ZTS runs in CI

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This doesn't seem to be a good idea. On top of drastically reworking how this script works (the elimination of ranged loops, etc.), this code looks significantly uglier. Is there a compelling reason to do this, given that Bash is available everywhere in some form?

**Comment by freqlabs** [comment]
@Conan-Kudo are you referring to the loop over $SINGLETEST? I don't understand why that was even a loop in the first place.

**Comment by freqlabs** [comment]
I have the shellcheck fixes staged to push once a full test run completes, and I'll address any test regressions on Linux then, too.

**Comment by freqlabs** [comment]
* Fix checkstyle and a few nits

**Pull request merged**
