### PR TITLE
[dracut] Add inclusion of user overrides to zfs-dracut module

### PR DESCRIPTION
**Pull request by techhazard**
### Motivation and Context

https://github.com/openzfs/zfs/issues/14075

### How Has This Been Tested?

I have not yet tested this

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by techhazard** [comment]
In my current debian version, the bash script is a bit different, but I did test including the override and it worked!
In the original debian version, in the systemd section it looks like this:
```sh
                for _item in scan cache ; do
                        dracut_install /lib/systemd/system/zfs-import-$_item.service

                        if ! [ -L "${initdir}/$systemdsystemunitdir/zfs-import.target.wants"/zfs-import-$_item.service ]; then
                                ln -s ../zfs-import-$_item.service "${initdir}/$systemdsystemunitdir/zfs-import.target.wants"/zfs-import-$_item.service
                                type mark_hostonly >/dev/null 2>&1 && mark_hostonly /lib/systemd/system/zfs-import-$_item.service
                        fi
                done
```
And I changed it to this:
```sh
                for _item in scan cache ; do
                        dracut_install /lib/systemd/system/zfs-import-$_item.service

                        for _override in /etc/systemd/system/zfs-import-${_item}.service.d/*.conf; do
                                dracut_install "${_override}"
                       done

                        if ! [ -L "${initdir}/$systemdsystemunitdir/zfs-import.target.wants"/zfs-import-$_item.service ]; then
                                ln -s ../zfs-import-$_item.service "${initdir}/$systemdsystemunitdir/zfs-import.target.wants"/zfs-import-$_item.service
                                type mark_hostonly >/dev/null 2>&1 && mark_hostonly /lib/systemd/system/zfs-import-$_item.service
                        fi
                done
```
This included my file of `/etc/systemd/system/zfs-import-scan.service.d/override.conf` and the zfs-import-scan now has a timeout of 15min :slightly_smiling_face:

**Review by behlendorf — APPROVED** [review]

**Comment by behlendorf** [comment]
@techhazard could you please update this and include you `signed-off-by` in the commit messages.  Then it should be good to go.

https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by

**Comment by techhazard** [comment]
I added `Signed-off-by:` for all 3 commits :slightly_smiling_face:

**Comment by techhazard** [comment]
Awesome thanks!

**Pull request closed without merging**
