### PR TITLE
[WIP] Add JSON output to zpool status

### PR DESCRIPTION
**Pull request by ofaaland**
### Motivation and Context

Add a new option j to the zpool status command to cause json dump of pool status to stdout.  This eases integration with external tools which use the zpool utility to monitor pool status.

### Description

When dumping the nvlist describing pool status, use the json nvlist dumper which was introduced to support channel programs.

TODO: add a test to use the option and verifies it's valid JSON.

### How Has This Been Tested?

Tested as part of an external patch set.  Needs more testing.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ahrens** [comment]
I think we would need to create a more well-defined nvlist/json schema, instead of using the config nvlist.

**Comment by colttt** [comment]
any news about that? it would be very nice to have something like that, because json is readable by mostly all monitoring systems:
```
{
  "pool": "nc_storage",
  "state": "ONLINE",
  "status": "",
  "action": "",
  "scan": "scrub repaired 0B in 10h51m with 0 errors on Sun Aug 14 11:15:29 2022",
  "scrub": "",
  "errors": "",
  "config": [
    {
      "Name": "nc_storage",
      "state": "ONLINE",
      "read": 0,
      "write": 0,
      "cksum": 0,
      "RAID-Type": [
        {
          "Name": "mirror-0",
          "state": "ONLINE",
          "read": 0,
          "write": 0,
          "cksum": 0,
          "DISKS": [
            {
              "Name": "j1d03-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            },
            {
              "Name": "j2d03-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            }
          ]
        },
        {
          "Name": "mirror-1",
          "state": "ONLINE",
          "read": 0,
          "write": 0,
          "cksum": 0,
          "DISKS": [
            {
              "Name": "j1d04-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            },
            {
              "Name": "j2d04-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            }
          ]
        },
        {
          "Name": "mirror-2",
          "state": "ONLINE",
          "read": 0,
          "write": 0,
          "cksum": 0,
          "DISKS": [
            {
              "Name": "j1d05-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            },
            {
              "Name": "j2d05-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            }
          ]
        },
        {
          "Name": "mirror-3",
          "state": "ONLINE",
          "read": 0,
          "write": 0,
          "cksum": 0,
          "DISKS": [
            {
              "Name": "j1d06-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            },
            {
              "Name": "j2d06-hdd",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            }
          ]
        }
      ]
    },
    {
      "Name": "logs",
      "state": "ONLINE",
      "read": 0,
      "write": 0,
      "cksum": 0,
      "RAID-Type": [
        {
          "Name": "mirror-9",
          "state": "ONLINE",
          "read": 0,
          "write": 0,
          "cksum": 0,
          "DISKS": [
            {
              "Name": "j1d00-ssd ",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            },
            {
              "Name": "j2d00-ssd ",
              "state": "ONLINE",
              "read": 0,
              "write": 0,
              "cksum": 0
            }
          ]
        }
      ]
    },
    {
      "Name": "cache",
      "state": "ONLINE",
      "read": 0,
      "write": 0,
      "cksum": 0,
      "DISKS": [
        {
          "Name": "j1d00-ssd ",
          "state": "ONLINE",
          "read": 0,
          "write": 0,
          "cksum": 0
        },
        {
          "Name": "j2d00-ssd ",
          "state": "ONLINE",
          "read": 0,
          "write": 0,
          "cksum": 0
        }
      ]
    }
  ]
}
```

**Comment by ofaaland** [comment]
@colttt no, I do not expect to have time to work on this.  I should close this PR.

**Comment by dvaerum** [comment]
I would love to see this argument implemented for `zpool import` too, to list all the not import pools in a json structure :grinning:

**Comment by colttt** [comment]
If you can't wait: https://github.com/kellyjonbrazil/jc has zpool status support

**Pull request closed without merging**
