### PR TITLE
Implement secpolicy_* functions

### PR DESCRIPTION
**Pull request by behlendorf**
Based on Linux POSIX style capabilities.

Signed-off-by: Brian Behlendorf behlendorf1@llnl.gov
Signed-off-by: Massimo Maggimassimo@mmmm.it

### CODE REVIEW

**Comment by FransUrbo** [comment]
@maxximino @behlendorf Is there any progress on this? Combining this PR with maxximino/zfs@b2f0012 and maxximino/zfs@f3ddf21, is this enough to get this going?

**Comment by ilovezfs** [comment]
FYI, I have implemented a simple version of this for OpenZFS on OS X. It checks for root privileges in the important cases, and otherwise allows read access:
https://github.com/openzfsonosx/spl/pull/7

This will be merged to master within the next couple days.

**Comment by behlendorf** [comment]
@ilovezfs interesting!  Thanks for pointing us to your implementation.

**Comment by maxximino** [comment]
@FransUrbo That was initially created for a Posix ACL implementation with NFSv4 on-disk format, which has been set aside for the current way (linux-specific encoding of the Posix ACL stored as xattr, exactly the same encoding used in all other linux filesystems). I think it can be useful also to implement delegation, should not be a huge effort. About namespaces/containers, I am not familiar enough with internals of UID namespaces to say something useful about that. About continuing this pull request, I would be really happy if someone does, but for the moment I can't. When I was working on Posix ACL, I hadn't hit problems due to this specific PR, but requires very diligent testing before merging: the worst possible outcome here is not a simple crash, but allowing operations / data access that should not be allowed.

**Pull request closed without merging**
