### PR TITLE
Remove pool io kstats

### PR DESCRIPTION
**Pull request by amotin**
This mostly reverts "3537 want pool io kstats" commit of 8 years ago.

From one side this code using pool-wide locks became pretty bad for
performance, creating significant lock contention in I/O pipeline.
From another, there are more efficient ways now to obtain detailed
statistics, while this statistics is illumos-specific and much less
usable on Linux and FreeBSD, reported only via procfs/sysctls.

This commit does not remove KSTAT_TYPE_IO implementation, that may
be removed later together with already unused KSTAT_TYPE_INTR and
KSTAT_TYPE_TIMER.

Closes: #12121

### How Has This Been Tested?
On 40-thread FreeBSD system heavy uncached 4KB reads from 8 ZVOLs show dramatic reduction of time spent on vdev queues locks.  Time spent inside vdev_queue_*() reduced from 8.7% to 2.7%.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by behlendorf — APPROVED** [review]

**Comment by behlendorf** [comment]
Re-opening, I accidentally referenced the wrong PR (this one) when merging an unrelated change.

**Review by ahrens — APPROVED** [review]

**Comment by amotin** [comment]
@snajpa There is per-disk statistics on each OS. There is `zpool iostat`. May be the numbers of `zpool iostat` can be fetched somehow directly, but I haven't looked.  But per-pool statistics summing _all_ vdevs in a way it was implemented was both inefficient in collecting and pretty useless in case of any special vdevs present, since all it can tell is "there is some activity".

**Comment by allanjude** [comment]
> @amotin "there are more efficient ways now to obtain detailed statistics" ... such as, please?
> 
> The only one I can think of involves executing a binary (zpool iostat) and either leaving it running and parsing its output, or launching it over and over again. Where can I find the said more efficient way to access pool io stats?
> 
> Thanks! :)

Sorry to bring up an old thread, but with the vdev properties feature that got merged last year, you can get these raw counters via `zpool get <counters> $pool $vdev`
It has both bytes and iops read/write etc.

**Comment by AceSlash** [comment]
@allanjude : the feature you are talking about is not yet available on ZFS 2.1. So for ZFS 2.1 we have no more file with the io and no way to get them from ZFS.

I don't know, is it just me or should this feature not be removed until there is a working replacement? This breaks monitoring tools.

**Pull request merged**
