### PR TITLE
zfs-2.1.3 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed zfs-2.1.3 patchset.

### Description
Mostly kernel fixes

### How Has This Been Tested?
Awaiting buildbot results

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by jumbi77** [comment]
- Can we get the newest [zed.d](https://github.com/openzfs/zfs/tree/master/cmd/zed/zed.d) scripts from master to 2.1.3? I noticed for. e.g. that pushover notification, which are in master for quite a while, is not available in 2.1.x
- Can we get [this](https://github.com/openzfs/zfs/pull/12333) in 2.1.3 if possible?

Thanks!

**Comment by tonyhutter** [comment]
@jumbi77 I just pushed some more zed fixes that merged cleanly.  Hopefully all the ones you were looking for are in now.  

I don't think we'll include #12333 in zfs-2.1.3 since we want point releases to be mostly bugfixes and low-risk changes.   #12333 modifies the raidz internals, so it's higher risk.

**Comment by jumbi77** [comment]
> @jumbi77 I just pushed some more zed fixes that merged cleanly. Hopefully all the ones you were looking for are in now.

Thanks for the quick answers.
I should have been more specific regarding ZED, sorry my bad:

- [https://github.com/openzfs/zfs/commit/da124ad8ec1b3b0f18057a6b0ff3160ca6053800#diff-1cc5ce3ba961a27d68399544f4c915368b91fd3bf695048a454a0341801cd11d](url)

- [https://github.com/openzfs/zfs/commit/fd778e44c88fd3215c8a7f5ec4989431ac02cd32#diff-1cc5ce3ba961a27d68399544f4c915368b91fd3bf695048a454a0341801cd11d](url)

BTW if I check the commit history of [zed](https://github.com/openzfs/zfs/commits/master/cmd/zed) there a quite some commits not in 2.1, just to name a few which might be relevant/bug fixes?
- [https://github.com/openzfs/zfs/commit/cf0a6dd3ede987212cad7f7c0afed64e54bd9975#diff-1cc5ce3ba961a27d68399544f4c915368b91fd3bf695048a454a0341801cd11d](url)
- [https://github.com/openzfs/zfs/commit/cfc564f9b11eed1421789fa018f7b3d141cc18d0#diff-1cc5ce3ba961a27d68399544f4c915368b91fd3bf695048a454a0341801cd11d](url)
- [https://github.com/openzfs/zfs/commit/5a54a4e0517959dd917c0f78d692f7364e597a68#diff-1cc5ce3ba961a27d68399544f4c915368b91fd3bf695048a454a0341801cd11d](url)
- [https://github.com/openzfs/zfs/commit/73218f41b4413ec75a5d877771a03ab98e8fb3c3#diff-1cc5ce3ba961a27d68399544f4c915368b91fd3bf695048a454a0341801cd11d](url)
- [https://github.com/openzfs/zfs/commit/38280c3526845852c4da09fd0c11090493ee58fb#diff-1cc5ce3ba961a27d68399544f4c915368b91fd3bf695048a454a0341801cd11d](url)
- And "a lot more commits" by @ nabijaczleweli

> I don't think we'll include #12333 in zfs-2.1.3 since we want point releases to be mostly bugfixes and low-risk changes. #12333 modifies the raidz internals, so it's higher risk.

Got it, thanks.

**Comment by jumbi77** [comment]
> @jumbi77 I just pushed some more zed fixes that merged cleanly. Hopefully all the ones you were looking for are in now.

Thanks for the quick answers.I should have been more specific regarding my commits, sorry my bad:

- [https://github.com/openzfs/zfs/commit/da124ad8ec1b3b0f18057a6b0ff3160ca6053800](https://github.com/openzfs/zfs/commit/da124ad8ec1b3b0f18057a6b0ff3160ca6053800)

- [https://github.com/openzfs/zfs/commit/fd778e44c88fd3215c8a7f5ec4989431ac02cd32](https://github.com/openzfs/zfs/commit/fd778e44c88fd3215c8a7f5ec4989431ac02cd32)

BTW if I check the commit history of [zed](https://github.com/openzfs/zfs/commits/master/cmd/zed) there a quite some commits not in 2.1, just to name a few which might be relevant/bug fixes?
- [https://github.com/openzfs/zfs/commit/cf0a6dd3ede987212cad7f7c0afed64e54bd9975](https://github.com/openzfs/zfs/commit/cf0a6dd3ede987212cad7f7c0afed64e54bd9975)
- [https://github.com/openzfs/zfs/commit/cfc564f9b11eed1421789fa018f7b3d141cc18d0](https://github.com/openzfs/zfs/commit/cfc564f9b11eed1421789fa018f7b3d141cc18d0)
- [https://github.com/openzfs/zfs/commit/5a54a4e0517959dd917c0f78d692f7364e597a68](https://github.com/openzfs/zfs/commit/5a54a4e0517959dd917c0f78d692f7364e597a68)
- [https://github.com/openzfs/zfs/commit/73218f41b4413ec75a5d877771a03ab98e8fb3c3](https://github.com/openzfs/zfs/commit/73218f41b4413ec75a5d877771a03ab98e8fb3c3)
- [https://github.com/openzfs/zfs/commit/38280c3526845852c4da09fd0c11090493ee58fb](https://github.com/openzfs/zfs/commit/38280c3526845852c4da09fd0c11090493ee58fb)
- And "a lot more commits" by @ nabijaczleweli

> I don't think we'll include #12333 in zfs-2.1.3 since we want point releases to be mostly bugfixes and low-risk changes. #12333 modifies the raidz internals, so it's higher risk.

Got it, thanks.

**Comment by tonyhutter** [comment]
@jumbi77  Question - are you checking the commit hashes or the commit subject lines?  I ask, because you mentioned https://github.com/openzfs/zfs/commit/cfc564f9b11eed1421789fa018f7b3d141cc18d0 wasn't in 2.1, but it was included in 2.1.1 as d6c2b89.

**Comment by nabijaczleweli** [comment]
Please pull in 3a661613dff54d363c603aceaed80ecafb3d4f68 (#12870), too, it's been showing up on sid since decemberish.

**Comment by jumbi77** [comment]
> @jumbi77 Question - are you checking the commit hashes or the commit subject lines? I ask, because you mentioned [cfc564f](https://github.com/openzfs/zfs/commit/cfc564f9b11eed1421789fa018f7b3d141cc18d0) wasn't in 2.1, but it was included in 2.1.1 as [d6c2b89](https://github.com/openzfs/zfs/commit/d6c2b89032bef566187a0498200cc32b8366b403).

Yes, my bad. I just compared commits on master branch with 2.1.3-staging and the referenced commit got into master much earlier (on Jun 30, 2021) than in 2.1.3-stagigung (on Sep 14, 2021), so I overlook them, sorry.

**Comment by tonyhutter** [comment]
@nabijaczleweli I included https://github.com/openzfs/zfs/commit/3a661613dff54d363c603aceaed80ecafb3d4f68 in my latest push (along with a boatload of other commits).

**Comment by tonyhutter** [comment]
Looks like all the bots are failing:
```
    FAIL cli_root/zfs_load-key/zfs_load-key_all (expected PASS)
    FAIL cli_root/zfs_load-key/zfs_load-key_https (expected PASS)
    FAIL cli_root/zfs_load-key/zfs_load-key_location (expected PASS)
    FAIL cli_root/zfs_load-key/zfs_load-key_recursive (expected PASS)
```
I'm guessing I botched something while backporting f33f12175.  Let me look into it

**Comment by gamanakis** [comment]
May I propose #13074 (one line fix) and possibly #13098?

**Comment by szubersk** [comment]
@tonyhutter please consider including 72f3c8b13019b8882f4536411e42734fd3b4a4d7 as it fixes compilation issues in various Linux distros

**Comment by tonyhutter** [comment]
@gamanakis @szubersk I just included them in my latest push.

**Comment by satmandu** [comment]
Any chance of getting this added as well? https://github.com/openzfs/zfs/pull/12714 (I'm seeing the issue the patch claims to address on a laptop after resumes from suspend running 2.1.2+ patches for kernel 5.17.)

**Comment by stuartthebruce** [comment]
Any estimate on the release date for this?

**Comment by gamanakis** [comment]
We should probably also include 82226e4, minor fix in `zstream dump`, related to PR #13014.

**Comment by tonyhutter** [comment]
@satmandu @gamanakis I included those in my latest push.
@stuartthebruce I think we have all the commits for the release now.  Once the release is passing the test suite, then it should be good to go.  Hopefully there's no oddball test failures we have to deal with.

**Comment by tonyhutter** [comment]
There seems to be some unexpected checksum errors that are causing a number of the FreeBSD test to fail:
```
    FAIL redundancy/redundancy_draid (expected PASS)
    FAIL redundancy/redundancy_draid_damaged (expected PASS)
    FAIL redundancy/redundancy_draid_spare1 (expected PASS)
    FAIL redundancy/redundancy_draid_spare2 (expected PASS)
    FAIL redundancy/redundancy_draid_spare3 (expected PASS)
    FAIL replacement/replace_rebuild (expected PASS)
    FAIL replacement/replace_resilver (expected PASS)
```
I'm going to look into those..

**Comment by freqlabs** [comment]
For deadman_sync: 72f06d01b555503245b45690ec645d4bfc43c939

**Comment by tonyhutter** [comment]
@freqlabs thanks, included in my latest push

**Comment by freqlabs** [comment]
It's odd that inheritance/inherit_001_pos failing on FreeBSD was considered unexpected. It's on the maybe list to fail for FreeBSD.

**Comment by behlendorf** [comment]
@freqlabs I'm not sure I follow.  I don't have the test run link handy anymore, but what I recall from the log was the `inheritance/inherit_001_pos` test failed, was then retried because it was in the "maybe" list, but the retry also failed.  Aside from the test failing twice in a row, it seems to me the test suite itself handled this right.

**Comment by jaen** [comment]
Correct me if I'm wrong, but is this release supposed to still not be compatible with kernels newer than 5.15, despite all the fixes cherry-picked into this branch? At least I don't see anything that bumps the relevant field in the metadata file. Does this mean that we'll have to wait another couple months before being able to use ZFS with 5.16 or 5.17?

**Comment by freqlabs** [comment]
@behlendorf okay, I had not realized that the maybe list is what drives the retry mechanism. The output does not show the expected failures anywhere when there is a retry, so I assumed it was broken.

**Review by freqlabs — APPROVED** [review]

**Comment by satmandu** [comment]
@jaen I just rebuilt from this PR and it also works with 5.17-rc7.

**Comment by jaen** [comment]
Hmm, maybe it would make sense to delay it for 5.17 proper then and be able to bump two versions at once, since we're already waited a bit for the bump? What is one week more ;' )

**Comment by satmandu** [comment]
5.17 should be[ released this weekend unless something goes wrong](https://lore.kernel.org/lkml/CAHk-=wjkkYX8OvTv60+XvQkAK4Pg0QC0Hn-4+n7Q0t1+QWw7Sw@mail.gmail.com/). Kernel releases are usually on Sundays...

**Comment by satmandu** [comment]
It would be nice to have official 5.17 support, and then ask the debian maintainers to release 2.1.3 and then ask the Ubuntu maintainers to try to get it into 22.04....

**Comment by tonyhutter** [comment]
Release is out:
https://github.com/openzfs/zfs/releases/tag/zfs-2.1.3

@satmandu yea I understand - unfortunately the kernel is always a moving target and it's a always a problem to get the timing right.  We really couldn't keep up the release any longer (this PR has been out for over a month).  I know FreeBSD has been hoping for zfs-2.1.3 for their 13.1 release, and hopefully we were able to make their deadline.

**Comment by stuartthebruce** [comment]
Many thanks. I have installed it on a few test systems and see the new,
```
[root@zfsexport1 ~]# cat /sys/module/zfs/parameters/zfs_arc_prune_task_threads 
1
```
Many thanks for fixing this particularly painful issue, along with fixes for a few others I reported. The Open ZFS community rocks!

**Comment by jaen** [comment]
@tonyhutter in that case, would you be willing to make a release with just the meta bump faster if it turns out that ZFS is already compatible on 5.17 release? Sorry if that's unreasonable, I'm not too familiar with OpenZFS release process.

**Comment by satmandu** [comment]
It might also be a good idea to have a rolling point release for every kernel release, even if just to bump the supported kernel version. If zfs is being tested against all the RC kernels, (ideally there would be some level of CI for this—ubuntu'd mainline kernel builds might make this relatively easy), then a point release just after final kernel release would help people who test the mainline kernels _and_ people who test zfs, helping _both_ projects.

**Comment by satmandu** [comment]
It might also be a good idea to have a rolling point release for every kernel release, even if just to bump the supported kernel version. If zfs is being tested against all the RC kernels, (ideally there would be some level of CI for this—ubuntu'd mainline kernel builds might make this relatively easy), then a point release just after final kernel release would help people who test the mainline kernels _and_ people who test zfs, helping both projects.

**Pull request merged**
