### PR TITLE
Support idmapped mount for kernel 6.3

### PR DESCRIPTION
**Pull request by youzhongyang**
This PR adds changes needed for idmapped mount support in kernel 6.3.

Signed-off-by: Youzhong Yang <yyang@mathworks.com>

### Motivation and Context

Linux kernel 6.3 [changed a bunch of APIs](https://github.com/torvalds/linux/commit/05e6295f7b5e05f09e369a3eb2882ec5b40fff20) to use the dedicated idmap type for mounts (struct mnt_idmap), we need to detect these changes and make zfs work with the new APIs.

### Description

The new struct mnt_idmap is hidden and those essential APIs such as make_vfsuid, make_vfsgid, from_vfsuid, and from_vfsgid are defined as GPL only. We have to work around this.

The approach is to redefine struct mnt_idmap in the same way as it is in kernel 6.3. In the future if its definition is changed, our test cases should be able to catch it.

### How Has This Been Tested?

- Ran zfs test suite under kernel 6.3-rc2. Test suite run against 6.3-rc4 is still in progress.
- Ran zfs test suite under kernel 5.15.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by kode54** [comment]
My dmesg log is aglow with a flood of:

```
zio pool=zroot vdev=/dev/disk/by-id/nvme-WDS100T3X0C-00SJG0_192725805072-part3 error=5 type=5 offset=0 size=0 flags=1049728
```

**Comment by youzhongyang** [comment]
The commit "[block: add a sanity check for non-write flush/fua bios](https://github.com/torvalds/linux/commit/b4a6bb3a67aa0c37b2b6cd47efc326eb455de674)" introduced the change. 

I patched bio_set_flush() and tested again, it's now all clear. I am not sure if this is the right approach, need to think about how we should tackle this issue.

```
diff --git a/include/os/linux/kernel/linux/blkdev_compat.h b/include/os/linux/kernel/linux/blkdev_compat.h
index c7405ffab..c5c6385be 100644
--- a/include/os/linux/kernel/linux/blkdev_compat.h
+++ b/include/os/linux/kernel/linux/blkdev_compat.h
@@ -426,7 +426,7 @@ static inline void
 bio_set_flush(struct bio *bio)
 {
 #if defined(HAVE_REQ_PREFLUSH) /* >= 4.10 */
-       bio_set_op_attrs(bio, 0, REQ_PREFLUSH);
+       bio_set_op_attrs(bio, 0, REQ_PREFLUSH | REQ_OP_WRITE);
 #elif defined(WRITE_FLUSH_FUA) /* >= 2.6.37 and <= 4.9 */
        bio_set_op_attrs(bio, 0, WRITE_FLUSH_FUA);
 #else
```

**Comment by behlendorf** [comment]
@youzhongyang thanks for sorting out both of these 6.3 issues.  I'll work on getting this reviewed.

**Comment by youzhongyang** [comment]
This PR has been updated and rebased. The writepage_t change is now gone from the PR.

**Comment by satmandu** [comment]
With this PR merged I was able to build a module for 6.3-rc6. But then booting I get this error:
```
[   31.658170] ------------[ cut here ]------------
[   31.658176] memcpy: detected field-spanning write (size 832) of single field "((void*)((dn->dn_phys)->dn_bonus + (((dn->dn_phys)->dn_nblkptr - 1) * sizeof (blkptr_t))))" at /var/lib/dkms/zfs/2.1.99.20230410/build/module/zfs/dbuf.c:4112 (size 320)
[   31.658194] WARNING: CPU: 0 PID: 539 at /var/lib/dkms/zfs/2.1.99.20230410/build/module/zfs/dbuf.c:4112 dbuf_sync_leaf+0x585/0x770 [zfs]
[   31.658398] Modules linked in: lp(+) parport efi_pstore dmi_sysfs ip_tables x_tables autofs4 zfs(POE) spl(OE) raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear hid_magicmouse hid_logitech_hidpp hid_logitech_dj mlx4_ib hid_generic ib_uverbs mlx4_en ib_core uas usbhid hid usb_storage amdgpu iommu_v2 gpu_sched drm_buddy i2c_algo_bit drm_ttm_helper ttm crct10dif_pclmul crc32_pclmul drm_display_helper ghash_clmulni_intel sha512_ssse3 cec rc_core aesni_intel mxm_wmi iTCO_wdt drm_kms_helper syscopyarea sysfillrect sysimgblt intel_pmc_bxt iTCO_vendor_support crypto_simd mpt3sas nvme raid_class drm cryptd mlx4_core e1000e scsi_transport_sas i2c_i801 i2c_smbus ahci nvme_core xhci_pci libahci xhci_pci_renesas video wmi
[   31.658458] CPU: 0 PID: 539 Comm: dp_sync_taskq Tainted: P           OE      6.3.0-rc6 #2
[   31.658461] Hardware name: MSI MS-7998/C236A WORKSTATION (MS-7998), BIOS 2.A0 06/15/2018
[   31.658463] RIP: 0010:dbuf_sync_leaf+0x585/0x770 [zfs]
[   31.658643] Code: 0f 87 cd 42 1e 00 a8 01 75 22 48 89 d1 48 89 de 48 c7 c2 88 a4 bc c1 48 c7 c7 30 a5 bc c1 c6 05 b1 8b 2e 00 01 e8 1b c6 b7 d3 <0f> 0b 49 8b 4d 60 0f b6 41 03 48 8d b1 c0 00 00 00 83 e8 01 48 98
[   31.658646] RSP: 0000:ffffa4f2416d3bd8 EFLAGS: 00010282
[   31.658649] RAX: 0000000000000000 RBX: 0000000000000340 RCX: 0000000000000027
[   31.658651] RDX: ffff955b3ec20548 RSI: 0000000000000001 RDI: ffff955b3ec20540
[   31.658653] RBP: ffffa4f2416d3c90 R08: ffffffffc1bca578 R09: 0000000000000000
[   31.658654] R10: 0000000000ffff0a R11: 0000000000000636 R12: ffff95500c6c2ab8
[   31.658655] R13: ffff9550350d47b0 R14: ffff95501a259800 R15: ffff955013072c00
[   31.658657] FS:  0000000000000000(0000) GS:ffff955b3ec00000(0000) knlGS:0000000000000000
[   31.658659] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   31.658661] CR2: 000055687ddef568 CR3: 00000001151a3005 CR4: 00000000003706f0
[   31.658663] Call Trace:
[   31.658665]  <TASK>
[   31.658668]  ? zpl_get_file_info+0x88/0x240 [zfs]
[   31.658863]  ? mutex_lock+0x12/0x40
[   31.658869]  dbuf_sync_list+0xad/0x110 [zfs]
[   31.659046]  dnode_sync+0x461/0xb40 [zfs]
[   31.659240]  ? __schedule+0x48e/0x15a0
[   31.659244]  ? dnode_multilist_index_func+0x96/0xb0 [zfs]
[   31.659420]  ? mutex_lock+0x12/0x40
[   31.659424]  sync_dnodes_task+0x76/0xb0 [zfs]
[   31.659599]  taskq_thread+0x27e/0x490 [spl]
[   31.659615]  ? wake_up_q+0x90/0x90
[   31.659620]  ? taskq_thread_spawn+0x50/0x50 [spl]
[   31.659634]  kthread+0xe6/0x110
[   31.659636]  ? kthread_complete_and_exit+0x20/0x20
[   31.659639]  ret_from_fork+0x1f/0x30
[   31.659644]  </TASK>
[   31.659645] ---[ end trace 0000000000000000 ]---
```

Happy to open an issue for this if that would be helpful.

**Comment by youzhongyang** [comment]
I've seen this too:

```
[ 1667.309351] memcpy: detected field-spanning write (size 3904) of single field "((void*)((dn->dn_phys)->dn_bonus + (((dn->dn_phys)->dn_nblkptr - 1) * sizeof (blkptr_t))))" at /tmp/zfs-build-root-YvJzdwOd/BUILD/zfs-kmod-2.1.99/_kmod_build_6.3.0-0.rc5.20230405git76f598ba7d8e.44.fc39.x86_64/../zfs-2.1.99/module/zfs/dbuf.c:4112 (size 320)
```

```
[ 1667.357445] memcpy: detected field-spanning write (size 3904) of single field "((void*)((&ddnp[i])->dn_bonus + (((&ddnp[i])->dn_nblkptr - 1) * sizeof (blkptr_t))))" at /tmp/zfs-build-root-YvJzdwOd/BUILD/zfs-kmod-2.1.99/_kmod_build_6.3.0-0.rc5.20230405git76f598ba7d8e.44.fc39.x86_64/../zfs-2.1.99/module/os/linux/zfs/zio_crypt.c:902 (size 320)
```

I don't see why the dn_bonus can't be 3904 bytes. How could it assume it's only 320 bytes (uint8_t dn_bonus[DN_OLD_MAX_BONUSLEN] where DN_OLD_MAX_BONUSLEN=320)? This looks more or less a bug in include/linux/fortify-string.h.

We should think about how we can make it happy.

**Comment by arda2012** [comment]
Thanks for adding support for this. Is any backport to 2.1 planned, resp. is 2.2 planned for near future, or should we switch to master for now ? I know the correct approach would be to stick to an LTS kernel for now :-)

**Comment by kode54** [comment]
Also never to use ZFS with bleeding edge hardware. Mainly never buying hardware less than 5 years old.

**Pull request merged**
