### PR TITLE
Corrected the typo in zfs/cmd/zfs/zfs_main.c line number 404 pbkfd2it…

### PR DESCRIPTION
**Pull request by Spencer-Kinny**
Corrected the typo

### CODE REVIEW

**Comment by behlendorf** [comment]
@Spencer-Kinny this typo fix looks right to me.  Did you mean to close this?

**Comment by Spencer-Kinny** [comment]
@behlendorf 

Actually I later realized that I have forgotten to add the Signed off section in comments, so cancelled the branch.

Can we still go ahead with this branch. I will keep these things in mind next time onwards.

**Comment by freqlabs** [comment]
@Spencer-Kinny you can add the signed-off-by to the commit and force-push to update:
```
git commit --amend -s
git push --force
```

**Comment by Spencer-Kinny** [comment]
> 
> 
> @Spencer-Kinny you can add the signed-off-by to the commit and force-push to update:
> 
> ```
> git commit --amend -s
> git push --force
> ```

@freqlabs 

After amending and force pushing it said "Everything up-to-date"

**Comment by Spencer-Kinny** [comment]
@freqlabs 
@behlendorf 

I have corrected the errors in checkstyle, hope this gets pulled :+1: )

**Review by gmelikov — APPROVED** [review]

**Comment by behlendorf** [comment]
@Spencer-Kinny merged, thanks for fixing this!

**Pull request merged**
