### PR TITLE
zfs-2.1.7 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patchset for zfs-2.1.7

### Description
Misc bugfixes and updates for 6.1 kernel.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rincebrain** [comment]
Suggest either #14161 or reverting e257bd481bb77181e475bf35292c1a4b0cb2c57a.

**Comment by freqlabs** [comment]
`cli_root/zfs_receive/receive-o-x_props_override` fails upon hitting an assert added by 0f4ee295ba94803e5833f57481cfdbee5d1160d4 and fixed by 63652e1546 which was not backported. There's a lot of unrelated stuff in that commit, so here's just the fix backported: https://github.com/openzfs/zfs/commit/9c765f9b7285456732530f1440a217697bedfc22

**Comment by solbjorn** [comment]
Humbly suggesting https://github.com/openzfs/zfs/pull/14035, it unblocks objtool from processing the icp module and improves compatibility with different kernel versions and x86 Kconfig options. It can be ported by just dropping the bits from the files which don't exist yet in 2.1.6.

**Comment by ryao** [comment]
Sorry for being late to comment, I had a rough week last week.

Anyway, I would like to recommend the inclusion of the following commits that apply cleanly:

cf66e7e594fc7063db8050f2b7c718ae3f94641b
710fd1ded68491a164d85aedc69ffd4675ec5c59
fcd7293d4e7852a99c5c57443d6799895e10bc9f
fd8c3012b3eedc6eed3dda67bf71cfb243400128
4df8ccc83dc59c6921a4b8df4cd01f08ead3114a
891ac937beb959cad94a2ba267e4b56dee930a5e
9276e202eba330baf253ff7b0f7a631d5915c116
de6c0d3d8cb279e0dd6a4831d85a9c45047908ba
7c6d94728c9f5deef7e7cc0bf4320385345de5bd
d25153d55568afc92a7b3ec8329d7fbad7382a80
f7bda2de9786017348fd814603735f2be4182825
9a49c6b782443ba6e627f2261c45f082ad843094
dee8934e8fcd002eb826cf29aa453632d634b826
a36b37d4de5d90bf3016a7ca23686c3295f6b01a
2ba240f3583e421e87ca3c5be0fb6146bf9c3f07
bfaa1d98f4cef71938bdbde4fd01d2db2559fccb
19516b69ee41c9d3e239cb132c31fa9b13af2356
0aae8a449b935e60740b8b282d4bc14da23fc96d
09453dea6a986278873cd77a571c9b26a53fdb02
aa822e4d9c0f68ff9c7d236cc7c8a88bdf375aea
711b35dc24a8165929a9402ff8406248b65467bc
3146fc7edf7e1290396b92d51952b9188b873e7f
1bd02680c0dfb0e1350b0efed931d62861ad27b3
c6b161e390e9daf41ff6b0709cf6dfe529fa0627
6ae2f9088853737b87998408656fe4c3a7b9235b
eaaed26ffb3a14c0c98ce1e6e039e62327ab4447
4ecd96371bcd71b4f0e3be3591098037a58977cb
c77d2d741571038956ea911743608f1c6266bb2e

The following commits do not apply cleanly, but I would like to backport them anyway:

e949d36040e5e79fe0dfda6a33451111cc5a0476
4170ae4ea600fea6ac9daa8b145960c9de3915fc
dcce0dc5f009e8a3ec6dc48f5fc99abc4d74200f

In the case of the last two, I only care about backporting the changes to `lib/libshare/os/linux/smb.c`, which should apply cleanly. e949d36040e5e79fe0dfda6a33451111cc5a0476 had been rejected from 2.1.6 for being both too new and scary. It is not quite so new anymore and it fixes potential race conditions on non-Intel platforms, which is why I think it should be backported.

**Comment by ryao** [comment]
Here are some more commits that I think should be backported that apply cleanly:

4acc36ed7c5c1e1a8ab005de9f89880dd31ba112
062d3d056bf2b721f3db68f5c368b1c722ac8585
e5646c5e372621be3b17a07c378512b502888925
4dcc2bde9c8347fd7969871b69e72cba0b6d4ef7
0b2428da20c69bf32bbb9cbf561aa615fee64395
8af08a69cda63e6d7983fc2f32f9fed4155b95be
1e1ce10e5579a530606060f095f2f139916621fe
c23738c70eb86a7f04f93292caef2ed977047608
b445b25b273d263f032fadd717e5731185b74bf5

This one does not apply cleanly, but I still think it should be backported anyway:

6c8e9f09c22446cb8a1415ed1db05231cd659f69
eb9bec0a5d19abf9404f52081424fbb814e6188a
abb42dc5e1d5073ac72d9294fa78ab2203406b1c
f66ffe68787f9675ad7cce7644a1f81f28a86939
86db35c447aa3f4cc848497d78d54ec9c985d1ed

And here is one to consider for fun:

9dcdee788985b4aa9bbf250af3e018056402ba9f

It does not apply cleanly because `bzero()` was removed from HEAD. Otherwise, it would apply cleanly.

**Comment by tonyhutter** [comment]
@freqlabs @solbjorn - Thanks, I just pulled those commits in
@rincebrain - I pulled in your PR to master, but am hitting merge conflicts when I try to cherry-pick it into zfs-2.1.7.  If the conflicts arn't too bad, I'll try to include it.
@ryao - I'll take a look at that list

**Comment by ryao** [comment]
I would like to suggest #14179 be backported. It should not apply cleanly and fixing the conflict would basically be a new patch to change a single character from 3 to 1.

There were a few other man page corrections in this vein done in ab8d9c1783c4fe51f3ef8518f560fedd2c6fab19, but the corrections were not broken out of the commit. They are listed in the commit message, so it would be easy to manually fix them. I am extremely busy this week, but I will try to make time to send a patch doing that. If it is not ready in time for 2.1.7, it can go into 2.1.8. The man page has been wrong long enough that waiting another release to correct it would not be the end of the world.

**Comment by thesamesam** [comment]
There's also https://github.com/openzfs/zfs/pull/14187.

**Comment by ryao** [comment]
> There's also #14187 for Clang 15/16.

That one is only for Clang 15. We need 1e1ce10e5579a530606060f095f2f139916621fe and abb42dc5e1d5073ac72d9294fa78ab2203406b1c on top of that for clang 16. I have already recommended them here in:

https://github.com/openzfs/zfs/pull/14162#issuecomment-1315960484

**Comment by ryao** [comment]
b37d495e04ed6fc0012b2eccfff80af9e8887422 should also be included. I missed it yesterday when making my list.

**Comment by rincebrain** [comment]
> @freqlabs @solbjorn - Thanks, I just pulled those commits in @rincebrain - I pulled in your PR to master, but am hitting merge conflicts when I try to cherry-pick it into zfs-2.1.7. If the conflicts arn't too bad, I'll try to include it. @ryao - I'll take a look at that list

If you want, I can merge it, it should be pretty simple to pull the atoms out and shove them in even if the diff is messy if you just naively CP it.

**Comment by ryao** [comment]
UBSan and ASan builds would benefit from #14150, although that one is not yet in master and we would need to check to verify that it is enough to make those builds work in 2.1.y. @szubersk would you mind checking?

**Comment by jumbi77** [comment]
> [b37d495](https://github.com/openzfs/zfs/commit/b37d495e04ed6fc0012b2eccfff80af9e8887422) should also be included. I missed it yesterday when making my list.

Thanks for taking the time to list commits which could be included! I always found it hard to compare 2.x-staging with master/figuring out which commits are (yet) only in master https://github.com/openzfs/zfs/compare/zfs-2.1.7-staging...master

**Comment by ryao** [comment]
> > [b37d495](https://github.com/openzfs/zfs/commit/b37d495e04ed6fc0012b2eccfff80af9e8887422) should also be included. I missed it yesterday when making my list.
> 
> Thanks for taking the time to list commits which could be included! I always found it hard to compare 2.x-staging with master/figuring out which commits are (yet) only in master (comparing with github [zfs-2.1.7-staging...master](https://github.com/openzfs/zfs/compare/zfs-2.1.7-staging...master) isnt accurate)

That would probably be easier if it were a list of all commits here rather than just a list of commits that were not included. I made it against the 2.1.7-staging branch, so there might be some slight overlap with commits that were already included in this PR, but not in the the 2.1.7-staging branch. In fact, there are a few commits by others that I appear to have recommended adding, despite them already being here. I just realized not that long ago. I have not yet combed through the list to identify and remove all of the duplicates, but there should only be about 2-3 of them.

**Comment by ryao** [comment]
@tonyhutter I made my list against the 2.1.7-staging branch, which meant that I recommended several commits for inclusion that were already part of this PR in https://github.com/openzfs/zfs/pull/14162#issuecomment-1315960484. I have just removed the duplicates from that comment.

**Comment by szubersk** [comment]
> UBSan and ASan builds would benefit from #14150, although that one is not yet in master and we would need to check to verify that it is enough to make those builds work in 2.1.y. @szubersk would you mind checking?

Unfortunately, ASan/UBSan hasn't been cherry-picked for the release branches. I'm happy to take a shot at it if you find it useful.

**Comment by ryao** [comment]
> > UBSan and ASan builds would benefit from #14150, although that one is not yet in master and we would need to check to verify that it is enough to make those builds work in 2.1.y. @szubersk would you mind checking?
> 
> Unfortunately, ASan/UBSan hasn't been cherry-picked for the release branches. I'm happy to take a shot at it if you find it useful.

My mistake.

**Comment by solbjorn** [comment]
> @freqlabs @solbjorn - Thanks, I just pulled those commits in @rincebrain - I pulled in your PR to master, but am hitting merge conflicts when I try to cherry-pick it into zfs-2.1.7. If the conflicts arn't too bad, I'll try to include it. @ryao - I'll take a look at that list

Thanks!
But seems like only b844489ec0e3 was pulled from [!14035](https://github.com/openzfs/zfs/pull/14035) -- in fact, there are 3 in the PR, all of whose are fixes:

b844489ec0e3
61cca6fa0506
73b8f700b68d

**Comment by stuartthebruce** [comment]
It would be nice to include https://github.com/openzfs/zfs/pull/14171 as well.

**Comment by tonyhutter** [comment]
I just did a big push that included nearly all the suggested commits with a few exceptions:

- Didn't include these, since I didn't want to selectively port only the smb.c part of them:
dcce0dc Fix oversights from 4170ae4e
4170ae4 Fix TOCTOU race conditions reported by CodeQL and Coverity

- Didn't include clang fixes since it's still going though review: https://github.com/openzfs/zfs/pull/14150

- This had some merge conflicts:
e949d36 Fix assertions in crypto reference helpers

**Comment by outofforest** [comment]
Hello, Is there any ETA for 2.7.1 release?

**Comment by tonyhutter** [comment]
@outofforest I just now pulled in some more commits, but hopefully we can get it out this week.

**Comment by ryao** [comment]
Two more patches to consider for fixing runtime issues:

* 97fac0fb70e35bb01c0d97f227c802c0fcbbf3da
* 587a39b7290b8437dbc15edbf679f33d72459df0

**Comment by tonyhutter** [comment]
@ryao thanks, included in my latest push.  Hopefully that's everything!

**Comment by freqlabs** [comment]
We could also bring in d6df4441c03ae1fb90f57b125d2c4813cc1561ca

**Comment by freqlabs** [comment]
I'd also like to see the fix in #13782 included. It applies cleanly except for the makefile. I've resolved the conflict in truenas/zfs@14a29d1d1de2351a4d04a7d7bcb8a60ac39093e9

**Comment by tonyhutter** [comment]
https://github.com/openzfs/zfs/releases/tag/zfs-2.1.7

**Comment by mabachel** [comment]
I have problems installing it on Fedora 36: https://github.com/openzfs/zfs/issues/14248

**Comment by cdluminate** [comment]
> @szubersk I can upload the new version asap. But before the regression bug in `dkms/unstable` package [1] gets fixed, we will see build failures. So, I'd prefer to postpone the upload a little bit after dkms gets fixed, so that fewer Debian unstable users will suffer from this dkms regression bug.
> 
> [1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025214 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025171 The two bugs refer to the same thing. just for your information.

The dkms bug is already fixed. And I uploaded 2.1.7-1 to Debian unstable several minutes ago.

**Comment by szubersk** [comment]
Thanks, @cdluminate! Now waiting for the mirrors to be updated.

**Comment by eirnym** [comment]
Fine, I've upgraded zfs to 2.1.7 on Arch Linux and it's failing to run on the latest 5.x. I'll try tomorrow to upgrade kernel to 6.x if it will work… 

I can downgrade kernel, how to downgrade zfs?

**Comment by szubersk** [comment]
@eirnym, would you mind opening an Issue and providing more details? We could continue the discussion there.

**Pull request merged**
