### PR TITLE
zfs-2.1.5 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patches for zfs-2.1.5.

### Description
This will support the 5.18 kernel.  Patches initially taken from the `zfs-2.1.5-staging` branch.  

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rincebrain** [comment]
#13517 perhaps? Or too feature-y?

**Comment by freqlabs** [comment]
> #13517 perhaps? Or too feature-y?

If not the whole thing, at least the bug fix in bf533a1b0628642298dc4f4de30c022980fec981 would be good.

**Comment by freqlabs** [comment]
A few more I spotted:
aad91df0752580e3e67b72f3e6dc391da69c830f
3c617c79211659e42039477102646a03a7bfd5e9
e41013078a90d5790c737eec573ec376ca21a234

**Comment by tonyhutter** [comment]
>> #13517 perhaps? Or too feature-y?
>>
> If not the whole thing, at least the bug fix in bf533a1 would be good.

@behlendorf what's your opinion on including either #13517 or just bf533a1?

**Comment by tonyhutter** [comment]
Included in my latest push:
42cf2ad0e Remove wrong assertion in log spacemap
e41013078 libzfs: Fail making a dataset handle gracefully
3c617c792 libzfs: mount: don't leak mnt_param_t if mnt_func fails
aad91df07 Reject zfs send -RI with nonexistent fromsnap

**Comment by freqlabs** [comment]
One for the CI that just bit me:
196e7c76174b50df4ab54f0b41a58e5659e15a48 ztest: reduce runtime of zloop.sh in CI

**Comment by behlendorf** [comment]
> @behlendorf what's your opinion on including either https://github.com/openzfs/zfs/pull/13517 or just https://github.com/openzfs/zfs/commit/bf533a1b0628642298dc4f4de30c022980fec981?

Pulling in the bf533a1b06 bug fix seems like a good idea to me.  As for the backport in #13517 I can see the appeal, but for the moment I'd suggest we hold off.  This change is a little more invasive than just a bug fix, it'd be nice to get some more mileage on it first in the master branch.

**Comment by dm17** [comment]
CentOS is blocking? I didn't realize ZFS needed to be successfully built for all major distros for a release to happen - I guess it makes sense though?

**Review by freqlabs — APPROVED** [review]

**Comment by scineram** [comment]
This should have https://github.com/openzfs/zfs/pull/13537.

**Review by freqlabs — COMMENTED** [review]
The release build fails on FreeBSD main because of -Wunused-but-set-variable being treated as an error.
I'm not sure backporting all those fixes is feasible, so would it be ok to disable this warning instead?

98aa3a077

**Comment by behlendorf** [comment]
I think disabling the warnings would be pretty reasonable, and also including https://github.com/openzfs/zfs/pull/13537.

**Review by freqlabs — APPROVED** [review]

**Review by behlendorf — APPROVED** [review]

**Comment by stuartthebruce** [comment]
Given that CentOS 8 is EOL should that buildbot be switched to Rocky Linux 8 or AlmaLinux 8?

**Comment by rincebrain** [comment]
I believe if you look under the covers, it was, it just didn't get renamed.

**Comment by stuartthebruce** [comment]
> I believe if you look under the covers, it was, it just didn't get renamed.
> 
Thanks. I do indeed see in config.log the expected version of gcc and kernel corresponding to the latest RHEL 8.6, and there is a reference to "--with-bugurl=http://bugs.almalinux.org/"

**Comment by tonyhutter** [comment]
You are all correct, "Centos 8" in buildbot is really Almalinux 8:
https://github.com/openzfs/zfs-buildbot/blob/master/master/master.cfg#L465

**Comment by devsk** [comment]
hmm...how long does "buildbot/FreeBSD stable/13 amd64 (TEST)" usually take? Its been going on and on

**Comment by rincebrain** [comment]
The FBSD stable/13 bot at least appears to have been broken for a week, so I would not expect it to succeed soon.

**Comment by devsk** [comment]
> The FBSD stable/13 bot at least appears to have been broken for a week, so I would not expect it to succeed soon.

Is anyone working on fixing it?

**Comment by sunilvaltix** [comment]
Is there any chance of this getting resolved any time soon? Release 2.1.5 is needed for 5.18 support (5.17 is EOL)

**Comment by rincebrain** [comment]
#13571 reminds me that perhaps a30927f would be good to include? (Though I realized after it went in that the description is now wrong with how the patch changed in the review...oops.)

**Comment by behlendorf** [comment]
> https://github.com/openzfs/zfs/issues/13571 reminds me that perhaps https://github.com/openzfs/zfs/commit/a30927f763834d3b16b4945ff8d5638ede69d545 would be good to include?

I think it'd be nice to have, but my recollection is this one didn't apply cleanly so I didn't initially include it.

**Comment by devsk** [comment]
make log for "buildbot/Fedora 35 x86_64" has this:

```  CC [M]  /tmp/zfs-build-buildbot-LCJ5fo6i/BUILD/zfs-kmod-2.1.5/_kmod_build_5.18.5-100.fc35.x86_64/module/zcommon/cityhash.o
In file included from ./include/linux/string.h:253,
                 from /tmp/zfs-build-buildbot-LCJ5fo6i/BUILD/zfs-kmod-2.1.5/_kmod_build_5.18.5-100.fc35.x86_64/../zfs-2.1.5/include/os/linux/spl/sys/strings.h:24,
                 from /tmp/zfs-build-buildbot-LCJ5fo6i/BUILD/zfs-kmod-2.1.5/_kmod_build_5.18.5-100.fc35.x86_64/../zfs-2.1.5/module/icp/algs/edonr/edonr.c:32:
In function 'fortify_memcpy_chk',
    inlined from 'EdonRInit' at /tmp/zfs-build-buildbot-LCJ5fo6i/BUILD/zfs-kmod-2.1.5/_kmod_build_5.18.5-100.fc35.x86_64/../zfs-2.1.5/module/icp/algs/edonr/edonr.c:491:3:
./include/linux/fortify-string.h:328:25: error: call to '__write_overflow_field' declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
  328 |                         __write_overflow_field(p_size_field, size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [scripts/Makefile.build:288: /tmp/zfs-build-buildbot-LCJ5fo6i/BUILD/zfs-kmod-2.1.5/_kmod_build_5.18.5-100.fc35.x86_64/module/icp/algs/edonr/edonr.o] Error 1
```
This test was not failing yesterday.

**Comment by behlendorf** [comment]
> make log for "buildbot/Fedora 35 x86_64" has this:

This is due to Fedora moving to gcc 12.1 with enables some additional default warnings and the CI performing a debug build where all warnings are considered fatal.  I've opened PR https://github.com/openzfs/zfs/pull/13575 to address these warnings, but I don't think we need to hold up the release for these changes.

**Comment by devsk** [comment]
> > make log for "buildbot/Fedora 35 x86_64" has this:
> 
> This is due to Fedora moving to gcc 12.1 with enables some additional default warnings and the CI performing a debug build where all warnings are considered fatal. I've opened PR #13575 to address these warnings, but I don't think we need to hold up the release for these changes.

Brian, If that is the case, we should release 2.1.5 asap. It has seen quite a bit of delay already (you approved the changes like a week ago).

**Comment by tonyhutter** [comment]
@devsk we included one more last-minute commit yesterday, but everything should be good to go now.  I'll try to push out the release today.

**Comment by tonyhutter** [comment]
Released: https://github.com/openzfs/zfs/releases/tag/zfs-2.1.5

**Comment by devsk** [comment]
> Released: https://github.com/openzfs/zfs/releases/tag/zfs-2.1.5

And upgraded! Thank you!

**Comment by stuartthebruce** [comment]
Many thanks for another quality release.

Is it expected that 2.1.5 is in the production repo for EL8.6 but the testing repo for EL7.9? Naively I would have thought would be consistent on declaring a ZFS release production ready or not? Or is has there not been as much testing on EL7?

Note, it also seems strange that 2.1.4 is in both testing and production for EL8.6, and exclusively in testing for EL8.5. Or perhaps I am looking in the wrong place?

**Comment by rincebrain** [comment]
Sigh, this should really be in the documentation somewhere to reference, or ideally the name or policy should change.

behlendorf posted an explanation once, which I'm not going to go dig up right now, but from what I recall:
* "testing" is the release series that would be "stable" in the next point release of that version of EL, if applicable (e.g. if 2.1.0 came out while 2.0.5 was out in EL8.4, EL8.5 would get 2.1.x as stable and EL8.4 would get 2.1.0 in testing)
* Once a point release is no longer the latest one, it stops getting updates to the stable branch, so in the above example, if it was 2.0.5 once EL8.5 came out, EL8.4 would never get 2.0.6 or 2.0.7  in stable.

Since EL7 is no longer getting point releases, I believe it logically follows that new releases, as long as the EL7 repo is being updated, would live in the testing repo forever.

**Comment by stuartthebruce** [comment]
Thanks for the explanation. That still leaves a mystery (at least for me) how 2.1.4 ended up in both testing and "stable" for EL8.6?

More generally, is there a distro-agnostic declaration somewhere of which releases are declared production ready, or is that implied by odd vs even in the second release digit, e.g., 2.0 (stable), 2.1 (development), 2.2 (stable)...

**Comment by rincebrain** [comment]
If it doesn't say rc or pre, it's considered stable, AFAIK.

I would not expect the zfs-testing repo to ever contain an older release than the non-testing repo, so if the zfs repo contained 2.1.4, zfs-testing would contain at least 2.1.4, and since it's the latest release and still getting updates, then they both get 2.1.5. It would only be after 2.2 that they would diverge.

Perhaps I should go replace my use of the word "stable" with "older" so people stop thinking any of the releases are considered unstable.

**Comment by stuartthebruce** [comment]
> Perhaps I should go replace my use of the word "stable" with "older" so people stop thinking any of the releases are considered unstable.

I think that would be helpful if it is not too disruptive. In the meantime I will try to remember that `testing` in the repo name does not indicate anything about stability.

**Comment by awehrfritz** [comment]
It's been a while since the 2.1.5-release. In the meantime, kernel version 5.19 has been released and the 5.18 series is end-of-life with the 5.18.19 release last month. Fedora has subsequently also switched to 5.19 which is not supported by ZFS 2.1.5.

@tonyhutter do you have already an estimate on when ZFS 2.1.6 will be released? I could not find a PR with the respective changes either, just the [zfs-2.1.6-staging](https://github.com/openzfs/zfs/tree/zfs-2.1.6-staging) branch which is compatible with the 5.19-kernel.

**Comment by tonyhutter** [comment]
@awehrfritz thanks for the heads-op.  I hadn't realized Fedora 36 had switched to the 5.19.8 kernel.  I've opened a new PR for zfs-2.1.6: https://github.com/openzfs/zfs/pull/13886

**Pull request merged**
