### PR TITLE
FreeBSD: incorporate changes to the VFS_QUOTACTL(9) KPI

### PR DESCRIPTION
**Pull request by jharmening**
VFS_QUOTACTL(9) has been updated to allow each filesystem to indicate
whether it has changed the busy state of the mount.  The filesystem
may still assume that its .vfs_quotactl entrypoint is always called
with the mount busied, but only needs to unbusy the mount (and clear
*mp_busy) if it does something that actually requires the mount to be
unbusied.  It no longer needs to blindly copy-paste the UFS protocol
for calling vfs_unbusy(9) for the Q_QUOTAOFF and Q_QUOTAON commands.

### Motivation and Context

Decouples per-filesystem quotactl() implementations from UFS-specific rules.
ZFS portion chases https://reviews.freebsd.org/D30218 and must land in lockstep

### How Has This Been Tested?
build and basic functional testing on FreeBSD-current/amd64

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
I'll defer to the other FreeBSD reviewers on Phabricator as far as the VFS part is concerned.  Let's be sure get it committed to FreeBSD first (it's fine to commit the ZFS changes in FreeBSD first, as long as we're following through with the upstreaming PR here) to make sure we have the FreeBSD version number locked in. Then we can safely upstream the ZFS portion here.

**Comment by jharmening** [comment]
> I'll defer to the other FreeBSD reviewers on Phabricator as far as the VFS part is concerned. Let's be sure get it committed to FreeBSD first (it's fine to commit the ZFS changes in FreeBSD first, as long as we're following through with the upstreaming PR here) to make sure we have the FreeBSD version number locked in. Then we can safely upstream the ZFS portion here.

Committed to FreeBSD in a4b07a2701f5.   ZFS changes should be identical to what's posted here.

**Review by freqlabs — APPROVED** [review]

**Review by behlendorf — APPROVED** [review]

**Comment by freqlabs** [comment]
This should fix the build failures on FreeBSD main we've started seeing today.

**Comment by jharmening** [comment]
> This should fix the build failures on FreeBSD main we've started seeing today.

What needs to happen for it to get merged?  I don't have sufficient privilege to do that myself.

**Comment by behlendorf** [comment]
@tonynguien the CI failures here are unrelated, this is ready to go when you get a chance.

**Pull request merged**
