### PR TITLE
These are the commands supported by the modctl system call

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
#12895

### Description
~~Part 1 for now. The mechtabs come next. See #12895. WIP.~~

~~On top of #12844, #12899, and #12906. Could probably not be. otherwise~~ g2g.

A bit split off into #12902 and #12901, calculations below treat it as an integral part of this series.

### How Has This Been Tested?
~~Three files removed, -805~~ See below, builds.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – none apply
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
I think I'm done. Here's some fun stats:
```
nabijaczleweli@tarta:~/store/code/zfs$ git diff dumpy --stat
 configure.ac                                |    1 +
 include/os/freebsd/zfs/sys/freebsd_crypto.h |    7 +-
 include/sys/crypto/api.h                    |  367 +--------------------------
 include/sys/crypto/common.h                 |  396 +----------------------------
 include/sys/crypto/icp.h                    |    3 -
 lib/libicp/Makefile.am                      |   10 +-
 module/icp/Makefile.in                      |   18 +-
 module/icp/algs/edonr/edonr.c               |    6 +
 module/icp/algs/modes/cbc.c                 |   17 +-
 module/icp/algs/modes/gcm.c                 |   14 +-
 module/icp/api/kcf_cipher.c                 |  930 --------------------------------------------------------------------
 module/icp/api/kcf_ctxops.c                 |    8 +-
 module/icp/api/kcf_digest.c                 |  491 ------------------------------------
 module/icp/api/kcf_mac.c                    |  405 +++---------------------------
 module/icp/api/kcf_miscapi.c                |  127 ----------
 module/icp/core/kcf_callprov.c              | 1445 +--------------------------------------------------------------------------------------------------------
 module/icp/core/kcf_mech_tabs.c             |  509 +++++++------------------------------
 module/icp/core/kcf_prov_lib.c              |   72 +-----
 module/icp/core/kcf_prov_tabs.c             |  375 ++--------------------------
 module/icp/core/kcf_sched.c                 | 1626 +----------------------------------------------------------------------------------------------------------------------
 module/icp/illumos-crypto.c                 |   20 +-
 module/icp/include/modes/modes.h            |    6 -
 module/icp/include/sys/bitmap.h             |  183 --------------
 module/icp/include/sys/crypto/elfsign.h     |  137 ----------
 module/icp/include/sys/crypto/impl.h        |  885 ++++-------------------------------------------------------------
 module/icp/include/sys/crypto/ioctl.h       | 1480 ------------------------------------------------------------------------------------------------------------
 module/icp/include/sys/crypto/ioctladmin.h  |  136 ----------
 module/icp/include/sys/crypto/ops_impl.h    |  630 ----------------------------------------------
 module/icp/include/sys/crypto/sched_impl.h  |  422 ++-----------------------------
 module/icp/include/sys/crypto/spi.h         |  540 +++-------------------------------------
 module/icp/include/sys/modctl.h             |  449 ---------------------------------
 module/icp/include/sys/modhash.h            |  147 -----------
 module/icp/include/sys/modhash_impl.h       |  108 --------
 module/icp/io/aes.c                         |  226 +++++------------
 module/icp/io/edonr_mod.c                   |   63 -----
 module/icp/io/sha1_mod.c                    |  154 +++---------
 module/icp/io/sha2_mod.c                    |  158 +++---------
 module/icp/io/skein_mod.c                   |  136 +++-------
 module/icp/os/modconf.c                     |  176 -------------
 module/icp/os/modhash.c                     |  927 --------------------------------------------------------------------
 module/icp/spi/kcf_spi.c                    |  695 ++++++---------------------------------------------
 module/os/freebsd/zfs/crypto_os.c           |   12 +-
 module/os/freebsd/zfs/hkdf.c                |    2 -
 module/os/freebsd/zfs/zio_crypt.c           |    7 -
 module/os/linux/icp/Makefile.in             |    5 +
 module/os/linux/icp/api/kcf_cipher.c        |  193 +++++++++++++++
 module/os/linux/zfs/zio_crypt.c             |   46 ++--
 module/zfs/dsl_crypt.c                      |    1 -
 module/zfs/hkdf.c                           |   14 +-
 49 files changed, 784 insertions(+), 14001 deletions(-)
```

And
```
nabijaczleweli@tarta:~/store/code/zfs$ git show dumpy..These-are-the-commands-supported-by-the-modctl-system-call  --stat | grep changed,
 1 file changed, 3 insertions(+), 26 deletions(-)
 17 files changed, 214 insertions(+), 365 deletions(-)
 3 files changed, 3 insertions(+), 86 deletions(-)
 4 files changed, 5 insertions(+), 354 deletions(-)
 2 files changed, 72 deletions(-)
 2 files changed, 20 deletions(-)
 1 file changed, 13 deletions(-)
 6 files changed, 22 insertions(+), 72 deletions(-)
 15 files changed, 27 insertions(+), 285 deletions(-)
 5 files changed, 12 insertions(+), 94 deletions(-)
 8 files changed, 38 insertions(+), 1270 deletions(-)
 4 files changed, 1 insertion(+), 26 deletions(-)
 2 files changed, 21 insertions(+), 94 deletions(-)
 4 files changed, 5 insertions(+), 37 deletions(-)
 3 files changed, 464 deletions(-)
 8 files changed, 25 insertions(+), 237 deletions(-)
 8 files changed, 898 deletions(-)
 4 files changed, 1 insertion(+), 47 deletions(-)
 6 files changed, 9 insertions(+), 29 deletions(-)
 7 files changed, 42 insertions(+), 357 deletions(-)
 4 files changed, 384 deletions(-)
 5 files changed, 10 insertions(+), 84 deletions(-)
 5 files changed, 17 insertions(+), 7 deletions(-)
 2 files changed, 2 insertions(+), 52 deletions(-)
 2 files changed, 3 insertions(+), 544 deletions(-)
 18 files changed, 237 insertions(+), 1323 deletions(-)
 5 files changed, 11 insertions(+), 20 deletions(-)
 4 files changed, 3 insertions(+), 37 deletions(-)
 2 files changed, 4 insertions(+), 80 deletions(-)
 1 file changed, 3 insertions(+), 14 deletions(-)
 3 files changed, 1617 deletions(-)
 18 files changed, 74 insertions(+), 3874 deletions(-)
 7 files changed, 23 insertions(+), 113 deletions(-)
 8 files changed, 110 deletions(-)
 3 files changed, 139 deletions(-)
 13 files changed, 20 insertions(+), 808 deletions(-)
```
for a total sum-of-diffstats of +835, -14052 (this is oddly in line with the grand diff, what it means is that I didn't need to patch anything to keep it working; icp is mostly nothing).

Net -13217. 14 files gone entirely.

**Comment by nabijaczleweli** [comment]
Caught a few more for a new total of +659 -14182 (net -13523). As another fun stat: the before sizing: 
```
-rw-r--r-- 1 nabijaczleweli users 9.2M Dec 26 23:50 icp.ko
-rw-r--r-- 1 nabijaczleweli users 1.8M Dec 26 23:50 libicp.a
-rw-r--r-- 1 nabijaczleweli users 256K Dec 26 23:51 icp.ko.stripped
-rw-r--r-- 1 nabijaczleweli users 300K Dec 26 23:51 libicp.a.stripped
```
vs. the new sizing:
```
-rw-r--r-- 1 nabijaczleweli users 7.4M Dec 27 03:12 icp.ko
-rw-r--r-- 1 nabijaczleweli users 1.2M Dec 27 03:12 libicp.a
-rw-r--r-- 1 nabijaczleweli users 188K Dec 27 03:09 icp.ko.stripped
-rw-r--r-- 1 nabijaczleweli users 237K Dec 27 03:09 libicp.a.stripped
```

Also, as a question: there's a
```
	kstat_t				*pd_kstat;
	kcf_prov_stats_t		pd_ks_data;
```
which gets installed *with the same name* (`NONAME_provider_stats`). There's a possibility to either fix it or get rid of it (though it seems to actually be updated, so probably just fix the naming).

**Comment by nabijaczleweli** [comment]
Here's the stats with just passing `pd_description` to the name field and making/using an encrypted dataset; there's no name collisions and I think this is more than good enough:
```
$ grep . /proc/spl/kstat/kcf/*
/proc/spl/kstat/kcf/AES Software Provider:2 1 0x01 4 1088 71376096974236 71516314982324
/proc/spl/kstat/kcf/AES Software Provider:name                            type data
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_total                   4    715
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_passed                  4    715
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_returned_busy           4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:3 1 0x01 4 1088 71376096992164 71516315039746
/proc/spl/kstat/kcf/SHA1 Software Provider:name                            type data
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_total                   4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_passed                  4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_returned_busy           4    0
/proc/spl/kstat/kcf/SHA2 Software Provider:4 1 0x01 4 1088 71376097011273 71516315072009
/proc/spl/kstat/kcf/SHA2 Software Provider:name                            type data
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_total                   4    178
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_passed                  4    178
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_returned_busy           4    0
/proc/spl/kstat/kcf/Skein Software Provider:5 1 0x01 4 1088 71376097026634 71516315102994
/proc/spl/kstat/kcf/Skein Software Provider:name                            type data
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_total                   4    0
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_passed                  4    0
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_returned_busy           4    0
```

**Comment by nabijaczleweli** [comment]
After off-list discussion, I've added @mcmilk's sha1 pruning commit on top, for an additional -3543. His blake3 patchset applies and builds cleanly on top after auto-merge.

The CI failures seem to all be (have been, at least) `projecttree_002_pos`, which I don't see how it could be affected by this.

**Comment by nabijaczleweli** [comment]
I've been running a write loop on my router for the past few days with the kstat names, and I have this:
```
/proc/spl/kstat/kcf/AES Software Provider:2 1 0x01 4 1088 71376096974236 1497162397517901
/proc/spl/kstat/kcf/AES Software Provider:name                            type data
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_total                   4    87083
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_passed                  4    87083
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/AES Software Provider:kcf_ops_returned_busy           4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:3 1 0x01 4 1088 71376096992164 1497162397576187
/proc/spl/kstat/kcf/SHA1 Software Provider:name                            type data
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_total                   4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_passed                  4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/SHA1 Software Provider:kcf_ops_returned_busy           4    0
/proc/spl/kstat/kcf/SHA2 Software Provider:4 1 0x01 4 1088 71376097011273 1497162397608544
/proc/spl/kstat/kcf/SHA2 Software Provider:name                            type data
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_total                   4    34350
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_passed                  4    34350
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/SHA2 Software Provider:kcf_ops_returned_busy           4    0
/proc/spl/kstat/kcf/Skein Software Provider:5 1 0x01 4 1088 71376097026634 1497162397640912
/proc/spl/kstat/kcf/Skein Software Provider:name                            type data
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_total                   4    0
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_passed                  4    0
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_failed                  4    0
/proc/spl/kstat/kcf/Skein Software Provider:kcf_ops_returned_busy           4    0
```

Setting `checksum=sha512` on the dataset makes the kstats increase (as expected), but `checksum=skein` hasn't moved a tick. Food for thought.

**Comment by nabijaczleweli** [comment]
Rebased, g2g, please consider the kstat issue.

**Comment by nabijaczleweli** [comment]
holy brsch, I ain't ever seen a clean CI run like this

**Comment by mcmilk** [comment]
> holy brsch, I ain't ever seen a clean CI run like this

Nice :ok_hand:

**Comment by nabijaczleweli** [comment]
Rebased

**Comment by nabijaczleweli** [comment]
Rebased

**Comment by nabijaczleweli** [comment]
Rebased

**Review by behlendorf — APPROVED** [review]

**Comment by nabijaczleweli** [comment]
Any opinion on `/proc/spl/kstat/kcf/NONAME_provider_stats` btw? As in:
  1. leave it as-is (useless, no way to know which one it is)?
  2. make it `/proc/spl/kstat/kcf/{AES,SHA2,Skein} Software Provider`, like in https://github.com/openzfs/zfs/pull/12901#issuecomment-1011655316 (2/3 of these actually work) (single-line change)?
  3. get rid of it?

**Comment by behlendorf** [comment]
I'd actually be inclined to get rid of both `/proc/spl/kstat/kcf/framework_stats` and `/proc/spl/kstat/kcf/NONAME_provider_stats`.  To my knowledge these nothing consumes these stats, and I've never had a need to go looking for them so I suspect they won't be missed.

**Comment by nabijaczleweli** [comment]
`/proc/spl/kstat/kcf/framework_stats` are already gone because nothing ever changed them (!!), I'll add `NONAME_provider_stats` pruning on top here, then.

**Comment by nabijaczleweli** [comment]
Topmost commit, another +1 -135. `/proc/spl/kstat/kcf/` is no more.

**Review by behlendorf — APPROVED** [review]
I'm good with this.  Hopefully one last rebase to resolve the conflicts and it's good to go.

**Pull request closed without merging**
