### PR TITLE
Specify a balanced NUMA policy for kernel buffers on FreeBSD

### PR DESCRIPTION
**Pull request by markjdb**
### Motivation and Context
Buffers used for ARC data and metadata are allocated from UMA, the FreeBSD kernel's memory allocator.  Such buffers can consume a large fraction of the system's memory.

On NUMA systems, UMA zones (i.e., kmem caches) have a first-touch policy by default.  That is, when allocating memory, the allocator will return memory from the NUMA domain in which the allocating thread is currently running.  If a zone is created with the UMA_ZONE_ROUNDROBIN flag, the allocator will instead attempt to balance allocations across all domains.

Switch the ABD chunk and ZIO data buffer caches to use this balanced policy instead.  There are two reasons for this:
- Buffers may be cached for a long time and a first-touch policy doesn't obviously make sense.  A round-robin policy is a more sensible default even if it isn't optimal for some workloads.
- The first-touch policy interacts poorly with FreeBSD's and ZFS' low memory handling.  This policy makes it easy to completely exhaust one domain's free pages without touching another.  In this situation there is no backpressure on the ARC because it has no awareness of per-domain free page counts.  Meanwhile, because the first-touch policy is strict, it is possible for ZFS to trigger low-memory deadlocks even when other domains have plentiful free pages.

UMA's first-touch policy simply isn't designed for a consumer like ZFS, which is somewhat unusual among others in FreeBSD.  Rather than making UMA more complicated and less predictable to try and handle ZFS' requirements, let's change ZFS to try and balance its memory usage.

### Description
The patch introduces a new kmem_cache_create() flag which is plumbed into UMA_ZONE_ROUNDROBIN on FreeBSD.  There is no change in behaviour on Linux.

### How Has This Been Tested?
I used pgbench on a NUMA system to replicate a couple of problems:
- severe NUMA domain imbalance, causing all other memory allocations to fall back to the unaffected domain and resulting in some paging
- an infrequent deadlock that has been seen in production by at least one user

This patch resolves the problem and gives smoother system behaviour.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by freqlabs — APPROVED** [review]

**Comment by amotin** [comment]
I have feeling I've tried it a while ago, and have value feelings that something was not great there, probably performance-wise, that is why I dropped it. But I may be wrong now.

I haven't seen the deadlock problem mentioned, but I saw myself and do have TrueNAS ticket for cases when size of NUMA domains is not equal.  In that case ZFS receiving lowmem events shrinks all of ARC, that makes it effectively limited to double of smallest domain.  It would be good if UMA could progressively redirect requests from domain that is reaching its limits.

**Comment by markjdb** [comment]
> I have feeling I've tried it a while ago, and have vague feelings that something was not great there, probably performance-wise, that is why I dropped it. But I may be wrong now.
>
> I haven't seen the deadlock problem mentioned, but I saw myself and do have TrueNAS ticket for cases when size of NUMA domains is not equal. In that case ZFS receiving lowmem events shrinks all of ARC, that makes it effectively limited to double of smallest domain. It would be good if UMA could progressively redirect requests from domain that is reaching its limits.

I did try to implement something like this, but it makes UMA more complicated and hard to reason about for the benefit of a single consumer. For example, we could check to see if a new slab allocation would trigger paging pressure on the local domain, and instead fall back to a different domain in that case. But what about workloads like file streaming or memory-bound database workloads where there is always some paging pressure? In that case we would fall back to remote domains unnecessarily and hurt performance where NUMA affinity really matters, e.g., for mbuf allocations. I don't see a clear solution.

I couldn't come up with a sensible policy, and since ZFS already has to do a lot of work to cooperate nicely with the rest of the VM system, I felt that ZFS is the right place to handle this problem. I'm open to other suggestions.

> PS: With my recently implemented uncached prefetch with short-living ARC buffers it may be that first-touch for ARC is not so useless.

Do we know at allocation time whether the buffer is going to be short-lived? If so we could allocate them from a separate zone with the first-touch policy.

**Comment by amotin** [comment]
> > PS: With my recently implemented uncached prefetch with short-living ARC buffers it may be that first-touch for ARC is not so useless.
> 
> Do we know at allocation time whether the buffer is going to be short-lived? If so we could allocate them from a separate zone with the first-touch policy.

Actually I was wrong, it is already handled in different way: ARC_FLAG_UNCACHED is translated into ARC_HDR_ALLOC_LINEAR, that does not use the ABD zone, so it should still use NUMA affility.

**Comment by behlendorf** [comment]
Where do we stand with this change?

**Comment by mjguzik** [comment]
I think the idea is a little messy.

I have the venerable package building workload with poudriere with experimental patches to make it numa-aware. With the proposed patch distfiles may easily land in the wrong domain even when there is tons of ram available everywhere, when otherwise they would not.

Perhaps it would be feasible to make round robin act like first touch as long as the target domain is above some % free? This could be a dedicated _alloc entry point as to not pessimize the "fast" path in the current allocator for other cases.

**Comment by amotin** [comment]
It's being a while since I tried this last time.  So I don't have very strong opinion.  One of my concerns is that ABD usually allocates many pages at a time, and I suppose round-robin means it will try to allocate each next one from a different domain, that make me think there may appear much more cross-domain traffic and I lock contentions.

**Pull request closed without merging**
