### PR TITLE
Fix data corruption when cloning embedded blocks.

### PR DESCRIPTION
**Pull request by pjd**
Don't overwrite blk_phys_birth, as for embedded blocks it is part of the payload.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ryao** [comment]
> I'm also working on adding tests, but I'd like to be able to have a more complete coverage and currently there is no userland tool apart from cp(1) that uses copy_file_range(2).

We can add our own tools to the ZTS, although getting tests that use `cp(1)` would be great in itself.

> Maybe integrating pjdfstest would be beneficial? I could extend fstest tool to allow testing copy_file_range(2) with different offsets and sizes.

We could use a github runner to integrate it into PRs, although at the moment, github runners do not support FreeBSD and we would like test coverage of this on FreeBSD since it is the only platform in the main repository where this feature is enabled.

**Review by ryao — APPROVED** [review]

**Comment by rincebrain** [comment]
The problem with using `cp(1)` on Linux, at least, would be that you'd need to get a very new `cp(1)` to make the relevant calls once that's plumbed in, unless you were trying to test the behavior of older versions specifically...

**Comment by ryao** [comment]
> The problem with using `cp(1)` on Linux, at least, would be that you'd need to get a very new `cp(1)` to make the relevant calls once that's plumbed in, unless you were trying to test the behavior of older versions specifically...

It is possible to have tests disabled if the userland tools are not new enough.

That said, I envision the initial version of the test being FreeBSD specific with Linux support added later when Linux support is merged into the repository.

**Comment by pjd** [comment]
I've cp(1) tests ready that work on FreeBSD. I'll create a pull request soon.

**Pull request merged**
