### PR TITLE
FreeBSD: Don't save user FPU context in kernel threads

### PR DESCRIPTION
**Pull request by mattmacy**
Signed-off-by: Matt Macy <mmacy@FreeBSD.org>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by amotin — APPROVED** [review]

**Comment by freqlabs** [comment]
This introduced a different panic when I last checked it. I'll check to make sure it was the latest incarnation...

**Comment by freqlabs** [comment]
Yeah this is what I tested, it made it impossible to boot.

**Comment by mattmacy** [comment]
> Yeah this is what I tested. It made it impossible to boot.
> Screen Shot 2020-09-10 at 3 44 43 PM

Try again.

**Comment by freqlabs** [comment]
Same panic still.

**Comment by behlendorf** [comment]
@freqlabs were you able to resolve the panic?

**Comment by freqlabs** [comment]
> @freqlabs were you able to resolve the panic?

We're still working on it.

**Review by freqlabs — APPROVED** [review]

**Comment by freqlabs** [comment]
My panic is unrelated

**Pull request merged**
