### PR TITLE
zstd early abort, 2.1 backport edition

### PR DESCRIPTION
**Pull request by rincebrain**
### Motivation and Context
I'd like to use early abort before 3.0.

### Description
The actual `zfs_zstd.c` changes are pretty clean - I had to change back a few things that have been modified since (like the ZFS_ASAN_ENABLED macro). I bumped the version string on the module for the same reason I did the last time - I've seen DKMS decide "oh, this module version number is the same, I don't need to upgrade it".

Imported bf533a1b for the same reason I initially wrote it in master; moved lz4 into zcommon so it could be called from zzstd.ko, moved `lz4_init` and `fini` out of `zio_init` and into kernel.c and zfs_prop.c because we need to init lz4 before zstd, otherwise surprising outcomes (like libzpool consumers crashing) might ensue.

zloop crashed when I initially pushed the branch, but the crash seems unrelated to these changes (it's in the zio gang block code?)

(I also noticed I got the tunable settings wrong in the man page. Whoops...)

### How Has This Been Tested?
It built, it passed a run of ZTS on my testbed, it passed tests when I pushed the branch.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by adamdmoss** [comment]
While I don't think my personal opinion carries any weight, IMHO:
* this isn't the sort of thing that should go into `2.1.x` ...
* ... but there's easily enough interesting stuff (including this) in `master` to warrant to `2.2` release RSN, and that should probably happen.

**Comment by rincebrain** [comment]
If people don't think anything but e.g. very targeted bugfixes should go in, sure, that's fine; I'm already running my own branch with a number of backports anyway, I'm just trying to minimize the delta from that over time, both because if I'm finding it useful, other people probably do too, and because then I'm less likely to hit bugs nobody else is going to see because I'm running a combination nobody else is. :)

**Comment by behlendorf** [comment]
After looking at the final change my feeling is we shouldn't rush to get this in a 2.1.x release.  While it's not a huge change it is a bit disruptive, I'd suggest we get some more experience with it in the master branch (or cherry picked in to a custom version) and revisit this for a future point release.

**Comment by rincebrain** [comment]
I have, FWIW, been running this in my local branch for a while without having burned the house down yet.

**Comment by Ornias1993** [comment]
> After looking at the final change my feeling is we shouldn't rush to get this in a 2.1.x release. While it's not a huge change it is a bit disruptive, I'd suggest we get some more experience with it in the master branch (or cherry picked in to a custom version) and revisit this for a future point release.

I tend to agree, I doubt users expect this change in a patch release...
However a 2.2 would be something that is worth considering if we can stack a few more "medium scope" changes like this into it :)

**Comment by Ornias1993** [comment]
Upstream? This IS the upstream.

this PR is just a backport, so obviously its already in master ;-)

**Comment by isopix** [comment]
@Ornias1993: thanks for reply. I was thinking that's maybe some separate branch. So assembling rescuecd and when HDDs will arrive, and will start now pool.

Anybody could me explain how to apply zstd early abort to newly created pool?

**Comment by rincebrain** [comment]
You don't need to do  anything, it just happens if you try doing a write with zstd level >= 3 and a record >= 128k, unless you reach out and set the global "please don't" tunable off.

**Comment by rincebrain** [comment]
It was set to at least zstd-3 and 128k is that there's always going to be a point at which doing the additional compression passes is more expensive than just doing it once would have been, the early abort code is using zstd-1 as the second pass so using it as a filter on zstd-1 or faster would not make much sense, and zstd-2 is not that much more expensive than 1.

128k was used as a threshold because, IIRC, there's a lot of variability in how much benefit you get as recordsizes get smaller, so 128k was a "safe" choice to ensure the default max recordsize could benefit for large files, where it's going to be the biggest win, without penalizing people who use lots of smaller records. It's possible it could or should be adjusted down with more data showing it's beneficial in those cases some, most, or all of the time, but that was, as I recall, why that was picked to start.

The whole concept here was that LZ4 is very fast at skipping data it decides is incompressible, so could we leverage that to improve zstd performance, so LZ4 doesn't need any such addition.

**Comment by isopix** [comment]
But what 'zstd_earlyabort_pass=1' does? Is it set to '1' by default

> It was set to at least zstd-3 and 128k is that there's always going to be a point at which doing the additional compression passes is more expensive than just doing it once would have been, the early abort code is using zstd-1 as the second pass so using it as a filter on zstd-1 or faster would not make much sense, and zstd-2 is not that much more expensive than 1.
Was this reply about 'zstd_earlyabort_pass=1' 
Is it set to '1' by default and I don't have to pass it to module?

> 128k was used as a threshold because, IIRC, there's a lot of variability in how much benefit you get as recordsizes get smaller, so 128k was a "safe" choice to ensure the default max recordsize could benefit for large files, where it's going to be the biggest win, without penalizing people who use lots of smaller records. It's possible it could or should be adjusted down with more data showing it's beneficial in those cases some, most, or all of the time, but that was, as I recall, why that was picked to start.
> 
> The whole concept here was that LZ4 is very fast at skipping data it decides is incompressible, so could we leverage that to improve zstd performance, so LZ4 doesn't need any such addition.
So LZ4 and ZSTD has two stages:
1) early abort - for whole file (1st pass)
2) late abort - if file is not discarded for compression in 'early abort', then there's 2nd pass for every block.

Am I right?

> 
> LZ4 is a good enough option that it's now the default if you don't specify anything in master, for whatever that's worth.
What does mean 'specfying in master'? Is it mistake/typo or some kind of relationship in nested datasets or something?
Or did you mean i I don't use 'master', but stable release (without ZSTD), that then LZ4 is enough?

**Comment by rincebrain** [comment]
The default is for it to be enabled, yes. You don't have to set anything.

The feature is not in the 2.1 release series, it will be in whatever comes after that. This was a PR to include it in the 2.1 release series, but [the answer was ultimately no](https://github.com/openzfs/zfs/pull/13517#issuecomment-1150448840), so I suppose I should just close it now.

No, that's not how literally any of this works. Everything about compression on ZFS is per record.

"in master" refers to being in the latest code in the repository, not necessarily a release.

**Pull request closed without merging**
