### PR TITLE
WIP: Add the ability to uninitialize devices

### PR DESCRIPTION
**Pull request by rincebrain**
### Motivation and Context
When I was playing with #12439, I imaged a disk from the original pool with the "fun" dataset so I could play with it in a VM, then I wanted to scribble over all the unused data, but I had already run initialize.

[Here's a demo on a file generated with truncate -s 10G on a compress=lz4 filesystem](https://gist.github.com/rincebrain/9755f6e971743fa68f568a44a3c98ab0)

* I could have overlooked a way this is possible currently, but I didn't see a way in the code, and couldn't figure out a combination of options that would do it independent of my understanding of the code.
* I considered calling it clear initialize and using -C instead, since I think that might be more intuitive, but thought avoiding having both -c and -C or using -u and calling it clear was worth the possible slight loss of clarity.
* Need more tests than just "hey, I tried it on the case I needed it for and a trivial test pool and confirmed it didn't break when moved to an unmodified master host"
* As the XXX says, the comment I added might not be correct - going to go back and poke at it further once I work up a few tests...
* It might be useful to be able to tell whether `zpool initialize -u` will do anything before running it, either by changing the behavior of `zpool status -i` or growing a new flag there or in `zpool initialize`? (I think I'd prefer to change the status -i behavior, but don't know if somebody wrote something like `if (strcmp("(uninitialized",[...]))`)

### Description
Added a `zpool initialize -u` for clearing the "initialized" status on devices.

### How Has This Been Tested?
Well, on the real pool disk image I wanted this for originally, it did what I wanted, and importing said disk image on unmodified master worked fine and then went initializing on request without a whimper starting from 0, and then the trivial single-disk test pool I made for this behaved as expected too.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
I've found myself wanting this same functionality on a few occasions. Rather than adding a new flag for this I think it may be preferable to simply allow an initialized vdev to be re-initialized without any error.  This is effectively how the `zpool trim` command works today since it's normal to regularly trim the same vdevs.  The TRIM code is structured is basically the same way as the initialize code so it could be used as a reference for how to do this.

My only concern would be that we're slightly changing the established behavior for initialize.

**Comment by rincebrain** [comment]
I opted for a -u instead of just "oh you meant do it over again" because I thought the ability to, say, online -e a vdev from 6 to 8 TB and then initialize only the parts you haven't before seemed like it might make a significant difference for the original usecase of "make sure all the parts have been written before so they're preallocated", and an explicit flag seemed cleaner than either "make you remember to say --incremental if you grew the vdev and don't want to start over" or "somehow special case the initialization having finished and the size not having changed since the last time you did it".

**Comment by UFTL** [comment]
rincebrain wrote:
"then I wanted to scribble over all the unused data, but I had already run initialize."

And there we have the name of the new function... 'scribble', to differentiate it from initialize. Initialize is to expand the file system into the existing drive space using 0xdeadbeefdeadbeef to avoid performance penalties later on; scribble is to write zeros to all free space to reduce VM or compressed backup file size or to overwrite potentially sensitive data left behind on now-unused sectors.

Now all we need is a --scribble flag that automatically resets zpool initialize progress so it'll run again, and changes the zfs_initialize_value to '0', then resets it to '0xdeadbeefdeadbeef' once it's done.

**Comment by rincebrain** [comment]
I don't really think it needs a separate clever name, just a --force would do, possibly with a --zero if that's a common use case for people versus writing deadbeef.

Much as I enjoy whimsical names, they tend to be a barrier for people who are unfamiliar with the tools, and I could see "scribble" being interpreted as, say, overwriting all your data, not just the free space, to pick one example.

**Pull request closed without merging**
