### PR TITLE
Linux 5.17 compat: GENHD_FL_EXT_DEVT / GENHD_FL_NO_PART_SCAN

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Issue #13294

### Description

As of the 5.17 kernel the `GENHD_FL_EXT_DEVT` flag has been removed and the
`GENHD_FL_NO_PART_SCAN` flag renamed `GENHD_FL_NO_PART`.  Update `zvol_alloc()`
to set `GENHD_FL_NO_PART` for the newer kernels which is sufficient.  The
behavior for prior kernels remains unchanged.
    
torvalds/linux@1ebe2e5f9d68e94c ("block: remove GENHD_FL_EXT_DEVT")
torvalds/linux@46e7eac647b34ed4 ("block: rename GENHD_FL_NO_PART_SCAN to GENHD_FL_NO_PART")

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Wenri** [comment]
I think this PR can't solve the problem, at least on my side using clang compiler. The reason is that `GENHD_FL_NO_PART` in 5.17 is not defined as a macro, but an enumerator constant:

```c
enum {
	GENHD_FL_REMOVABLE			= 1 << 0,
	GENHD_FL_HIDDEN				= 1 << 1,
	GENHD_FL_NO_PART			= 1 << 2,
};
```

According to my test using clang, `#if defined` can't tell the existence of an enumerator constant, as it is not a preprocessor identifier. Here is the patch I used during my test:

```patch
--- a/module/os/linux/zfs/zvol_os.c	2022-04-06 18:41:25.312647604 +0800
+++ b/module/os/linux/zfs/zvol_os.c	2022-04-06 18:25:06.686248568 +0800
@@ -908,8 +908,8 @@
 		 * ZFS_VOLMODE_DEV disable partitioning on ZVOL devices: set
 		 * gendisk->minors = 1 as noted in include/linux/genhd.h.
 		 * Also disable extended partition numbers (GENHD_FL_EXT_DEVT)
-		 * and suppresses partition scanning (GENHD_FL_NO_PART_SCAN)
-		 * setting gendisk->flags accordingly.
+		 * and suppresses partition scanning (GENHD_FL_NO_PART_SCAN /
+		 * GENHD_FL_NO_PART) setting gendisk->flags accordingly.
 		 */
 		zso->zvo_disk->minors = 1;
 #if defined(GENHD_FL_EXT_DEVT)
@@ -917,6 +917,10 @@
 #endif
 #if defined(GENHD_FL_NO_PART_SCAN)
 		zso->zvo_disk->flags |= GENHD_FL_NO_PART_SCAN;
+#elif defined(GENHD_FL_NO_PART)
+		zso->zvo_disk->flags |= GENHD_FL_NO_PART;
+#else
+#error "Can't find usable flags to suppress partition scanning!"
 #endif
 	}
 	zso->zvo_disk->first_minor = (dev & MINORMASK);
```

And then the compilation failed with:

```
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/../os/linux/zfs/zpl_xattr.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/../os/linux/zfs/zvol_os.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/vdev_raidz_math_sse2.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/vdev_raidz_math_ssse3.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/vdev_raidz_math_avx2.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/vdev_raidz_math_avx512f.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/vdev_raidz_math_avx512bw.o
/var/lib/dkms/zfs/2.1.4/build/module/zfs/../os/linux/zfs/zvol_os.c:923:2: error: "Can't find usable flags to suppress partition scanning!"
#error "Can't find usable flags to suppress partition scanning!"
 ^
/var/lib/dkms/zfs/2.1.4/build/module/zfs/../os/linux/zfs/zvol_os.c:1120:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                add_disk(zv->zv_zso->zvo_disk);
                ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[5]: *** [scripts/Makefile.build:288: /var/lib/dkms/zfs/2.1.4/build/module/zfs/../os/linux/zfs/zvol_os.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [scripts/Makefile.build:550: /var/lib/dkms/zfs/2.1.4/build/module/zfs] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:1829: /var/lib/dkms/zfs/2.1.4/build/module] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.17.1-xanmod1-gllvm'
make[2]: *** [Makefile:55: modules-Linux] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/2.1.4/build/module'
make[1]: *** [Makefile:878: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/2.1.4/build'
make: *** [Makefile:739: all] Error 2
```

**Comment by behlendorf** [comment]
Thanks for the quick feedback.  Yes, that would make sense I overlooked it was an enum type and wasn't setup to test it locally.  Sorry about that, I'll go ahead and update this PR with an actual configure check to detect which flags are supported.

**Comment by behlendorf** [comment]
@Wenri if you get a moment to verify the updated patch that would be appreciated.  Thanks.

**Comment by Wenri** [comment]
Thanks for the patch. I can confirm the configure check works on 2.1.4.
I applied this patch on top of OpenZFS 2.1.4-0york0, and repeated the steps in Issue #13294.

```shell
~  $ zfs --version
zfs-2.1.4-1wenri0~issue13294
zfs-kmod-2.1.4-1wenri0~issue13294
~  $ ls -lah /dev/zvol/dpool/win10gpu*
lrwxrwxrwx 1 root root 9 Apr 12 18:20 /dev/zvol/dpool/win10gpu -> ../../zd0
~  $ ls -lah /dev/zd0*
brw-rw---- 1 root disk 230, 0 Apr 12 18:20 /dev/zd0
~  $ zfs get volmode dpool/win10gpu
NAME            PROPERTY  VALUE    SOURCE
dpool/win10gpu  volmode   dev      local
~  $ sudo fdisk -l /dev/zvol/dpool/win10gpu 
Disk /dev/zvol/dpool/win10gpu: 240 GiB, 257698037760 bytes, 503316480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: F5017AC6-9C88-49C9-9BC8-74F0D4CEF648

Device                        Start       End   Sectors   Size Type
/dev/zvol/dpool/win10gpu1      2048    206847    204800   100M EFI System
/dev/zvol/dpool/win10gpu2    206848    239615     32768    16M Microsoft reserved
/dev/zvol/dpool/win10gpu3    239616 502292422 502052807 239.4G Microsoft basic data
/dev/zvol/dpool/win10gpu4 502292480 503312383   1019904   498M Windows recovery environment
```

With this patch, OpenZFS can hide the partition table correctly.

**Comment by behlendorf** [comment]
@ckane would you mind reviewing this kernel compatibility fix.

**Comment by ckane** [comment]
> @ckane would you mind reviewing this kernel compatibility fix.

I just got back from a work trip, but should be able to take a look by the end of the week

**Review by tonyhutter — APPROVED** [review]

**Pull request merged**
