### PR TITLE
Revert "Linux 6.5 compat: register_sysctl_table removed"

### PR DESCRIPTION
**Pull request by bwatkinson**
This reverts commit b35374fd6474603170fd9a3c7503da6eb13ac712 as there are error messages when loading the SPL module. Errors seemed to be tied to duplicate a duplicate entry.

Reverting b35374f as there is a error when trying to load the SPL module using `zfs.sh`.

### Motivation and Context

Fixes issue with loading SPL kernel module. Here is stack trace from dmesg that shows the error that is happening:
```699333.793823] sysctl duplicate entry: /kernel/spl/kmem//slab_kvmem_total
[699333.800474] CPU: 20 PID: 1042641 Comm: insmod Kdump: loaded Tainted: P        W  OE    --------- -  - 4.18.0-408.el8.x86_64 #1
[699333.811941] Hardware name: GIGABYTE R272-Z32-00/MZ32-AR0-00, BIOS R21 10/08/2020
[699333.819410] Call Trace: 
[699333.821943]  dump_stack+0x41/0x60
[699333.825347]  __register_sysctl_table+0x4a8/0x4e0
[699333.830053]  ? spl_random_init+0x173/0x173 [spl]
[699333.834768]  spl_proc_init+0x3b/0x1c0 [spl]
[699333.839050]  spl_init+0x46/0xe8d [spl] 
[699333.842897]  do_one_initcall+0x46/0x1d0
[699333.846826]  ? do_init_module+0x22/0x220
[699333.850835]  ? kmem_cache_alloc_trace+0x142/0x280
[699333.855620]  do_init_module+0x5a/0x220
[699333.859451]  load_module+0x14ba/0x17f0
[699333.863282]  ? __do_sys_finit_module+0xb1/0x110
[699333.867893]  __do_sys_finit_module+0xb1/0x110
[699333.872340]  do_syscall_64+0x5b/0x1a0
[699333.876091]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[699333.881231] RIP: 0033:0x7f2b2e14e9bd
[699333.884898] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9b 64 38 00 f7 d8 64 89 01 48
[699333.903729] RSP: 002b:00007ffe56275c98 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[699333.911381] RAX: ffffffffffffffda RBX: 0000564fa69397e0 RCX: 00007f2b2e14e9bd
[699333.918591] RDX: 0000000000000000 RSI: 0000564fa5ae88b6 RDI: 0000000000000003
[699333.925803] RBP: 0000564fa5ae88b6 R08: 0000000000000000 R09: 00007f2b2e4d8740
[699333.933013] R10: 0000000000000003 R11: 0000000000000246 R12: 0000000000000000
[699333.940223] R13: 0000564fa69397b0 R14: 0000000000000000 R15: 0000000000000000 
[699333.947444] ------------[ cut here ]------------
[699333.952143] name 'kstat'
[699333.954774] WARNING: CPU: 20 PID: 1042641 at fs/proc/generic.c:672 remove_proc_entry+0x15c/0x170
[699333.963642] Modules linked in: spl(OE+) loop ipmi_ssif sunrpc intel_rapl_msr intel_rapl_common amd64_edac_mod edac_mce_amd amd_energy kvm_amd kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel ast rapl drm_vram_helper pcspkr drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops sp5100_tco drm acpi_ipmi ccp k10temp ptdma i2c_piix4 ipmi_si acpi_cpufreq vfat fat binfmt_misc xfs libcrc32c sd_mod sg crc32c_intel ahci igb libahci i2c_algo_bit libata dca nvme nvme_core t10_pi dm_mirror dm_region_hash dm_log dm_mod ipmi_devintf ipmi_msghandler fuse [last unloaded: spl]
[699334.016734] CPU: 20 PID: 1042641 Comm: insmod Kdump: loaded Tainted: P        W  OE    --------- -  - 4.18.0-408.el8.x86_64 #1
[699334.028198] Hardware name: GIGABYTE R272-Z32-00/MZ32-AR0-00, BIOS R21 10/08/2020
[699334.035669] RIP: 0010:remove_proc_entry+0x15c/0x170
[699334.040627] Code: 48 8b 53 78 4c 8b 80 a0 00 00 00 48 8b 92 a0 00 00 00 e8 f0 90 d1 ff 0f 0b eb 86 48 89 ee 48 c7 c7 40 f5 90 8b e8 dd 90 d1 ff <0f> 0b e9 78 ff ff ff e8 d8 8d d1 ff 0f 1f 84 00 00 00 00 00 0f 1f
[699334.059449] RSP: 0018:ffffb599b2bf7c70 EFLAGS: 00010282
[699334.064755] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[699334.071966] RDX: ffff9ce36e526e80 RSI: ffff9ce36e516658 RDI: ffff9ce36e516658
[699334.079176] RBP: ffffffffc06b1300 R08: 0000000000000000 R09: c0000000ffff7fff
[699334.086388] R10: 0000000000000001 R11: ffffb599b2bf7a88 R12: ffffffff8c49a8c0
[699334.093598] R13: ffffffffc06bc258 R14: ffffffffc06bc410 R15: 0000000000000000
[699334.100808] FS:  00007f2b2f237740(0000) GS:ffff9ce36e500000(0000) knlGS:0000000000000000
[699334.108971] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[699334.114796] CR2: 0000564fa693c058 CR3: 000000051ab9a000 CR4: 0000000000350ee0
[699334.122007] Call Trace:
[699334.124538]  ? spl_random_init+0x173/0x173 [spl]
[699334.129253]  spl_proc_init+0x146/0x1c0 [spl]
[699334.133622]  spl_init+0x46/0xe8d [spl] 
[699334.137470]  do_one_initcall+0x46/0x1d0
[699334.141396]  ? do_init_module+0x22/0x220
[699334.145405]  ? kmem_cache_alloc_trace+0x142/0x280
[699334.150191]  do_init_module+0x5a/0x220
[699334.154020]  load_module+0x14ba/0x17f0
[699334.157855]  ? __do_sys_finit_module+0xb1/0x110
[699334.162470]  __do_sys_finit_module+0xb1/0x110
[699334.166908]  do_syscall_64+0x5b/0x1a0
[699334.170654]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[699334.175793] RIP: 0033:0x7f2b2e14e9bd
[699334.179459] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9b 64 38 00 f7 d8 64 89 01 48
[699334.198289] RSP: 002b:00007ffe56275c98 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[699334.205936] RAX: ffffffffffffffda RBX: 0000564fa69397e0 RCX: 00007f2b2e14e9bd
[699334.213145] RDX: 0000000000000000 RSI: 0000564fa5ae88b6 RDI: 0000000000000003
[699334.220355] RBP: 0000564fa5ae88b6 R08: 0000000000000000 R09: 00007f2b2e4d8740
[699334.227566] R10: 0000000000000003 R11: 0000000000000246 R12: 0000000000000000
[699334.234776] R13: 0000564fa69397b0 R14: 0000000000000000 R15: 0000000000000000
[699334.241987] ---[ end trace ef62332069acbbd1 ]---
[699334.246691] ------------[ cut here ]------------
[699334.251393] name 'slab'
[699334.253937] WARNING: CPU: 20 PID: 1042641 at fs/proc/generic.c:672 remove_proc_entry+0x15c/0x170
[699334.262797] Modules linked in: spl(OE+) loop ipmi_ssif sunrpc intel_rapl_msr intel_rapl_common amd64_edac_mod edac_mce_amd amd_energy kvm_amd kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel ast rapl drm_vram_helper pcspkr drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops sp5100_tco drm acpi_ipmi ccp k10temp ptdma i2c_piix4 ipmi_si acpi_cpufreq vfat fat binfmt_misc xfs libcrc32c sd_mod sg crc32c_intel ahci igb libahci i2c_algo_bit libata dca nvme nvme_core t10_pi dm_mirror dm_region_hash dm_log dm_mod ipmi_devintf ipmi_msghandler fuse [last unloaded: spl]
[699334.315888] CPU: 20 PID: 1042641 Comm: insmod Kdump: loaded Tainted: P        W  OE    --------- -  - 4.18.0-408.el8.x86_64 #1
[699334.327345] Hardware name: GIGABYTE R272-Z32-00/MZ32-AR0-00, BIOS R21 10/08/2020
[699334.334815] RIP: 0010:remove_proc_entry+0x15c/0x170
[699334.339773] Code: 48 8b 53 78 4c 8b 80 a0 00 00 00 48 8b 92 a0 00 00 00 e8 f0 90 d1 ff 0f 0b eb 86 48 89 ee 48 c7 c7 40 f5 90 8b e8 dd 90 d1 ff <0f> 0b e9 78 ff ff ff e8 d8 8d d1 ff 0f 1f 84 00 00 00 00 00 0f 1f
[699334.358596] RSP: 0018:ffffb599b2bf7c70 EFLAGS: 00010282
[699334.363902] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[699334.371113] RDX: ffff9ce36e526e80 RSI: ffff9ce36e516658 RDI: ffff9ce36e516658
[699334.378330] RBP: ffffffffc06b12fb R08: 0000000000000000 R09: c0000000ffff7fff
[699334.385540] R10: 0000000000000001 R11: ffffb599b2bf7a88 R12: ffffffff8c49a8c0
[699334.392751] R13: ffffffffc06bc258 R14: ffffffffc06bc410 R15: 0000000000000000
[699334.399962] FS:  00007f2b2f237740(0000) GS:ffff9ce36e500000(0000) knlGS:0000000000000000
[699334.408125] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[699334.413951] CR2: 0000564fa693c058 CR3: 000000051ab9a000 CR4: 0000000000350ee0
[699334.421162] Call Trace:
[699334.423692]  ? spl_random_init+0x173/0x173 [spl]
[699334.428409]  spl_proc_init+0x159/0x1c0 [spl]
[699334.432773]  spl_init+0x46/0xe8d [spl]
[699334.436623]  do_one_initcall+0x46/0x1d0
[699334.440547]  ? do_init_module+0x22/0x220
[699334.444553]  ? kmem_cache_alloc_trace+0x142/0x280
[699334.449339]  do_init_module+0x5a/0x220
[699334.453177]  load_module+0x14ba/0x17f0
[699334.457010]  ? __do_sys_finit_module+0xb1/0x110
[699334.461626]  __do_sys_finit_module+0xb1/0x110
[699334.466063]  do_syscall_64+0x5b/0x1a0
[699334.469808]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[699334.474939] RIP: 0033:0x7f2b2e14e9bd
[699334.478594] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9b 64 38 00 f7 d8 64 89 01 48
[699334.497419] RSP: 002b:00007ffe56275c98 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[699334.505064] RAX: ffffffffffffffda RBX: 0000564fa69397e0 RCX: 00007f2b2e14e9bd
[699334.512274] RDX: 0000000000000000 RSI: 0000564fa5ae88b6 RDI: 0000000000000003
[699334.519484] RBP: 0000564fa5ae88b6 R08: 0000000000000000 R09: 00007f2b2e4d8740
[699334.526696] R10: 0000000000000003 R11: 0000000000000246 R12: 0000000000000000
[699334.533907] R13: 0000564fa69397b0 R14: 0000000000000000 R15: 0000000000000000
[699334.541119] ---[ end trace ef62332069acbbd2 ]---
[699334.545827] ------------[ cut here ]------------
[699334.550531] name 'kmem'
[699334.553074] WARNING: CPU: 20 PID: 1042641 at fs/proc/generic.c:672 remove_proc_entry+0x15c/0x170
[699334.561936] Modules linked in: spl(OE+) loop ipmi_ssif sunrpc intel_rapl_msr intel_rapl_common amd64_edac_mod edac_mce_amd amd_energy kvm_amd kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel ast rapl drm_vram_helper pcspkr drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops sp5100_tco drm acpi_ipmi ccp k10temp ptdma i2c_piix4 ipmi_si acpi_cpufreq vfat fat binfmt_misc xfs libcrc32c sd_mod sg crc32c_intel ahci igb libahci i2c_algo_bit libata dca nvme nvme_core t10_pi dm_mirror dm_region_hash dm_log dm_mod ipmi_devintf ipmi_msghandler fuse [last unloaded: spl]
[699334.615026] CPU: 20 PID: 1042641 Comm: insmod Kdump: loaded Tainted: P        W  OE    --------- -  - 4.18.0-408.el8.x86_64 #1
[699334.626490] Hardware name: GIGABYTE R272-Z32-00/MZ32-AR0-00, BIOS R21 10/08/2020
[699334.633964] RIP: 0010:remove_proc_entry+0x15c/0x170
[699334.638930] Code: 48 8b 53 78 4c 8b 80 a0 00 00 00 48 8b 92 a0 00 00 00 e8 f0 90 d1 ff 0f 0b eb 86 48 89 ee 48 c7 c7 40 f5 90 8b e8 dd 90 d1 ff <0f> 0b e9 78 ff ff ff e8 d8 8d d1 ff 0f 1f 84 00 00 00 00 00 0f 1f
[699334.657759] RSP: 0018:ffffb599b2bf7c70 EFLAGS: 00010282
[699334.663064] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[699334.670274] RDX: ffff9ce36e526e80 RSI: ffff9ce36e516658 RDI: ffff9ce36e516658
[699334.677484] RBP: ffffffffc06b12f6 R08: 0000000000000000 R09: c0000000ffff7fff
[699334.684697] R10: 0000000000000001 R11: ffffb599b2bf7a88 R12: ffffffff8c49a8c0
[699334.691908] R13: ffffffffc06bc258 R14: ffffffffc06bc410 R15: 0000000000000000
[699334.699117] FS:  00007f2b2f237740(0000) GS:ffff9ce36e500000(0000) knlGS:0000000000000000
[699334.707282] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[699334.713104] CR2: 0000564fa693c058 CR3: 000000051ab9a000 CR4: 0000000000350ee0
[699334.720318] Call Trace:
[699334.722848]  ? spl_random_init+0x173/0x173 [spl]
[699334.727570]  spl_proc_init+0x16c/0x1c0 [spl]
[699334.731939]  spl_init+0x46/0xe8d [spl]
[699334.735788]  do_one_initcall+0x46/0x1d0
[699334.739711]  ? do_init_module+0x22/0x220
[699334.743715]  ? kmem_cache_alloc_trace+0x142/0x280
[699334.748500]  do_init_module+0x5a/0x220
[699334.752330]  load_module+0x14ba/0x17f0
[699334.756162]  ? __do_sys_finit_module+0xb1/0x110
[699334.760773]  __do_sys_finit_module+0xb1/0x110
[699334.765211]  do_syscall_64+0x5b/0x1a0
[699334.768964]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[699334.774101] RIP: 0033:0x7f2b2e14e9bd
[699334.777761] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9b 64 38 00 f7 d8 64 89 01 48
[699334.796592] RSP: 002b:00007ffe56275c98 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[699334.804236] RAX: ffffffffffffffda RBX: 0000564fa69397e0 RCX: 00007f2b2e14e9bd
[699334.811445] RDX: 0000000000000000 RSI: 0000564fa5ae88b6 RDI: 0000000000000003
[699334.818655] RBP: 0000564fa5ae88b6 R08: 0000000000000000 R09: 00007f2b2e4d8740
[699334.825871] R10: 0000000000000003 R11: 0000000000000246 R12: 0000000000000000
[699334.833088] R13: 0000564fa69397b0 R14: 0000000000000000 R15: 0000000000000000
[699334.840298] ---[ end trace ef62332069acbbd3 ]---
[699334.845002] ------------[ cut here ]------------
[699334.849705] name 'taskq-all'
[699334.852682] WARNING: CPU: 20 PID: 1042641 at fs/proc/generic.c:672 remove_proc_entry+0x15c/0x170
[699334.861550] Modules linked in: spl(OE+) loop ipmi_ssif sunrpc intel_rapl_msr intel_rapl_common amd64_edac_mod edac_mce_amd amd_energy kvm_amd kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel ast rapl drm_vram_helper pcspkr drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops sp5100_tco drm acpi_ipmi ccp k10temp ptdma i2c_piix4 ipmi_si acpi_cpufreq vfat fat binfmt_misc xfs libcrc32c sd_mod sg crc32c_intel ahci igb libahci i2c_algo_bit libata dca nvme nvme_core t10_pi dm_mirror dm_region_hash dm_log dm_mod ipmi_devintf ipmi_msghandler fuse [last unloaded: spl]
[699334.914640] CPU: 20 PID: 1042641 Comm: insmod Kdump: loaded Tainted: P        W  OE    --------- -  - 4.18.0-408.el8.x86_64 #1
[699334.926097] Hardware name: GIGABYTE R272-Z32-00/MZ32-AR0-00, BIOS R21 10/08/2020
[699334.933567] RIP: 0010:remove_proc_entry+0x15c/0x170
[699334.938525] Code: 48 8b 53 78 4c 8b 80 a0 00 00 00 48 8b 92 a0 00 00 00 e8 f0 90 d1 ff 0f 0b eb 86 48 89 ee 48 c7 c7 40 f5 90 8b e8 dd 90 d1 ff <0f> 0b e9 78 ff ff ff e8 d8 8d d1 ff 0f 1f 84 00 00 00 00 00 0f 1f
[699334.957348] RSP: 0018:ffffb599b2bf7c70 EFLAGS: 00010282
[699334.962652] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[699334.969862] RDX: ffff9ce36e526e80 RSI: ffff9ce36e516658 RDI: ffff9ce36e516658
[699334.977084] RBP: ffffffffc06b12ec R08: 0000000000000000 R09: c0000000ffff7fff
[699334.984294] R10: 0000000000000001 R11: ffffb599b2bf7a88 R12: ffffffff8c49a8c0
[699334.991503] R13: ffffffffc06bc258 R14: ffffffffc06bc410 R15: 0000000000000000
[699334.998715] FS:  00007f2b2f237740(0000) GS:ffff9ce36e500000(0000) knlGS:0000000000000000
[699335.006880] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[699335.012702] CR2: 0000564fa693c058 CR3: 000000051ab9a000 CR4: 0000000000350ee0
[699335.019914] Call Trace:
[699335.022444]  ? spl_random_init+0x173/0x173 [spl]
[699335.027159]  spl_proc_init+0x17f/0x1c0 [spl]
[699335.031526]  spl_init+0x46/0xe8d [spl]
[699335.035374]  do_one_initcall+0x46/0x1d0
[699335.039294]  ? do_init_module+0x22/0x220
[699335.043305]  ? kmem_cache_alloc_trace+0x142/0x280
[699335.048089]  do_init_module+0x5a/0x220
[699335.051919]  load_module+0x14ba/0x17f0
[699335.055752]  ? __do_sys_finit_module+0xb1/0x110
[699335.060368]  __do_sys_finit_module+0xb1/0x110
[699335.064808]  do_syscall_64+0x5b/0x1a0
[699335.068559]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[699335.073689] RIP: 0033:0x7f2b2e14e9bd
[699335.077348] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9b 64 38 00 f7 d8 64 89 01 48
[699335.096180] RSP: 002b:00007ffe56275c98 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[699335.103825] RAX: ffffffffffffffda RBX: 0000564fa69397e0 RCX: 00007f2b2e14e9bd
[699335.111036] RDX: 0000000000000000 RSI: 0000564fa5ae88b6 RDI: 0000000000000003
[699335.118244] RBP: 0000564fa5ae88b6 R08: 0000000000000000 R09: 00007f2b2e4d8740
[699335.125455] R10: 0000000000000003 R11: 0000000000000246 R12: 0000000000000000
[699335.132666] R13: 0000564fa69397b0 R14: 0000000000000000 R15: 0000000000000000
[699335.139882] ---[ end trace ef62332069acbbd4 ]---
[699335.144590] ------------[ cut here ]------------
[699335.149291] name 'taskq'
[699335.151920] WARNING: CPU: 20 PID: 1042641 at fs/proc/generic.c:672 remove_proc_entry+0x15c/0x170
[699335.160783] Modules linked in: spl(OE+) loop ipmi_ssif sunrpc intel_rapl_msr intel_rapl_common amd64_edac_mod edac_mce_amd amd_energy kvm_amd kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel ast rapl drm_vram_helper pcspkr drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops sp5100_tco drm acpi_ipmi ccp k10temp ptdma i2c_piix4 ipmi_si acpi_cpufreq vfat fat binfmt_misc xfs libcrc32c sd_mod sg crc32c_intel ahci igb libahci i2c_algo_bit libata dca nvme nvme_core t10_pi dm_mirror dm_region_hash dm_log dm_mod ipmi_devintf ipmi_msghandler fuse [last unloaded: spl]
[699335.213883] CPU: 20 PID: 1042641 Comm: insmod Kdump: loaded Tainted: P        W  OE    --------- -  - 4.18.0-408.el8.x86_64 #1
[699335.225347] Hardware name: GIGABYTE R272-Z32-00/MZ32-AR0-00, BIOS R21 10/08/2020
[699335.232818] RIP: 0010:remove_proc_entry+0x15c/0x170
[699335.237783] Code: 48 8b 53 78 4c 8b 80 a0 00 00 00 48 8b 92 a0 00 00 00 e8 f0 90 d1 ff 0f 0b eb 86 48 89 ee 48 c7 c7 40 f5 90 8b e8 dd 90 d1 ff <0f> 0b e9 78 ff ff ff e8 d8 8d d1 ff 0f 1f 84 00 00 00 00 00 0f 1f
[699335.256609] RSP: 0018:ffffb599b2bf7c70 EFLAGS: 00010282
[699335.261919] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[699335.269130] RDX: ffff9ce36e526e80 RSI: ffff9ce36e516658 RDI: ffff9ce36e516658
[699335.276340] RBP: ffffffffc06b122b R08: 0000000000000000 R09: c0000000ffff7fff
[699335.283553] R10: 0000000000000001 R11: ffffb599b2bf7a88 R12: ffffffff8c49a8c0
[699335.290765] R13: ffffffffc06bc258 R14: ffffffffc06bc410 R15: 0000000000000000
[699335.297981] FS:  00007f2b2f237740(0000) GS:ffff9ce36e500000(0000) knlGS:0000000000000000
[699335.306145] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[699335.311971] CR2: 0000564fa693c058 CR3: 000000051ab9a000 CR4: 0000000000350ee0
[699335.319180] Call Trace:
[699335.321711]  ? spl_random_init+0x173/0x173 [spl]
[699335.326425]  spl_proc_init+0x192/0x1c0 [spl]
[699335.330794]  spl_init+0x46/0xe8d [spl]
[699335.334641]  do_one_initcall+0x46/0x1d0
[699335.338560]  ? do_init_module+0x22/0x220
[699335.342564]  ? kmem_cache_alloc_trace+0x142/0x280
[699335.347347]  do_init_module+0x5a/0x220
[699335.351177]  load_module+0x14ba/0x17f0
[699335.355012]  ? __do_sys_finit_module+0xb1/0x110
[699335.359628]  __do_sys_finit_module+0xb1/0x110
[699335.364066]  do_syscall_64+0x5b/0x1a0
[699335.367817]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[699335.372950] RIP: 0033:0x7f2b2e14e9bd
[699335.376614] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9b 64 38 00 f7 d8 64 89 01 48
[699335.395439] RSP: 002b:00007ffe56275c98 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[699335.403082] RAX: ffffffffffffffda RBX: 0000564fa69397e0 RCX: 00007f2b2e14e9bd
[699335.410293] RDX: 0000000000000000 RSI: 0000564fa5ae88b6 RDI: 0000000000000003
[699335.417505] RBP: 0000564fa5ae88b6 R08: 0000000000000000 R09: 00007f2b2e4d8740
[699335.424723] R10: 0000000000000003 R11: 0000000000000246 R12: 0000000000000000
[699335.431934] R13: 0000564fa69397b0 R14: 0000000000000000 R15: 0000000000000000
[699335.439146] ---[ end trace ef62332069acbbd5 ]---
[699335.443860] ------------[ cut here ]------------
[699335.448570] name 'spl'
[699335.451026] WARNING: CPU: 20 PID: 1042641 at fs/proc/generic.c:672 remove_proc_entry+0x15c/0x170
[699335.459892] Modules linked in: spl(OE+) loop ipmi_ssif sunrpc intel_rapl_msr intel_rapl_common amd64_edac_mod edac_mce_amd amd_energy kvm_amd kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel ast rapl drm_vram_helper pcspkr drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops sp5100_tco drm acpi_ipmi ccp k10temp ptdma i2c_piix4 ipmi_si acpi_cpufreq vfat fat binfmt_misc xfs libcrc32c sd_mod sg crc32c_intel ahci igb libahci i2c_algo_bit libata dca nvme nvme_core t10_pi dm_mirror dm_region_hash dm_log dm_mod ipmi_devintf ipmi_msghandler fuse [last unloaded: spl]
[699335.512975] CPU: 20 PID: 1042641 Comm: insmod Kdump: loaded Tainted: P        W  OE    --------- -  - 4.18.0-408.el8.x86_64 #1
[699335.524433] Hardware name: GIGABYTE R272-Z32-00/MZ32-AR0-00, BIOS R21 10/08/2020
[699335.531905] RIP: 0010:remove_proc_entry+0x15c/0x170
[699335.536874] Code: 48 8b 53 78 4c 8b 80 a0 00 00 00 48 8b 92 a0 00 00 00 e8 f0 90 d1 ff 0f 0b eb 86 48 89 ee 48 c7 c7 40 f5 90 8b e8 dd 90 d1 ff <0f> 0b e9 78 ff ff ff e8 d8 8d d1 ff 0f 1f 84 00 00 00 00 00 0f 1f
[699335.555703] RSP: 0018:ffffb599b2bf7c70 EFLAGS: 00010282
[699335.561005] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[699335.568216] RDX: ffff9ce36e526e80 RSI: ffff9ce36e516658 RDI: ffff9ce36e516658
[699335.575427] RBP: ffffffffc06b12e8 R08: 0000000000000000 R09: c0000000ffff7fff
[699335.582639] R10: 0000000000000001 R11: ffffb599b2bf7a88 R12: ffffffff8c49a8c0
[699335.589857] R13: ffffffffc06bc258 R14: ffffffffc06bc410 R15: 0000000000000000
[699335.597076] FS:  00007f2b2f237740(0000) GS:ffff9ce36e500000(0000) knlGS:0000000000000000
[699335.605242] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[699335.611073] CR2: 0000564fa693c058 CR3: 000000051ab9a000 CR4: 0000000000350ee0
[699335.618283] Call Trace:
[699335.620814]  ? spl_random_init+0x173/0x173 [spl]
[699335.625531]  spl_proc_init+0x1a0/0x1c0 [spl]
[699335.629897]  spl_init+0x46/0xe8d [spl]
[699335.633744]  do_one_initcall+0x46/0x1d0
[699335.637661]  ? do_init_module+0x22/0x220
[699335.641665]  ? kmem_cache_alloc_trace+0x142/0x280
[699335.646451]  do_init_module+0x5a/0x220
[699335.650280]  load_module+0x14ba/0x17f0
[699335.654115]  ? __do_sys_finit_module+0xb1/0x110
[699335.658730]  __do_sys_finit_module+0xb1/0x110
[699335.663169]  do_syscall_64+0x5b/0x1a0
[699335.666923]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[699335.672061] RIP: 0033:0x7f2b2e14e9bd
[699335.675717] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9b 64 38 00 f7 d8 64 89 01 48
[699335.694543] RSP: 002b:00007ffe56275c98 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[699335.702195] RAX: ffffffffffffffda RBX: 0000564fa69397e0 RCX: 00007f2b2e14e9bd
[699335.709412] RDX: 0000000000000000 RSI: 0000564fa5ae88b6 RDI: 0000000000000003
[699335.716623] RBP: 0000564fa5ae88b6 R08: 0000000000000000 R09: 00007f2b2e4d8740
[699335.723834] R10: 0000000000000003 R11: 0000000000000246 R12: 0000000000000000
[699335.731044] R13: 0000564fa69397b0 R14: 0000000000000000 R15: 0000000000000000
[699335.738256] ---[ end trace ef62332069acbbd6 ]---
```

### Description

Just reverting b35374f for now till this issue is resolved.

### How Has This Been Tested?

Ran `zfs.sh -v`. Sometimes you have to run it twice, such as doing `zfs.sh -v && zfs.sh -uv && zfs.sh -v` for the error to trigger.

CentOS Stream release 8
Kernel: 4.18.0-408.el8.x86_64

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by bwatkinson** [comment]
@ckane can you take a look at this.

**Review by behlendorf — APPROVED** [review]

**Comment by ckane** [comment]
Yeah I can take a look - is this only happening on Linux 4.18/CentOS 8, or also has this been repeated on newer systems? @bwatkinson can you share the `zfs_config.h` that was generated by your build on the affected system? I'm suspecting maybe a leak in the cleanup code?

**Comment by ckane** [comment]
also another question: do you need ZFS pools imported to repeat this behavior? Or does it crash with no active pools?

**Comment by adamdmoss** [comment]
I also see these spl_init hangs, on Ubuntu 22.04.2, kernel 6.2.xxx (6.2.0-1009-lowlatency).  Will retest now that the backout has landed.

**Comment by ckane** [comment]
*sigh*

```
AC_DEFINE(HAVE_SYSCTL_REGISTER_TABLE
```

and

```c
#ifdef HAVE_REGISTER_SYSCTL_TABLE
```

Gonna verify fixing this typo corrects the problem and then I'll re-PR.

**Comment by adamdmoss** [comment]
Yeah, much better after the backout. :)  Cheers.

**Comment by ckane** [comment]
Here's the new PR with the typo fixed: #15138 15138

**Comment by ckane** [comment]
Thanks everyone for catching this one and for providing the helpful feedback here!

**Pull request merged**
