### PR TITLE
zfs-2.2.2 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Patchset for 2.2.2.  This release includes the fix for dirty dbuf corruption: https://github.com/openzfs/zfs/issues/15526

### Description
Include fix for data corruption.  Full details in: https://github.com/openzfs/zfs/issues/15526.  Other fixes also included.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by robn — APPROVED** [review]

**Review by amotin — APPROVED** [review]
Looks good to me, but I've just found and fixed one more simple block cloning issue, that would be nice to include: https://github.com/openzfs/zfs/pull/15603 .

**Comment by AllKind** [comment]
@tonyhutter Two other things:
Would it be possible to add a note to the release notes, as proposed in https://github.com/openzfs/zfs/issues/15575 ?

Regarding:
https://github.com/openzfs/zfs/issues/15404 and https://github.com/openzfs/zfs/issues/15586

I just verified myself, when using the tarball https://github.com/openzfs/zfs/releases/download/zfs-2.2.1/zfs-2.2.1.tar.gz, make native-deb-utils fails:

```
make native-deb-utils 
cp -r contrib/debian debian; chmod +x debian/rules;
cp contrib/debian/control debian/control; \
dpkg-buildpackage -b -rfakeroot -us -uc;
cp: cannot stat 'contrib/debian/control': No such file or directory
dpkg-buildpackage: error: cannot read debian/control: No such file or directory
make: *** [Makefile:14364: native-deb-utils] Error 255
```

Would be nice not to carry that problem into the next (now 3rd) release.

**Comment by KungFuJesus** [comment]
Github's mention tracking kind of makes this redundant but... probably worth including:
https://github.com/openzfs/zfs/commit/acb33ee1c169bf1c1f687db18fa1815ffa68f246

**Comment by mmatuska** [comment]
Please include #15546 too

**Comment by telsasoft** [comment]
Just curious if you'll also revert [Disable block cloning by default](https://github.com/openzfs/zfs/commit/479dca51c66a731e637bd2d4f9bba01a05f9ac9f) here/now/later.

**Comment by FL140** [comment]
> Just curious if you'll also revert [Disable block cloning by default](https://github.com/openzfs/zfs/commit/479dca51c66a731e637bd2d4f9bba01a05f9ac9f) here/now/later.

I would be also interested if this would be safe to enable again, since from my understanding block cloning was not responsible for the data loss problems after all, but just increased the possibility for corruption. If I understand it correctly the real bug got fixed in https://github.com/openzfs/zfs/pull/15571 which is included in the commits for 2.2.2.
If I got that right it should be safe to enable block cloning again without problems, right?

**Comment by amotin** [comment]
@telsasoft @FL140 The idea is to re-enable block cloning in some of the following 2.2 releases. 2.2.2 includes number of block cloning fixes too, making it more robust.  But at least https://github.com/openzfs/zfs/pull/15617 I couldn't get in time, the issue @ixhamza found just yesterday.  Though we are getting to more and more rare cases and could now benefit from another round of tests.

**Comment by FL140** [comment]
Great, I a absolutely appreciate testing. I have no issue with having the feature disabled until this is rock solid. So since I upgraded the pools as recommended after the upgrade to Ubuntu 23.10 I have to ask to make sure this is the correct approach now.

2.2.1 disabled the block cloning feature by just ignoring the setting all the time, correct? So we DON'T? need to set `zfs_bclone_enabled=0` in addition. That way the feature will get activated when the hotfix get's removed in an upstream version.

In addition `zfs_dmu_offset_next_sync=0` is not required any longer after upgrade to 2.2.2 as that one got fixed in the release.

I am sure about `zfs_dmu_offset_next_sync` but can someone of the devs please confirm on `zfs_bclone_enabled`? THX

**Comment by robn** [comment]
@FL140 yes, the 2.2.2 defaults are `zfs_bclone_enabled=0` and `zfs_dmu_offset_next_sync=1`, and we believe those settings to be totally safe.

**Comment by FL140** [comment]
> @FL140 yes, the 2.2.2 defaults are `zfs_bclone_enabled=0` and `zfs_dmu_offset_next_sync=1`, and we believe those settings to be totally safe.

Thank's for confirming, unfortunately I just ran in a really bad "... uncorrectable I/O failure and failure mode property for this pool is set to panic." after using the 2.2.2 branch from @tonyhutter with this patchset!

* I build a Ubuntu package from that branch without applying additional settings or patches.
* Then I resarted the computer, everything looked good.
* Then I ran the script https://github.com/0x5c/zfs-bclonecheck to get an idea which files have been cloned after the feature got enabled.
* That led to the error above and a crashed system.
* Brave enough I restarted the computer and (very unexpectedly) the computer booted, and I am writing those lines from a running system where `zpool status` tells me `errors: No known data errors`.

Honestly I am really trying to keep being positive here after the last to weeks, but this is getting more frustrating by every day. Upgrading to a stable Distro should never end up in such a f**k*p, sorry but I am getting frustrated right now and need a stable systems again ASAP.

Trying to being rational I will investigate this further in ~9h to add as much info as possible, but I will have to dd the disk prior any further steps, this is getting to dangerous.

So right now I can't tell if this is caused by any of the patches, but my guess would be that due to the "block cloning" bug (which we now know has a different background) there is a problem with the cloned data!? which was produced since 2.2.0 and prior 2.2.2. But I can't tell if that is the case. If anyone can point me in the right direction I am happy to investigate. But I really need a working machines again within the next days.

**Comment by FL140** [comment]
I ran the script in https://github.com/openzfs/zfs/issues/15586#issuecomment-1827585952 to build the packages.

**Comment by FL140** [comment]
Noted that 2.2.2 just got released while I ran into that, I will compile the packages again with the official 2.2.2, but I guess the result will be the same as the patchset is the same in the official 2.2.2 branch and in @tonyhutter 2.2.2 branch, or did I miss something?

**Comment by 0x5c** [comment]
> Then I ran the script https://github.com/0x5c/zfs-bclonecheck to get an idea which files have been cloned after the feature got enabled.

Did the script output anything? If so, did it get to print the list of paths? At least that could give an idea what zdb invocation in the script triggered it.

**Comment by FL140** [comment]
> > Then I ran the script https://github.com/0x5c/zfs-bclonecheck to get an idea which files have been cloned after the feature got enabled.
> 
> Did the script output anything? If so, did it get to print the list of paths? At least that could give an idea what zdb invocation in the script triggered it.

Thanks for the fast reply. No the script crashed with the above message very early. I made a screenshot but I think it will not be of much help here. The exact output (retyped from screenshot except pool name) was:
```
$ ./bclonecheck.sh xyzpool
loading concrete vdev 0, metaslab 107 of 108 ...
error: error: error: Pool 'xyzpool' has encountered an uncorrectable I/O failure and the failure mode property for this pool is set to panic.
Pool 'xyzpool' has encountered an uncorrectable I/O failure and the failure mode property for this pool is set to panic.
```

**Comment by 0x5c** [comment]
> `loading concrete vdev 0, metaslab 107 of 108 ...`

This output is not from the first zdb invocation. Since it is the only one touches the BRT (ie: block cloning), this **seems to exclude any bug related to block cloning** or the new zdb feature to dump the BRT.

The rest of the script is one long series of pipes which 
1. Dumps the entire list of blocks in the pool
2. Uses standard utilities to filter only the blocks that match DVAs dumped from the BRT and extract only the dataset and object IDs
3. Runs `zfs_ids_to_path` with the IDs through xargs
4. Breaks the lines into two columns using `column`

With that output, the failure could be just before or during 1), or one of the `zfs_ids_to_path` invocations in 3). It's hard to tell since 4) doesn't stream and waits to have received the full input before making columns.

If you try again, do this change to the script
```diff
-... | xargs -n2 zfs_ids_to_path -v "$zpool" | column -ts: -N DATASET,PATH -l2
+... | xargs -n2 zfs_ids_to_path -v "$zpool"
```

**Comment by FL140** [comment]
> > `loading concrete vdev 0, metaslab 107 of 108 ...`
> 
> This output is not from the first zdb invocation. Since it is the only one touches the BRT (ie: block cloning), this **seems to exclude any bug related to block cloning** or the new zdb feature to dump the BRT.
> 
> The rest of the script is one long series of pipes which
> 
> 1. Dumps the entire list of blocks in the pool
> 2. Uses standard utilities to filter only the blocks that match DVAs dumped from the BRT and extract only the dataset and object IDs
> 3. Runs `zfs_ids_to_path` with the IDs through xargs
> 4. Breaks the lines into two columns using `column`
> 
> With that output, the failure could be just before or during 1), or one of the `zfs_ids_to_path` invocations in 3). It's hard to tell since 4) doesn't stream and waits to have received the full input before making columns.
> 
> If you try again, do this change to the script
> 
> ```diff
> -... | xargs -n2 zfs_ids_to_path -v "$zpool" | column -ts: -N DATASET,PATH -l2
> +... | xargs -n2 zfs_ids_to_path -v "$zpool"
> ```
> 
> EDIT: Just to make sure, also add `cat "${tempdir}/dvas.txt"` on line 46

Thank's for the input, actually I am in the *lucky* position, that I am quite good with shell scripts, so I WILL investigate this for sure, but after a very long night I will fist dd the whole SSD prior any further steps. So expect feedback in the next days.

**Comment by FL140** [comment]
> @FL140 its unclear to me if you are seeing errors on the _released_ 2.2.2, please confirm? If so, is it only coming from `zdb`, or from the kernel on your imported pool?

@robn While that happened with the tonyhutter branch of 2.2.2 this should be the same as the released 2.2.2. Which I build, installed just after the tonyhutter branch and I am running at the moment. The commits are exactly the same. As written I will investigate this in depth over the next days, but I want to dd the 1.7TB pool prior that. Then I will run the script again and report the results back. I will also disect the script and trace where it happens, if it happens again.

What I really don't get though is that I get the message that the pool is in a panic mode and after a reboot it is happy working as nothing ever happened and `zpool status` also doesn't report an error.

**Comment by robn** [comment]
> What I really don't get though is that I get the message that the pool is in a panic mode and after a reboot it is happy working as nothing ever happened and zpool status also doesn't report an error.

That's why I asked if you got this from `zdb`, or from the kernel?

**Comment by FL140** [comment]
@robn disecting 0x5c:zfs-bclonecheck.git/bclonecheck.sh:

```
zdb -TTT rpool > /home/junk/wrk/202311xx_zfs_bclone_bug/zdb_-TTT_rpool.txt 2>&1
```
runs without an error and produces the file content:
```
BRT: used 242M; saved 268M; ratio 2.10x
BRT: vdev 0: refcnt 2.96K; used 242M; saved 268M

DVA              REFCNT
0:95c74b6000     1
0:e367d98000     11
0:11290a8a000    8
0:16f11346000    1
0:55678b8000     1
0:12ea7f88000    1
0:19a2eea4000    1
0:135279a0000    1
0:19a2c178000    1
0:13526fe8000    1
0:13e20948000    1
0:135dca20000    1
0:1412ae80000    1
0:16f10ea6000    1
0:126ffe86000    1
0:13156380000    1
0:12e32d30000    1
0:16f1083e000    1
0:12e31d6a000    1
0:b574f5e000     1
0:19710aac000    1
0:19a1fe00000    1 
0:1816f10c000    1
0:135395b8000    1
0:1a32a184000    1
0:19a23486000    1 
0:12e328d6000    1
0:1357e174000    1
0:95c7336000     1
0:12bb6d7a000    1
0:13526ef0000    1
0:19a2d628000    1
0:19a1f4b0000    1
0:12554cca000    1
0:14068298000    1
0:19a2b69c000    1
0:1328b224000    1
0:12d1727e000    1
0:16f0f9f4000    1
0:1352f10a000    1
0:16f08174000    1
0:172ccbda000    1
0:19a2e1c0000    1
0:19a22ffe000    1
0:13c82cc4000    14
0:13526558000    1
0:136a6d3c000    3
0:135eec74000    1
0:16f10926000    1
0:19a1f6d6000    1
...
```

**Comment by 0x5c** [comment]
> runs without an error and produces the file content:

That's the only part we already knew works, it's everything else that isn't clear

**Comment by FL140** [comment]
> > runs without an error and produces the file content:
> 
> That's the only part we already knew works, it's everything else that isn't clear
@0x5c Trying to be brave here, but running, crashing and rebooting takes time... I also ran `zdb -bbb -vvv rpool` and piped the output into a file. The command runns for a while an produces a lot of output the last lines are:
```
objset 2599 object 681556 level 0 offset 0x0 DVA[0]=<0:e5b6312000:4000> [L0 ZFS plain file] fletcher4 uncompressed unencrypted LE contiguous unique single size=2a00L/2a00P birth=3037L/3037P fill=1 cksum=000004b481acec6a:0019be5dce474a76:59995f394f4d41e5:b4a59628ffa2de73
objset 2599 object 681558 level 0 offset 0x0 DVA[0]=<0:e5b6316000:16000> [L0 ZFS plain file] fletcher4 uncompressed unencrypted LE contiguous unique single size=15200L/15200P birth=3037L/3037P fill=1 cksum=000023cb3739a922:056dd8676eb9838c:6fdb243beb3694a2:c9f579861a026a5f
objset 2599 object 681560 level 0 offset 0x0 DVA[0]=<0:dd9a03e000:8000> [L0 ZFS plain file] fletcher4 uncompressed unencrypted LE contiguous unique single size=7a00L/7a00P birth=3037L/3037P fill=1 cksum=00000e91e361d955:00e0247e264f3287:e95ef021a16b879c:b548a146581c7c1a
objset 2599 object 681562 level 0 offset 0x0 DVA[0]=<0:dd9a046000:14000> [L0 ZFS plain file] fletcher4 uncompressed unencrypted LE contiguous unique single size=12e00L/12e00P birth=3037L/3037P fill=1 cksum=00002010b9374856:044749cdc30778c4:1d32532cc28b4b9e:90f3ced384692d70
objset 2599 object 681564 level 0 offset 0x0 DVA[0]=<0:c8d7f3e000:2000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=3200L/2000P birth=3037L/3037P fill=1 cksum=000001b2fc6fcf73:000a38b09c05f58d:1fc5dd9fe340c1b1:d19da9daf072e7b5
objset 2599 object 681566 level 0 offset 0x0 DVA[0]=<0:d069fd2000:c000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=d800L/c000P birth=3037L/3037P fill=1 cksum=00001669f83a735d:0232dd1493502c0f:723e8ba7ad602441:403bfa38ee32afde
objset 2599 object 0 level 0 offset 0x14ccc000 DVA[0]=<0:e5b7ece000:2000> DVA[1]=<0:4817ca0000:2000> [L0 DMU dnode] fletcher4 lz4 unencrypted LE contiguous unique double size=4000L/2000P birth=3037L/3037P fill=16 cksum=00000063de0f58e8:0002d884acc610f1:0a6973e77175480b:797dbe666cc2f7a2
objset 2599 object 681568 level 0 offset 0x0 DVA[0]=<0:e5b632c000:4000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=5200L/4000P birth=3037L/3037P fill=1 cksum=0000062a7f582e76:003c12084343a468:4ca8e764b6c23efb:b46a9922e0803acd
objset 2599 object 681570 level 0 offset 0x0 DVA[0]=<0:dd9a034000:2000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=3600L/2000P birth=3037L/3037P fill=1 cksum=000002cff59dfb73:000eda27835750ca:2b07894ba7d25ea4:3016558a82029269
objset 2599 object 681572 level 0 offset 0x0 DVA[0]=<0:dd9a05a000:8000> [L0 ZFS plain file] fletcher4 uncompressed unencrypted LE contiguous unique single size=6a00L/6a00P birth=3037L/3037P fill=1 cksum=00000c91ceefa2c8:00a7fd51175d0128:cb0f19abbc77c062:990da7cbed68e69f
objset 2599 object 681574 level 0 offset 0x0 DVA[0]=<0:e5b6330000:6000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=7800L/6000P birth=3037L/3037P fill=1 cksum=00000a91bf829d7f:0089e2ab8c5afdc8:5c884fcd9ae81bb7:bbec7afdde761e9b
objset 2599 object 681576 level 0 offset 0x0 DVA[0]=<0:c8d7f40000:4000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=4400L/4000P birth=3037L/3037P fill=1 cksum=00000435125513bd:003122a98aeec693:2c129628b122d35e:1b70c74f66d30b4c
objset 2599 object 681578 level 0 offset 0x0 DVA[0]=<0:c8d7f44000:2000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=3a00L/2000P birth=3037L/3037P fill=1 cksum=000002a8c0b7a71d:000d5d8a44e1df03:259df52eda052b5a:95e5799d2f115763
objset 2599 object 681580 level 0 offset 0x0 DVA[0]=<0:e5b6336000:2000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=3200L/2000P birth=3037L/3037P fill=1 cksum=0000021059d2b65f:000c09f6e28ebe02:24c4347119c75ab3:f16e1db5e6b19ef6
objset 2599 object 681582 level 0 offset 0x0 DVA[0]=<0:dd9a062000:6000> [L0 ZFS plain file] fletcher4 uncompressed unencrypted LE contiguous unique single size=4600L/4600P birth=3037L/3037P fill=1 cksum=00000851b46907fe:00491ee9c1d4b5c5:a94a0bc07f738bb5:fe9d40a2890f89b3
objset 2599 object 681584 level 0 offset 0x0 DVA[0]=<0:dd9a068000:2000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=3800L/2000P birth=3037L/3037P fill=1 cksum=00000269ab7edeb1:000cd46398c2786c:25372348cb655b47:df4acbb17f83db8f
objset 2599 object 681586 level 0 offset 0x0 DVA[0]=<0:d069fde000:2000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=2600L/2000P birth=3037L/3037P fill=1 cksum=0000008c92beae36:00040e16fe3fb8f4:0f035d3cf3ae2a6a:27d6553641ca00f0
objset 2599 object 681588 level 0 offset 0x0 DVA[0]=<0:d069fe0000:2000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=4000L/2000P birth=3037L/3037P fill=1 cksum=000003b571189581:000f9eea523970f1:2a4511d60f7e494c:47930f96ac19e121
objset 2599 object 681590 level 0 offset 0x0 DVA[0]=<0:e5b6338000:c000> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=ca00L/c000P birth=3037L/3037P fill=1 cksum=
```
Looking on that my first guess would be a bad checksum!? But then I don't know how often the output is flushed and if we are missing stuff at the end...

Any ideas on how to proceed from here?

**Comment by 0x5c** [comment]
Does it panic the system, exits, or stalls after those last lines? If it doesn't trigger a panic proper,  it's hard to tell without running the modified script if it is `zdb -bbb -vvv` itself crashing intermittently or `zfs_ids_to_path` choking on one of those objset/object ID pairs.

Also before you test the modified script, can you run `zdb -TTT "$zpool" | grep -Po '^[0-9a-f]+:[0-9a-f]+(?=\s)' > <somepath>/dvas.txt` in /bin/sh and check it *only* has the DVAs? We've already seen it won't crash, but I wonder if the DVAs are properly extracted.

**Comment by FL140** [comment]
> Does it panic the system, exits, or stalls after those last lines? If it doesn't trigger a panic proper, it's hard to tell without running the modified script if it is `zdb -bbb -vvv` itself crashing intermittently or `zfs_ids_to_path` choking on one of those objset/object ID pairs.
> 

I didn't run the script as a whole I took the relevant commands one after the other and analyzed the output. So I can confirm that `zdb -bbb -vvv` itself leads to the pool panic and then a system stall which can only be handled by a reboot. The output of `dvas.txt` looks correct to me. So when running `cat zdb_-bbb_-vvv_rpool.txt |grep 'level 0' | grep -wf dvas.txt | cut -d\  -f2,4 | xargs -n2 zfs_ids_to_path -v rpool| uniq -c | column -ts: -N COUNT,DATASET,PATH -l2` (Tweaked the output a bit to remove duplicated lines and get a count of them instead.) I get a list of effected files (86). so it is definitely `zdb -bbb -vvv` what triggers the zpool panic.

`zfs_ids_to_path` runs just fine.

> Also before you test the modified script, can you run `zdb -TTT "$zpool" | grep -Po '^[0-9a-f]+:[0-9a-f]+(?=\s)' > <somepath>/dvas.txt` **in /bin/sh** and check it _only_ has the DVAs? We've already seen it won't crash, but I wonder if the DVAs are properly extracted.

yes, they are as far as I can tell.

It boils down to the `zdb -bbb -vvv` command which encounters something that make it trigger the pool panic. So I guess it is zdb source code patching time, but I really have to make a break now. THX to anyone for the help so far in tracking this down.

**Pull request merged**
