### PR TITLE
Rewrite Makefile shellcheck rule to find all shellscripts

### PR DESCRIPTION
**Pull request by gdevenyi**
### Motivation and Context

As noted by #10510 a number of bashisms and related issues have crept into the shell scripts in the codebase. The current code does not successfully locate all shell scripts, and hence doesn't test all of them.

### Description

Rewrote the find code which locates shell scripts to explicitly pattern patch against the shebang of every file in order to locate sh/bash/dash/ksh scripts.

### How Has This Been Tested?

Tested locally on Ubuntu 18.04 it finds more shell scripts now, such as vdev_id 

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [X] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [X] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gdevenyi** [comment]
This change causes the ``make shellcheck`` to fail due to a large number of new issues it identifies, in particular, all of the tests have a huge number of ``note: Double quote to prevent globbing and word splitting. [SC2086]``

We could either exclude this check (probably bad idea, I think vdev_id needs to be fixed here) or fix all those files....

[shellcheck.log](https://github.com/openzfs/zfs/files/4847474/shellcheck.log)

**Comment by behlendorf** [comment]
> We could either exclude this check (probably bad idea, I think vdev_id needs to be fixed here) or fix all those files....

Initially we excluded some shell scripts while we focused on getting the rest ship shape.  The intention was to eventually expand shellcheck to all the scripts as you've done in this PR.  However, due to the number of scripts which need to be fixed I think a reasonable next step would be expand the shellcheck to all scripts _except_ the `.ksh` scripts for now.  We can get them in a subsequent pass.

**Comment by gdevenyi** [comment]
Okay, I will re-adjust the code to exclude ksh files.

**Comment by behlendorf** [comment]
> Okay, I will re-adjust the code to exclude ksh files.

Thanks.  You'll also need to make sure this PR fixes whatever issues are uncovered in the other scripts before we can merge it.  Otherwise we'll break the style check for everyone.

**Comment by gdevenyi** [comment]
> Thanks. You'll also need to make sure this PR fixes whatever issues are uncovered in the other scripts before we can merge it. Otherwise we'll break the style check for everyone.

I'll do my best to address the issues. It stands at 1766 excluding the tests so it'll take a while.

**Comment by gdevenyi** [comment]
Update, not as bad, only 259, all the shell scripts in config/ are auto-generated.

We'll have to fix those by auditing the m4 files, which for now I think is out-of-scope of this.

**Comment by mschilli87** [comment]
@gdevenyi: I should have some hours to spare this weekend an am familiar with POSIX shell. So if you have trivial work left by Friday evening and think another pair of hands would be useful, feel free to contact me. I'm just not sure if my help would be worth the extra effort for synchronizing between two people changing the code. So no hard feelings if I don't hear from you. :wink:

**Comment by gdevenyi** [comment]
Converting to a draft to avoid accidental merging like https://github.com/openzfs/zfs/pull/10513 before the bugs are fixed.

Considering #10736 I will not attempt to fix it up since it has a big rewrite and defer to that PR.

**Comment by gdevenyi** [comment]
@mschilli87 I would be happy to accept PRs on this branch on my fork if you want to help contribute to the fixes!

**Comment by gdevenyi** [comment]
Ref: https://github.com/dylanaraps/pure-sh-bible

**Pull request closed without merging**
