### PR TITLE
freebsd clone range fixes

### PR DESCRIPTION
**Pull request by mjguzik**
fixes EXDEV escaping to userspace and breaking tools like cp

    API contract requires VOPs to handle EXDEV internally, worst case by
    falling back to the generic copy routine. This broke with the recent
    changes.
    
    While here whack custom loop to lock 2 vnodes with vn_lock_pair, which
    provides the same functionality internally. write start/finish around
    it plays no role so got eliminated.
    
    One difference is that vn_lock_pair always takes an exclusive lock on
    both vnodes. I did not patch around it because current code takes an
    exclusive lock on the target vnode. zfs supports shared-locking for
    writes, so this serializes different calls to the routine as is, despite
    range locking inside. At the same time you may notice the source vnode
    can get some traffic if only shared-locked, thus once more this goes
    the safer route of exclusive-locking. Note this should be patched to
    use shared-locking for both once the feature is considered stable.
    
    Technically the switch to vn_lock_pair should be a separate change, but
    it would only introduce churn immediately whacked by the rest of the
    patch.

### CODE REVIEW

**Comment by mjguzik** [comment]
@mav @pjd

**Review by amotin — APPROVED** [review]

**Comment by mjguzik** [comment]
vn_lock_pair interface just changed, this will need an update which i'll be posting later

**Comment by mcmilk** [comment]
Could you please rebase this?

**Comment by behlendorf** [comment]
@mjguzik if you can rebase this PR and resolve the outstanding conflict I'll get it merged.  Thanks for sorting this out.

**Comment by mjguzik** [comment]
ops, will have to do it tomorrow, will require a build test for all archs

**Comment by mjguzik** [comment]
all done

**Review by behlendorf — APPROVED** [review]

**Pull request closed without merging**
