### PR TITLE
Resilver performance tuning

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Update the default values for two resilver tunings to maximize performance. These changes do increase the possible memory footprint but my feeling is the performance improvements are worth the tradeoff.  Note that neither the allowed number of outstanding I/Os has  changed (`zfs_vdev_scrub_max_active`) nor the non-interactive I/O tunables so this should not change interactive performance.

### Description

97cda28c9ae00a10427fbf62a8b7066dab6f0947 -  Increase default `zfs_rebuild_vdev_limit` to 64MB

When testing distributed rebuild performance with more capable hardware it was observed than increasing the `zfs_rebuild_vdev_limit` to 64M reduced the rebuild time by 17%.  Beyond 64MB there was some improvement (~2%) but it was not significant when weighed against the increased memory usage.

467fd500931937047a5d0433effc1ce22072abcb - Increase default `zfs_scan_vdev_limit` to 16MB

For HDD based pools the default `zfs_scan_vdev_limit` of 4M per-vdev can significantly limit the maximum scrub performance.  Increasing the default to 16M can double the scrub speed from 80 MB/s per disk to 160 MB/s per disk.
    
### How Has This Been Tested?

Local scrub, sequential resilver, and sequential rebuild tests using a HDD based dRAID pool (draid2:11d:106c:2s-0).  Our updated test results show that allowing additional memory to be used for the scan/rebuild queues can significantly improve performance.  Earlier performance testing was done with less capable hardware originally obscured this due to other bottlenecks in the system.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
@akashb-22 you may be interested in this PR as well.  Our testing matches what you were seeing, we're able to get the vast majority of the performance improvements with these two changes to the default tunings.

**Comment by amotin** [comment]
As I've said in private, considering how high this is going, we should better limit all those to a reasonable fraction of ARC.  Otherwise for small systems it may any up too much.  And even if such systems should better be properly configured, there should be some safety belts.

**Comment by behlendorf** [comment]
Agreed!  I've updated the PR accordingly.

**Comment by jumbi77** [comment]
In case this gets upstreamed we should also update [module parameter description](https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Module%20Parameters.html#zfs-scan-vdev-limit) for `zfs_scan_vdev_limit` and maybe add a new section for `zfs_rebuild_vdev_limit`.

**Review by tonynguien — APPROVED** [review]

**Comment by behlendorf** [comment]
Refreshed with a minor update to the rebuild code to divide the maximum 1/4 of arc_c_max by the number of top-level vdev is in the pool.

**Review by amotin — APPROVED** [review]

**Review by akashb-22 — APPROVED** [review]

**Pull request closed without merging**
