### PR TITLE
Fix projid accounting for xattr objects

### LINKED ISSUE #16355: Xattr objects, which are created before upgrade to feature@project_quota, get account-ed in the wrong project id after the upgrade
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	| 5.10.194-1.el8
Architecture	|
OpenZFS Version	| zfs-kmod-2.2.99-1.*.c98295eed

### Describe the problem you're observing
zpool upgraded with 'feature@project_quota' needs re-layout of SA's to fix the SA_ZPL_PROJID at SA_PROJID_OFFSET (128). Its necessary for the correct accounting of object usage against its projid. Old object (created before upgrade) when gets a projid assigned, its SA gets re-layout via sa_add_projid(). If object has xattr dir, SA of xattr dir also gets re-layout. But SA re-layout of xattr objects inside a xattr dir is not done.
### Describe how to reproduce the problem
Create zpool with 'feature@project_quota' disabled
```
$ sudo zpool create mytestpool -o feature@project_quota=disabled disk.1 
$ sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  disabled               local
$ sudo zfs create mytestpool/fs1
```
Create xattr objects
```
$ cd /mytestpool/fs1
$ sudo chmod 0777 ../fs1
$ mkdir dir1
$ ls -id dir1
2 dir1
$ attr -s passwd dir1 < /etc/passwd
```
```
 Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         2    1   128K    512      0     512    512  100.00  ZFS directory
                                               176   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED 
        dnode maxblkid: 0
        path    /dir1
        uid     1000
        gid     1000
        atime   Sun Jul  7 13:12:07 2024
        mtime   Sun Jul  7 13:12:07 2024
        ctime   Sun Jul  7 13:14:50 2024
        crtime  Sun Jul  7 13:12:07 2024
        gen     14
        mode    40700
        size    2
        parent  34
        links   2
        pflags  40800000044
        xattr   3
        microzap: 512 bytes, 0 entries

Indirect blocks:
               0 L0 EMBEDDED et=0 200L/1cP B=14

                segment [0000000000000000, 0000000000000200) size   512
                
```
```
  Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         3    1   128K    512      0     512    512  100.00  ZFS directory
                                               168   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED 
        dnode maxblkid: 0
        path    /dir1/<xattrdir>
        uid     1000
        gid     1000
        atime   Sun Jul  7 13:12:07 2024
        mtime   Sun Jul  7 13:14:50 2024
        ctime   Sun Jul  7 13:14:50 2024
        crtime  Sun Jul  7 13:12:07 2024
        gen     14
        mode    41777
        size    4
        parent  2
        links   2
        pflags  40800000145
        microzap: 512 bytes, 2 entries

                user.passwd = 128 (type: Regular File)
                security.selinux = 4 (type: Regular File)
Indirect blocks:
               0 L0 EMBEDDED et=0 200L/55P B=46

                segment [0000000000000000, 0000000000000200) size   512
```
Upgrade feature@project_quota:
```
$ sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  disabled               local

$ sudo zpool upgrade mytestpool
This system supports ZFS pool feature flags.

Enabled the following features on 'mytestpool':
  project_quota
$  sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  enabled                local
$cd ../
$ sudo zfs umount mytestpool/fs1
$ sudo zfs mount mytestpool/fs1
$ cd fs1
$  sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  active                 local
```
Configure project 111 on dir1
```
$ sudo zfs projectspace mytestpool/fs1
$
$ zfs project dir1
    0 - dir1
$
Set project id 111 on dir1
$ zfs project -p 111 -s -r dir1
$
```
Check usage of Project 111
```
$ sudo zfs projectspace mytestpool/fs1
TYPE     NAME   USED  QUOTA  OBJUSED  OBJQUOTA
Project  0     16.0E   none    16.0E      none
Project  3     2.50K   none        2      none
Project  111      1K   none        2      none
```
Project 111 should have a total of 4 objects account-ed (1 for dir1 ino 2, 1 for xattr dir ino 3 and 2 for xattr’s ino 128 and ino 4. But it's only accounting 2 in project 111 (1 for dir1 ino 2 and 1 for xattr dir ino 3). Xattr ino 128 and ino 4 are account-ed in the invalid projid 3.

### PR DESCRIPTION
**Pull request by jsai20**
zpool upgraded with 'feature@project_quota' needs re-layout of SA's to fix the SA_ZPL_PROJID at SA_PROJID_OFFSET (128). Its necessary for the correct accounting of object usage against its projid. Old object (created before upgrade) when gets a projid assigned, its SA gets re-layout via sa_add_projid(). If object has xattr dir, SA of xattr dir also gets re-layout. But SA re-layout of xattr objects inside a xattr dir is not done.

Fix zfs_setattr_dir() to re-layout SA's on xattr objects, when setting projid on old xattr object (created before upgrade).

Signed-off-by: Jitendra Patidar <jitendra.patidar@nutanix.com>
Closes #16355

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by jsai20** [comment]
Verification of fix:

Create zpool with 'feature@project_quota' disabled
```
$ sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  disabled               local
$ sudo zfs create mytestpool/fs1
```
Create xattr objects
```
$ cd /mytestpool/fs1
$ sudo chmod 0777 ../fs1
$ mkdir dir1
$ ls -id dir1
2 dir1
$ attr -s passwd dir1 < /etc/passwd
```
```
$ sudo zdb -ddddd -U /etc/zfs/zpool.cache mytestpool/fs1 2
Dataset mytestpool/fs1 [ZPL], ID 259, cr_txg 11, 27.5K, 10 objects, rootbp DVA[0]=<0:27a00:200> DVA[1]=<0:4027400:200> [L0 DMU objset] fletcher4 lz4 unencrypted LE contiguous unique double size=1000L/200P birth=116L/116P fill=10 cksum=0000000e269ac6aa:000005196745f887:0000f58fee9b987c:001ff84f86f94495

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         2    1   128K    512      0     512    512  100.00  ZFS directory
                                               176   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED 
        dnode maxblkid: 0
        path    /dir1
        uid     1000
        gid     1000
        atime   Sun Jul  7 13:41:10 2024
        mtime   Sun Jul  7 13:41:10 2024
        ctime   Sun Jul  7 13:49:48 2024
        crtime  Sun Jul  7 13:41:10 2024
        gen     15
        mode    40700
        size    2
        parent  34
        links   2
        pflags  40800000044
        xattr   3
        microzap: 512 bytes, 0 entries

Indirect blocks:
               0 L0 EMBEDDED et=0 200L/1cP B=15

                segment [0000000000000000, 0000000000000200) size   512
```
```
 Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         3    1   128K    512      0     512    512  100.00  ZFS directory
                                               168   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED 
        dnode maxblkid: 0
        path    /dir1/<xattrdir>
        uid     1000
        gid     1000
        atime   Sun Jul  7 13:41:10 2024
        mtime   Sun Jul  7 13:49:48 2024
        ctime   Sun Jul  7 13:49:48 2024
        crtime  Sun Jul  7 13:41:10 2024
        gen     15
        mode    41777
        size    4
        parent  2
        links   2
        pflags  40800000145
        microzap: 512 bytes, 2 entries

                security.selinux = 4 (type: Regular File)
                user.passwd = 128 (type: Regular File)
Indirect blocks:
               0 L0 EMBEDDED et=0 200L/55P B=116

                segment [0000000000000000, 0000000000000200) size   512
```
Upgrade feature@project_quota:
```
$ sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  disabled               local

$ sudo zfs projectspace mytestpool/fs1
$
$ sudo zpool upgrade mytestpool
This system supports ZFS pool feature flags.

Enabled the following features on 'mytestpool':
  project_quota
$  sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  enabled                local
$ cd ../
$ sudo zfs umount mytestpool/fs1
$ sudo zfs mount mytestpool/fs1
$ cd fs1
$  sudo zpool get feature@project_quota mytestpool
NAME        PROPERTY               VALUE                  SOURCE
mytestpool  feature@project_quota  active                 local
```
Configure project 111 on dir1
```
$ sudo zfs projectspace mytestpool/fs1
$
$ zfs project dir1
    0 - dir1
$
Set project id 111 on dir1
$ zfs project -p 111 -s -r dir1
```
Check usage of Project 111
```
$ sudo zfs projectspace mytestpool/fs1
TYPE     NAME   USED  QUOTA  OBJUSED  OBJQUOTA
Project  0     16.0E   none    16.0E      none
Project  111   3.50K   none        4      none
```
With the fix, total 4 objects correctly account-ed under project 111 (1 for dir1 ino 2, 1 for xattrdir ino 3, and 2 for xattr's ino 128 and 4).

**Comment by tonyhutter** [comment]
Can you explain the difference between this PR and https://github.com/openzfs/zfs/pull/16288?  They seem related.

**Comment by jsai20** [comment]
> Can you explain the difference between this PR and #16288? They seem related.

When project id (aka projid) is configured on old objects (files/dirs created before feature@project_quota), zfs_setattr() does add projid on object via sa_add_projid(). sa_add_projid() function does re-layout of SA's to add the SA_ZPL_PROJID at fixed offset SA_PROJID_OFFSET (128).
Corresponding code snip from zfs_setattr()
```

        if (projid != ZFS_INVALID_PROJID && !(zp->z_pflags & ZFS_PROJID)) {
                /*
                 * For the existed object that is upgraded from old system,
                 * its on-disk layout has no slot for the project ID attribute.
                 * But quota accounting logic needs to access related slots by
                 * offset directly. So we need to adjust old objects' layout
                 * to make the project ID to some unified and fixed offset.
                 */
                if (attrzp)
                        err = sa_add_projid(attrzp->z_sa_hdl, tx, projid);
                if (err == 0)
                        err = sa_add_projid(zp->z_sa_hdl, tx, projid);

                if (unlikely(err == EEXIST))
                        err = 0;
                else if (err != 0)
                        goto out;
                else
                        projid = ZFS_INVALID_PROJID;
        }

```
Above code also adding projid on xattr-dir (attrzp case) via sa_add_projid().

So, PR #16288 fixes this core function sa_add_projid(), where its losses SA_ZPL_DXATTR() when doing SA re-layout to add projid at fixed offset.

Now, each xattr object inside xattr-dir gets the projid added via zfs_setattr()->zfs_setattr_dir()
Corresponding code snip of zfs_setattr()
```
                if (attrzp) {
                        if (err2 == 0 && handle_eadir)
                                err = zfs_setattr_dir(attrzp);
                        zrele(attrzp);
                }

```
So, currently zfs_setattr_dir() does add projid on xattr object direct, without re-layout via sa_add_projid(). effectively, SA_ZPL_PROJID gets added at incorrect offset on xattr objects and not at the expect offset SA_PROJID_OFFSET (128). This cause mis-accounting of xattr objects under invalid project.
So, this PR #16356 fixes the projid accounting for xattr objects.  Fix does call sa_add_projid() similar to actual object and xattr-dir object, so that SA_ZPL_PROJID for xattr object gets added at the correct offset and it effectively gets accounted under correct projid.

**Comment by tonyhutter** [comment]
I just did a test run on this PR using the instructions in https://github.com/openzfs/zfs/pull/16356#issuecomment-2230269958:
```
# Without this PR
$ sudo ~/zfs/zfs projectspace mytestpool/fs1
TYPE     NAME   USED  QUOTA  OBJUSED  OBJQUOTA
Project  0     16.0E   none    16.0E      none
Project  3        1K   none        2      none
Project  111      1K   none        2      none

# With this PR
$ sudo ~/zfs/zfs projectspace mytestpool/fs1
TYPE     NAME   USED  QUOTA  OBJUSED  OBJQUOTA
Project  0     16.0E   none    16.0E      none
Project  111      2K   none        4      none
```

So as far as I can tell it looks correct: `mytestpool/fs1` is all under project 111.

**Comment by tonyhutter** [comment]
Side note - I see that `upgrade_projectquota_001_pos` is currently on the skip list in `tests/test-runner/bin/zts-report.py.in`.  We may want to re-enable it if the `lsattr` issue is resolved:
```
#                                                                                
# Some tests require that the lsattr utility support the project id feature.     
#                                                                                
project_id_reason = 'lsattr with set/show project ID required'
```

I did run the updated test manually on a VM and it passed.

**Review by tonyhutter — APPROVED** [review]

**Comment by tonyhutter** [comment]
Can we get more reviewer on this PR?

**Review by behlendorf — APPROVED** [review]

**Pull request merged**
