### PR TITLE
ZTS: Fix incorrect use of libtest in user_run by xattr_003_neg

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

You can't use user_run to eval ksh functions defined in libtest unless you
include libtest in the user shell.

### Description

Simplify user_run to preserve the environment and quote the command string
as one argument.

Fix xattr_003_neg by:
* running ksh as the user
* feeding it the commands to include libtest *then* run get_xattr
* assert this fails
* use variables for filenames so they don't change in the user's shell
* don't log the contents of /etc/passwd
* cleanup all byproducts

### How Has This Been Tested?

I ran the userquota tests on FreeBSD and Linux and the projectquota tests on Linux.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
* Fixed commit message

**Review by behlendorf — APPROVED** [review]

**Review by jwk404 — APPROVED** [review]

**Comment by freqlabs** [comment]
Huh, that's funny. I must have messed up my test procedure on FreeBSD, and I wonder what's different about Ubuntu 🤔

**Comment by freqlabs** [comment]
Nope I'm definitely seeing all the userquota tests pass on FreeBSD when I run them locally. Weird.

**Comment by freqlabs** [comment]
* Rebased
* Revert back to a full login when switching user, this seems to affect evaluation of redirection operators in a few tests
* log_note the contents of the out and err files from the command to help future debugging

**Comment by freqlabs** [comment]
Well that fixed everything I broke, but it broke what I fixed 😄
I'll take another stab tomorrow.

**Comment by freqlabs** [comment]
I suspect the sudoers file on these bots is filtering out PATH from the environment or something. Maybe I can find a flag to explicitly keep it.

**Comment by behlendorf** [comment]
@freqlabs the CI should be [customizing the sudoers file](https://github.com/openzfs/zfs-buildbot/blob/master/scripts/bb-bootstrap.sh#L158-L159) already to prevent exactly this.  But perhaps it's not quite working as intended?

**Comment by freqlabs** [comment]
* export PATH

**Comment by freqlabs** [comment]
* Use env to ensure correct PATH
* Split changes into separate commits for libtest and xattr test

**Review by behlendorf — APPROVED** [review]

**Pull request closed without merging**
