### PR TITLE
Fix boot on non-zfs-root systems

### PR DESCRIPTION
**Pull request by Vaelatern**
### Motivation and Context

On systems where Dracut has already changed the `root=` value, the dracut module overwrites `root`.

https://github.com/void-linux/void-packages/issues/37667

### Description

I could have filed a bug report but this patch should fix the problem.

Basically the change is to not change `root` until the script actually wants to change `root`.

### How Has This Been Tested?

I've not sufficiently tested the changes. The patch is based on the patch by the problem-reporter who did test it.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [X] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [X] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ahesford** [comment]
The trouble with this approach is that, by re-parsing the KCL, it circumvents any intentional rewrite that ought to govern whether the ZFS module takes responsibility for root management. Modules that rewrite `root` should only do so if they intend to take control and understand the argument as specified which, in this case, should leave "zfs:" and "ZFS=" arguments untouched by the time the ZFS module gets to it.

**Comment by Vaelatern** [comment]
@ahesford it's unclear, do you mean this approach will accidentally overwrite `root` anyway?

**Comment by ahesford** [comment]
No, my point is really hypothetical. Suppose somebody writes a module that injects a cmdline hook that rewrites `$root` based on some external condition. (It might assign priority 90 to preempt the priority 95 default cmdline hooks.) Maybe it tries to auto-select root based on device availability and allows the user to omit a root argument altogether. Maybe it removes or adds a ZFS= root based on pool import ability.

If the ZFS module only parses then kernel cmdline directly when `root` is unset (the approach in #13589), the ZFS module will respect these runtime changes. Always parsing and making decisions about the original cmdline doesn't admit the possibility of dynamically reconfiguring the root argument before ZFS decides to take over or ignore the root.

**Comment by behlendorf** [comment]
@Vaelatern @ahesford thanks for looking in to this.  If you two can settle on the preferred approach it'd be nice to wrap this up.

**Comment by ahesford** [comment]
I have a weak preference for my approach on the off chance *some* module, somewhere, might have already parsed `root` from the kernel command line and possibly rewritten it in a way that the ZFS module should be aware of.

However, it's a contrived example, so if @Vaelatern has a stronger preference for re-parsing from the KCL, this approach is fine by me.

**Comment by Vaelatern** [comment]
I think either would be fine. I have a weak preference for my approach because something else might have munged `root` in some way they don't want parsed.

Either approach really would probably be fine. It's not worth being configurable behaviour imo.

**Comment by ahesford** [comment]
Just merge this one. This has bitten a second Void user and we should settle on an approach that we can backport to the Void package.

I don't know how broadly this bug will affect everybody else; I know Arch also includes the Dracut module in the main package, so its users will have the same problem.

**Comment by thesamesam** [comment]
Pff, just when I decide to just go with @ahesford's for Gentoo!

**Pull request merged**
