### PR TITLE
Simplify and optimize random_int_between().

### PR DESCRIPTION
**Pull request by pjd**
### Description

There is not need for a loop in this function, it can be simplified.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by amotin — COMMENTED** [review]
I don't know whether it is important here, but I think the loop was intended to make all results equally probable.  The proposed variant may have different probabilities of results if the range size is not a integer fraction of original random function range.

**Comment by buzzingwires** [comment]
I personally wouldn't expect a test that calls something so generic as `random_int_between` to be ultra-dependent on uniform distribution, but that is only an assumption. If I recall correctly, there are some implementations of uniform PRNGs that use %, though.

Could always test either implementation by writing a short script to repeatedly call it, then organize the output in a histogram.

**Comment by buzzingwires** [comment]
Made a Gist with the testing idea: https://gist.github.com/buzzingwires/6e389c321a7585699a939caee94d828d

**Review by behlendorf — APPROVED** [review]
LGTM.  Nothing I'm aware of in the test suite is picky about the distribution so that shouldn't be a problem.

**Pull request merged**
