### PR TITLE
Colorize patchset

### PR DESCRIPTION
**Pull request by mcmilk**
### Motivation and Context

This is just a rebase of these two pull requests:
- Colorize zpool iostat output #14459
- Colorize zfs list output #14350

The requested changes by @behlendorf and @Low-power (light blue) were added.
When the testings are fine, the changes could be applied.

I will not copy and paste the wordings of the two requests... this PR is just a sum up of the conversation of the other two pull requests.

@ethan-coe-renner - thank you, for working on this.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Low-power** [comment]
> #define	ANSI_BLUE	"\033[1;34m" /* light blue */

I think the difference in this color code should be reflected in its name; may be `ANSI_BRIGHT_BLUE`?

**Comment by mcmilk** [comment]
> ANSI_BRIGHT_BLUE

I also thought about that, but we will not need the standard blue for anything ... so i decided to keep the ANSI_BLUE define, but with the wanted brighter color. I could just rename it and delete the standard blue define. This `ANSI_BLUE` color is also used by the `zfs diff` code - there the brighter blue is also better I think.

**Comment by Low-power** [comment]
Yes, we definitely want the blue in `zfs diff` to be brighter, and so more readable too.

**Comment by mcmilk** [comment]
We have two BLUE definitions now:
1) `BOLD_BLUE` - used as _primary blue_
2) `ANSI_BLUE` - currently unused

@Low-power - this should be fine I think :-)

**Comment by Low-power** [comment]
> `BOLD_BLUE` - used as primary blue

Why not `ANSI_BOLD_BLUE`? I think this is an ANSI color too.

**Comment by mcmilk** [comment]
> > `BOLD_BLUE` - used as primary blue
> 
> Why not `ANSI_BOLD_BLUE`? I think this is an ANSI color too.

I have no preference with this. I can change it to some longer value like `ANSI_BOLD_BLUE`. But I found `BOLD_BLUE` okay.

**Comment by mcmilk** [comment]
> > `BOLD_BLUE` - used as primary blue
> 
> Why not `ANSI_BOLD_BLUE`? I think this is an ANSI color too.

DONE :)

**Review by Low-power — APPROVED** [review]
Tested on my system, without issue.

**Review by behlendorf — APPROVED** [review]

**Comment by ethan-coe-renner** [comment]
@mcmilk , thanks for making these changes!

**Pull request closed without merging**
