### PR TITLE
Update zfs documentation (zfs_metaslab_mem_limit)

### PR DESCRIPTION
**Pull request by jumbi77**
### Description

~~According to https://github.com/openzfs/zfs/blob/master/man/man4/zfs.4#L301 zfs_metaslab_mem_limit should be 25 instead of 75~~

EDIT: Instead of changing the code, I updated the documentation of this module parameter like behlendorf suggested.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Thanks for the suggested fix.  However, in this case it's the documentation which is wrong and not the code, this threshold was intentionally changes in ca5777793ee10b9f7bb57aef00a6c8d57969625e and we failed to update the docs.  Would you mind refreshing the PR to instead change the man page to say 75.

**Comment by jumbi77** [comment]
@behlendorf changed doc instead and forced pushed.

BTW: Since you marked two delphix dev's for review: I just noted that the delphix fork updated the code instead the doc to 25.
git code: https://github.com/delphix/zfs/blob/master/module/zfs/metaslab.c#L296
git blame: https://github.com/delphix/zfs/blame/master/module/zfs/metaslab.c#L296

**Comment by behlendorf** [comment]
Oh indeed, I believe you were probably right with the original code change.  Let's just verify what was intended here with @pcd1193182 , certain 25% would be a more reasonable limit in this case.

**Comment by mmaybee** [comment]
Yup, agreed. While there may be special cases, 75% seems rather high for the default.

**Comment by jumbi77** [comment]
Ok, I just reverted the man page change back and change the default value in the code to 25 like my first approach and force pushed.... seems like the PR gets closed with the push... my origin fork/branch seems clear though: https://github.com/jumbi77/zfs/commits/patch-1

Since its a trivial change, I don't mind if you (dev with write access) change the value directly without re-opening/opening another PR.

**Comment by pcd1193182** [comment]
The intended value is 25; the error is the result of a mismerge that happened when we introduced the btrees.

**Comment by behlendorf** [comment]
@jumbi77 if you wouldn't mind opening a new PR with the change that would make it a little easier for us to merge it with our workflow.  If you're rather, I'm happy to open the PR with the commit you referenced.

**Pull request closed without merging**
