### PR TITLE
contrib: link zpool to zfs in bash-completion

### PR DESCRIPTION
**Pull request by Harry-Chen**
### Motivation and Context

Currently user won't have completion of `zpool` command until they trigger completion of `zfs` first. This patch adds a link to `zfs`, thus user can use both to initialize the completion.

Fixes: #16320

### Description

Create a symlink to `zfs` as `zpool` under `contrib/bash_completion.d`.

### How Has This Been Tested?

Tested the whole configuration, compilation and installation process. It wors as expected. No other functionality is affected.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by tonyhutter** [comment]
Can we get more more reviewer on this PR?

**Review by robn — APPROVED** [review]
It hardly matters, and I have no real opinion nor any idea what good practice is for completion scripts, but:

Would it be better to install this as a hard link instead of a symlink, or even a whole separate copy of the file?

**Comment by Harry-Chen** [comment]
> It hardly matters, and I have no real opinion nor any idea what good practice is for completion scripts, but:
> Would it be better to install this as a hard link instead of a symlink, or even a whole separate copy of the file?

I look at `/usr/share/bash-completion/completions` on my debian system, and many packages choose to use a symlink, e.g. `vg*` all go to `lvm`, and `lxc_*` go to `_lxc`. I think making hard links or copying might be confusing to users, and a symlink clearly shows the relationship between files.

**Comment by robn** [comment]
Works for me, thanks for checking :+1:

**Review by mcmilk — APPROVED** [review]

**Comment by tonyhutter** [comment]
For some reason the Centos and Fedora builders were failing.  I just started a re-run of those tests.  If all goes well I will merge the PR.

**Comment by Harry-Chen** [comment]
> For some reason the Centos and Fedora builders were failing. I just started a re-run of those tests. If all goes well I will merge the PR.

There is an error

```text
  CC       contrib/pam_zfs_key/pam_zfs_key_la-pam_zfs_key.lo
ln -s zfs contrib/bash_completion.d/zpool
ln: failed to create symbolic link 'contrib/bash_completion.d/zpool': File exists
make[4]: *** [Makefile:14165: contrib/bash_completion.d/zpool] Error 1
```

`zpool` is created and preserved in the release tarball, thus causing the `File exists` error when being created again.

Sorry for not finding such situation, I will fix it soon.

**Comment by Harry-Chen** [comment]
The building issue is now fixed. @tonyhutter

**Pull request merged**
