### PR TITLE
Use percpu_counter for obj_alloc counter of Linux-backed caches

### PR DESCRIPTION
**Pull request by sdimitro**
### Motivation

A previous commit enabled the tracking of object allocations
in Linux-backed caches from the SPL layer for debuggability.
The commit is: 9a170fc6fe54f1e852b6c39630fe5ef2bbd97c16

Unfortunately, it also introduced minor performance regressions
that were highlighted by the ZFS perf test-suite. Within Delphix
we found that the regression would be from -1%, all the way up
to -8% for some workloads.

### Description

This commit brings performance back up to par by creating a
separate counter for those caches and making it a percpu in
order to avoid lock-contention.

### Testing

The initial performance testing was done by myself, and the
final round was conducted by @tonynguien who was also the one
that discovered the regression and highlighted the culprit.

### CODE REVIEW

**Comment by richardelling** [comment]
LGTM, but wondering why you're using the Linux-only percpu_* rather than aggsum_* as we're using in arc.c?

**Comment by amotin** [comment]
It seems this code uses the counter almost solely for write, reading it only sporadically on user request and not requiring atomicity. For such usage aggsum is a waste of resources, since it does provide atomic reads.  I think there should be introduced some platform-independent KPI for write-only counters, likely just a wrapper over whatever provided by each platform.

**Comment by sdimitro** [comment]
I did the mistake and opened this as a proper review. I should have opened it as a draft since it seems like I'd need to iterate a bit more to make it compile in all environments.

@richardelling I did think about using the aggsum code but that code is licensed under CDDL and the code that I'm changing is in the SPL which is GPL. I think not many people have touched the aggsum code so we could relicense it if we wanted to but it just seemed too much for this change.

@amotin I'd be interested in working with others in such counters. That said this undertaking is tangential to this PR.

**Comment by amotin** [comment]
For reference this is a counter(9) KPI available on FreeBSD to be used in write-mostly cases: https://www.freebsd.org/cgi/man.cgi?query=counter&sektion=9&manpath=freebsd-release-ports

**Comment by sdimitro** [comment]
cc @tonynguien

**Pull request merged**
