### PR TITLE
add async dmu and async COW support

### PR DESCRIPTION
**Pull request by mattmacy**
#10377 plus dbuf state machine changes to read-modify-write when doing incremental block overwrites.

https://www.bsdcan.org/2012/schedule/attachments/203_ZFSOptimizedForBlock_BSDCAN2012.pptx
https://lists.freebsd.org/pipermail/zfs-devel/2013-September/000388.html

Co-authored-by: Will Andrews <wca@FreeBSD.org>
Co-authored-by: Matt Macy <mmacy@FreeBSD.org>
Signed-off-by: Matt Macy <mmacy@FreeBSD.org>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by adamdmoss** [comment]
There's no description so this looks like a draft; is it ready for testing nonetheless?  How would one test?
Thanks.

**Comment by mattmacy** [comment]
> There's no description so this looks like a draft; is it ready for testing nonetheless? How would one test?
> Thanks.

https://www.bsdcan.org/2012/schedule/attachments/203_ZFSOptimizedForBlock_BSDCAN2012.pptx
https://lists.freebsd.org/pipermail/zfs-devel/2013-September/000388.html

**Comment by adamdmoss** [comment]
I'm having a bit of trouble contriving a situation where this is clearly beneficial.

I wrote a mmap()ing test which read-modify-writes a 10GB file in-place at various intervals on datasets with 1mb records (+lz4 but mostly with uncompressible data):
* Rewriting every byte
* RMWing a single word every 8k
* RMWing a single word every 80k
* Repeating the above having snapshotted the dataset first
* With/without msync() at each write
* On spinning media and NVME

Times between trunk and this branch @ 1e4dd4739fc50ed33fb498943abc2af34495441e are highly comparable (this branch was typically about 4% slower but that's within the realm of regular variance).

I included the time to complete a sync() after each test, which may have been a mistake.

Any hints as to a clearer win case or a different metric I should measure?
Thanks.

**Comment by mattmacy** [comment]
> I'm having a bit of trouble contriving a situation where this is clearly beneficial.
> 
> I wrote a mmap()ing test which read-modify-writes a 10GB file in-place at various intervals on datasets with 1mb records (+lz4 but mostly with uncompressible data):
> 
>     * Rewriting every byte
> 
>     * RMWing a single word every 8k
> 
>     * RMWing a single word every 80k
> 
>     * Repeating the above having snapshotted the dataset first
> 
>     * With/without msync() at each write
> 
>     * On spinning media (backed by l2arc) and NVME
>       (Linux kernel 5.3.x)
> 
> 
> Times between trunk and this branch @ [1e4dd47](https://github.com/openzfs/zfs/commit/1e4dd4739fc50ed33fb498943abc2af34495441e) are highly comparable (this branch was typically about 4% slower but that's within the realm of regular variance).
> 
> I included the time to complete a sync() after each test, which may have been a mistake.
> 
> Any hints as to a clearer win case or a different metric I should measure?
> Thanks.

It eliminates reads for blocks that are filled within a txg, but not within a given write. 
image(4)

**Comment by mattmacy** [comment]
@adamdmoss We were still reading L0 blocks synchronously in unaligned writes. Can you please try again. Thanks.

**Comment by adamdmoss** [comment]
My benchmark is perhaps a bit faster - more in-line with master, perhaps a few % faster - but I don't think the benchmark is designed for the strengths of this branch as I now understand it a little better.  I think I really need other heavy I/O load simultaneous to COW ops...

**Comment by adamdmoss** [comment]
I've been running this consistently for 3 weeks now without issues, FWIW.

**Comment by mattmacy** [comment]
> I've been running this consistently for 3 weeks now without issues, FWIW.

Cool. Looks like my last update broke things will fix once I have downstreaming ready to go.

**Comment by adamdmoss** [comment]
Checking current status since the last comment left things ambiguous - is this fixed and ready to go now? :)

**Comment by adamdmoss** [comment]
(bump)

**Pull request closed without merging**
