### PR TITLE
Install bashcompletion file in appropriate location

### PR DESCRIPTION
**Pull request by siv0**
This patchset is the result of trying to build Debian Packages for 2.2.0-rc4 for Proxmox[0]
The changes in debian/contrib were only targeted at the fix (I did not try to install the resulting packages)

[0] https://git.proxmox.com/?p=zfsonlinux.git;a=tree

### Motivation and Context

Somewhere between zfs-2.1.12 and zfs-2.2.0-rc4 a change caused the bash completion to
actually get installed to DESTDIR - I assume 612b8dff5bc3d827efb864a199a62bda1a419254
introduced it.
Instead of working around the different location used in Debian based distributions (/usr/share/bash-completion/completions/, instead of /etc/bash_completion.d) in debian/rules [1] , setting the path during ./configure seems preferable) 

[1] https://github.com/openzfs/zfs/blob/4647353c8b2b5ca506da45bb9b01e1f3ef521847/contrib/debian/rules.in#L75
 (similar workaround can be found in Debian upstream and Proxmox rules files)

### Description

commit 1/3 sets the bashcompletiondir variable based on the vendor, inspired by similar settings for initdir and initconfdir
commit 2/3 is a small update to contrib/debian/control, in order to make building packages work on Debian Bookworm (the dkms package is virtual and should be replaced by dh-sequence-dkms)
commit 3/3 adapts contrib/debian/rules to not move the bashcompletion file around anymore

### How Has This Been Tested?

on Debian 12 I ran:
git clean -fdx; ./autogen.sh; ./configure --with-config=user; cp -a contrib/debian .; dpkg-buildpackage -b -uc -us
(the --with-config=user was a shorter way instead of providing the custom kernel-header location in Proxmox VE)
on Fedora 38:
git clean -fdx; ./autogen.sh ; ./configure  ; make rpm
and verifying that the bash completion file was installed in the correct location

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
@usaleem-ix would you mind reviewing this.

**Review by usaleem-ix — APPROVED** [review]
LGTM.

Sorry for the delay, this one got lost in emails.

**Comment by usaleem-ix** [comment]
@siv0 it looks this PR has caused a regression. https://github.com/openzfs/zfs/issues/15355 might be of interest to you. `make rpm` and `make deb` is failing reliably on Debian after these changes.

**Comment by siv0** [comment]
> @siv0 it looks this PR has caused a regression. #15355 might be of interest to you. `make rpm` and `make deb` is failing reliably on Debian after these changes.

Thanks for the heads-up - I'll take a look!

**Pull request closed without merging**
