### PR TITLE
[WIP] zfs-0.8.5 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Patchset for zfs-0.8.5 point release

### Description
Since zfs-2.0.0 has hit RC status, 0.8.5 will be a smaller, mostly buildfix-only release.   

Also, I want to give a big thanks to everyone who contributed to the `zfs-0.8.5-staging` branch! :+1: 

### How Has This Been Tested?
Builds on Fedora 32, but I still need to test on Fedora 33 rawhide.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by mskarbek** [comment]
If I could have a request please keep this minimal (possibly kernel compatibility only) and release with kernel 5.9.

**Comment by gdevenyi** [comment]
Maybe https://github.com/openzfs/zfs/pull/10916 if it passes final testing?

**Comment by tonyhutter** [comment]
@gdevenyi it looks like #10916 is still going through review.

**Comment by gdevenyi** [comment]
Right, well, I'm not sure of the relative timeframes, but I think its important enough to include if it gets sorted in time.

**Comment by gdevenyi** [comment]
Saw a user requested https://github.com/openzfs/zfs/pull/10291

**Comment by gyakovlev** [comment]
87688b686bb4ede154d502cf9a342126c25789c0 should apply cleanly, without it kernel-builtin on powerpc does not work.
gentoo already carries it downstream for 0.8.4, no big deal if not included, but would be nice if it is.

**Comment by InsanePrawn** [comment]
should this include systemd generator patches? ec41cafee1, 62663fb7ec, b717f9b95e, ceadc0dbbd
@rlaager?

**Comment by rlaager** [comment]
> should this include systemd generator patches? [ec41caf](https://github.com/openzfs/zfs/commit/ec41cafee1dac132775ca3eaa9aa7f56cf30b30f), [62663fb](https://github.com/openzfs/zfs/commit/62663fb7ec191ca2f872aec1636e94934212936f), [b717f9b](https://github.com/openzfs/zfs/commit/b717f9b95e6b85ea502318f6350a6b6b6a237ebd), [ceadc0d](https://github.com/openzfs/zfs/commit/ceadc0dbbd5594db153a61c3d82a6d98e1adca7d)
> @rlaager?

I'd be in favor of that. Also de817cc7b7c2ab3dfa8348ae0e826e84c1d416eb, which goes with b717f9b95e6b85ea502318f6350a6b6b6a237ebd.

**Comment by ndanyluk** [comment]
I've heard some people on other forums suggest that 5.9 might be a LTS kernel.  If possible, could this release support 5.9 so that those that want to pin to an LTS can get the latest kernel?

**Comment by Ornias1993** [comment]
@ndanyluk 5.9 compatibility fixes (as far as we currently know) are included in this PR.
However, if you want to upgrade in about 6 months to something that would have the longest support, I think kernel 5.9 + OpenZFS2.0 would be the best way to go...

**Comment by ndanyluk** [comment]
> 
> 
> @ndanyluk 5.9 compatibility fixes (as far as we currently know) are included in this PR.
> However, if you want to upgrade in about 6 months to something that would have the longest support, I think kernel 5.9 + OpenZFS2.0 would be the best way to go...

Gotcha, thank you! Reason I mentioned it was because I saw the 2.0-rc2 release and it only had listed support up through kernel 5.8.  I would love to upgrade, but I'm running on a device that finally got a lot of work submitted to mainline around the kernel 5.4-5.7 timeline so the only LTS that will have my device's full support is the next one (if 5.9 turns out to be that next LTS)

**Comment by Ornias1993** [comment]
> Gotcha, thank you! Reason I mentioned it was because I saw the 2.0-rc2 release and it only had listed support up through kernel 5.8. 

2.0 has the same compatibility fixes.
The reason it isn't listed, is because there officially isn't a 5.9 release yet, so it cant be guaranteed.

**Comment by tonyhutter** [comment]
@gdevenyi @gyakovlev @InsanePrawn @rlaager thanks for the patch suggestions.  I've included them in my latest push.

**Comment by InsanePrawn** [comment]
Should acfd2d4 also be included? It's a rather simple patch.

**Comment by awehrfritz** [comment]
When can we expect this release to happen?

Given that this release will contain all the compatibility fixes for Linux 5.9, I would assume (hope) this release to happen shortly after Linux 5.9 is out, but I couldn’t find any information in this regard.

In general, since ZFS required smaller changes for many (all?) the kernel releases in recent times, it would be nice if ZFS patch releases could be synced with this Linux development cycle. I understand that OpenZFS is not a Linux-only project, but given that more and more users employ ZFS on Linux systems it’s a very important aspect in my opinion. Also, Fedora users like myself will appreciate this very much as Fedora is very quick to adopt the latest kernel version, even in released distributions.

Last, having the procedure for patch releases documented somehow would go a long way, and be especially useful for new/inexperienced users - also considering the otherwise excellent documentation of OpenZFS.

**Comment by Ornias1993** [comment]
@awehrfritz This has been discussed before in an issue.
It's done when it's done. 
Considering Linus doesn't even have an official release date, we can't even discuss how long after his release this is going to be released.

That being said: As 5.9 isn't released yet, we certainly can't say anything final about 5.9 compatibility yet. All issues we currently know are fixed, but openzfs is not officially supporting 5.9 until it's released and fully tested

> In general, since ZFS required smaller changes for many (all?) the kernel releases in recent times, it would be nice if ZFS patch releases could be synced with this Linux development cycle.

Patch releases might or might not include support for new kernels. Thats not a guarantee, hence syncing with the kernel is also not a promise because there might be nothing to sync ;)

> I understand that OpenZFS is not a Linux-only project, but given that more and more users employ ZFS on Linux systems it’s a very important aspect in my opinion

That only goes for fedora mostly, most linux users don't use the newest kernel release. To be frankfully honest: I'm both thankfull and a bit done with fedora users by now. Always use a bleeding edge kernel and complain when things aren;t made to work with it yet. 

Don't use bleeding edge if you want the best compatibility.

> Also, Fedora users like myself will appreciate this very much as Fedora is very quick to adopt the latest kernel version, even in released distributions.

This is mostly limited to fedora, most distro's don't ship the latest and greatest kernel version


> Last, having the procedure for patch releases documented somehow would go a long way, and be especially useful for new/inexperienced users - also considering the otherwise excellent documentation of OpenZFS.

I'm the one working on said documentation lately, what do you want to see? I'm already working on documenting what could and couldn't be included in patch releases. I can't document release schedual if thats what you want, because there is none.

OpenZFS does not follow a release plan, releases are solid when they are solid.

**Comment by tonyhutter** [comment]
Released, closing PR:
https://github.com/openzfs/zfs/releases/tag/zfs-0.8.5

**Comment by eli-schwartz** [comment]
@Ornias1993 Arch Linux also supports the latest and greatest kernel. As the current zfs packager for Arch, I want kernel support to be prompt. But I'm also willing to put my money where my mouth is, which is why, since I and others have convinced the zfs maintainers to produce a staging branch for user-contributed stable backports, I personally went out of my way to backport all changes needed, thereby creating the basis of this pull request.

The community would like to help make maintenance releases easier. Correspondingly, the community hopes that maintenance releases happen more often; ideally, at least cutting a release every time the staging branch has commits which successfully add support for a newly released kernel.

Today, a release was cut that solves various outstanding issues with the mainline (unreleased) kernel, which is even better.

Everyone wins. No need to feel begrudging of Arch and Fedora users. Solving this early means you don't need to panic when Ubuntu LTS is just released and you finally realize "oh no, zfs doesn't support this year-old kernel, everything is on fire".

**Comment by tonyhutter** [comment]
@eli-schwartz thanks for your help backporting the kernel fixes. And as a reminder to all, if you want to backport changes to the next release, we have a `zfs-0.8.6-staging` branch already up.  Just create a PR against that branch and we can easily pull it in.

**Comment by gyakovlev** [comment]
looks like `META` still lists `5.6` as maximum in `0.8.5` release, I guess it's intended or just an overlook?
I've set  gentoo builds of `0.8.5` to require up to `5.8` for now, as release notes say.

**Comment by awehrfritz** [comment]
Great! Thanks a lot @tonyhutter for all your effort and work on getting those patch releases done!

Also thanks to @eli-schwartz for backporting the support for the latest Linux kernels. While I have only first-hand experience with ZFS on Fedora (and Armbian), this is indeed an issue for quite a number of people as it affects users of Fedora, Arch, Gentoo and the various derivatives of the former distributions.

I haven't done any real development work for ZFS myself, but I am eager to test and contribute to bugfixes wherever I encounter them (one of which is among the patches backported to 0.8.5). This is obviously something users of bleeding-edge distributions will experience more often than others which is why we are the once that speak up and report those bugs much more than others.

@Ornias1993 I have been the one that initiated the latest patch release staging-branch discussion (see #10722), where others (e.g. @eli-schwartz and @gdevenyi) had similar attempts before. My suggestion here to sync the ZFS patch releases with Linux kernel releases was meant as a constructive initiative to make it easier for ZFS package maintenance and developers to get ZFS tested on new kernel releases by a wider userbase, and thus catch issues early on. This doesn't need to be a strict release schedule, more of an intent to issue a patch release soon after (or towards the end of) the Linux kernel release cycle, which would lead to having other bugfixes pushed out in regular intervals as well. I must say that I didn't expect such a destructive feedback here, as @tonyhutter and @behlendorf have been nothing but supportive in this effort and their response has always been very constructive!

**Comment by ndanyluk** [comment]
> 
> 
> Great! Thanks a lot @tonyhutter for all your effort and work on getting those patch releases done!
> 
> Also thanks to @eli-schwartz for backporting the support for the latest Linux kernels. While I have only first-hand experience with ZFS on Fedora (and Armbian), this is indeed an issue for quite a number of people as it affects users of Fedora, Arch, Gentoo and the various derivatives of the former distributions.
> 
> I haven't done any real development work for ZFS myself, but I am eager to test and contribute to bugfixes wherever I encounter them (one of which is among the patches backported to 0.8.5). This is obviously something users of bleeding-edge distributions will experience more often than others which is why we are the once that speak up and report those bugs much more than others.
> 
> @Ornias1993 I have been the one that initiated the latest patch release staging-branch discussion (see #10722), where others (e.g. @eli-schwartz and @gdevenyi) had similar attempts before. My suggestion here to sync the ZFS patch releases with Linux kernel releases was meant as a constructive initiative to make it easier for ZFS package maintenance and developers to get ZFS tested on new kernel releases by a wider userbase, and thus catch issues early on. This doesn't need to be a strict release schedule, more of an intent to issue a patch release soon after (or towards the end of) the Linux kernel release cycle, which would lead to having other bugfixes pushed out in regular intervals as well. I must say that I didn't expect such a destructive feedback here, as @tonyhutter and @behlendorf have been nothing but supportive in this effort and their response has always been very constructive!

Agreed, thanks @tonyhutter @eli-schwartz and others for all your effort on getting this patch release done!

To echo @awehrfritz a bit, I think that the documentation could be helped by a simple statement that says something to the effect of "OpenZFS does not follow a strict release schedule, point releases are tagged as needed to support the latest stable Linux kernel found at kernel.org".

As a new user of ZFS, I've been wondering this for months but have been afraid to ask.  I have a system with a relatively recent SoC that only recently got features/drivers mainlined (from 5.5-5.7).  So I've been eagerly awaiting 5.9 hoping it will be a LTS release and that once it releases I can pin my kernel to that LTS.  Knowing that OpenZFS intends to support the release (or even provide best effort compatibility) can help me and others like me make informed decisions.  But right now, I've been reading through issues, staging branches, and PRs trying to gauge when 0.8.5 or 0.8.6 would launch.  Thankfully, it seems like a lot of compatibility work for 5.9 is already there so I'm eagerly awaiting the official release expected for Sunday

**Comment by Ornias1993** [comment]
@eli-schwartz Thanks for the addition, it seems I was mistaken. 

Anyway:
After my PR adding conventional commits get it, i've PR ready-to-go to document which PR's qualify for backporting. So thats something.

Before adding aims for releases to the docs (for example "soon after the kernel"), I think we first need to look into a good testing protocol for this. Preferably automated even. Because currently that has to be manually checked and I suspect thats also causing some delays....

Maybe we could add some optional bots that tests the latest-and-greatest kernel version, just like we test FreeBSD HEAD?
Also: some forms of building aren't checked by the bots according to recent issues, this also needs to be addressed imho...

If those things are automated a little better, we can start aiming for more frequent releases soon after.

@ndanyluk OpenZFS always indents to support a kernel release, thats not the problem. The timeframe of the support-releases (mostly) is. That being said (and to be very clear) 5.9 support is NOT in 0.8.5 (actually due to a fluke 5.8 is even problematic)

**Comment by Ornias1993** [comment]
@tonyhutter Could you also look into fixing the changelog?

"Signed-off-by: Coleman Kane ckane@colemankane.org #10696"

I doubts thats a change ;)

**Comment by tonyhutter** [comment]
@Ornias1993 sorry about that!  I have a script that generates the changelog and it must have parsed the commits wrong.  I've fixed the changelog.

@gmelikov thanks, I forgot to bump the kernel version when I updated META.  There's a fix here: https://github.com/openzfs/zfs/pull/11019

**Comment by Ornias1993** [comment]
@tonyhutter Interesting, As i'm working on some automation after (and based on) #10977
Would you mind to share? :)

**Comment by tonyhutter** [comment]
@Ornias1993 it's really just a throwaway script:
```bash
git log | sed -r 's/^\ +//g' | awk 'BEGIN {cl=""} /^Closes /{cl=cl" "$2} /^commit/{c=5; print "- "msg""cl; cl=""; num=$2 } {if (c&&!--c){msg=$0}}'
```

**Comment by Ornias1993** [comment]
> @Ornias1993 it's really just a throwaway script:
> 
> ```shell
> git log | sed -r 's/^\ +//g' | awk 'BEGIN {cl=""} /^Closes /{cl=cl" "$2} /^commit/{c=5; print "- "msg""cl; cl=""; num=$2 } {if (c&&!--c){msg=$0}}'
> ```

Throw away or not, thanks none-the-less 👍

**Pull request closed without merging**
