### PR TITLE
uClibc does not include aio.h; fallback zpool_read_label to zpool_read_label_slow

### PR DESCRIPTION
**Pull request by jlsalvador**
### Motivation and Context
OpenZFS version was stuck in Builroot to 2.0.x because the commit e50b5217e7a85f1466edf88d5f3ea5aed0c2fd22 includes `aio.h`; and uClibc does not support `aio.h`. uClibc is used by default by Builroot. I wish to upgrade the OpenZFS version for Buildroot.

### Description
~~If you're using uClibc, the function `zpool_read_label` will returns `zpool_read_label_slow`, in order to skip the use of `aio.h`.
I have included `features.h` in order to load the def `__UCLIBC__`.~~
When `aio.h` is not available (uClibc), the function `zpool_read_label` will fallback to `zpool_read_label_slow`.

### How Has This Been Tested?
Compiling ZFS using glibc, musl, uclibc on Amd64 and Arm64.
~~Can someone check klibc, please? (I think klibc has not `features.h`) :-(~~

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
This is better served as just `__has_include(<aio.h>)` (provided whatever ancient CentOS GCC supports `__h_i`; failing that, a HAVE_AIO_H autohell config macro).

**Comment by jlsalvador** [comment]
> This is better served as just `__has_include(<aio.h>)` (provided whatever ancient CentOS GCC supports `__h_i`; failing that, a HAVE_AIO_H autohell config macro from `AC_CHECK_HEADERS` – avoiding "is this uclibc/is this the uclibc that's good now/does klibc have the thing we need to check if this is the good uclibc/&c." is the exact point of both of those).

I read a bit about `__has_include`, seems it only applies to header files.

https://clang.llvm.org/docs/LanguageExtensions.html#:~:text=Note%20that%20__has_include_next%2C%20like%20the%20GNU%20extension%20%23include_next%20directive%2C%20is%20intended%20for%20use%20in%20headers%20only%2C
> Note that __has_include_next, like the GNU extension #include_next directive, is intended for use in headers only.

So, I will try with `AC_CHECK_HEADERS`.

**Comment by nabijaczleweli** [comment]
I mean, in this case, you really only care if you *have* `<aio.h>`, right? Also, you've linked to the `__has_include_next` directive (which is, indeed, header-only, since it's the counterpart to `#include_next <...>`) – you're looking for https://clang.llvm.org/docs/LanguageExtensions.html#include-file-checking-macros, which can be used everywhere

**Comment by jlsalvador** [comment]
> I mean, in this case, you really only care if you _have_ `<aio.h>`, right? Also, you've linked to the `__has_include_next` directive (which is, indeed, header-only, since it's the counterpart to `#include_next <...>`) – you're looking for https://clang.llvm.org/docs/LanguageExtensions.html#include-file-checking-macros, which can be used everywhere

You are right, thank you!.

**Comment by nabijaczleweli** [comment]
Hm, it appears that CentOS 7 only ships GCC 4.8.5 (gcc-4.8.5-44) and __has_include() [only appears in GCC 5](https://gcc.gnu.org/gcc-5/changes.html).

**Comment by jlsalvador** [comment]
> Hm, it appears that CentOS 7 only ships GCC 4.8.5 (gcc-4.8.5-44) and __has_include() [only appears in GCC 5](https://gcc.gnu.org/gcc-5/changes.html).

So with this patch, CentOS 7 + GCC 4.8.5 will fallback to `zpool_read_label_slow`. :-/
So autoconf + configure.sh flag then?

**Comment by nabijaczleweli** [comment]
That appears to be the only option, yeah.

**Comment by jlsalvador** [comment]
Superseded by #13254

**Pull request closed without merging**
