### PR TITLE
avoid unneccessary zio allocation and wait

### PR DESCRIPTION
**Pull request by Finix1979**
In function dmu_buf_hold_array_by_dnode, the usage of zio is only for reading operation. We only create zio and wait it in reading scenario. 

### Motivation and Context

For performance enhancement.

It is mentioned in #11251
### Description

Add if (read) before zio creation, waiting calling.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by behlendorf — APPROVED** [review]
Looks good, can you just address the cstyle warning on line 534 (>80 chars) and then add your [signed-off-by](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by) to the commit.  `git commit --amend -s`

**Comment by adamdmoss** [comment]
Nice observation, @Finix1979 ; Out of interest did you spot this from manual inspection or did a tool (i.e. static analysis) provide hints?

**Comment by Finix1979** [comment]
> Nice observation, @Finix1979 ; Out of interest did you spot this from manual inspection or did a tool (i.e. static analysis) provide hints?

I try to understand zvol logic by reading source code step by step :)

**Comment by gmelikov** [comment]
@Finix1979 Do you have some numbers about performance difference? I'm interested what's the impact here.

**Comment by Finix1979** [comment]
> @Finix1979 Do you have some numbers about performance difference? I'm interested what's the impact here.

I don't have the number, just find this by accident :)

**Pull request merged**
