### PR TITLE
Linux 6.12 compatibility

### PR DESCRIPTION
**Pull request by robn**
### Motivation and Context

> Gotta work
> Gotta make that money, make purse
> Got a fur coat, so I make it purr
> Give 'em whiplash when they see me earn
> Gotta, gotta, gotta work
> 
> Gotta make that money, make purse
> Got a fur coat, so I make it purr
> Gotta get that credit, get perks
> Gotta, gotta, gotta work
> 
> – _Work_, ATEEZ, 2024.

[Linux 6.12-rc1](https://lore.kernel.org/lkml/CAHk-=wiwVOCZsC6a4dLdb1UjL2fS_CnLNjrPL0XGFbDd9C26Cg@mail.gmail.com/T/#u) dropped, requiring the usual smattering of updates.

### Description

See commit messages.

The only possibly gnarly one is the top commit, removing the `PG_error` flag. I'm reasonably certain that our use has been an effective no-op since ~2017 (Linux 4.17), so this change is benign, but our `mmap()` magic is deeper than my ken, so I'd appreciate an expert consideration (@behlendorf? @bwatkinson?). Notes and references in the commit message.

### How Has This Been Tested?

Compiled and passed basic sanity check (create, fio, export, import, scrub, unload) on kernels:

- 4.19.319
- 5.4.281
- 5.10.223
- 6.1.102
- 6.2.16
- 6.3.13
- 6.4.16
- 6.5.13
- 6.6.43
- 6.7.12
- 6.8.12
- 6.9.12
- 6.10.3
- 6.11.0
- 6.12-rc1

(not (yet) 5.15.167, because there's some weird build quirk happening on my test rig, unrelated to this change. will update).

ZTS run in progress, will update here when its done.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by behlendorf — APPROVED** [review]
Thanks Rob this looks good.  I'll need to look more closely in to the `PR_error` flag removal with 6.12 but since you've left it for 6.11 and earlier there shouldn't be an issue with the supported kernel versions.

**Comment by darkbasic** [comment]
@robn did you manage to run the test suite against 6.12? If so did it run cleanly?

**Comment by robn** [comment]
@darkbasic ran it overnight on 6.12.0, and yes, clean run.

**Comment by darkbasic** [comment]
Thanks @robn I've backported it into 2.2.x and I'm feeling confident shipping it in the Arch Linux DKMS if you managed to run the test suite against 6.12.0.

**Comment by usaleem-ix** [comment]
@robn since 6.12.0 is out and we have test suite running cleanly against 6.12.0, should we update META for 6.12?

**Comment by behlendorf** [comment]
Yes we should, https://github.com/openzfs/zfs/pull/16793

**Comment by brneto** [comment]
@robn, How about Linux 6.12.3? I'm trying to install it in my debian bookworm with kernel 6.12.3 in a rpi5 and the mod is failing. Is there something I can do?

**Comment by robn** [comment]
@brneto open a new issue, filling out all the fields.

**Pull request closed without merging**
