### PR TITLE
ZFS 0.8.6 Linux 5.10 sendfile backport

### PR DESCRIPTION
**Pull request by veggiemike**
### Motivation and Context

This is a backport of pull request #11351 to ZFS 0.8.6.

### Description

Cherry-picked 1c2358c on top of my `zfs-0.8.6-fixes` branch from pull request #11348.

Given that backporting to 0.8.6 means going back to not caring (much) about the common/os split, I've applied ALL the `zvol.c`, `zvol_os.c`, `zfs_vnops.c`, and `zfs_vnops_os.c` changes to the original files in `module/zfs/`.  Here's a summary of the other conflicts in the commit when cherry-picked onto 0.8.6:

- I left `zpl_fallocate_common()` in `zpl.h` and in `zpl_file.c` because it's still needed.  Looks like on master this has either been removed or split up and moved somewhere else.  I left it alone.

- `uio.uio_limit` was set to `MAXOFFSET_T` in 0.8.6 in a couple hunks that failed, but the hunks were removing the entire `uio` struct, so it seemed harmless.

- Looks like master uses `ITOZ()` in a couple places that broke hunks, but again, it was in code being removed.

- `zfs_write_simple()` doesn't exist in 0.8.6.  I copied the entire function into `zfs_vnops.c` and declared it in `zfs_vnops.h`... Seems to work OK with a little tweaking.

- Moved `zfs_uio.c` back into `zcommon`.

After that, there's a series of small commits fixing compilation errors I'd induced.

### How Has This Been Tested?

Code now compiles against 5.10.  Basic testing seems good.  I can import my pool, play with ZVOLs, clone and compile the Linux kernel.  I haven't seen any problems, but I also have not specifically tested `sendfile(2)`.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Ornias1993** [comment]
This should be send to a (yet to be created) 0.8.7 staging branch, not the 0.8 this release branch.

**Comment by veggiemike** [comment]
Shoot, I may have a problem.  I just tried to update kernel modules on a virtual machine using a zfs root filesystem via rsync and got this:

```
rsync: write failed on "/vm/t/lib/modules/5.10.1-mdl+/modules.alias": File too large (27)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]
```

Looks like I'm getting a slew of "File to o large" errors reported in syslog, too.

With the system booted back into 5.9 w/ ZFS 0.8.6 I don't have any problems...  so...  either my backport isn't quite right, or I'm missing something else to get things fully working in 5.10.

**Comment by behlendorf** [comment]
There are two follow commits you'll want to include #11373 #11378.  Though from the error message it doesn't sound like you hit the #11378 issue.

**Comment by veggiemike** [comment]
> There are two follow commits you'll want to include #11373 #11378. Though from the error message it doesn't sound like you hit the #11378 issue. The CI tests also indicate this isn't quite right.

I cherry-picked those 2 commits and tried again.  Same behavior.  I've also cherry-picked all 3 onto ZFS 2.0 with the exact same behavior (but much simpler backport).

**Comment by veggiemike** [comment]
> > There are two follow commits you'll want to include #11373 #11378. Though from the error message it doesn't sound like you hit the #11378 issue. The CI tests also indicate this isn't quite right.
> 
> I cherry-picked those 2 commits and tried again. Same behavior. I've also cherry-picked all 3 onto ZFS 2.0 with the exact same behavior (but much simpler backport).

I did the same testing w/ 2.0.1-staging prior to its release and everything worked fine...  So, whoever did the cherry-picking over the holidays did a better job than I did.  ;-)

@behlendorf, I'll close this PR until I get around to comparing 2.0.1's contents to my branch... which might not happen, as I'm probably going to transition my systems to 2.0 at this point.

**Pull request closed without merging**
