### PR TITLE
Added check for broken alien version

### LINKED ISSUE #11650: Debian 11 Source DKMS Build Fails Due to 'alien' and 'dh'
### System information

| Type | Version/Name |
| ----- | -------------- |
| Distribution Name | Debian |
| Distribution Version | 11 Bullseye/Testing (Soft Freeze) |
| Linux Kernel |  5.10.0-3-amd64 |
| Architecture | amd64 |
| ZFS Version | 2.0.3 |
| SPL Version | Unknown |

### Describe the problem you're observing

On a fresh installation of Debian 11 Testing (currently in a Soft Freeze), it is impossible to build the required *.deb packages due to an error with `alien` (which actually shows an error from `dh`). Apparently the build process first creates RPMs (regardless of the distribution) and then tries (and fails) to convert them to other formats.

On a somewhat related note, I was able to build OpenZFS 2.0.0 in the past on Debian 10 Buster/Stable without any issues.

### Describe how to reproduce the problem

I am following the [Debian and Ubuntu DKMS installation guide](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html#debian-and-ubuntu). Download OpenZFS 2.0.3 on Debian 11 and build with these settings:

```
$ ./configure --enable-systemd
$ make -j $(nproc) deb-utils deb-dkms
```

### Include any warning/errors/backtraces from the system logs

Here is the actual error reported by the `make` command:

```
make[1]: Entering directory '/root/zfs-2.0.3/zfs-dkms-2.0.3'
dh
dh: error: specify a sequence to run
make[1]: *** [debian/rules:7: binary] Error 25
make[1]: Leaving directory '/root/zfs-2.0.3/zfs-dkms-2.0.3'
make: *** [Makefile:1695: deb-dkms] Error 1
```

This error also occurs when using the `alien` command manually. Is [this the official alien project](https://github.com/mildred/alien)? It has been untouched since 2011.

```
$ alien zfs-2.0.3-1.x86_64.rpm
Warning: Skipping conversion of scripts in package zfs: postinst postrm prerm
Warning: Use the --scripts parameter to include the scripts.
Package build failed. Here's the log:
dh
dh: error: specify a sequence to run
make: *** [debian/rules:7: binary] Error 25
```

As an alternative, I tried using [fpm](https://github.com/jordansissel/fpm) but it failed to properly convert the packages. Various errors existed with the *.deb packages it created.

```
$ for i in $(ls -1 | grep -P '\.rpm' | grep -v -P '\.src'); do fpm -s rpm -t deb $i; done
$ sudo dpkg -i ./*.deb
dpkg: error processing archive ./libnvpair3_2.0.3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'libnvpair3':
 'Depends' field, invalid package name '/sbin/ldconfig': must start with an alphanumeric character
dpkg: error processing archive ./libuutil3_2.0.3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'libuutil3':
 'Depends' field, invalid package name '/sbin/ldconfig': must start with an alphanumeric character
dpkg: error processing archive ./libzfs4_2.0.3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'libzfs4':
 'Depends' field, invalid package name '/sbin/ldconfig': must start with an alphanumeric character
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'libzfs4-devel':
 'Depends' field, reference to 'rpmlib':
 implicit exact match on version number, suggest using '=' instead
dpkg: error processing archive ./libzfs4-devel_2.0.3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'libzfs4-devel':
 'Depends' field, reference to 'rpmlib': version 'CompressedFileNames': version number does not start with digit
dpkg: error processing archive ./libzpool4_2.0.3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'libzpool4':
 'Depends' field, invalid package name '/sbin/ldconfig': must start with an alphanumeric character
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'python3-pyzfs':
 'Depends' field, reference to 'rpmlib':
 implicit exact match on version number, suggest using '=' instead
dpkg: error processing archive ./python3-pyzfs_2.0.3-1_all.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'python3-pyzfs':
 'Depends' field, reference to 'rpmlib': version 'CompressedFileNames': version number does not start with digit
dpkg: error processing archive ./zfs-dkms_2.0.3-1_all.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'zfs-dkms':
 'Depends' field, invalid package name '/bin/sh': must start with an alphanumeric character
dpkg: error processing archive ./zfs-dracut_2.0.3-1_all.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'zfs-dracut':
 'Depends' field, invalid package name '/bin/sh': must start with an alphanumeric character
dpkg: error processing archive ./zfs-initramfs_2.0.3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'zfs-initramfs':
 'Depends' field, invalid package name '/bin/sh': must start with an alphanumeric character
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'zfs-test':
 'Depends' field, reference to 'rpmlib':
 implicit exact match on version number, suggest using '=' instead
dpkg: error processing archive ./zfs-test_2.0.3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'zfs-test':
 'Depends' field, reference to 'rpmlib': version 'CompressedFileNames': version number does not start with digit
Errors were encountered while processing:
 ./libnvpair3_2.0.3-1_amd64.deb
 ./libuutil3_2.0.3-1_amd64.deb
 ./libzfs4_2.0.3-1_amd64.deb
 ./libzfs4-devel_2.0.3-1_amd64.deb
 ./libzpool4_2.0.3-1_amd64.deb
 ./python3-pyzfs_2.0.3-1_all.deb
 ./zfs-dkms_2.0.3-1_all.deb
 ./zfs-dracut_2.0.3-1_all.deb
 ./zfs-initramfs_2.0.3-1_amd64.deb
 ./zfs-test_2.0.3-1_amd64.deb
```

### LINKED ISSUE #11848: Add a warning for certain alien versions?
### Describe the feature would like to see added to OpenZFS
Certain versions of alien (e.g. 8.95.3) produce broken debs from the OpenZFS RPMs (cf. #11650 ), both in ways that are trivially visible (e.g. erroring out in make deb-dkms/deb-utils/deb-kmod) and in ways that are not visible until you install them if you patch that flaw (in particular, they land a lot of the files one directory "up" from where you might expect - so instead of /usr/include, things wind up in /include, and so on).

### How will this feature improve OpenZFS?
It might be nice to print a notification on running make deb-utils/etc if the alien version detected was known to be broken, warning people that if it breaks, it's not "our" fault, possibly citing #11650 or the relevant Debian bugs for further context.

### Additional context
This hasn't been that big a deal yet, because 8.95.3 isn't shipping until Debian bullseye and Ubuntu hirsute (and the bug is specific to generating debs, so that covers most of the relevant bases), but it is broken 100% of the time on those versions, and will lead to bug reports coming in once nontrivial numbers of people actually have that version installed.

It'd be nice if Debian/Ubuntu shipped a newer version with this fixed and never shipped 8.95.3 in a released version, but I don't want to suggest betting on that when we know it's broken.

### PR DESCRIPTION
**Pull request by rincebrain**
Implemented the suggested detection of a broken alien version from #11848 

### Motivation and Context
Closes #11848 ; does not fix #11650, merely detects the broken version discovered from that.

### Description
Added a check for alien 8.95.3, which is known to fail to generate debs 100% of the time, and instead print out a message informing the developer that it's known to be broken and linking them to more information.

### How Has This Been Tested?
Tried compiling with alien 8.95 and 8.95.3 installed, verified that it bailed out on the latter and built normally with the former.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Just to be clear do I understand correctly that only this version of alien is effected?  Both older and newer versions work fine?  It would be best if we could make sure Debian bullsye ships with a working version, even if we do expect most users to use the distribution provided packages and not alien.  @aerusso do you happen to know if getting a newer (or even older) version is still possible?  Regardless, adding a warning does seem like the least we can do.

**Comment by rincebrain** [comment]
Technically, 8.95.2 and 8.95.1 are also affected by at least one of the two bugs, but nobody's shipped those in a released distro that I could find, so I didn't make the check more versatile. It'd be simple enough to do if you'd prefer.

There's not yet any version newer than 8.95.3; one presumes they would ship patches for this in that version, but it's not been cut yet, so who knows.

You have to go out of your way to get 8.95 on bullseye - I think your options are grabbing the buster packages for it or building it yourself. There's not really an easy way to just go "apt install alien-8.95" without some work on your part.

**Comment by behlendorf** [comment]
Once Debian bullseye is available we'll want to add it to the CI and that looks like it's going to be an issue unless this is resolved in the distribution.  Is there either a Debian or alien bug we can reference for this?  This might also be a good time to revisit adding some proper deb style packaging in the repository as long it doesn't conflict with the downstream packaging.

**Review by behlendorf — APPROVED** [review]

**Comment by freqlabs** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985835

Awesome, looks like someone is on it as of today.

**Comment by behlendorf** [comment]
That's good news.  It sounds like we'll probably want to include this change either way but it'll be nice if this can get resolved before it's a wide spread issue.

**Pull request merged**
