### PR TITLE
Fix dracut. Document it.

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
@behlendorf: as promised in https://github.com/openzfs/zfs/pull/13017#issuecomment-1036394027

### Description
Uh, well. In order to write documentation I had to actually test whether the magic half of dracut was depending on, well, worked. Turns out it didn't. Which, well, means it didn't. Which explains why it's consistently kinda nondescriptly ass and we keep (kept?) getting people whose basic setups were failing. It's honestly a miracle and an incredible accident this'd worked at all.

Also, the non-systemd path (`zfs-mount.sh`) needs either removing or fixing; I haven't the slightest how you'd adjust network key loading. I don't even know *if* it works because I don't have a system or even distribution I could test it with. Well, I'm not building Gentoo I guess?

### How Has This Been Tested?
Thoroughly. See commit messages. As far as the new manual goes, here's the dracut.bootup(7)-style flowchart:
image
image

And PDF: [job_1958-stdin___jaczleweli_PDF.pdf](https://github.com/openzfs/zfs/files/8414026/job_1958-stdin___jaczleweli_PDF.pdf) (I don't usually target postscript in ZFS manuals, but, well, this looks shockingly alright in landscape)

Closes #13291

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – none apply
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Thanks!  The flow chart is great to see.  Let's see if we can get some additional eyes on this.  cc: @Rudd-O @c0d3z3r0 @prometheanfire

**Comment by prometheanfire** [comment]
I love this, where was this 2-3 years ago lol

**Comment by nabijaczleweli** [comment]
1.5-week bump

**Review by behlendorf — APPROVED** [review]
Going over the commits everything here looks reasonable.  I haven't manually tested it myself, but this is a nice step forward and the documentation is much appreciated.  I'm going to go ahead and integrate it, if any unexpected issues arise we can investigate them as they're reported.

**Comment by Rudd-O** [comment]
Why was this closed??  This is amazing work, looks like it got closed by accident in the commit above.

**Comment by thesamesam** [comment]
> Why was this closed?? This is amazing work, looks like it got closed by accident in the commit above.

It was merged in https://github.com/openzfs/zfs/commit/47636f5661abf202c725f1975939878e7156d3c8 (as the first commit in the series, by the looks of it). Not everyone uses merge commits.

Can you point to a commit which you think got lost?

**Comment by nabijaczleweli** [comment]
I've re-validated that the entire diff is applied in 47636f5661abf202c725f1975939878e7156d3c8^..47a02e39721bd226646dbdfe3063563a4a5e9749.

**Pull request closed without merging**
