### PR TITLE
do not allocate memory if vdev has no children

### PR DESCRIPTION
**Pull request by ikozhukhov**
### Description

on DilOS we can see on debug build a lot of noise message about 0 kmem_alloc
```
WARNING: kmem_alloc(): sleeping allocation with size of 0; see kmem_zerosized_log for details
``` 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ikozhukhov** [comment]
could you please describe your proposed check - you mean: try to check/idenitfy type of vdev where we can see zeroed kmem_alloc in this function ? or something else?
example will be more useful to me.

**Comment by behlendorf** [comment]
> check/idenitfy type of vdev where we can see zeroed kmem_alloc in this function

Yes exactly.  Specifically, which `vd->vdev_ops` structure is being used when there are no children.  For example, are these the `vdev_replacing_ops` or `vdev_spare_ops`?  I'd just like to understand under what situation is this expected.

**Comment by ahrens** [comment]
Could this be for indirect vdevs?

**Comment by ikozhukhov** [comment]
hi all, we can see issue with scenario: create mirrored pool -> upload some traffic -> add mirrored drives to pool -> add traffic -> add mirrored drives to pool -> try to remove second mirrored drives and monitor logs on DilOS debug build - we can see messages about `kmem_alloc(): sleeping allocation with size of 0;`

**Comment by behlendorf** [comment]
Closing as stale.

**Pull request closed without merging**
