### PR TITLE
Prune (most) checks for pre-3.10 kABI

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
I thought it'd make the build faster, I guess

### Description
A full reconfigure (`time sh -c "./autogen.sh && ./configure CC=cc CFLAGS='-O3 -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers'"`) went from
```
real    2m3.998s
user    4m36.190s
sys     0m59.043s
```
to
```
real    1m54.983s
user    3m35.966s
sys     0m46.875s
```
which is a minute in user-space and 13 seconds in the kernel, which ain't half bad, I'd say, even if it only translated to 10 seconds on my dev box (amd64, 2xE5645 (2x6x2, 2.40GHz), clang 13.0.0-++20210511102624+4433f4601e8a-1\~exp1\~20210511203417.1496, options as above), but all of 46 seconds on my router (x32, E6400 (1x2x1, 2.13GHz), gcc 10.2.1-6, default options):
```
real    4m11.242s
user    5m18.201s
sys     0m46.937s
```
to
```
real    3m25.565s
user    4m8.580s
sys     0m36.922s
```

The amount of compiled kABI modules went from 227 to 162.

Broken down per file in config/.

### How Has This Been Tested?
I, uh, built it on Buster (4.19) and current Sid (5.10). Most of these are really obvious and all-minus (since they were previously turned into errors), but there are a few that had to touch code outside of config/.

zfs_config.h changes are as such:
```diff
diff --git a/zfs_config.h-before b/zfs_config.h-after
index 9e9d46f..f281a37 100644
--- a/zfs_config.h-before
+++ b/zfs_config.h-after
@@ -20,15 +20,9 @@
 /* vfs_getattr wants 2 args */
 /* #undef HAVE_2ARGS_VFS_GETATTR */
 
-/* zlib_deflate_workspacesize() wants 2 args */
-#define HAVE_2ARGS_ZLIB_DEFLATE_WORKSPACESIZE 1
-
 /* bdi_setup_and_register() wants 3 args */
 /* #undef HAVE_3ARGS_BDI_SETUP_AND_REGISTER */
 
-/* vfs_getattr wants 3 args */
-/* #undef HAVE_3ARGS_VFS_GETATTR */
-
 /* vfs_getattr wants 4 args */
 #define HAVE_4ARGS_VFS_GETATTR 1
 
@@ -137,9 +131,6 @@
 /* blk_queue_flush() is GPL-only */
 /* #undef HAVE_BLK_QUEUE_FLUSH_GPL_ONLY */
 
-/* blk_queue_secdiscard() is available */
-/* #undef HAVE_BLK_QUEUE_SECDISCARD */
-
 /* blk_queue_secure_erase() is available */
 #define HAVE_BLK_QUEUE_SECURE_ERASE 1
 
@@ -167,12 +158,6 @@
 /* check_disk_change() exists */
 #define HAVE_CHECK_DISK_CHANGE 1
 
-/* clear_inode() is available */
-#define HAVE_CLEAR_INODE 1
-
-/* dentry uses const struct dentry_operations */
-#define HAVE_CONST_DENTRY_OPERATIONS 1
-
 /* copy_from_iter() is available */
 #define HAVE_COPY_FROM_ITER 1
 
@@ -195,30 +180,12 @@
 /* lookup_bdev() wants dev_t arg */
 /* #undef HAVE_DEVT_LOOKUP_BDEV */
 
-/* sops->dirty_inode() wants flags */
-#define HAVE_DIRTY_INODE_WITH_FLAGS 1
-
 /* disk_*_io_acct() available */
 /* #undef HAVE_DISK_IO_ACCT */
 
 /* Define to 1 if you have the <dlfcn.h> header file. */
 #define HAVE_DLFCN_H 1
 
-/* d_make_root() is available */
-#define HAVE_D_MAKE_ROOT 1
-
-/* d_prune_aliases() is available */
-#define HAVE_D_PRUNE_ALIASES 1
-
-/* dops->d_revalidate() operation takes nameidata */
-/* #undef HAVE_D_REVALIDATE_NAMEIDATA */
-
-/* eops->encode_fh() wants child and parent inodes */
-#define HAVE_ENCODE_FH_WITH_INODE 1
-
-/* sops->evict_inode() exists */
-#define HAVE_EVICT_INODE 1
-
 /* fops->aio_fsync() exists */
 /* #undef HAVE_FILE_AIO_FSYNC */
 
@@ -234,12 +201,6 @@
 /* iops->follow_link() nameidata */
 /* #undef HAVE_FOLLOW_LINK_NAMEIDATA */
 
-/* fops->fsync() with range */
-#define HAVE_FSYNC_RANGE 1
-
-/* fops->fsync() without dentry */
-/* #undef HAVE_FSYNC_WITHOUT_DENTRY */
-
 /* generic_fillattr requires struct user_namespace* */
 /* #undef HAVE_GENERIC_FILLATTR_USERNS */
 
@@ -279,9 +240,6 @@
 /* yes */
 #define HAVE_INODE_LOCK_SHARED 1
 
-/* inode_owner_or_capable() exists */
-#define HAVE_INODE_OWNER_OR_CAPABLE 1
-
 /* inode_owner_or_capable() takes user_ns */
 /* #undef HAVE_INODE_OWNER_OR_CAPABLE_IDMAPPED */
 
@@ -375,9 +333,6 @@
 /* kmem_cache_create_usercopy() exists */
 #define HAVE_KMEM_CACHE_CREATE_USERCOPY 1
 
-/* kstrtoul() exists */
-#define HAVE_KSTRTOUL 1
-
 /* ktime_get_coarse_real_ts64() exists */
 #define HAVE_KTIME_GET_COARSE_REAL_TS64 1
 
@@ -426,9 +381,6 @@
 /* Define to 1 if you have the <memory.h> header file. */
 #define HAVE_MEMORY_H 1
 
-/* iops->mkdir() takes umode_t */
-#define HAVE_MKDIR_UMODE_T 1
-
 /* Define to 1 if you have the `mlockall' function. */
 #define HAVE_MLOCKALL 1
 
@@ -450,9 +402,6 @@
 /* percpu_counter_init() wants gfp_t */
 #define HAVE_PERCPU_COUNTER_INIT_WITH_GFP 1
 
-/* posix_acl_chmod() exists */
-/* #undef HAVE_POSIX_ACL_CHMOD */
-
 /* posix_acl_from_xattr() needs user_ns */
 #define HAVE_POSIX_ACL_FROM_XATTR_USERNS 1
 
@@ -537,9 +486,6 @@
 /* set_special_state() exists */
 #define HAVE_SET_SPECIAL_STATE 1
 
-/* struct shrink_control exists */
-#define HAVE_SHRINK_CONTROL_STRUCT 1
-
 /* kernel_siginfo_t exists */
 /* #undef HAVE_SIGINFO */
 
@@ -784,7 +730,7 @@
 /* #undef ZFS_IS_GPL_COMPATIBLE */
 
 /* Define the project alias string. */
-#define ZFS_META_ALIAS "zfs-2.1.99-174_g7457b024b"
+#define ZFS_META_ALIAS "zfs-2.1.99-217_g55ee35018"
 
 /* Define the project author. */
 #define ZFS_META_AUTHOR "OpenZFS"
@@ -814,7 +760,7 @@
 #define ZFS_META_NAME "zfs"
 
 /* Define the project release. */
-#define ZFS_META_RELEASE "174_g7457b024b"
+#define ZFS_META_RELEASE "217_g55ee35018"
 
 /* Define the project version. */
 #define ZFS_META_VERSION "2.1.99"
```

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – none should apply
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
I was always curious how much keeping these checks slowed things down.  We actually kept most of these checks intentionally because the upstream Linux kernel doesn't make any promises about ABI stability.  So while the interface being checked may not have changed since 3.10 there is some value in keeping the check to verify the interface is what we expect.  This way we can detect at configure time if the latest kernel decided to change any of these interfaces and produce a useful error (rather than at compile time).  The only checks we've dropped are for interfaces not present in any 3.10 or newer kernel.  After going through all of these do you have a sense of how many checks fell in this second category?

**Comment by nabijaczleweli** [comment]
I mean, I don't really, uh, know. This is 56 files and 1800 lines, if I thought deeply and reverently about every single one I would explode on the spot.

But the ABI for 3.10 will never change, that's what you pay RedHat for. We couldn't possibly care less about the ABI for pre-3.10 since, AIUI, we'll refuse to configure on kernels before Linux-Minimum:. And what's the flow for when kernel 6.29 removes, like, `get_disk_ro()`? It's gonna fail to build either way. There aren't macros for it anymore. Everything assumes `get_disk_ro()`. Right, so what are you going to do? Remove the check from the configure script, let it build until it hits an error in a user, fix it, and add another layered check to the configure script. Well, that, or figure out what the problem is, add the layered check, let it build, and then fix it, but most people who open issues of this sort are Gentoo users, not kernel developers who've just made that change. So you have to let'er rip anyway to find out what's wrong and how, in addition to git-logging mainline.

Plus, we also implicitly depend on large chunks of the Linux API that's never changed before, and will fail exactly the same way if it does – this just cuts out a massive 1800-line over-a-minute middle-man you're gonna remove for debugging anyway (mostly, there's some bugfixes as noted and one left-over I couldn't wrap my head around) – reverting all the interfaces we had to check for before into their primordial expressly-relied-on state of "it's not broken between L-Minimum: and L-Maximum:". The fix remains to copy a similar one and adapt it to the new interface, and not having an ancient borderline-untestable hunk in place can nary make it more difficult.
(If the aggressive pruning is retained, I'd also expect this to degrade much better in the than the 5.12-tmpfile-like case, but who knows.)

**Comment by behlendorf** [comment]
That's right.  We only support back to 3.10 kernels, and really that means we should only need to check for interfaces which were added post-3.10.  Anything which was part of 3.10 we can assume exists, which as you pointed out is what we do for a fairly large number of functions.  Although I'd wager we actually do have checks for a large percentage of the kernel interfaces we use.  Basically we have one for every function which has changed since about 2.6.32.

As for new kernels, thankfully when they make an ABI change it's usually pretty obvious and will manifest itself as a build failure.  That's the easy case.  What's much less common, but has definitely bit us in the past, is when a change is made which doesn't result in a build failure but does change the behavior of an interface.  To make sure we catch this kind of thing at configure time all of the checks written in the last few years are quite strict.  They should be verifying not just that the function exists but that the return type and all argument types are exactly as expected.  This way we're more likely to detect any potential problems with new kernels right away.

I understand people want the configure checks to be as quick as possible.  But as the person who often needs to handle every new kernel change I find the additional checks valuable.  Perhaps there's a reasonable way to make these checks optional and be disabled by default.

**Comment by nabijaczleweli** [comment]
Makes sense, thanks for the explanation. I don't think switching over to an alternative set of checks (or adding these ones, but slightly elsewhere and only sometimes) is really worth the hassle and mental overhead.

**Pull request closed without merging**
