### PR TITLE
patchset for compatibility with musl libc

### PR DESCRIPTION
**Pull request by stef**
this patch set contains changes to zfsonlinux so it compiles with musl an alternative libc that ships with alpine linux for example. The biggest patch is the support for TIRPC an external RPC library, since musl does not ship such functionality.

### CODE REVIEW

**Comment by stef** [comment]
re: licensing of libtirpc

ryao commented on config/musl.m4 in 20e5610 on Aug 18, 2014
> libtirpc is GPLv2 licensed. We cannot link to it in a manner that permits redistribution. We will need to port the Transport-Independent RPC library from Illumos.

and later:

ryao commented on module/nvpair/nvpair.c in 20e5610 on Aug 18, 2014
> ...
> Unfortunately, we cannot do that due to the library license.

it seems that libtirpc is in fact 3 clause BSD licensed, and the license is wrong in the alpine linux APKBUILD file.

**Comment by ryao** [comment]
@stef It is wrong in the Gentoo ebuild file too. I have filed a bug:

https://bugs.gentoo.org/show_bug.cgi?id=567362

If you add autotools checks so that libtirpc can be used as a fallback, we can merge this.

**Comment by prometheanfire** [comment]
do we want to reopen this then or comment on a related issue?

**Comment by ryao** [comment]
@prometheanfire I cannot reopen this. @stef or @behlendorf could though.

**Comment by behlendorf** [comment]
If we can get the patch stack refreshed against the latest master so it can be applied we can definitely revisit this so it can be applied.

**Comment by stef** [comment]
i'm not sure i have the time in the short term for this.

**Pull request closed without merging**
