### PR TITLE
Revert "systemd: Use non-absolute paths in Exec* lines"

### PR DESCRIPTION
**Pull request by rincebrain**
This, uh, broke RHEL-based distros. #14943

### CODE REVIEW

**Comment by rincebrain** [comment]
@xnox FYI. Maybe it's possible to gate this against some kind of version check so people can have their cake and eat it too? I think more debugging would be required though, since the reporter said this is happening even after the version listed as doing that...

**Comment by xnox** [comment]
Revert is fine. It will fix rhel7 if that's what is still supposedly supported (an ultra stable, obsolete release, upgrading to latest zfs-linux but ok)

rhel9 is confusing - i don't see any actual failures in the bug report, where is rhel9 failure detected?

**Comment by xnox** [comment]
Need more information as to what and how broke on rhel9.

**Comment by rincebrain** [comment]
I said RHEL-based. Rocky Linux is one of the ones that wandered off and made their own CentOS-alike when CentOS changed models, and is what they meant in the thread by RL9. I'm booting my actual RHEL9 testbed to see if it reproduces there as well.

I don't have a particularly strong opinion on supporting EL7 or not at the moment, but if we're going to stop supporting it, we should probably update the documentation and drop a ton of configure checks, and I haven't seen anyone proposing that.

**Comment by xnox** [comment]
> I'm guessing something is different in the configuration of RL9 if this is breaking on v252..

everything is working fine on RL9 without any reverts, without any need for any higher systemd.

**Comment by behlendorf** [comment]
While rhel7 is ancient it's still used and I'd like to maintain support for it until it's EOL (2024).  Perhaps we can do something conditionally as suggested above, we're already dynamically generation these files.  In the meanwhile, I agree we should revert this.

**Review by behlendorf — APPROVED** [review]

**Pull request merged**
