### PR TITLE
zfs-2.2.4 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patchset for zfs-2.2.4.  

### Description
Support 6.8 kernel, misc other fixes.

### How Has This Been Tested?
Test built.  Buildbot will test.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by tonyhutter** [comment]
TODO: pull in https://github.com/openzfs/zfs/pull/16106 once it's approved.

**Comment by ixhamza** [comment]
I think we can also pull https://github.com/openzfs/zfs/pull/16098, which was recently merged to `zfs-2.2.4-staging`.

**Comment by tonyhutter** [comment]
@ixhamza thanks, meant to pull that in.  I just rebased this PR on zfs-2.2.4-staging so it's included now.

**Comment by clhedrick** [comment]
How about [ZAP: Massively switch to _by_dnode() interfaces](https://github.com/openzfs/zfs/commit/80cc516295fef1a429542fcfeea369c6bbb85ce4)

I'm seeing problems that. while it may not be caused by ZFS, might benefit from this.

**Comment by amotin** [comment]
> How about [ZAP: Massively switch to _by_dnode() interfaces](https://github.com/openzfs/zfs/commit/80cc516295fef1a429542fcfeea369c6bbb85ce4)

It is included into #16106 , that is already in review.

**Comment by usaleem-ix** [comment]
@tonyhutter Please consider https://github.com/openzfs/zfs/pull/16092.

**Comment by Harry-Chen** [comment]
I suggest considering the following fixes:

* #15979 and #15980, both are fixes to the building process.
* #15977 that fixes the behavior on OpenRC.

**Comment by tonyhutter** [comment]
All - everything that has been requested has been cherry-picked in.  I also re-based on zfs-2.2.4-sraging to pull in some recent PRs that got merged.

**Comment by aenigma1372** [comment]
My apologies if this was already included in a release at some point, although I don't recall seeing it in any of the previous ZFS 2.2.x releases.  Would #15197 be a potential candidate for inclusion in this release?  I believe previously it was mentioned that more testing was needed, so wasn't sure if I missed it being included in a previous release, if it needs to bake longer yet and/or if there are other blockers, or if it was just an oversight that it wasn't included in a release as of yet?

**Comment by tonyhutter** [comment]
@aenigma1372 I think https://github.com/openzfs/zfs/pull/15197 is a great performance improvement.  However it's a fairly big change, and I would lean towards being cautious and putting it in a future 2.3.0 release.  If someone wants to backport it and vouch for it's stability ("we've been running this at scale with zero issues") then maybe we can get it in a future 2.2.x release.

**Comment by Gendra13** [comment]
Speaking of big changes:
Are there any plans to re-enable block-cloning by default with 2.2.4?

**Comment by tonyhutter** [comment]
> Are there any plans to re-enable block-cloning by default with 2.2.4?
 
No plans so far

**Comment by patrickdk77** [comment]
> My apologies if this was already included in a release at some point, although I don't recall seeing it in any of the previous ZFS 2.2.x releases. Would #15197 be a potential candidate for inclusion in this release? I believe previously it was mentioned that more testing was needed, so wasn't sure if I missed it being included in a previous release, if it needs to bake longer yet and/or if there are other blockers, or if it was just an oversight that it wasn't included in a release as of yet?

I just backported it, and am testing it out, if you also want to test: https://github.com/patrickdk77/zfs/tree/backport-pr15197

**Comment by pharshalp** [comment]
Is #16104 up for consideration for this release?

**Comment by aenigma1372** [comment]
> @aenigma1372 I think #15197 is a great performance improvement. However it's a fairly big change, and I would lean towards being cautious and putting it in a future 2.3.0 release. If someone wants to backport it and vouch for it's stability ("we've been running this at scale with zero issues") then maybe we can get it in a future 2.2.x release.

@tonyhutter Thanks for the quick reply, and I agree that it should be a pretty nice performance improvement, but I suspected that it might need more time to bake as well.  At least it looks like #16107 made it into this patch set, so I believe that should help a bit with performance as well in the interim until #15197 is ready for a stable release.  Maybe in the meanwhile someone with the resources will be able to test it at scale, but if not, I look forward to seeing it in 2.3.x with any luck.

**Comment by rincebrain** [comment]
> Is #16104 up for consideration for this release?

The only reason I might not suggest it is just that it got merged in git very recently, and it'd be nice to wait a little bit before shipping in a "stable" release. I've seen 0 problems with testing it personally, but I'm personally very wary of things going into a  stable release very fast, no matter how much I think it's stable, unless it's an immediate and dire issue.

And unfortunately, while I would say it's a bad situation, it's not really an immediate problem - it's been this way for a while, so it feels like letting it bake until 2.2.5 or something would be the way I would lean, personally, as much as I am pleased it's been improved. (I'm still very wary of saying "fixed", after a lot of false positives.)

**Comment by tonyhutter** [comment]
We'll need https://github.com/openzfs/zfs/pull/16125 for Fedora 40 to work.

**Comment by tonyhutter** [comment]
Also on our radar: https://github.com/openzfs/zfs/pull/16129

**Comment by Harry-Chen** [comment]
From #16005, 506fe78c48 should also be backported, then the incorrect `ASSERT0` in 9c40ae0 can be fixed.

**Comment by jumbi77** [comment]
What about https://github.com/openzfs/zfs/commit/44f337be30e1502b32c8d381344044f15dd34674 ?

**Comment by AllKind** [comment]
I went through the commit list of the last 3 months and compiled a list of things I think should be included.
Mostly fixes plus 3 new features.
Maybe there are reasons not to include them, that I'm not aware of. Just trying to be a bit of help.

Fix locale-specific time f07389d3ad48ba21480dedcd79b75fe0a31e27bc
zfs-kmod: fix empty rpm requires/conflicts 87d81d1d13e0ef848d2d533a4f12f5de41026e73
ZTS: user_namespace_004.ksh avoid error in cleanup if unsupported cdae59e1530061cf4caa549a062994161c4383c6
Add newline to two zpool messages 9b43d7ba85059d37533d42f62cbb646203fd4a94
Do no use .cfi_negate_ra_state within the assembly on Arm64 90ba19eb7b81f0225e63bedfb902000d23383921
Add the BTI elf note to the AArch64 SHA2 assembly c6da985e28d7071b187bd928e7fd41ba9e9f6aa7
AUTHORS: refresh with recent new contributors e2035cdbf70e2d4e6f819ce6d5f6a286a152d264
return NULL at end of send_progress_thread e5ddecd1a7e33bc341e7b5e8dd25d2fe478de8f2
Fix panics when truncating/deleting files 30c4eba4eaaef92cbc1b8d2eed6689600a342386
vdev props comment and manpage should include zfsd and FreeBSD mentions ea2862cdda1009a98a6f7b390e34b705bb7d90ae
zap_leaf: make l_hash[] variable length to silence UBSAN b21b967bd5095d431b71ef63f09e0d31c0ef0b08
Give a better message from 'zpool get' with invalid pool name b6bbaa837271698f238a9264c4070416077fb67b
xdr: header cleanup a9a4290173dfdfd25aabd623bc3ccd994126794a
Fix buffer underflow if sysfs file is empty 2553f94c4299aaf31c5ceea4bfbfcc811cf76513
ZTS: fix flakiness in cp_files_002_pos e39e20b6dc73bd7df1f097c23b5297bcc989ed53
Fix option string, adding -e and fixing order c9d8f6c59a268f65075bb9e510a58b1eec8015f7
freebsd: fix missing headers in distribution tarball 90ff732358390ac395999577b703dcb4d3e0df59
Check for minimum partition size af4da5ccf28e1de6d4f6771a8d9d7cc578aba087

Add zfetch stats in arcstats cd3e6b4f4c5e0b514f3e76e194b2a5753264d44f (minor feature upgrade)
Parallel pool import c183d164aa11e61dfe1f34907c1a029d75162f1d (very useful new feature)
Add ashift validation when adding devices to a pool b1e46f869e773086c23c565d7d5b261577023cfb (very important update, as people regularly fall into this trap)

**Comment by clhedrick** [comment]
We have limited opportunities to do reboots. One is coming up in a week. It looks like 2.2.4 won't be finished by then. There are some fixes there that could make a difference to us. Would it make sense to deploy 2.2.4 as it is now, i.e. from last week when it was tagged as 2.2.4? It works on a test system.

**Comment by Harry-Chen** [comment]
The soversion of `libzpool` should be updated in master and cherry-picked to 2.2.4.

Some symbols are removed, including `brt_zap_indirect_blockshift`, `dmu_buf_dnode_enter`, `zfs_brt_prefetch`, etc. Also many symbols have been added since last soversion bump in fe6babce (#11817).

@behlendorf What's your opinion on this?

**Comment by tonyhutter** [comment]
@harry-chen 506fe78 is included in my latest push.  I don't have an opinion one way or the other on the library versioning.

@jumbi77 44f337b is included in my latest push

@AllKind everything on your list is included in my latest push, except "Parallel pool import" (c183d16) since it's a complex feature that only got merged last week.

**Comment by Harry-Chen** [comment]
@behlendorf As mentioned in https://github.com/openzfs/zfs/pull/16107#issuecomment-2083007714 I suggest a soversion bump of `libzpool` in 2.2.4. If you agree I could submit a PR to do that.

**Review by behlendorf — APPROVED** [review]

**Pull request merged**
