### PR TITLE
Compatibility update for 5.14 for blk_alloc_disk()

### PR DESCRIPTION
**Pull request by ckane**
In Linux 5.14, blk_alloc_queue is no longer exported, and its usage
has been superseded by blk_alloc_disk, which returns a gendisk struct
from which we can still retrieve the struct request_queue* that is
needed in the one place where it is used. This also replaces the call
to alloc_disk(minors), and minors is now set via struct member
assignment.

### Motivation and Context
This API change results in a failure to compile on 5.14rc1

### How Has This Been Tested?
Tested on my system by booting on kernel 5.14. Unfortunately, wasn't able to test extensively because 5.14 appears to introduce a amdgpu regression that causes drm/Xorg to crash. That said, booted multiple times and tried a few tests from cmdline and it seems to work.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
@ckane thanks for digging in to this!  I put together a very [similar patch](https://github.com/behlendorf/zfs/commit/cdcffdd6f7e5de2cc83075966a9409420e84e681) but ran in problems booting 5.14-rc1 as well so I wasn't able to test it.  It looks like we basically have the same fix I just did a little more restructuring to condense the `#if` conditionals for readability and put the configure test in `config/kernel-make-request-fn.m4` instead.  It'd be great if you could take a look and let me know what you think of this alternate version.  Then we can decide how to proceed.

**Comment by ckane** [comment]
Thanks @behlendorf - I'll give yours a spin on my system after I go through this bisect exercise on 5.14rc1 to get an idea about what's breaking this kernel for me. I was able to boot to console (I normally get into X11 using `startx` anyhow), just couldn't go graphical. I think your approach is more complete, so if it works for me I'll just recommend going with your solution.

**Comment by ckane** [comment]
Ok @behlendorf - I managed to test yours today and it seems to work identically to my version on 5.14, so looks good to me. I don't know what the boot issue is on 5.14rc1 but it sounds like it isn't just me and isn't related to this at all. As well, I tested against code merged for 5.14rc2, works the same, and kernel is still unresponsive for me when I try to use Xorg.

**Review by pcd1193182 — APPROVED** [review]

**Comment by behlendorf** [comment]
@ckane I've gone ahead and opened up PR #12409 with the alternate version of this fix.  It should be identical to the one you tested.  @ckane @pcd1193182 if you could both re-review it I think we should be able to move forward with getting this kernel compatibility issue resolved.

**Pull request closed without merging**
