### PR TITLE
Fix hangs with parallel pool import

### LINKED ISSUE #16172: Parallel zpool import hangs
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 15.0-CURRENT
Kernel Version	|  git cf04a777 (from Apr 23, 2024)
Architecture	| amd64
OpenZFS Version	| zfs-2.2.99-456-FreeBSD_g1f940de07

### Describe the problem you're observing

When attempting to import six pools in parallel, the `zpool import` command hangs.  It seems to import all pools, but fail to mount datasets for some of them.  It has hanged on six attempts so far out of seven. (The good news is that the one time it didn't hang, it ran twice as fast as before the parallel pool import feature.)

### Describe how to reproduce the problem

I created six zpools, each consisting of a 4-disk RAIDZ2 array.  All disks were 2.5" SAS 1.8TB SEAGATE ST2000NX0263.  Then I created 1024 child file systems on each pool.  All children are mounted, but they contain no files.  To reproduce the hang, I just run `zpool import -a`.

### Include any warning/errors/backtraces from the system logs
There are no errors in any logs.

Here are the stack traces from the hung zpool process:
<details open>
    <summary>Thread 1</summary>

```
#0  _umtx_op_err () at /usr/home/somers/src/freebsd.org/src/lib/libsys/amd64/_umtx_op_err.S:38
#1  0x0000096a3a705f22 in _thr_umtx_timedwait_uint (mtx=0x96a3a70a2a8, id=id@entry=0, clockid=<optimized out>, abstime=<optimized out>, shared=15, shared@entry=0)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_umtx.c:223
#2  0x0000096a3a6fc5a9 in _thr_sleep (curthread=curthread@entry=0xc0542e12000, clockid=0, abstime=abstime@entry=0x0) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_kern.c:196
#3  0x0000096a3a6f7b57 in cond_wait_user (cvp=0xc0542e536c0, mp=0xc0543400108, abstime=0x0, cancel=1) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:318
#4  cond_wait_common (cond=cond@entry=0xc0542e87178, mutex=mutex@entry=0xc0542e87160, abstime=abstime@entry=0x0, cancel=cancel@entry=1)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:378
#5  0x0000096a3a6f7dd1 in __thr_cond_wait (cond=0x96a3a70a2a8, cond@entry=0xc0542e87178, mutex=0xf, mutex@entry=0xc0542e87160)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:393
#6  0x0000096a371cec7f in tpool_wait (tpool=tpool@entry=0xc0542e87150) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:529
#7  0x0000096211ec5f41 in import_pools (pools=<optimized out>, pools@entry=0xc0549e72000, props=0x0, mntopts=mntopts@entry=0x0, flags=flags@entry=0, orig_name=0x0, new_name=0x0, 
    import=0x96a32008bd0) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/cmd/zpool/zpool_main.c:3585
#8  0x0000096211eba8e5 in zpool_do_import (argc=0, argv=<optimized out>) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/cmd/zpool/zpool_main.c:4090
#9  0x0000096211eb4534 in main (argc=3, argv=0x96a3200a338) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/cmd/zpool/zpool_main.c:11621
```
</details>
<details open>
    <summary>Thread 2</summary>

```
#0  _umtx_op_err () at /usr/home/somers/src/freebsd.org/src/lib/libsys/amd64/_umtx_op_err.S:38
#1  0x0000096a3a705f22 in _thr_umtx_timedwait_uint (mtx=0xc0543422248, id=id@entry=0, clockid=<optimized out>, abstime=<optimized out>, shared=15, shared@entry=0)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_umtx.c:223
#2  0x0000096a3a6fc5a9 in _thr_sleep (curthread=curthread@entry=0xc0542eacf00, clockid=0, abstime=abstime@entry=0x0) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_kern.c:196
#3  0x0000096a3a6f7b57 in cond_wait_user (cvp=0xc0542e536a0, mp=0xc0543400108, abstime=0x0, cancel=1) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:318
#4  cond_wait_common (cond=cond@entry=0xc0542e87170, mutex=mutex@entry=0xc0542e87160, abstime=abstime@entry=0x0, cancel=cancel@entry=1)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:378
#5  0x0000096a3a6f7dd1 in __thr_cond_wait (cond=0xc0543422248, cond@entry=0xc0542e87170, mutex=0xf, mutex@entry=0xc0542e87160)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:393
#6  0x0000096a371cef6b in tpool_worker (arg=0xc0542e1a090) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:150
#7  0x0000096a3a6f8cb5 in thread_start (curthread=0xc0542eacf00) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_create.c:289
#8  0x0000000000000000 in ?? ()
```
</details>
<details open>
    <summary>Thread 3</summary>

```
#0  _umtx_op_err () at /usr/home/somers/src/freebsd.org/src/lib/libsys/amd64/_umtx_op_err.S:38
#1  0x0000096a3a705f22 in _thr_umtx_timedwait_uint (mtx=0xc05434221b8, id=id@entry=0, clockid=<optimized out>, abstime=<optimized out>, shared=15, shared@entry=0)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_umtx.c:223
#2  0x0000096a3a6fc5a9 in _thr_sleep (curthread=curthread@entry=0xc0542eaa500, clockid=0, abstime=abstime@entry=0x0) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_kern.c:196
#3  0x0000096a3a6f7b57 in cond_wait_user (cvp=0xc0542e536a0, mp=0xc0543400108, abstime=0x0, cancel=1) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:318
#4  cond_wait_common (cond=cond@entry=0xc0542e87170, mutex=mutex@entry=0xc0542e87160, abstime=abstime@entry=0x0, cancel=cancel@entry=1)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:378
#5  0x0000096a3a6f7dd1 in __thr_cond_wait (cond=0xc05434221b8, cond@entry=0xc0542e87170, mutex=0xf, mutex@entry=0xc0542e87160)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:393
#6  0x0000096a371cef6b in tpool_worker (arg=0xc0542e1a0f0) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:150
#7  0x0000096a3a6f8cb5 in thread_start (curthread=0xc0542eaa500) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_create.c:289
#8  0x0000000000000000 in ?? ()
```
</details>
<details open>
    <summary>Thread 4</summary>

```
#0  _umtx_op_err () at /usr/home/somers/src/freebsd.org/src/lib/libsys/amd64/_umtx_op_err.S:38
#1  0x0000096a3a705f22 in _thr_umtx_timedwait_uint (mtx=0xc0543422218, id=id@entry=0, clockid=<optimized out>, abstime=<optimized out>, shared=15, shared@entry=0)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_umtx.c:223
#2  0x0000096a3a6fc5a9 in _thr_sleep (curthread=curthread@entry=0xc0542eac100, clockid=0, abstime=abstime@entry=0x0) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_kern.c:196
#3  0x0000096a3a6f7b57 in cond_wait_user (cvp=0xc0565cbb060, mp=0xc0543400508, abstime=0x0, cancel=1) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:318
#4  cond_wait_common (cond=cond@entry=0xc05442523a8, mutex=mutex@entry=0xc0544252390, abstime=abstime@entry=0x0, cancel=cancel@entry=1)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:378
#5  0x0000096a3a6f7dd1 in __thr_cond_wait (cond=0xc0543422218, cond@entry=0xc05442523a8, mutex=0xf, mutex@entry=0xc0544252390)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:393
#6  0x0000096a371cec7f in tpool_wait (tpool=tpool@entry=0xc0544252380) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:529
#7  0x0000096a354b85d6 in zfs_foreach_mountpoint (hdl=0xc0542e3e000, handles=0xc0565c4c540, num_handles=1025, func=0x96a354b8d20 <zfs_mount_one>, data=<optimized out>, 
    data@entry=0x96a4e0c9df0, parallel=parallel@entry=B_TRUE) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libzfs/libzfs_mount.c:1267
#8  0x0000096a354b8b33 in zpool_enable_datasets (zhp=zhp@entry=0xc054425d7c0, mntopts=mntopts@entry=0x0, flags=flags@entry=0)
    at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libzfs/libzfs_mount.c:1301
#9  0x0000096211ec6e6f in do_import (config=<optimized out>, newname=newname@entry=0x0, mntopts=0x0, props=0x0, flags=0)
    at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/cmd/zpool/zpool_main.c:3445
#10 0x0000096211ec631f in do_import_task (arg=0xc0542e1a120) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/cmd/zpool/zpool_main.c:3471
#11 0x0000096a371cf0b3 in tpool_worker (arg=0xc0542e1a120) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:199
#12 0x0000096a3a6f8cb5 in thread_start (curthread=0xc0542eac100) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_create.c:289
#13 0x0000000000000000 in ?? ()
```
</details>
<details open>
    <summary>Thread 5</summary>

```
#0  _umtx_op_err () at /usr/home/somers/src/freebsd.org/src/lib/libsys/amd64/_umtx_op_err.S:38
#1  0x0000096a3a705f22 in _thr_umtx_timedwait_uint (mtx=0xc05434220c8, id=id@entry=0, clockid=<optimized out>, abstime=<optimized out>, shared=15, shared@entry=0)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_umtx.c:223
#2  0x0000096a3a6fc5a9 in _thr_sleep (curthread=curthread@entry=0xc0542e15f00, clockid=0, abstime=abstime@entry=0x0) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_kern.c:196
#3  0x0000096a3a6f7b57 in cond_wait_user (cvp=0xc0542e536a0, mp=0xc0543400108, abstime=0x0, cancel=1) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:318
#4  cond_wait_common (cond=cond@entry=0xc0542e87170, mutex=mutex@entry=0xc0542e87160, abstime=abstime@entry=0x0, cancel=cancel@entry=1)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:378
#5  0x0000096a3a6f7dd1 in __thr_cond_wait (cond=0xc05434220c8, cond@entry=0xc0542e87170, mutex=0xf, mutex@entry=0xc0542e87160)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:393
#6  0x0000096a371cef6b in tpool_worker (arg=0xc0542e1a150) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:150
#7  0x0000096a3a6f8cb5 in thread_start (curthread=0xc0542e15f00) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_create.c:289
#8  0x0000000000000000 in ?? ()
```
</details>
<details open>
    <summary>Thread 6</summary>

```
#0  _umtx_op_err () at /usr/home/somers/src/freebsd.org/src/lib/libsys/amd64/_umtx_op_err.S:38
#1  0x0000096a3a705f22 in _thr_umtx_timedwait_uint (mtx=0xc05434220f8, id=id@entry=0, clockid=<optimized out>, abstime=<optimized out>, shared=15, shared@entry=0)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_umtx.c:223
#2  0x0000096a3a6fc5a9 in _thr_sleep (curthread=curthread@entry=0xc0542e16d00, clockid=0, abstime=abstime@entry=0x0) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_kern.c:196
#3  0x0000096a3a6f7b57 in cond_wait_user (cvp=0xc0542e536a0, mp=0xc0543400108, abstime=0x0, cancel=1) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:318
#4  cond_wait_common (cond=cond@entry=0xc0542e87170, mutex=mutex@entry=0xc0542e87160, abstime=abstime@entry=0x0, cancel=cancel@entry=1)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:378
#5  0x0000096a3a6f7dd1 in __thr_cond_wait (cond=0xc05434220f8, cond@entry=0xc0542e87170, mutex=0xf, mutex@entry=0xc0542e87160)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:393
#6  0x0000096a371cef6b in tpool_worker (arg=0xc0542e1a270) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:150
#7  0x0000096a3a6f8cb5 in thread_start (curthread=0xc0542e16d00) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_create.c:289
#8  0x0000000000000000 in ?? ()
```
</details>
<details open>
    <summary>Thread 7</summary>

```
#0  _umtx_op_err () at /usr/home/somers/src/freebsd.org/src/lib/libsys/amd64/_umtx_op_err.S:38
#1  0x0000096a3a705f22 in _thr_umtx_timedwait_uint (mtx=0xc0543422278, id=id@entry=0, clockid=<optimized out>, abstime=<optimized out>, shared=15, shared@entry=0)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_umtx.c:223
#2  0x0000096a3a6fc5a9 in _thr_sleep (curthread=curthread@entry=0xc0542eadd00, clockid=0, abstime=abstime@entry=0x0) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_kern.c:196
#3  0x0000096a3a6f7b57 in cond_wait_user (cvp=0xc0542e536a0, mp=0xc0543400108, abstime=0x0, cancel=1) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:318
#4  cond_wait_common (cond=cond@entry=0xc0542e87170, mutex=mutex@entry=0xc0542e87160, abstime=abstime@entry=0x0, cancel=cancel@entry=1)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:378
#5  0x0000096a3a6f7dd1 in __thr_cond_wait (cond=0xc0543422278, cond@entry=0xc0542e87170, mutex=0xf, mutex@entry=0xc0542e87160)
    at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_cond.c:393
#6  0x0000096a371cef6b in tpool_worker (arg=0xc0542e1a2a0) at /usr/home/somers/src/freebsd.org/src/sys/contrib/openzfs/lib/libtpool/thread_pool.c:150
#7  0x0000096a3a6f8cb5 in thread_start (curthread=0xc0542eadd00) at /usr/home/somers/src/freebsd.org/src/lib/libthr/thread/thr_create.c:289
#8  0x0000000000000000 in ?? ()
```
</details>

### PR DESCRIPTION
**Pull request by asomers**
### Motivation and Context
The parallel pool import feature (#16093) can greatly increase the number of threads used by /sbin/zpool .  If it reaches the OS-imposed per-process limit and then tries to import an additional pool, the command will hang.  This PR fixes such hangs.

### Description
The PR consists of four distinct commits:
* Ensure that `tpool_dispatch` returns an error if it cannot start at least 1 worker.  Previously it would silently fail.
* If `tpool_dispatch` fails while mounting file systems, make libzfs fall back to serial execution.  This fixes the bug, though with inconsistent performance.
* Allow /sbin/zpool to control the threadpool size used by libzfs when mounting file systems.  This improves the performance of the solution in the previous commit.  However, it changes the libzfs ABI.
* Add an ATF test for `tpool_dispatch` to ensure correct behavior if it cannot start even one worker.  Due to lack of test infrastructure within the OpenZFS repository, this commit is not actually included in this PR.  Instead, I plan to commit it directly to FreeBSD.

### How Has This Been Tested?
In addition to the aforementioned libtpool test, I have tested this change by importing 6 pools in parallel, each with 1501 file systems.  Before my changes, that would fail on 7 out of 8 attempts.  Now it always succeeds, with consistent performance.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

Fixes #16172

### CODE REVIEW

**Review by behlendorf — APPROVED** [review]
> However, it changes the libzfs ABI.

Thanks for calling this out.  The original parallel import code has ended up in tagged release yet so this isn't a major problem.

> Add an ATF test for tpool_dispatch to ensure correct behavior if it cannot start even one worker. Due to lack of test infrastructure within the OpenZFS repository, this commit is not actually included in this PR. Instead, I plan to commit it directly to FreeBSD.

Good.

@grwilson can you review this.

**Comment by asomers** [comment]
@behlendorf if it's ok to change the libzfs abi, could you please tell me how to update the libzfs.abi file?  It looks like it's automatically generated somehow.

**Comment by behlendorf** [comment]
@asomers you can download an updated abi file from the artifacts for this PR (at the bottom).  You'll just need to replace the current abi file in this PR with the new once after inspecting the differences, then force update the PR.

https://github.com/openzfs/zfs/actions/runs/9007873783?pr=16178

**Comment by asomers** [comment]
> @asomers you can download an updated abi file from the artifacts for this PR (at the bottom). You'll just need to replace the current abi file in this PR with the new once after inspecting the differences, then force update the PR.

Ahh, that's easy.  Done!

**Review by grwilson — APPROVED** [review]

**Comment by asomers** [comment]
Now that this PR has been merged downstream into FreeBSD, here is a review for the libtpool ATF test.  https://reviews.freebsd.org/D45587

**Pull request closed without merging**
