### PR TITLE
[2.1.10] contrib: dracut: fix race with root=zfs:dset when necessities required

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Trivial backport of #14690

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
rebased

**Comment by nabijaczleweli** [comment]
I see a `zfs-2.1.10` tag. Did you miss this somehow again.

**Review by tonyhutter — APPROVED** [review]

**Comment by tonyhutter** [comment]
@nabijaczleweli sorry it fell through the cracks.  We'll try to include it in zfs-2.1.11, which we're putting together right now.

**Comment by tonyhutter** [comment]
@nabijaczleweli  I cherry-picked your commit into the proposed zfs-2.1.11 patchstack: https://github.com/openzfs/zfs/pull/14766

**Comment by nabijaczleweli** [comment]
May be best to add a `Closes: #14691` to the PR description there then.

**Comment by behlendorf** [comment]
Closing, this was included in 2.1.11.

**Pull request closed without merging**
