### PR TITLE
Fix ACL checks for NFS kernel server

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

For Linux NFS kernel server ops, fsuid and fsgid in
cred are populated with ids that operation is
being performed as, but euid and egid remain 0.

In Linux when setresuid(2) and setresgid(2) are
called, the fsuid and fsgid are set to the euid
and egid respectively.

The use of fsuid / fsgid is prescribed in Linux kernel documentation under the section "Open File Credentials" in `Documentation/security/credentials.rst`.

### Description

This PR changes ZFS ACL checks to evaluate
fsuid / fsgid rather than euid / egid to avoid
accidentally granting elevated permissions to
NFS clients.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
Fixes #13217

**Review by sdimitro — APPROVED** [review]
This definitely fixes https://github.com/openzfs/zfs/issues/13217 for me. Have you given any thought to Brian's feedback here: https://github.com/openzfs/zfs/issues/13217#issuecomment-1068581024

**Comment by freqlabs** [comment]
I'm testing out changing most uses of crgetuid/crgetgid to crgetfsuid/crgetfsgid, except for the ioctls/delegation. There are also a ton of unused/unimplemented SPL cred functions (especially on the FreeBSD side) I'm cleaning out while here.

**Comment by freqlabs** [comment]
Yeah I'll go with Brian's suggestion instead. The fsuid/fsgid will work for the ioctls/delegation, and it's cleaner to keep crgetuid/crgetgid and expunge crgetfsuid/crgetfsgid. Having both is more confusing than it needs to be.

**Comment by freqlabs** [comment]
* Also removed FreeBSD's kidmap.h and unused sid functions from SPL

**Review by behlendorf — APPROVED** [review]

**Comment by freqlabs** [comment]
* Failed to save an edit whoops

**Pull request merged**
