### PR TITLE
zfs-2.1.2 proposed patch set

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patch set for zfs-2.1.2.  It's currently the same as the `zfs-2.1.2-staging` branch.

### Description
This is a smaller release to build on Fedora 35 and the latest FreeBSD.

### How Has This Been Tested?
Buildbot will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gyakovlev** [comment]
if fix for https://github.com/openzfs/zfs/issues/11900 land please include it, it's pretty nasty one

**Comment by tonyhutter** [comment]
@gyakovlev yep, the fix for that is https://github.com/openzfs/zfs/pull/12724 and it looks like will be merged soon.

I also plan to pull in https://github.com/openzfs/zfs/pull/12725 once it's merged too.

**Comment by satmandu** [comment]
Maybe https://github.com/openzfs/zfs/pull/12759 would be worth having as well?

**Comment by Bronek** [comment]
Yes pls include #12759 , I am affected by this.

**Comment by satmandu** [comment]
Looks like https://github.com/openzfs/zfs/pull/12800 is necessary but not sufficient to get building on 5.16 working. (Though I'm still seeing [[5.16] blkcg_gq not found](https://github.com/openzfs/zfs/issues/12755) as a remaining build issue for 5.16.)

Since we're in the 5.16 cycle now, it would be nice to get building on the 5.16-rc kernels working with a new point release.

**Comment by freqlabs** [comment]
It would be nice to get 7443299fe0b8caaadbfc18f778732bb26c899e41 in as well.

**Comment by tonyhutter** [comment]
Sorry for the radio silence - I'm back from vacation and will get back to working on this.

**Comment by tonyhutter** [comment]
I think we're just waiting on some 5.16 kernel fixes: https://github.com/openzfs/zfs/pull/12819

**Pull request merged**
