### PR TITLE
linux: overlayfs support

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

Existing PRs for overlayfs support have made great progress over several years. I've incorporated the outstanding feedback and rebased.

### Description

https://github.com/openzfs/zfs/pull/9600 and https://github.com/openzfs/zfs/pull/12209 with the outstanding feedback incorporated:

* Feature flags removed
This means in cases where a pool is not cleanly exported you may end up
with loss of unflushed TX_RENAME_EXCHANGE and TX_RENAME_WHITEOUT
transactions and all transactions that follow them in the ZIL for that
dataset if the pool is then imported by a release build of ZFS that
does not recognize the new TX types. A warning message is logged to
dmesg and the pool is fully usable, just missing the last changes.
Debug builds will panic when they fail to replay the full log, failing this assert:
```
        ASSERT(!claimed || !(zh->zh_flags & ZIL_CLAIM_LR_SEQ_VALID) ||
            (max_blk_seq == claim_blk_seq && max_lr_seq == claim_lr_seq) ||
            (decrypt && error == EIO));
```
Not great, but better than not being able to import the pool at all.
* AUTHORS sorted
* Error handlers in zvol replay vector for new TX types
* GC z_is_stale
* Squashed wip/fixup commits

### How Has This Been Tested?
https://github.com/amir73il/unionmount-testsuite
https://github.com/openzfs/zfs/pull/9600#issuecomment-1224253694
https://github.com/openzfs/zfs/pull/12209#issuecomment-1284407478

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
I can probably pare down the changes to the abi files.

**Review by amotin — APPROVED** [review]
Looks good to me.  I just think we could be nicer to people running with debug and relax the assertion a bit either in separate commit or even PR to then merge it into all still active stable branches.

**Review by Ornias1993 — APPROVED** [review]
The PR thoroughly cleans up the work done and applies all given feedback accordingly.

With OverlayFS for docker being added into TrueNAS SCALE Nightly, this should gather feedback rather quickly as well. 

With a trusted OpenZFS partner company heavily relying on this feature and the above, I see no issues with merging this.

Some additional notes though:
- We might in the future actually want to test the use of overlayFS itself as well

**Comment by freqlabs** [comment]
* Dropped changes to ABI files

**Comment by wizpresso-steve-cy-fan** [comment]
Thank you for the work, this will definitely help people who runs Docker on top of ZFS, since ZFS dataset creation cost (which is what the ZFCS Docker backend currently does for each OCI image layer) is very high, and it will clobber `zfs list` output to an annoying point where Proxmox usually froze because of that. This would also mean k3s will finally be working with ZFS out of the box which is a yearlong problem

**Review by behlendorf — APPROVED** [review]
While it's not great to lack replay support for these log entries on FreeBSD, I think it is something we can live with.  Although I'd love to see it implemented in the future.

@freqlabs as a follow up to this PR let's also make sure to open a PR to relax the debug assertion and convert it to log an error.  We can then easily backport to the 2.1 series so this is handled a bit better.

@cyphar @snajpa thank you both for all your work on this!  It'll be great to finally support this functionality.

**Comment by ryao** [comment]
Please rebase this on master and repush so we can get results from the new CodeQL static analyzer before this is merged. It is a big enough PR that I would prefer to see the results from the static analyzer before it is merged, since the way things are setup by GitHub, most of us cannot see the results from it after it is merged without pushing it into branches in our own GitHub development repositories with the appropriate workflow file.

**Comment by cyphar** [comment]
As discussed in #12209, I didn't know whether dropping the log would be acceptable (whether or not there is a data persistence expectation by users that is being violated by dropping parts of the log somewhat silently). But if this truly is acceptable, this is far more preferable to having feature flags that have complicated semantics (and requiring you to enable feature flags to get fairly minor filesystem features). It also seems the issues which caused the previous version of #9600 to be reverted have disappeared on newer kernels?

**Comment by behlendorf** [comment]
@cyphar I share your concerns.  While it's definitely not ideal, realistically I think it's acceptable given the complexity of the feature flag semantics and the rare circumstances where it might ever be a problem.  As for the https://github.com/openzfs/zfs/pull/9600 changes the remaining work there was largely some cleanup and manual testing which was done.  I wouldn't be against adding some new test cases to verify it works on a wider range of kernels but I don't think it needs to hold this merge.

**Comment by Codelica** [comment]
Sorry for the self-service post here, but will this hit in the next 2.1.x release or ?

And THANKS...  this is huge IMO 👍

**Comment by Ornias1993** [comment]
> Sorry for the self-service post here, but will this hit in the next 2.1.x release or ?
> 
> And THANKS... this is huge IMO 👍

If you want it added you can ask and check here:
https://github.com/openzfs/zfs/pull/14162

**Comment by behlendorf** [comment]
Thanks, it's great to see this work merged.  Overlayfs support will not be included in the 2.1.x releases, but in the next major release.

**Comment by gmelikov** [comment]
Looks like it was closed by mistake in https://github.com/openzfs/zfs/commit/86db35c447aa3f4cc848497d78d54ec9c985d1ed ?

**Comment by freqlabs** [comment]
Not by mistake, that commit is in this PR.

**Pull request closed without merging**
