### PR TITLE
zfs-2.0.6 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Misc fixes plus support for the 5.14 kernel.

### Description
This is a proposed patchset for zfs-2.0.6.  It's basically the `zfs-2.0.6-staging` branch plus a few other patches to build on the 5.14 kernel.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
@tonyhutter Can we also get 86b5f4c121885001a472b2c5acf9cb25c81685c9 please?

**Comment by tonyhutter** [comment]
@freqlabs I've included it in my latest push

**Comment by amotin** [comment]
@tonyhutter could you also include few more FreeBSD fixes:
46197dc85892fc15a21b409dc78054a28ac85d6e
eecceeae9feee7f7398c423e81b276a394c8ffae
f8646c871a422046fba7eb24c0cdfc53b5ffc546 ?

**Comment by tonyhutter** [comment]
@amotin included in my latest push.

**Comment by tonyhutter** [comment]
Released:
https://github.com/openzfs/zfs/releases/tag/zfs-2.0.6

**Comment by Evernow** [comment]
> 
> 
> Released:
> https://github.com/openzfs/zfs/releases/tag/zfs-2.0.6

Is this the last planned 2.0 release?

**Pull request closed without merging**
