### PR TITLE
Add workaround for broken Linux pipes

### PR DESCRIPTION
**Pull request by rincebrain**
### Motivation and Context
I couldn't stop hitting #13232 on my Pi 4 when I wanted to benchmark some things.

### Description
Adds an env variable, ZFS_NO_PIPE_MAX, which disables the problematic F_SETPIPE_SZ.

This should be documented somewhere, but I wasn't sure where - `zfs(8)`? `zfs-recv(8)`? `zpool(8)`?

### How Has This Been Tested?
WIthout this change, running dd [send stream] | zfs recv on my Pi 4 hangs at least once every 5 times, often more frequently; with this change and no env variable set, same thing; with it set, it hasn't hung in 1024 runs.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by behlendorf — COMMENTED** [review]
That's quite unfortunate.  Given how easily you've been able to hit this I wonder if we shouldn't instead invert the logic here and disable this optimization by default.  Do you have a feel for how much increasing the pipe size really helps performance?

**Comment by rincebrain** [comment]
It seemed to need a slow system to be reasonably often hittable.

I can benchmark it with and without later.

**Comment by behlendorf** [comment]
About the documentation, adding it to `zfs.8` seem reasonable.  We already document the `ZFS_MOUNT_HELPER` environment variable here.

**Comment by szubersk** [comment]
Nice catch, Rich!

I don't see https://bugzilla.kernel.org/show_bug.cgi?id=212295 integrated into the current Linux master branch. This issue is destined to come back over and over again on slower/embedded systems. @behlendorf suggestion to invert the logic (`ZFS_PIPE_MAX`) is solid, especially that the bug exists in Linux longterm 5.10 and 5.15 lines.

**Comment by rincebrain** [comment]
It's not integrated anywhere, no - they emailed it to LKML once and it got no response.

**Comment by rincebrain** [comment]
There, I've revised it to default to not setting the pipe size unless you specify the variable and documented it in `zfs(8)`.

This update inspired by managing to start repeatedly hitting this on my 5900X.

**Review by behlendorf — APPROVED** [review]
Looks good to me after sorting out the mandoc warnings.

**Comment by rincebrain** [comment]
If this push fails, I'm ignoring this PR until the broken useless linter is fixed to run outside of the CI.

**Pull request merged**
