### PR TITLE
Fix concurrent sequential and healing resilver

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Issue #14881.

### Description

This commit fixes an unlikely scenario where it was possible for a sequential and healing resilver to be initiated concurrently.

Furthermore, while investigating it became clear that it was possible for `zpool clear` to start a healing resilver when it wasn't needed at all.  This occurs because during a `vdev_open()` the device is presumed to be healthy as long as it can be opened and passes some basic sanity checks.  It's not until the device is validated that a bad label is detected and it's set unavailable. However, by this point an async resilver will have already been requested if the DTL isn't empty.

Now this will result in an unnecessary resilver, which by itself won't cause any serious problems.  However, if the ZED is running, and the faulted vdev is part of a dRAID pool, and its label has been overwritten, and there are distributed spares available. Then running `zpool clear` will generate a bad_label zevent which will cause the ZED to kick in a hot spare using a sequential resilver at the exact moment that vdev_open() mistakenly initiated an unneeded healing resilver for the now unavailable vdev.

Fix this by updating `spa_vdev_attach()` to check not only for active healing resilvers but for any which have been scheduled. In addition, prevent the unneeded healing resilver by rechecking that it's really needed before initiating it in `spa_async_thread()`.

### How Has This Been Tested?

Manually tested using the test case provided in #14881.  A version of that test should included in the ZTS but that will take a little more work.  I've opened this PR to get a full CI run with this change.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ghoshdipak** [comment]
We have tried fixing the above scenario(Issue [#14881](https://github.com/openzfs/zfs/issues/14881)) using the below patch (https://github.com/akashb-22/zfs/tree/concurrent-resilver), This fix is almost similar to your fix but prioritizes rebuild rather than healing resilver for draid vdevs, as replacement is done to a distributed spare. This is done by updating 'spa_vdev_attach()' to cancel any scheduled resilver as well as the in-progress healing resilver whenever a rebuild is requested by ZED. However, in this scenario we mostly clear any scheduled resilver as that is the case here but we've added additional check as a precaution to cancel any in-progress healing resilver whenever a rebuild is kicked in.
Additionally, we have added a testcase based on the above scenario to ZTS which reliably fails before this patch.

**Comment by behlendorf** [comment]
@ghoshdipak there are two separate issues at play here we want to handle.

1) There's a window where a sequential rebuild can be started even if a healing resilver has been scheduled.
2) `vdev_reopen()` can incorrectly diagnosis that a healing resilver should be started because `dsl_scan_assess_vdev()` is called before `vdev_validate()` has a chance to fault any existing, but damaged, leaf vdevs.

In my testing fixing 2) was sufficient to avoid 1).  However, my version of the patch still does leave a small window where if the ZED tried to kick in the hot spare while it was the async task was scheduled it would fail.  That's not great.  Conversely, I'm leery of allowing `zpool replace` to convert a healing resilver to the rebuild.  We should try and keep this interlock simple.  Whichever is requested first is allowed to run.

As I see it, issue 2) above is really the core problem.  Why don't we instead fix `vdev_reopen()` so it either never makes the incorrect `SPA_ASYNC_RESILVER` request, or we cancel it immediately at the end of `vdev_reopen()` to close that race.  This way we can avoid adding any special handling to `spa_vdev_attach()` beyond failing with `ZFS_ERR_RESILVER_IN_PROGRESS` when a resilver was scheduled.

**Comment by behlendorf** [comment]
@akashb-22 thanks for verifying that fixes the issue and effectively closes the race.  If you can open a new PR with that change, the change to `spa_vdev_attach()` from this PR, and your new case I'll go ahead and close out this PR in favor of the new one.

**Comment by behlendorf** [comment]
Closing as duplicate of https://github.com/openzfs/zfs/pull/14892

**Pull request closed without merging**
