### PR TITLE
Combined asm for some x86_64 ports

### PR DESCRIPTION
**Pull request by andrewc12**
Create a single module/lua/setjmp/setjmp_x86_64.S
from the following repositories
openzfs/zfs/master
openzfsonosx/openzfs-fork/macOS
for testing, discussion and possible inclusion upstream

https://github.com/openzfs/zfs/pull/14169
https://github.com/openzfsonwindows/openzfs/pull/176
https://github.com/openzfsonosx/openzfs/pull/115

Signed-off-by: Andrew Innes <andrew.c12@gmail.com>

### CODE REVIEW

**Comment by andrewc12** [comment]
@solbjorn @behlendorf do you seen any problems with how I've refactored this?

**Comment by solbjorn** [comment]
Looks okay to me. One thing I'd add comments like `/* __APPLE__ */` near elses and endifs, otherwise it's sometimes hard to track where is what.

**Review by behlendorf — APPROVED** [review]
Looks pretty reasonable.

**Comment by behlendorf** [comment]
@andrewc12 if you're happy with the current version would you mind rebasing it against the latest master source and marking it ready for review.

**Comment by andrewc12** [comment]
@behlendorf I would gladly, but atm @lundman is currently trying to merge the seperate asm used by windows which also touches this file.

I would love to knock out all of them at once which was the original intent of this PR, so no matter how it goes I'll be waiting untill after he's finished his work. 🙂

**Comment by andrewc12** [comment]
I might revisit this again in the future after https://github.com/openzfs/zfs/pull/14228 is merged

**Comment by lundman** [comment]
Might not be clear, but #14228 takes care of all the changes in here and expands it to make all assembler files sharable with windows and macOS. Moving the header file was the hardest part tho.

**Comment by andrewc12** [comment]
Ahh sweet. @behlendorf can you take a look at that one instead?

**Pull request closed without merging**
