### PR TITLE
Bump Linux-Maximum to 5.8

### PR DESCRIPTION
**Pull request by ndanyluk**
Bump max kernel version to 5.8 to match the supported releases indicated in the release notes

### Motivation and Context

Release 0.8.5 included fixes/commits targeting 5.8/5.9 compatibility. The release notes indicate support for kernels up to 5.8 but the META file still indicates 5.6.

This was first raised in one of the comments in [the proposed 0.8.5 patch set](https://github.com/openzfs/zfs/pull/10933) 

### Description

I modified the META file to allow packages to be built for 5.7-5.8 kernels.

### How Has This Been Tested?

I have only tested by building DKMS .deb packages on Ubuntu 20.04 (arm64, kernel 5.7 & 5.8 installed)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Ornias1993** [comment]
LGTM
That being said, are you sure this is still tested-to-be-working on  2.6.32?

**Review by Ornias1993 — APPROVED** [review]

**Comment by ndanyluk** [comment]
@Ornias1993 to be honest, I'm not sure.  I only tested the 5.7/5.8 kernels on my system.  Do the buildbots cover 2.6.32?

Happy to merge, but this is my first OpenZFS PR, so I'd like to not break anything :joy:

**Review by gmelikov — APPROVED** [review]

**Comment by Ornias1993** [comment]
> @Ornias1993 to be honest, I'm not sure. I only tested the 5.7/5.8 kernels on my system. Do the buildbots cover 2.6.32?

They don't, thats why I'm a bit hessitant to call 2.6.32 supported, personally.

> This is my first OpenZFS PR, so I'd like to not break anything 😂

Don't worry about it, your PR is perfectly fine :)

**Comment by tonyhutter** [comment]
@ndanyluk thanks for this fix - I overlooked updating it for the 0.8.5 release.  Can you please make your PR against the `zfs-0.8.6-staging` branch instead of `zfs-0.8-release` though?  You should just be able to change the base branch in the drop down menu in github at the top of this PR.

@Ornias1993 we actually do support the 2.6.32 kernel for the 0.8.x release (since we support Centos 6), but we don't support it for `master`.  Centos 6 does go end of life in November though so I expect we'll drop ZFS support for it then.

**Comment by Ornias1993** [comment]
> @Ornias1993 we actually do support the 2.6.32 kernel for the 0.8.x release (since we support Centos 6), but we don't support it for `master`. Centos 6 does go end of life in November though so I expect we'll drop ZFS support for it then.

I understand it's officially supported, but did someone actually test the release on 2.6.32 before release?

**Comment by ndanyluk** [comment]
> 
> 
> @ndanyluk thanks for this fix - I overlooked updating it for the 0.8.5 release. Can you please make your PR against the `zfs-0.8.6-staging` branch instead of `zfs-0.8-release` though? You should just be able to change the base branch in the drop down menu in github at the top of this PR.

No problem, happy to help! I just changed the base branch to 0.8.6 I think.

**Comment by Ornias1993** [comment]
> I just changed the base branch to 0.8.6 I think.

Worked out pretty fine, don't worry about those test failures. Not your fault :)

**Review by tonyhutter — APPROVED** [review]

**Comment by gdevenyi** [comment]
Perhaps this is a place where a rare 0.8.5.1 would be appropriate to get out quickly with this single fix?

**Comment by behlendorf** [comment]
@gdevenyi the value in the META file is only informational.  So while it may be a little misleading it won't cause any build issues.  The 0.8.5 tag as is will build and work with the now released 5.9 kernel.  I've gone ahead and updated the [release notes](https://github.com/openzfs/zfs/releases/tag/zfs-0.8.5) to make it clear it's compatible.

**Comment by ndanyluk** [comment]
> 
> 
> @gdevenyi the value in the META file is only informational. So while it may be a little misleading it won't cause any build issues. The 0.8.5 tag as is will build and work with the now released 5.9 kernel. I've gone ahead and updated the [release notes](https://github.com/openzfs/zfs/releases/tag/zfs-0.8.5) to make it clear it's compatible.

Is the value only informational? When I built DKMS packages on Ubuntu 20.04 I had to update META to include kernel 5.8 or my packages wouldn't build (at least if memory serves).

**Comment by Ornias1993** [comment]
Afaik some package creators do indeed use it.
It is't technically required for ZFS though...

**Comment by behlendorf** [comment]
@ndanyluk that's right.  If for some reason you needed to update META to get it to build I'd be interested to know why it failed.  It's possible some of the downstream distribution packaging may make use of this.  But if they're carrying patches for that, it seems reasonable they could manually bump the version in the META file for now as well.

**Pull request merged**
