### PR TITLE
zfs-2.1.8 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Support 6.1+ kernels

### Description
Proposed patches for zfs-2.1.8

### How Has This Been Tested?
Buildbot will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ryao** [comment]
Here are some candidates for backporting:

- f63c9dc70a40f930b09b586e6bc53cabf90fa3a1
- d30577c9dd811688f2609ad532b011b99bceb485
- b72efb751147ab57afd1588a15910f547cb22600
- f25f1f90914098d3fba3082f0152c7cec824b49d
- f6f215f07f05224baff601729be7d00a64440d0d
- fb000f786721204283af88ba0b76bf482704d470
- 018f26041d67447de28c293c35e1f664ce3c1abb
- 29e1b089c14bf0f09d16801652cd82376fa3feb2
- bd9dc5a1dcc1d2ec88477af3f6f0bc8c9bdef286
- fb11b1570a473dfe864fcac71b5220a28503fa5d
- 24502bd3a79d71b726f723ced55b0e7ccb5db840
- f3f5263f8a9b0f8b51051698f68fbd76e181a685
- 9be34ec99ec7bb518ad508851b0e60c86bfbbd24
- dc95911d21a19930848302aac9283fff68e4a41b
- 70ac2654f579e138d04ed747967fb0d603b0cacb
- d31a7cb4fa59c7a2ff39cd091643c18617b601c1
- f900279e6dafeeef3398ea5c65fd174a2746a013
- 5401472cd0599dda4fdf71f9ba318785cbca2025
- 242a5b748cbf02001a1324f3e195df56f8f28f5a
- 2709ace096b8448f07537f978863ad061cc3c7da
- ba87ed14103dd4b5e2cd40c347c4a653950ced16
- 7b9a423076f4da36b68009ced22259cd243166f6

This is not a comprehensive list. I will need to do a more thorough pass later.

**Comment by ryao** [comment]
It is technically still in a PR, but #14304 is needed to fix a regression introduced in 2.1.7. I am mentioning that here to encourage others to speed up the review process so that we can get it into 2.1.8.

**Comment by ryao** [comment]
Here is one more patch that really should be included in 2.1.8:

1f3bc5ea8074dc98edbee6eb90a308b283117954

**Comment by behlendorf** [comment]
And 07f2793e869196fcbcd5057d9ada377674262fe3 which was pointed out in #14375.

**Comment by tonyhutter** [comment]
Thanks all, I'm working to incorporate these changes.

**Comment by tonyhutter** [comment]
@ryao and others - everything requested is in with the following exceptions:

018f260 deadlock between spa_errlog_lock and dp_config_rwlock
I think this is not applicable since it fixes an issue that is not in zfs-2.1.x

dc95911 zfs list: Allow more fields in ZFS_ITER_SIMPLE mode
Too many merge conflicts

d31a7cb Address theoretical uninitialized variable usage in zstream
No zstream_decompress.c/zstream_recompress.c in zfs-2.1.18 so not applicable?

5401472 Linux PPC: Fix build failures on kernels built without CONFIG_SPE
Doesn't apply cleanly, needs 48cf170

2709ace ztest: comparisons against errno should not assign to it
Not applicable

**Comment by sempervictus** [comment]
@tonyhutter when do things like corrective receive get into tags? Is it a matter of time in `master` or some sort of version-strategy for features vs fixes?

**Comment by sempervictus** [comment]
While working on my own additions to 2.1.8, i'm running into a bunch of pain related to ab8d9c1783c and similar (great) cleanup efforts in my  backporting efforts. Any chance that the language-level cleanups/improvements can start making it into the tags? The various `static` markings are handy, the type/signedness cleanup as well - they all help the compiler to better reason about what's being built and how to do it correctly. It would also make official backporting of functionality like the pending SLOG performance PR more or less "drop-in" as opposed to having to figure out whether macros and interfaces are correct fail-by-fail.

**Comment by ryao** [comment]
Gentoo needs d27c7ba62f32124df8c57b7a2e38cdf59c041521 backported.

**Comment by gyakovlev** [comment]
> Gentoo needs [d27c7ba](https://github.com/openzfs/zfs/commit/d27c7ba62f32124df8c57b7a2e38cdf59c041521) backported.

it's not super critical for gentoo, there's probably 2 systems in the world running this particular config (both mine lol)
but it should apply cleanly anyway, I'm running it on 2.1.7 right now.

but it will certainly benefit latest fedora/ppc64le, it also runs 128b ldbl toolchain and  probably has more users.


another candidate for inclusion is:
https://github.com/openzfs/zfs/commit/b10f73f78eb223dd799a87474c537a69113edee1
should apply cleanly.

**Comment by ryao** [comment]
> it's not super critical for gentoo, there's probably 2 systems in the world running this particular config (both mine lol)

I had been under the impression that the plan was to support it going forward for any users who wanted it.

**Comment by gyakovlev** [comment]
> > it's not super critical for gentoo, there's probably 2 systems in the world running this particular config (both mine lol)
> 
> I had been under the impression that the plan was to support it going forward for any users who wanted it.

It will be the default ABI going forward, it’s just still WIP at the moment and almost nobody runs it, except me, and Fedora ofc.

**Comment by tonyhutter** [comment]
@ryao @gyakovlev I just pulled in your commits (d27c7ba b10f73f).  Hopefully those are the last ones.

>  Any chance that the language-level cleanups/improvements can start making it into the tags?

Yea, I run into those a lot so I understand the pain...  There's some huge code cleanup patches in master that are not in zfs-2.1.x.  The short answer is that they probably won't be included, as it's major surgery to get them merged.  All I can say is that someday we'll fork master into a zfs-2.2 branch and have a clean slate for backporting again.

**Comment by sempervictus** [comment]
@tonyhutter: is there any formal plan or benchmark for when 2.2 will start to materialize?

**Comment by amotin** [comment]
@tonyhutter Could we include also trivial: 5f45e3f699091e257941c2a5c37d8a65d91cd3a9 f0a76fbec1e536291eb0ef973625e07a19db04d5 4df415aa864690163808147b82d9e5ce2be12f68 fd61b2eabaa172c3ef08f7dbfac6e228c7d49dc9 ?

**Comment by tonyhutter** [comment]
@amotin this PR just had a good set of of test runs and I like to start building and testing out packages.  Let's cap the current patchset as-is, and we'll try to get your commits included in zfs-2.1.9.

**Comment by eirnym** [comment]
Won't be worth a while to just cut off 2.1.x releases after that one and roll out 2.2 in a foreseeable future ?

**Pull request merged**
