### PR TITLE
FreeBSD: remove support for FreeBSD < 13.0-RELEASE

### PR DESCRIPTION
**Pull request by robn**
### Motivation and Context

I was doing some refactoring in some FreeBSD platform code, and had reason to look at when a particular kernel API was introduced. Then I noticed that 12.x didn't have the thing I was looking for, but also [as of 2023-12-31 12.x is EOL](https://www.freebsd.org/security/unsupported/) and you can't even easily construct a new 12.x system, so I couldn't even see if OpenZFS compiles on it. Given we don't really know if it works, and probably everyone has upgraded, and it shipped the old pre 2.0/ZoL ZFS, I figure there's approximately zero people in the world that run OpenZFS 2.2+ on FreeBSD 12.x, and we can drop support for it.

### Description

The first 13.0-RELEASE was `__FreeBSD_version` was `1300139`, so for every check for a version on or before this, remove the "previous" code.

This allows some macro cleanup as well, where macros existed just to map old things to new ones.

Then, bump README.

Note that while technically everything before 13.3-RELEASE is EOL (since 2024-06-30), support for that is limited to a single check (`vn_lock_pair()` args in `zfs_freebsd_copy_file_range()`) and removing it just feels petty, so I did not,

### How Has This Been Tested?

Compile checked on FreeBSD 13.2-RELEASE-p12, 13.3-RELEASE-p3, 14.1-RELEASE.

(more than ever before, I need to set up a ZTS rig for FreeBSD).

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by amotin — APPROVED** [review]
Thank you.  It is a big cleanup.  The chosen 13.0-RELEASE point choice is logical, since it is when 13-CURRENT turned into 13-STABLE with much symbolizes less volatile APIs/KPIs.

**Review by mcmilk — APPROVED** [review]
LGTM - it's needed I think :+1:

**Review by tonyhutter — APPROVED** [review]
I can confirm this builds on 13.3-STABLE, 14.1-STABLE, and 15.0-CURRENT.

**Comment by robn** [comment]
Thanks all!

**Pull request merged**
