### PR TITLE
zfs-2.2.5 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patchset for zfs-2.2.5

### Description
Support 6.9 kernel, and possibly the 6.10 kernel depending on testing.  Include various commits from zfs-2.2.5-staging branch.

### How Has This Been Tested?
Test built only.  Buildbot will test.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by amotin** [comment]
Lets include also 02c5aa9b092818785ed8db4e2246a828278138e3 to fix a reported memory leak on FreeBSD.
Also may be 800d59d5771806459a23f10f3c9ee8f2d178b9ed, since it is pretty small, but I don't insist.

**Comment by robn** [comment]
Here's what I'd hoped to get in to 2.2.5.

---

#### vdev fault fix

Not yet merged to master, but trivial and a fix to a real issue introduced in 2.2.4.

#16258 vdev_open: clear async fault flag after reopen

#### zdb fixes

Not yet merged to master, but I think trivial and fix real bugs.

#16355 zdb: fix BRT dump
#16334 zdb: dump `ZAP_FLAG_UINT64_KEY` ZAPs properly

#### adb_iter_page fixes

Has been uneventful in my own dogfooding.

#16108 abd_iter_page: rework to handle multipage scatterlists

#### Clang build fixes

Needed to build against Linux 6.7+ with Clang.

#16206 Use memset to zero stack allocations containing unions
#16201 linux: detect if kernel defines intptr_t

#### ZTS improvements

#16088 zts: allow running a single test by name only
#16096 zts: add a debug option to get full test output

#### Improved userspace assertions/backtraces

Just so much nicer for debugging, especially when supporting customers.

#16140 libspl: nice assertion output
#16167 Unbreak FreeBSD cross-build on MacOS
#16168 libspl_assert: always link -lpthread on FreeBSD
#16181 zdb/ztest: improve and harmonise crash output

#### Kernel version enforcement

Not yet merged, and I am not pushing it, but if it's a reasonable approach then now is as good a time as any.

#15986 config/kernel: enforce kernel max version, with escape hatch

---

All except #15986 picked to `zfs-2.2.5-staging` here: https://github.com/robn/zfs/commits/zfs-2.2.5-staging/.

I'd be happy to submit separate PRs for any/all, let me know what you'd like.

**Comment by SoongNoonien** [comment]
Hi, I'm really looking forward to 2.2.5 but I hopped for the fix in c98295eed2687cee704ef5f8f3218d3d44a6a1d8 to be included.

**Comment by tonyhutter** [comment]
@amotin @SoongNoonien I pulled in those commits.
@robn I pulled in everything except #15986 since that hasn't been merged yet.

**Comment by robn** [comment]
@tonyhutter you're a champ, thank you!

**Comment by robn** [comment]
@tonyhutter 401c51d has an `AUTHORS` update for this branch.

**Comment by satmandu** [comment]
Any chance of https://github.com/openzfs/zfs/pull/16264 getting merged and added to this?

Also would make sense to add this? https://github.com/openzfs/zfs/pull/16302

**Comment by mcmilk** [comment]
This one should also go in: https://github.com/openzfs/zfs/pull/16284
Because of this build error on FreeBSD 15: https://github.com/mcmilk/zfs/actions/runs/10013457994/job/27681101652

**Comment by jumbi77** [comment]
What about

https://github.com/openzfs/zfs/commit/34906f8bbee337ee5aa9b79c141517bff0a4e0ab

and the recent icp removal of old code by robn if its still in 2.x?

**Comment by robn** [comment]
@jumbi77 No on #16204, its a fix for #15888, which is not on 2.2.x.

I'm softly against taking #16209; it's supposed to be an effective no-op so there's nothing to be gained by taking it but a small risk that it has some unknown side-effect, which is no good for a stable series. But if someone really wanted it I wouldn't argue.

**Comment by jumbi77** [comment]
Got it, both fine by me. But just in case we integrate ZAP shrinking in 2.2.x (which I hope at some point), we should include the fix too :)

**Comment by tonyhutter** [comment]
@robn I pulled in the latest AUTHORS
@mcmilk I pulled in  #16284
@satmandu I pulled in https://github.com/openzfs/zfs/pull/16264 but not #16302.  #16302 appears to only save a a handful of cycles every second, so I don't know if it's worth the (minor) risk.

**Comment by EriksRemess** [comment]
Linux kernel 6.9 branch as of 6.9.12 (July 27th) is marked as EOL. Maybe target for this ZFS version should be set to 6.10?

**Comment by colmbuckley** [comment]
Just a quick note - anyone running Debian bookworm with backports enabled is probably having difficulty with a fresh install; the current linux package is based on 6.9 which isn't supported by 2.2.4; further the stable package is 6.1 which might be too much of a downgrade for many operators.

**Comment by tonyhutter** [comment]
@EriksRemess I'm currently testing this PR against Ubuntu 24 running a 6.10.2 kernel.  If that looks ok, then we can bump the supported kernel version for this release to 6.10.

**Comment by Harry-Chen** [comment]
I suggest pulling in #16376 (if merged).

**Comment by prometheanfire** [comment]
If https://github.com/openzfs/zfs/pull/16400 merges it might be worth adding to the stack.  (depending on how clean it'd be too)

**Comment by robn** [comment]
> If https://github.com/openzfs/zfs/pull/16400 merges it might be worth adding to the stack

-1 from me, 6.11 is not finalised and the zvol changes are slightly invasive; I'd be nervous about them being on a stable release so early in their life.

**Comment by satmandu** [comment]
Would it make sense to have https://github.com/openzfs/zfs/pull/16409 , https://github.com/openzfs/zfs/pull/16410 , https://github.com/openzfs/zfs/pull/16411  , and https://github.com/openzfs/zfs/pull/16413 as well here as they're minor and keep errors from happening in ZTS?

**Comment by tonyhutter** [comment]
Quick update - zfs-2.2.5 is currently passing on all the builders so I'm reluctant to add any more commits.  I also have been trying to test ZFS with the 6.10.x kernel on Ubuntu using the development kernel packages from: https://kernel.ubuntu.com/mainline/.  I noticed that their 6.10.2 kernel was really unstable, but their new 6.10.3 packages seem to be much better, so I'm running ZTS locally on a VM to see if 6.10 is supported.

**Comment by tonyhutter** [comment]
Unfortunately I'm seeing ZFS failures on Ubuntu 24.10 w/6.10.3 kernel:
```
Tests with results other than PASS that are unexpected:
    FAIL cli_root/zpool_create/zpool_create_features_007_pos (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_features_008_pos (expected PASS)
    FAIL cli_root/zpool_upgrade/zpool_upgrade_features_001_pos (expected PASS)
    FAIL cli_user/misc/arc_summary_001_pos (expected PASS)
    FAIL pyzfs/pyzfs_unittest (expected PASS)
```
My guess is that they're unrelated to the kernel but I don't want to hold up the release while I hunt them down.  

I'm going to start building the zfs-2.2.5 packages as-is.

**Comment by comrade-meowski** [comment]
It's only anecdotal evidence of course but if it's any help I'm always running several physical and virtual test instances with the very latest kernels+zfs combinations - no problems here with Ubuntu 24.04 (_not_ 24.10, I'm not tracking that) and kernel 6.10.3 with this zfs-2.2.5-staging branch. That's on my main daily driver laptop too so it's had 2-3 days of use with that combination with no obvious hiccups or regressions.

It would be really nice if someone could fix the pyzfs build failure on debian/ubuntu for this release though (#16155), we've been having to build on Ubuntu with --disable-pyzfs since 2.2.4.

**Comment by tonyhutter** [comment]
zfs-2.2.5 released: https://github.com/openzfs/zfs/releases/tag/zfs-2.2.5

**Comment by robn** [comment]
Congrats @tonyhutter, great work!

**Comment by prometheanfire** [comment]
Very nice, 6.10 not called out as supported due to issues in your testing?  I'm running on 6.10.3 (gentoo-kernel) without issue, but I haven't done things related to those tests.  I did have an issue with some backtraces before this patchset though (to be expected since it added support for 6.9 as well.

**Comment by tonyhutter** [comment]
@prometheanfire right, zfs-2.2.5 builds fine on 6.10 and I don't anticipate any issues.  I'd just like to get a clean test run on it to be sure it's 100% OK for 6.10.

**Pull request merged**
