### PR TITLE
get_key_material: skip validation when loading keys

### PR DESCRIPTION
**Pull request by hvdijk**
The restriction that an encryption key must be at least
MIN_PASSPHRASE_LEN characters long make sense when changing the
encryption key, but not when loading: as this restriction is not
enforced in the libraries, it is possible to bypass zfs change-key's
restrictions and end up with a key that becomes impossible to load with
zfs load-key, for example through pam_zfs_key.

Signed-off-by: Harald van Dijk <harald@gigawatt.nl>

I am not sure how to set up a test for this and would appreciate pointers for that.

### Motivation and Context

This partially addresses #12651, where we end up with a dataset for which we cannot load the key through `zfs load-key`.

### Description

When loading keys, this PR causes the call to `validate_key()`, which validates that the length of the key meets ZFS's requirements, to be skipped.

### How Has This Been Tested?

- Set up encryption
- Bypass `zfs change-key` to change the encryption key to something too short to pass validation (I used `pam_zfs_key` for that)
- Manage to successfully unload and re-load the key
- Attempt to use `zfs change-key` to change the key to something too short and see that that still gets rejected

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [X] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [X] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by AttilaFueloep** [comment]
> They're just other ways of loading keys

No, you can either use a passphrase to generate the wrapping key or you can pass in the wrapping key directly The wrapping key generated from a passphrase is always 32 bytes as should the raw keys be. Otherwise encryption wouldn't work.

**Comment by hvdijk** [comment]
> But as is this change disables the key validation when loading raw and hex keys too. The now removed error messages might be useful for spotting failures and it would be better to keep them. I think key validation should only be skiped for `keyformat=passphrase` (and maybe `keylocation=prompt`?).

Thanks for the explanation earlier on the `keyformat`. As for `keylocation`, I'm not really seeing why that should make a difference but this may again be something I'm not understanding that well.

> What would you think of dropping the check in `validate_key()` itself?

That makes sense, though if we don't need to base it on `keylocation` I think the resulting code is slightly simpler if we just pass along `do_verify`/`confirm_key` (like I now pushed). If we do need `keylocation`, then it should probably be what you suggested.

Code style wise, looking at how you're explicitly comparing to `B_FALSE`, I see that both testing `boolean_t` directly and comparisons to `B_FALSE` are used in the code base, is there a preferred form throughout the project (where ideally the ones that are not in that preferred form get updated) or is it just personal preference for each individual contributor?

**Comment by AttilaFueloep** [comment]
@hvdijk  I've gone ahead, wrote a test case, cherry-picked your commit on top of that and fixed the cstyle error. Please let me know if it's acceptable for you if I open a PR for that. If it's not, please suggest how to proceed. Thanks!

https://github.com/openzfs/zfs/compare/master...AttilaFueloep:zfs-pam-add-test?expand=1

**Comment by hvdijk** [comment]
> @hvdijk I've gone ahead, wrote a test case, cherry-picked your commit on top of that and fixed the cstyle error. Please let me know if it's acceptable for you if I open a PR for that. If it's not, please suggest how to proceed. Thanks!
> 
> https://github.com/openzfs/zfs/compare/master...AttilaFueloep:zfs-pam-add-test?expand=1

Thanks! I'm sorry it's taken me so long to get to this, I appreciate you picking this up. I'm happy for you to open a new PR and close this one in favour of yours.

**Comment by hvdijk** [comment]
Thanks, closing in favour of #12765.

**Pull request closed without merging**
