### PR TITLE
free_blocks(): Fix reports from 2016 PVS Studio FreeBSD report

### PR DESCRIPTION
**Pull request by ryao**
### Motivation and Context
In 2016, the authors of PVS Studio ran it on the FreeBSD kernel, which identified a number of bugs / cleanup opportunities in the FreeBSD ZFS kernel code. A few of them persist to the present day:

https://reviews.freebsd.org/D5245

Note that the scan was done against
freebsd/freebsd-src@46763fd4ca8a37f836c9bf2333f9d687509278f3.

In particular, we have the following in free_blocks():

\sys\cddl\contrib\opensolaris\uts\common\fs\zfs\dnode_sync.c (174): error V547: Expression '__left >= __right' is always true. Unsigned type value is always >= 0. \sys\cddl\contrib\opensolaris\uts\common\fs\zfs\dnode_sync.c (171): error V634: The priority of the '*' operation is higher than that of the '<<' operation. It's possible that parentheses should be used in the expression. \sys\cddl\contrib\opensolaris\uts\common\fs\zfs\dnode_sync.c (175): error V547: Expression '__left >= __right' is always true. Unsigned type value is always >= 0.

A couple of assertions accidentally typecast the arguments they check to unsigned in such a way that the result is always true. Also, parentheses are missing around `1<<epbs` in `(db->db_blkid * 1<<epbs)`. This works out to be okay due to multiplication not caring what order of operations we use, but it is better to fix it to be `(1ULL << epbs)`. Also, we add an assertion to verify that `epbs` is non-negative.

### Description
We switch the broken assertions from ASSERT3U to ASSERT3S to fix them. We also change `1<<epbs` to `(1ULL << epbs)` and add an assertion to ensure that `epbs` is non-negative.

### How Has This Been Tested?
The buildbot can test it.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by amotin — COMMENTED** [review]
Why not just (db->db_blkid << epbs) ?

Are i, off and num are guarantied to fit into int, considering start and end are uint64_t? Wouldn't int64_t be better?

**Comment by ryao** [comment]
> Why not just (db->db_blkid << epbs) ?

There is no particularly strong reason. I will change it to be `(db->db_blkid << epbs)`.

> Are i, off and num are guarantied to fit into int, considering start and end are uint64_t? Wouldn't int64_t be better?

Good point. I do not see any reason to think this is guaranteed to fit in a 32-bit value, with the sole exception of `epbs`, which is calculated this way in the caller `free_children()`:

>         unsigned int epbs, shift, i;
>         epbs = dn->dn_phys->dn_indblkshift - SPA_BLKPTRSHIFT;                                                         
>         ASSERT3U(epbs, <, 31);

The rest probably should be uint64_t. I will add some assertions to verify that we never see integer wrap-around from the use of unsigned arithmetic.

**Review by amotin — APPROVED** [review]
I am not sure from where ASSERT3U(epbs, <, 31) is coming from other than the caller uses unsigned int.  I am not sure why this function should assert it.

**Comment by ryao** [comment]
> I am not sure from where ASSERT3U(epbs, <, 31) is coming from other than the caller uses unsigned int. I am not sure why this function should assert it.

It is a shift, so it is supposed to be restricted to small values. If the subtraction underflows, the assertion will be tripped. This is a clever way of checking two things at once.

**Comment by amotin** [comment]
> > I am not sure from where ASSERT3U(epbs, <, 31) is coming from other than the caller uses unsigned int. I am not sure why this function should assert it.
> 
> It is a shift, so it is supposed to be restricted to small values. If the subtraction underflows, the assertion will be tripped. This is a clever way of checking two things at once. As for why we are asserting it here, it is just to make it obvious that an assertion was done.

I don't see in this function anything that would suggest that value 32 or even 63 is not valid.  I don't like arbitrary assertions.  They should improve code readability, not confuse.

**Comment by ryao** [comment]
> > > I am not sure from where ASSERT3U(epbs, <, 31) is coming from other than the caller uses unsigned int. I am not sure why this function should assert it.
> > 
> > 
> > It is a shift, so it is supposed to be restricted to small values. If the subtraction underflows, the assertion will be tripped. This is a clever way of checking two things at once. As for why we are asserting it here, it is just to make it obvious that an assertion was done.
> 
> I don't see in this function anything that would suggest that value 32 or even 63 is not valid. I don't like arbitrary assertions. They should improve code readability, not confuse.

Doing a bit shift by 32 on a 32-bit value would be undefined behavior according to the C standard. The same applies to a bit shift by 64 on a 64-bit value value.

That being said, the real constraint that matters here is that the subtraction not underflow, so I will just change it to `ASSERT3U(dn->dn_phys->dn_indblkshift, >=, SPA_BLKPTRSHIFT)`.

**Comment by amotin** [comment]
> Doing a bit shift by 32 on a 32-bit value would be undefined behavior according to the C standard. The same applies to a bit shift by 64 on a 64-bit value value.

Right.  Just db_blkid is 64-bit.

> That being said, the real constraint that matters here is that the subtraction not underflow, so I will just change it to `ASSERT3U(dn->dn_phys->dn_indblkshift, >=, SPA_BLKPTRSHIFT)`.

If you wish so.  To me this does not belong here.

**Review by behlendorf — APPROVED** [review]

**Pull request merged**
