### PR TITLE
KMC_KVMEM should use kvmalloc()

### PR DESCRIPTION
**Pull request by ahrens**
### Motivation and Context

`KMC_KVMEM` was designed to use `kvmalloc()` (see #9034).  However, this
was changed by #9813 to use `vmalloc()`, because `kvmalloc()` doesn't
always return page-aligned addresses.  However, the SPL kmem-cache
implementation doesn't need page-aligned addresses, because no SPL
caches request any particular alignment.
### Description

This commit changes `KMC_KVMEM` to use `kvmalloc()`, removes the
assertion that it returns page-aligned addresses, and asserts that SPL
caches to not request any particular alignment.

Note: this PR depends on https://github.com/openzfs/zfs/pull/10673, and includes that commit.  Please review the most recent commit (https://github.com/openzfs/zfs/commit/1b1fe1392113c7543fec1336d41b66a6cef1a9cc).

cc @c0d3z3r0 @loli10K 

### How Has This Been Tested?

ZTS

I could use help testing this with a KASAN build.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ahrens** [comment]
Whoops, I made a mistake in my testing.  The `zio_[data_]buf_cache`s request 4K alignment.  I don't think the alignment is really needed, but I'll need to test this a bit more before it's ready for integration.

**Comment by ahrens** [comment]
The SIMD instructions do have alignment requirements, of up to 64-bytes (e.g. for avx512).  So we'll have to find a way to return aligned addresses.  I'll look into making each buffer 63 bytes larger so that we can increase the returned pointer to make it aligned.

**Comment by adamdmoss** [comment]
Sorry for the dumb question, but why is kvmalloc() better than vmalloc() to warrant the change back?

As far as I can tell, kvmalloc() tries to allocate physically contiguous memory and falls back to virtually contiguous, while vmalloc() is just virtually contiguous.  Since it appears that virtually-contiguous is fine for SPL/ZFS and physically-contiguous memory is rarer, shouldn't we always just use vmalloc() and save physically-contiguous regions for kernel components that need it (i.e. DMA'able areas)?

**Comment by ahrens** [comment]
@adamdmoss My understanding is that kmalloc (and thus kvmalloc) is much faster than vmalloc, because it doesn't need to manipulate the page tables / TLB.

**Comment by adamdmoss** [comment]
Ah, cool - thanks for the explanation.  I like fast.  :)

**Comment by adamdmoss** [comment]
I suspect that ZFS's use of vmalloc() can directly cause kswapd to poke ZFS's own (newish) shrinker callbacks on access, if allocation is lazy as BrainSlayer suggests.  Since eviction, decryption and (occasionally) decompression want to allocate new memory, this can create a feedback loop causing very rapid ARC shrink.

I have a fistful of new heuristics to help ARC sizing decisions in general but I'd be interested in trying a (SIMD-safe :) ) version of this change to see if it helps to confirm the vmalloc-kswapd theory.

**Comment by BrainSlayer** [comment]
> I suspect that ZFS's use of vmalloc() can directly cause kswapd to poke ZFS's own (newish) shrinker callbacks on access, if allocation is lazy as BrainSlayer suggests. Since eviction, decryption and (occasionally) decompression want to allocate new memory, this can create a feedback loop causing very rapid ARC shrink.
> 
> I have a fistful of new heuristics to help ARC sizing decisions in general but I'd be interested in trying a (SIMD-safe :) ) version of this change to see if it helps to confirm the vmalloc-kswapd theory.

even if i know that kernel context allocations will never swap. feel free to give any proof or enhancements you find

**Comment by adamdmoss** [comment]
I made no assertion that we swap, only that kswapd has a mechanism to ask us to shrink, which is no secret.

**Comment by BrainSlayer** [comment]
since the memory in contiguous it it would not have any effect. correct me if i'm wrong but i think this still just belongs to userspace

**Comment by adamdmoss** [comment]
The changes from this PR are testing *very* well for me - I've gone from 7-8 gnome-shell 'page allocation failure's per day to zero so far.  This softly confirms my suspicion that vmalloc() is letting us severely overcommit.

>  I'll look into making each buffer 56 bytes larger so that we can increase the returned pointer to make it aligned.

**Comment by ahrens** [comment]
@adamdmoss Thanks for the offer!  I actually coded this up a while back, but ran into issues while testing it.  I've updated this PR to include that code.  If you have time, it would be great if you could take a look at it and see if it's still failing and why.

**Comment by adamdmoss** [comment]
> @adamdmoss Thanks for the offer! I actually coded this up a while back, but ran into issues while testing it. I've updated this PR to include that code. If you have time, it would be great if you could take a look at it and see if it's still failing and why.

Cool!  Any leads on the fail - is it test suite failures or some sort of runtime instability/asserts?

**Comment by ahrens** [comment]
@adamdmoss IIRC, it panic's while running the test suite.

**Comment by adamdmoss** [comment]
Quick question there - does the alignment-fudging have to be at the spl_slab_alloc() level or can it just be at the kv_alloc() level?  Is skc->skc_obj_align the only alignment hint(?) we get?

Does 3e8e23da0f3b5ff1a71ebb96db50180aef40ace8 still work? :)

**Comment by adamdmoss** [comment]
Lots of failing tests (looks like CI is just generally unhappy with all PRs lately) but nothing panic-y as far as I can tell now.

**Comment by behlendorf** [comment]
The CI has been cranky lately, but this looks more serious to me.  Many of the console logs indicate some kind of hang with zio's failing to complete.  For example:

http://build.zfsonlinux.org/builders/CentOS%208%20x86_64%20%28TEST%29/builds/1414/steps/shell_9/logs/console

**Comment by adamdmoss** [comment]
@behlendorf I missed those - those look bad.  Odd that a bug with this patch would manifest like that rather than something more panic-y, but I guess if memory is getting corrupted anything is possible.

**Comment by adamdmoss** [comment]
@ahrens I'm curious, the original alignment-unfriendly version of this PR was very simple:
c13bd21fde2a9ffcc6d36c25d8f1fa1f6f1c6dc5 ; adding alignment padding at the kv_alloc() level seems straightforward (if possibly wasteful), which I thought was going to be the original plan, and that would eliminate all the new complexity in spl_slab_alloc().  What am I missing?  Too wasteful to do this at kv_alloc()?
Cheers.

**Comment by ahrens** [comment]
@adamdmoss If you think that way will be simpler, go for it!

**Comment by adamdmoss** [comment]
Cool, I'll give it a shot. :)

**Comment by adamdmoss** [comment]
> The SIMD instructions do have alignment requirements, of up to 64-bytes (e.g. for avx512). So we'll have to find a way to return aligned addresses. I'll look into making each buffer 56 bytes larger so that we can increase the returned pointer to make it aligned.

**Comment by adamdmoss** [comment]
Having gone through the process of making that work and looking at the slab allocation code I'm now inclined to think that ideally the alignment padding does belong hidden inside spl_kmem_slab_t after all.  :rofl:
But that's also hairier to get right so I'll go with whatever doesn't explode the test machines, for now at least.

**Comment by adamdmoss** [comment]
Would kv_alloc() still need to return a page-aligned address or will 64-byte-aligned suffice?
Is there a repro for triggering the SIMD alignment assert or seeing some other SIMD alignment fallout?

**Comment by behlendorf** [comment]
> Would kv_alloc() still need to return a page-aligned address or will 64-byte-aligned suffice?

For the SIMD code 64-byte alignment should be sufficient.  There isn't any ASSERT I can think of offhand for this, but we do rely on the `zio_*` kmem cache buffers being at least 512b aligned (as requested by `zio_init()`), and the ABD buffers being page aligned.

**Comment by adamdmoss** [comment]
I'd appreciate some eyes on #11009 - especially @ahrens  - I think it's ready for review.
Or if it's silly to make a similar-but-separate issue for the approach over there, feel free to fold those changes into here if desired.  Thanks.

**Comment by adamdmoss** [comment]
> > Would kv_alloc() still need to return a page-aligned address or will 64-byte-aligned suffice?
> 
> For the SIMD code 64-byte alignment should be sufficient. There isn't any ASSERT I can think of offhand for this, but we do rely on the `zio_*` kmem cache buffers being at least 512b aligned (as requested by `zio_init()`), and the ABD buffers being page aligned.

Thanks.  I think there's a bit of a conflation between the alignment of the spl_kmem_slab_t itself - which is just whatever is returned by `kv_alloc()` - and the alignment required from the objects _inside_ the slab.

`spl_slab_alloc()` doesn't attempt to align the objects (though it does assert that they end up aligned as expected) and relies on the fact that the pointer it gets from kv_alloc() is aligned coarsely enough to satisfy all reasonable smaller alignments.

If I'm understanding it correctly, https://github.com/ahrens/zfs/tree/kmem3 is attempting to shift the object alignment responsibility into the slab-setup.  I approve of that deluxe approach (it could be a bit less wasteful of padding) but it's hairier - #11009 just puts page-alignment on top of kv_alloc() rather than moving the complexity into the slab.

**Comment by adamdmoss** [comment]
I don't think there's actually anything to gain from this PR (at least as measured on linux kernel 5.4) even if it were working - I've closed #11009 for that reason.

**Comment by amotin** [comment]
This seems to be long outdated.

**Pull request closed without merging**
