### PR TITLE
zfs-2.0.5 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patchset for zfs-2.0.5.  It builds on the 5.12 kernel.

### Description
This is the `zfs-2.0.5-staging` branch with a few minor fixes to the commit messages.

### How Has This Been Tested?
Buildbot will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Could we include 38280c3526845852c4da09fd0c11090493ee58fb in this, too? It's simple, localised, and fixes a PID leak into zombies in the ZED.

**Comment by aerusso** [comment]
I'd like to suggest:

 - 0ab84bff5 (fixes a  typo in the documentation)
 - 2037edbda (aligns a return code with convention on Linux)

Also, possibly consider 1daad9817, which tightens some runtime assertions.

**Comment by tonyhutter** [comment]
@nabijaczleweli @aerusso thanks, I'll take a look at those.

**Comment by tonyhutter** [comment]
@nabijaczleweli @aerusso I included your commits in my latest push.

**Comment by aerusso** [comment]
I think the ZTS failure on Ubuntu 20.04 should be fixed by b8e6401b794be9e8188d595d64f98b560d50cb6e .

**Comment by behlendorf** [comment]
And the kernel.org build failure can fixed with 272b178d524112f2a48996d431c9ed51fe41791f.

**Comment by tonyhutter** [comment]
@aerusso @behlendorf thanks, I just pulled those in

**Comment by tonyhutter** [comment]
I'm currently looking into the `make lint` errors in checkstyle...

**Comment by freqlabs** [comment]
Looks like FreeBSD main also needs 93f81eb7211becfa2acccac640e7f8c92fd76e0d

**Comment by tonyhutter** [comment]
@freqlabs thanks, I included it in my latest push.

**Comment by IvanVolosyuk** [comment]
Can we also add the panic fix from to the next stable release:
https://github.com/openzfs/zfs/pull/12210
https://github.com/openzfs/zfs/commit/afa7b3484556d3ae610a34582ce5ebd2c3e27bba

**Comment by freqlabs** [comment]
And 8dddb25d2c68e623426a38c9a475767cd8fecdc1. 🤦

**Comment by tonyhutter** [comment]
@IvanVolosyuk @freqlabs I included those commits in my latest push

**Comment by kernelOfTruth** [comment]
https://github.com/openzfs/zfs/commit/9ffcaa370aee6871c92c7c84aa65942fba63a884 Avoid deadlock when removing L2ARC devices under I/O

as well, please :pray:

**Comment by awehrfritz** [comment]
@tonyhutter any update on when we can expect the 2.0.5 release to happen? The lack of a stable ZFS release with support for Linux 5.12 forces all Fedora, Arch, Gentoo and OpenSUSE Tumbleweed users to run an unsupported/end-of-life kernel for weeks now.

**Comment by tonyhutter** [comment]
@awehrfritz hopefully this week.  I think we have all the patches we want in the branch, but there are some test failures I need to look into.

**Comment by awehrfritz** [comment]
> @awehrfritz hopefully this week.

Great! Looking forward to it.

**Comment by tonyhutter** [comment]
zfs-2.0.5 released yesterday:

https://github.com/openzfs/zfs/releases/tag/zfs-2.0.5

**Pull request closed without merging**
