### PR TITLE
zdb: add -B option to generate backup stream

### PR DESCRIPTION
**Pull request by robn**
### Motivation and Context

We were working on a data recovery for a client, and the dataset name table was damaged to the extent that referencing a snapshot we needed, or asking for its name, would panic ZFS.

On further investigation, we found that `dmu_send_obj` didn't care at all about the name, so we just needed a way to arrange for it to be called.

### Description

This adds a `-B` option, which will produce a standard backup stream from the given `pool/objset-id`. An optional arg can set the flags.

```
# zdb -B lucy/34760 Lecw | ./zstream dump
BEGIN record
	hdrtype = 1
	features = 3420000
	magic = 2f5bacbac
	creation_time = 63dc5e6c
...
```

Sponsored-By: Klara, Inc.

### How Has This Been Tested?

Only local testing on the specific feature. Test suite should get anything of interest.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by mcmilk** [comment]
@robn - In general - this is a really cool idea - and also the implementation looks straightforward.

Could you rebase the thing? It's needed for the new testing workflow... So we see, it doesn't break sth.
I will approve this next week, when the testings are run.

**Comment by robn** [comment]
> Could you rebase the thing? It's needed for the new testing workflow... So we see, it doesn't break sth. I will approve this next week, when the testings are run.

Oops! That's a thing I normally just do before a new push, not sure why I missed it this time. Done! Thanks for pointing it out!

**Comment by robn** [comment]
> Short writes may occur.

Yeah, fair. I've pushed something that should be a little more resilient.

**Review by Low-power — CHANGES_REQUESTED** [review]
Don't use arithmetic operation on a `void *` directly, cast it to `char *` first, like:

```c
static int
dump_backup_bytes(objset_t *os, void *buf, int len, void *arg)
{
	const char *p = buf;
	ssize_t nwritten;

	(void) os;
	(void) arg;

	/* Write the data out, handling short writes and signals. */
	while ((nwritten = write(1, p, len)) < len) {
		if (nwritten < 0) {
			if (errno == EINTR)
				continue;
			return (errno);
		}
		p += nwritten;
		len -= nwritten;
	}

	return (0);
}
```

**Review by Low-power — COMMENTED** [review]
Consider using some C99 features to reduce scpoe of some variables, and make initialization looks better:
```diff
--- a/cmd/zdb/zdb.c
+++ b/cmd/zdb/zdb.c
@@ -4897,9 +4897,6 @@ static void
 dump_backup(const char *pool, uint64_t objset_id, const char *flagstr)
 {
 	const char *c;
-	int err = 0;
-	offset_t off = 0;
-	dmu_send_outparams_t out = {0};
 
 	boolean_t embed = B_FALSE;
 	boolean_t large_block = B_FALSE;
@@ -4927,10 +4924,13 @@ dump_backup(const char *pool, uint64_t objset_id, const char *flagstr)
 		}
 	}
 
-	out.dso_outfunc = dump_backup_bytes;
-	out.dso_dryrun = B_FALSE;
+	offset_t off = 0;
+	dmu_send_outparams_t out = {
+		.dso_outfunc = dump_backup_bytes,
+		.dso_dryrun = B_FALSE
+	};
 
-	err = dmu_send_obj(pool, objset_id, 0, embed, large_block, compress,
+	int err = dmu_send_obj(pool, objset_id, 0, embed, large_block, compress,
 	    raw, /* saved */ B_FALSE, 1, &off, &out);
 	if (err != 0) {
 		fprintf(stderr, "dump_backup: dmu_send_obj: %s\n",
```

**Comment by robn** [comment]
> Don't use arithmetic operation on a `void *` directly, cast it to `char *` first, like:

Yeah, silly me.

> Consider using some C99 features to reduce scpoe of some variables, and make initialization looks better:

Agreed. I spend a lot of time in codebases where old conventions are still the rules, and a lot of ZFS still looks like that, so I don't think much about it. But reviewer wins here :)

Thanks!

**Comment by Low-power** [comment]
Lasty in this comment:
```c
/* Write the data out, handling short reads and signals. */
```
I think the code means **short writes** not reads.

**Comment by Low-power** [comment]
When trying out this feature, I accidently runs it without redirecting, thus trashed my terminal...

May be it is better to have a `isatty(STDOUT_FILENO)` check just like in **zfs-send(8)**.

**Comment by robn** [comment]
> I think the code means short writes not reads.

Sigh, I'm really having a day of it today. Thanks, fixed.

> May be it is better to have a isatty(STDOUT_FILENO) check just like in zfs-send(8).

Great suggestion. Done!

**Review by Low-power — APPROVED** [review]

**Review by behlendorf — COMMENTED** [review]
This is a nice addition to `zdb`.  However, it looks like it subtly broke two of the CI tests you'll need to run those failures down before we can integrate this.

```
Tests with results other than PASS that are unexpected:
    FAIL redacted_send/redacted_props (expected PASS)
    FAIL rsend/send_freeobjects (expected PASS)
```

Please also go ahead and add a new test case for this functionality under `tests/zfs-tests/tests/functional/cli_root/zdb/`.

**Comment by robn** [comment]
@behlendorf thanks for the heads up, I missed those - I thought they were _obviously_ false positives, with all the churn happening in the tests at the time.

I should have time to get back to this in the next week or two. Cheers.

**Review by behlendorf — APPROVED** [review]

**Review by mcmilk — APPROVED** [review]

**Comment by robn** [comment]
Not quite done with this yet, still have to add a test for it and I want to update the docs a little bit to say that it can handle sending whole real datasets, not just snapshots (which it obviously can, but I hadn't come at it from that angle, and then we used it for that and won the day :astonished:).

**Comment by behlendorf** [comment]
@robn sounds good.

**Comment by robn** [comment]
@behlendorf good to go (pending remaining tests). I added a commit to expose a function I need; up to you if you would prefer to squash it or not. Cheers!

**Review by behlendorf — APPROVED** [review]
This looks good.  Thanks for wrapping it up, I can squash it when merging.

**Comment by behlendorf** [comment]
Merged, I opted to keep the commits split.

**Comment by robn** [comment]
Thanks all!

**Pull request closed without merging**
