### PR TITLE
zfs-2.0.7 proposed patch set

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patch set for zfs-2.0.7. It's currently the same as the `zfs-2.0.7-staging` branch.

### Description
This is a smaller release to build on Fedora 35 and the latest FreeBSD.

### How Has This Been Tested?
Buildbot will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gyakovlev** [comment]
if fix for https://github.com/openzfs/zfs/issues/11900 land please include it, it's pretty nasty one

**Comment by freqlabs** [comment]
FreeBSD main needs 14b69c0929f3867f87418f6f4001994afb26e5dd

**Comment by rincebrain** [comment]
I'd also suggest 05679465 for both this and 2.1.

**Comment by tonyhutter** [comment]
> I'd also suggest 0567946 for both this and 2.1.

@rincebrain 2.0.x doesn't contain 59eab1093a361ca76849ca76b2ec079c8736e8e3, so I assume it doesn't actually need the 0567946 revert?

**Comment by rincebrain** [comment]
> > I'd also suggest [0567946](https://github.com/openzfs/zfs/commit/05679465ace023148ca6317580a6feada53f1643) for both this and 2.1.
> 
> @rincebrain 2.0.7 doesn't contain [59eab10](https://github.com/openzfs/zfs/commit/59eab1093a361ca76849ca76b2ec079c8736e8e3), so I assume it doesn't actually need the [0567946](https://github.com/openzfs/zfs/commit/05679465ace023148ca6317580a6feada53f1643) revert?

Ah, hm, I had overlooked that. I'd propose putting both in, then, unless you'd strongly prefer not to. (I'll even go do the PR if it doesn't apply cleanly for some reason.)

**Comment by tonyhutter** [comment]
@rincebrain I'll try to get them both in.  There's some merge conflicts I need to untangle though.

**Comment by tonyhutter** [comment]
@rincebrain the dependencies resolved without much of an issue. I've pulled in 59eab10 and 0567946.

**Comment by freqlabs** [comment]
Can we get aa4a84e616fdabc7c8ddae3ee47dc4f821bdc58 in here too, please.

**Comment by freqlabs** [comment]
It would be nice to get 7443299fe0b8caaadbfc18f778732bb26c899e41 in as well.

**Comment by tonyhutter** [comment]
Sorry for the radio silence - I'm back from vacation and will get back to working on this.

**Comment by jgottula** [comment]
As with 2.1.2, it'd be good if 2.0.7 could pull in #12759.

**Comment by tonyhutter** [comment]
We'll want these 5.16 kernel fixes as well: https://github.com/openzfs/zfs/pull/12819

**Comment by freqlabs** [comment]
> Can we get [aa4a84e](https://github.com/openzfs/zfs/commit/aa4a84e616fdabc7c8ddae3ee47dc4f821bdc588) in here too, please.

Seems this was missed

**Comment by tonyhutter** [comment]
>> Can we get aa4a84e in here too, please.

> Seems this was missed

Thanks, I just pushed it in

**Comment by tonyhutter** [comment]
The `zfs-test-functional` tests are failing since it's hitting the 6 hour limit in github workflows.  I'm going to manually run the tests in a VM to see what's taking so long.

**Comment by thesamesam** [comment]
@tonyhutter is it worth us downstream (Gentoo) transitioning to 2.1.2 or should we wait for 2.0.7?

**Comment by gyakovlev** [comment]
^ just to elaborate on previous question.
we maintain 2 branches of packages: stable and not-so-stable
currently zfs 2.0.x is stable
2.1.x is in testing

so are there any long term plans of maintaining 2.0.x branch or should we just transition stable users to 2.1.2+ ?

**Comment by behlendorf** [comment]
@gyakovlev the long term plan is to maintain the 2.1 branch as the LTS release, and to drop support for the 2.0 branch.  I'd suggest transitioning to the 2.1 branch once you're comfortable moving it out of testing.

**Pull request merged**
