### PR TITLE
Modify checksum obtain method of QAT

### PR DESCRIPTION
**Pull request by hedongzhang**
CpaDcGeneratefooter function that obtain the checksum code does not support the CPA_DC_STATELESS mode. So we get the adler32 chencksum of the end of the zlib from dc_results

Fix QAT compress defects: [Zlib may not be able to decompress some data compressed using QAT #12317](https://github.com/openzfs/zfs/issues/12317)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
@wli5 @cfzhu would you mind taking a look at this proposed QAT fix.

**Comment by cfzhu** [comment]
Thanks Hedong, @hedongzhang ,for your pull request, I need to reproduce this issue, could you provide more information?

**Comment by hedongzhang** [comment]
Hi @cfzhu ，As communicated before, this PR has nothing to do with that issue #12317, only optimizes the checksum acquisition. Do you think this is necessary？

**Comment by tonynguien** [comment]
@hedongzhang Can you address these minor cstyle issues? Thanks.
`
Run make checkstyle
./module/os/linux/zfs/qat_compress.c: 423: line > 80 characters
Error: line > 80 characters
./module/os/linux/zfs/qat_compress.c: 424: space or tab at end of line
Error: space or tab at end of line
make: *** [cstyle] Error 1
Makefile:1505: recipe for target 'cstyle' failed
Error: Process completed with exit code 2.
`

**Review by cfzhu — APPROVED** [review]

**Comment by cfzhu** [comment]
Hi Hedong @hedongzhang, sorry for my late replay, I need to do some tests for this, and all tests passed, I approved your request, thanks for your help.

**Comment by hedongzhang** [comment]
@cfzhu @tonynguien OK，I've had it repaired

**Review by behlendorf — APPROVED** [review]

**Comment by behlendorf** [comment]
@hedongzhang can you 1) squash these commits and rebase this against the latest master branch, 2) add your signed-off-by to the commit message, and 3) force update the PR.  Then this should be ready to go.

`git commit --amend -s`

**Comment by hedongzhang** [comment]
Hi @behlendorf , I closed this PR accidentally，can you reopen it?

**Comment by behlendorf** [comment]
No problem, reopened.

**Pull request merged**
