### PR TITLE
ZTS: cli_root/zfs_load-key: add separate key files

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
As fodder for #11956

### Description
https://github.com/openzfs/zfs/pull/11956#issuecomment-829619911

### How Has This Been Tested?
https://raw.githubusercontent.com/openzfs/zfs/b2275f00b9a297a176a605fa6db2419af2180637/tests/zfs-tests/tests/functional/cli_root/zfs_load-key/HEXKEY resolves

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by behlendorf — COMMENTED** [review]
You're going to need to add the new files to the `Makefile.am` so they get included by `make dist`.

**Comment by nabijaczleweli** [comment]
Done

**Review by behlendorf — APPROVED** [review]

**Comment by behlendorf** [comment]
Once the bots wrap up I'll go ahead and merge this.  It seems highly unlikely this would break anything but we can wait a few hours.  Thanks.

**Comment by behlendorf** [comment]
Merged as 6f4e132fec

**Pull request closed without merging**
