### PR TITLE
zfs-2.0-release backports wishlist

### PR DESCRIPTION
**Pull request by freqlabs**
This batch of commits applied cleanly to zfs-2.0-release. I only had to remove two draid lines from the test in 
0cc05d0 for all the tests to pass on FreeBSD. I also tried to avoid picking commits with ABI changes in them.

I know a few of these I've already been told won't be backported, but I've kept the full list.

### CODE REVIEW

**Comment by behlendorf** [comment]
Thanks for generating this list of backports, most of these look like good candidates.  We will want to prune the list down a bit to changes which resolve significant bugs, are clearly safe like documentation updates, are needed for kernel compatibility, or are needed to support our workflow.

**Comment by freqlabs** [comment]
* Dropped some nonessential code cleanup:
```
-Miscellaneous code cleanup
-FreeBSD: Prune some unneeded definitions
-Drop "All rights reserved" from files by trasz@FreeBSD.org
-libspl: lift common bits of getexecname()
-module/zfs/zvol.c: purge unused zvol_volmode_cb_arg
-.gitmodules: link to openzfs github repository
-cmd/zfs receive: allow dry-run (-n) to check property args
-Balance parentheses in parameter descriptions
-libzfs_crypto.c: remove unused key_locator enum
-zstreamdump: exec zstream dump
-Move zfsdev_state_{init,destroy} to common code
-Eliminate zfsdev_get_state_impl
-Return finer grain errors in libzfs unmount_one
```

**Comment by freqlabs** [comment]
-Use a helper function to clarify gang block size

**Comment by freqlabs** [comment]
> #11836 ?

Sure. FWIW I didn't look at anything that seemed to only relate to Linux, as we're not shipping any Linux-based release with zfs-2.0-release where I work. We'll be on zfs-2.1-release for TrueNAS SCALE.

**Comment by tonyhutter** [comment]
@freqlabs I see this is still marked as Draft - is it about ready for review, or are you still adding commits?

**Comment by freqlabs** [comment]
> @freqlabs I see this is still marked as Draft - is it about ready for review, or are you still adding commits?

I'm finished 👍

**Comment by tonyhutter** [comment]
Ok, I'll take a look

**Comment by tonyhutter** [comment]
You may have accidentally checked in a `tests/zfs-tests/tests/functional/acl/off/dosmode_readonly_write` binary in 9524a3ff8 when backporting 0936981d8.

**Comment by freqlabs** [comment]
* Removed sneaky dosmode_readonly_write binary

**Comment by nabijaczleweli** [comment]
if you're not including keylocation=https://, then you can drop "ZTS: cli_root/zfs_load-key: add separate key files"

**Comment by freqlabs** [comment]
* Dropped 05e971e

**Comment by tonyhutter** [comment]
@freqlabs thanks, it's looking ok to me.

@behlendorf what would you rate the risk level of c6eea8866 at?

**Comment by behlendorf** [comment]
@tonyhutter I think c6eea88 would be safe, but since it is a bit subtle and only a performance optimization I'd suggest we not include it for now.

**Comment by freqlabs** [comment]
* Dropped c6eea88

**Review by tonyhutter — APPROVED** [review]
Looks good, thanks for your backports!

**Comment by tonyhutter** [comment]
I totally missed this! - can you change the dropdown box at the top of the PR to make this change against the `openzfs:zfs-2.0.5-staging` branch, rather than the `openzfs:zfs-2.0-release` branch?

**Comment by freqlabs** [comment]
> I totally missed this! - can you change the dropdown box at the top of the PR to make this change against the `openzfs:zfs-2.0.5-staging` branch, rather than the `openzfs:zfs-2.0-release` branch?

Done 👍

**Comment by tonyhutter** [comment]
@behlendorf this should be good to go

**Pull request merged**
