### PR TITLE
[backport] 4.8, 5.16, and 5.17 compat patches

### PR DESCRIPTION
**Pull request by jonathonf**
### Motivation and Context

This PR backports a number of compat patches to the 2.1.* series

### Description

Cherry-picks:

* https://github.com/openzfs/zfs/commit/6bee1d685b55c4568a4437586d0f15f762de1ec4
* https://github.com/openzfs/zfs/commit/17b1caccdb8ec15f44b609c62ed9faadeb79bd02
* https://github.com/openzfs/zfs/commit/a5a87e5b451ded2c7d65c0a53ee3e9e4f32c11f9
* https://github.com/openzfs/zfs/commit/6be5c7dde8b27c51dee3565b706adb654c7e91cb
* https://github.com/openzfs/zfs/commit/021ac0424d87f04e0e610e06fdb9579cab0496b5
* https://github.com/openzfs/zfs/commit/6102d48a4ef04d2859fe79c3d01fedd48caf278b
* https://github.com/openzfs/zfs/commit/994f0c301c63f61fee8ca0e5b24b37e80fd4d90f
* https://github.com/openzfs/zfs/commit/fa03c73a4f8540fbba2f0b68d43799de0342bf69

### How Has This Been Tested?

5.16 and 5.17 compat patches tested on Arch Linux.
5.16 compat patches tested on Ubuntu 18.04.

### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [X] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [X] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by jonathonf** [comment]
5.16 compat patches are working fine (and have been since they were merged to master).

5.17 patches seem to be working fine with 5.17rc2. I'll give it another 24 hours or so before removing draft status.

**Comment by AttilaFueloep** [comment]
Once it is merged, you may want to include #13059 as well.

**Comment by tonyhutter** [comment]
Thank you for these backports. I see that you added:

```
    (cherry picked from commit a3fbe2b9421afcfafca58fbed93acc6d6bb7a5f6)
    Signed-off-by: Jonathon Fernyhough <jonathon@m2x.dev>
```
... to all the commit messages.  Historically, we don't change the commit message when backporting (unless there was some weird special case that needed to be documented).  Would you mind removing it just for consistency?

Otherwise, these look good to go.

**Comment by jonathonf** [comment]
Oops, I got that as "best practice" from somewhere. I'll force-push.

**Review by tonyhutter — COMMENTED** [review]
Thanks @jonathonf

**Comment by imwhocodes** [comment]
Hi @jonathonf 

Sorry to bother you here, I know it is not the most appropriate channel but do you have any plan for more release of ZoL scheduled for your Ubuntu-PPA? Last version in this repo is 5 fix/patch releases ahead 

I'm having some problem (mostly random total OS freezes when on heavy load on high zstd-compression and high block-size dataset ) and it would be nice to have up-to-date ZFS on Ubuntu to see if this problem have been already addressed (I saw some commit that could be related)

Sorry again and
Really thank you for your time

**Comment by gmelikov** [comment]
@imwhocodes unfortunately, https://www.google.com/search?q=Jonathon+Fernyhough+death

I didn't hear if anybody tried to fork his PPA, too.

**Comment by imwhocodes** [comment]
Sorry,
I didn't know his surname and that he was a so important and active figure in the open-source community

I'm deeply sorry

**Pull request merged**
