### PR TITLE
Update FreeBSD Versions

### PR DESCRIPTION
**Pull request by driesmp**
I guess this change is self explanatory,  so I didn't really do the checklist my apologies.

### CODE REVIEW

**Comment by freqlabs** [comment]
Let's keep the non-release branches mentioned as well. What do you think about this? 
```
* Supported FreeBSD versions are any supported branches and releases starting from 12.2-RELEASE.
```

**Comment by driesmp** [comment]
> Let's keep the non-release branches mentioned as well. What do you think about this?
> 
> ```
> * Supported FreeBSD versions are any supported branches and releases starting from 12.2-RELEASE.
> ```

Looks good to me, I was in search of a wording that wouldn't need updating each time a new branch is created or CURRENT is bumped. I think this accomplishes all of the above and that.

**Review by freqlabs — APPROVED** [review]
Thanks!

**Comment by behlendorf** [comment]
@driesmp could you force update this PR to include your [signed-off-by](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by) in the updated command message.

```
git commit --amend -s
```

**Pull request merged**
