### PR TITLE
RPM: Explicitly set the required min/max kernel version for the DKMS

### PR DESCRIPTION
**Pull request by awehrfritz**
Motivation, context and description as in: #12124

@tonyhutter: I would appreciate if we could include this patch in the stable releases as well. This should do the trick for the 2.0.x series, I am not sure though how to get this into the 2.1.0 release as there is no staging branch.

### CODE REVIEW

**Comment by behlendorf** [comment]
@awehrfritz I've included this in [2.1.0-rc6](https://github.com/openzfs/zfs/releases/tag/zfs-2.1.0-rc6).

**Comment by awehrfritz** [comment]
> @awehrfritz I've included this in [2.1.0-rc6](https://github.com/openzfs/zfs/releases/tag/zfs-2.1.0-rc6).

Great, thanks!

**Review by tonyhutter — APPROVED** [review]

**Review by behlendorf — APPROVED** [review]

**Comment by awehrfritz** [comment]
Great, thanks for merging this!

@tonyhutter, from the commit log in this branch, I gather that the 5.12 compatibility patches are backported to this branch. However, the META file still lists 5.11 as the maximum kernel version supported. Are there still some patches missing or is this an oversight?

**Comment by tonyhutter** [comment]
@awehrfritz  I actually just put out a PR for zfs-2.0.5 today, which includes the META update: https://github.com/openzfs/zfs/pull/12182

**Pull request merged**
