### PR TITLE
Increase default arc_c_max

### PR DESCRIPTION
**Pull request by grwilson**
Increase default arc_c_max
    
Now that the arc uses ADB buffers, we should be able to increase the default max size of the arc to match what is used by other platforms. This change sets the max size of the arc to 3/4 of all memory or all but 1GB, whichever is greater.
    
Signed-off-by: George Wilson <gwilson@delphix.com>
External-issue: DLPX-66501

### CODE REVIEW

**Comment by gmelikov** [comment]
Are we really sure to bump it? For example there was a case with starting VMs with KVM, qemu checks free memory, ARC isn't free for it, and it refuses to start VM. Maybe I've missed something and it's isn't so now.

**Comment by grwilson** [comment]
@gmelikov This is bumping the max that the arc can ever grow to. Currently it's been artificially set to 1/2 of memory of the VM. This doesn't mean that ZFS will automatically use all of the memory upon startup but rather what is the max that it could ever use. So default startup behavior should be very similar to what it is without this change. Also, you can still override the default maxsize as we've alway been able to do. 

From the digging I did, I found that the ARC had been limited to 1/2 all memory to deal with fragmentation. The ABD project specifically set out to address this but we never increased the default ARC size after that project integrated. From my testing on our workloads we are able to run fine with configuration. I'm hoping others can try this out and verify the same.

**Comment by behlendorf** [comment]
@gmelikov good question regarding VMs.  This is a change we'd like to make since the original core fragmentation reason for reducing the default has been resolved.  But we of course don't want to break anything so let's verify that this doesn't cause recent versions of qemu to fail when the ARC is maximally sized.

**Comment by kpande** [comment]
extensive testing with nfsd should be done here because of how it handles memory differently on Linux.

**Comment by behlendorf** [comment]
Unfortunately, in my testing this change does still cause some trouble with qemu even though the memory used by ZFS can be reclaimed.  I did do my testing under CentOS 7 so things may be different in newer qemu versions.

**Comment by Fabian-Gruenbichler** [comment]
On October 25, 2019 11:29 pm, Brian Behlendorf wrote:
> Unfortunately, in my testing this change does still cause some trouble with qemu even though the memory used by ZFS can be reclaimed.  I did do my testing under CentOS 7 so things may be different in newer qemu versions.

it definitely also happens for newer Qemu versions (we are using 4.x 
here, and have reports with the current default of "1/2 of memory" 
already). bumping this to "almost all memory" will lead to almost every 
VM start running into it.

if this default gets changed, please keep it in master/0.9.x so that 
users have a clear point when to adapt their module parameters (e.g., a 
ZFS major upgrade very often co-incides with a distro release upgrade, 
which would make "set zfs_arc_max" one of X config changes needed for 
that dist-upgrade, instead of something that hits on a regular 
maintenance upgrade process).

thanks!

**Comment by behlendorf** [comment]
@Fabian-Gruenbichler thanks for the confirmation.  By chance have you ever dug in to the qemu code to determine exactly what they're checking which causes this to fail.  My assumption has always been available memory plus page cache, but a pointer to the exact check to confirm this would be helpful.  If possible, we'd really like for this to work without requiring any changes to the default values.

**Comment by Fabian-Gruenbichler** [comment]
> @Fabian-Gruenbichler thanks for the confirmation. By chance have you ever dug in to the qemu code to determine exactly what they're checking which causes this to fail. My assumption has always been available memory plus page cache, but a pointer to the exact check to confirm this would be helpful. If possible, we'd really like for this to work without requiring any changes to the default values.

a quick glance points to the following sequence of [mmap operations](https://git.qemu.org/?p=qemu.git;a=blob;f=util/mmap-alloc.c;h=27dcccd8ec8e5a33121b3c69bf4458dde21b0eca;hb=HEAD#l149) as likely culprit:
```
guardptr = mmap(0, total, PROT_NONE, flags, guardfd, 0);
...
offset = QEMU_ALIGN_UP((uintptr_t)guardptr, align) - (uintptr_t)guardptr;
ptr = mmap(guardptr + offset, size, PROT_READ | PROT_WRITE, flags | map_sync_flags, fd, 0);
```

or, via strace:
```
mmap(NULL, 34361835520, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f11ca800000
mmap(0x7f11ca800000, 34359738368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
```

(this is for a VM with 32G memory, on a system with 16G ARC and 30G of otherwise free memory)

**Comment by behlendorf** [comment]
@Fabian-Gruenbichler thanks for the pointer, that's promising.  Since it's `mmap(2)` which is failing we _might_ be able to do something about this in the kernel module.

**Comment by Fabian-Gruenbichler** [comment]
On October 30, 2019 5:36 pm, kpande wrote:
> you should probably be using hugepages, anyway.

sure, and people do. it's optional though ;)

**Comment by dweeezil** [comment]
The problem with qemu is that it tries to allocate its memory in one huge chunk via _mmap()_ which doesn't play well with Linux's default overcommit mode 0 (heuristic mode, a.k.a. OVERCOMMIT_GUESS).

**Pull request closed without merging**
