### PR TITLE
Fixes to make dist

### PR DESCRIPTION
**Pull request by nivedita76**
make dist currently doesn't include all sources. Fix this.

### Description

Include FreeBSD module sources in make dist, add FreeBSD sources to distribution regardless of configured system in lib/, and cleanup some scattered missing files.
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by nivedita76** [comment]
The kernel include files under include/os/freebsd were previously not installed, even though the generic kernel include files are installed on freebsd as well. This change also installs those.

Let me know if freebsd should rather not install any kernel include files at all.

**Comment by freqlabs** [comment]
The goal is for the dist archive to be able to build any supported configuration on any supported platform from the one archive. It should include all sources, headers, auxiliary scripts, etcetera required to do so.

**Comment by nivedita76** [comment]
> The goal is for the dist archive to be able to build any supported configuration on any supported platform from the one archive. It should include all sources, headers, auxiliary scripts, etcetera required to do so.
> 
> Edit: Ah I see, "install" specifically. Well, I don't think it's necessary for the kernel headers to be installed. We do definitely want the user headers of course.

Right, I meant the make install target. On FreeBSD it installs "generic", i.e kernel include files not under os/, but not the ones under os/. This change currently installs the ones under os/ as well.

Also I forgot to mention one more question: make dist still doesn't include TESTS and config/suppressed-warnings.txt. These seem to be specific to buildbot, I wanted to check if we want to add them as well.

**Comment by nivedita76** [comment]
> Great, I think we should merge this as is.
> 
> `TEST` is only used by the CI, and frankly quite rarely. We normally rely of providing the same overrides via the commit comments so `TEST` currently provides mostly a documentation role of what's understood. That could be better done via a README.md or other documentation.
> 
> As for `suppressions.txt` moving that out of `.github` is probably a good idea since the `cppcheck` target depends on it and we want that to work with a dist tarball. The rest of the `.github` files I think we probably shouldn't include in `make dist`.

Do you want me to do a new commit moving suppressions.txt? I hadn't even noticed that one as it was inside a dotted-dir.

I was referring to the suppressed-warnings.txt inside the config/ subdir. It has a comment saying
`Expected warnings which should be suppressed by buildbot`
and isn't referenced anywhere in the source AFAICT.

**Comment by behlendorf** [comment]
> I was referring to the suppressed-warnings.txt inside the config/ subdir.

I'd completely forgotten that exists.  It appears to be unused by the buildbot currently, let's try removing it in a new PR and verify it doesn't cause any issue with buildbot.

> Do you want me to do a new commit moving suppressions.txt?

Please, I'll go ahead and merge this now.

**Pull request closed without merging**
