### PR TITLE
DKMS: Disable weak modules

### PR DESCRIPTION
**Pull request by gregory-lee-bartholomew**
Fedora does not guarantee a stable kABI, so weak modules should be dis-
abled. See the dkms man page for a more detailed explanation of the weak
module feature.

Signed-off-by: Gregory Bartholomew <gregory.lee.bartholomew@gmail.com>

### Motivation and Context
Closes issues #11242, #11128 and #9891 (and perhaps #11320?)

### Description
This pull request sets the DKMS option NO_WEAK_MODULES to "yes".

### How Has This Been Tested?
The details of how this issue was tested are described in issue #11242 (special thanks to @gogi983 for doing the testing)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gogi983** [comment]
We maybe should precise that this option need to be added either at the end of : 

`/usr/src/zfs-2.0.0/dkms.conf`

or create a conf file in /etc/dkms/ : 

`/etc/dkms/zfs.conf`

and append the option in it.

**Comment by gregory-lee-bartholomew** [comment]
@gogi983

The pull request I just submitted should take care of it. If it goes though, the end user shouldn't need to edit any files in future releases of zfs. Hopefully this problem will be gone for good. 🙂

**Comment by gogi983** [comment]
> @gogi983
> 
> The pull request I just submitted should take care of it. If it goes though, the end user shouldn't need to edit any files in future releases of zfs. Hopefully this problem will be gone for good. slightly_smiling_face

Yep, my bad, I had a look into it after commenting... ;)

**Review by behlendorf — APPROVED** [review]
This looks good to me.  Particularly for most distributions like Fedora where there is no stable kabi to depend on.  We could consider adding a `ZFS_DKMS_NO_WEAK_MODULES` option to `etc/default/zfs.in` to allow the previous behavior to be restored.  As was done for `ZFS_DKMS_ENABLE_DEBUG`.  However, personally I don't think that's really needed.

**Comment by gregory-lee-bartholomew** [comment]
I didn't test it, but based on the _dkms_ man page, the end user should be able to override this setting by adding `NO_WEAK_MODULES="no"` to `/etc/dkms/zfs.conf`.

**Pull request merged**
