### PR TITLE
zfs-2.1.10 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Include latest patches from the `zfs-2.1.10-staging` branch and fix builds on Fedora 37.

### Description
Patchset for zfs-2.1.10

### How Has This Been Tested?
Buildbot will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by stuartthebruce** [comment]
Is here a buildbot for EL9 x86_64?

**Comment by tonyhutter** [comment]
> Is here a buildbot for EL9 x86_64?

@stuartthebruce our internal buildbot that we use to test releases supports EL9 and F37.  I just haven't gotten around to backporting it to the main zfs-buildbot repo yet.   It's on my TODO list...

**Comment by tonyhutter** [comment]
@stuartthebruce I was able to put together the EL9/F37 buildbot PR: https://github.com/openzfs/zfs-buildbot/pull/270

**Comment by stuartthebruce** [comment]
@tonyhutter what version of the EL8 kernel are you building `kmod-zfs` against?

`kmod-zfs-2.1.9-1.el8.x86_64` causes `kernel-4.18.0-425.19.2.el8_7.x86_64` to panic at `zpool import`. Perhaps RH mistakenly broke the EL8 kernel ABI again.

**Comment by tonyhutter** [comment]
Quick update on this PR - it appears the tests are not being run in Centos 7 (even though it reports a green checkmark):
```
/usr/share/zfs/test-runner/bin/test-runner.py    -c "/usr/share/zfs/runfiles/common.run,/usr/share/zfs/runfiles/linux.run" -T "functional" -i "/usr/share/zfs/zfs-tests" -I "1"
  File "/usr/share/zfs/test-runner/bin/test-runner.py", line 294
    f"echo ZTS run {self.pathname} > /dev/kmsg"])
                                              ^
```
I believe we may need to pull in 8a7c4efd3cf47ce4a27b00c176845f1ac1c483c8 and see where that gets us.

**Comment by tonyhutter** [comment]
Released: https://github.com/openzfs/zfs/releases/tag/zfs-2.1.10

**Comment by saesh** [comment]
Thank you @tonyhutter!

**Pull request merged**
