### PR TITLE
libzfs: calculate receive times with sub-second precision

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
I send/receive tiny snapshots often enough that rounding up to a full second introduces a significant error.

### Description
```
nabijaczleweli@tarta:~/store/code/zfs$ sudo ./cmd/zfs/zfs send -RLcv filling/machine/szarotka/floppies@indices | sudo ./cmd/zfs/zfs recv -ev tarta-zoot
skipping snapshot filling/machine/szarotka/floppies@od-szafy because it was created after the destination snapshot (indices)
skipping snapshot filling/machine/szarotka/floppies@chown-0:0 because it was created after the destination snapshot (indices)
full send of filling/machine/szarotka/floppies@initial-backup estimated size is 12.3M
send from @initial-backup to filling/machine/szarotka/floppies@whiskas-supreme estimated size is 107M
send from @whiskas-supreme to filling/machine/szarotka/floppies@indices estimated size is 51.1K
total estimated size is 120M
receiving full stream of filling/machine/szarotka/floppies@initial-backup into tarta-zoot/floppies@initial-backup
received 19.0M stream in 0.320298429 seconds (59.4M/sec)
receiving incremental stream of filling/machine/szarotka/floppies@whiskas-supreme into tarta-zoot/floppies@whiskas-supreme
TIME        SENT   SNAPSHOT filling/machine/szarotka/floppies@whiskas-supreme
20:43:06    119M   filling/machine/szarotka/floppies@whiskas-supreme
received 133M stream in 1.998798670 seconds (66.7M/sec)
receiving incremental stream of filling/machine/szarotka/floppies@indices into tarta-zoot/floppies@indices
received 69.1K stream in 0.060070778 seconds (1.12M/sec)
nabijaczleweli@tarta:~/store/code/zfs$ sudo ./cmd/zfs/zfs send -i @indices filling/machine/szarotka/floppies@od-szafy | sudo ./cmd/zfs/zfs recv -ve tarta-zoot
receiving incremental stream of filling/machine/szarotka/floppies@od-szafy into tarta-zoot/floppies@od-szafy
received 88.0M stream in 1.097293428 seconds (80.2M/sec)
```

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – none apply
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Nine digits after the decimal is pretty ugly.  If you want exact values, I'd suggest we add the `-p` parsable option as was done for other commands to request this.  Then you could also print exact byte counts which would be useful for anyone trying to parse this.

**Comment by nabijaczleweli** [comment]
Yeah, I tend to agree, guess I wanted to exercise all the digits? (For no reason, ain't no device where those'd be remotely relevant. Not my decade.). Updated to use just two, which looks better and makes more sense:
```
skipping snapshot filling/machine/szarotka/floppies@od-szafy because it was created after the destination snapshot (indices)
skipping snapshot filling/machine/szarotka/floppies@chown-0:0 because it was created after the destination snapshot (indices)
full send of filling/machine/szarotka/floppies@initial-backup estimated size is 12.4M
send from @initial-backup to filling/machine/szarotka/floppies@whiskas-supreme estimated size is 108M
send from @whiskas-supreme to filling/machine/szarotka/floppies@indices estimated size is 52.6K
total estimated size is 120M
receiving full stream of filling/machine/szarotka/floppies@initial-backup into tarta-zoot/floppies@initial-backup
received 19.1M stream in 0.39 seconds (48.7M/sec)
receiving incremental stream of filling/machine/szarotka/floppies@whiskas-supreme into tarta-zoot/floppies@whiskas-supreme
TIME        SENT   SNAPSHOT filling/machine/szarotka/floppies@whiskas-supreme
06:22:09   56.9M   filling/machine/szarotka/floppies@whiskas-supreme
received 134M stream in 2.32 seconds (57.8M/sec)
receiving incremental stream of filling/machine/szarotka/floppies@indices into tarta-zoot/floppies@indices
received 70.6K stream in 0.05 seconds (1.32M/sec)
```

**Comment by behlendorf** [comment]
> I think the ideal would be to have a time pretty-printer as well, but, well

We do have `zfs_nicetime()` which could be used for this.  It'll give you the pretty time in either nanoseconds, microseconds, milliseconds, or seconds.  Whatever fits best in 5 digits (i.e. 300ns, 300us, 300ms, or 300s).  That would break anything parsing this output, but there's a decent chance changing it to a float will too.

**Comment by nabijaczleweli** [comment]
I was mostly thinking about something like "2:32:16.42 h" for 9136.42 seconds tbh. `zfs_nicenum()` will always return in seconds (except for when it returns in micro-/nanoseconds because something took no time because it was 0-sized, which is worse), and it's IMO worse/more crowded than the (new/)current "9136.42 seconds" format.
Plus, updating any reader to either parse as float/stop at the dot instead of ws is trivial (some might already do that OOB), but doing explicit units or time-formatting would be more trouble than is worth in that case I think.

**Comment by behlendorf** [comment]
Yes I agree, it's for all those reasons I didn't mention `zfs_nicetime()` initially.  We do have a very simple `secs_to_dhms()` function in `zpool_main.c` which could be moved to `libzutil` and extended for sub-second precision, but again I'm not sure it's actually desirable.  Sticking with just the two digits as you've done here seems preferable to me.

**Review by behlendorf — APPROVED** [review]

**Pull request merged**
