### PR TITLE
unbreak copy-builtin in 0.8.x

### PR DESCRIPTION
**Pull request by gyakovlev**
### Motivation and Context

acfc4944d0d6db114db9f2bb5401251c5bd767b6 broke `copy-builtin` in
release tarballs, because those do not contain `.gitignore` file.
so `copy-builtin` fails.

### Description

Adding `-f` to `rm` call will make it return `0` even if file does not exist.

### How Has This Been Tested?

tested `0.8.6` release tarball's `copy-builtin` with above change, it did not fail.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gyakovlev** [comment]
@veggiemike ^ FYI

**Comment by veggiemike** [comment]
Bugger.  Yeah, that was an oversight.  Agreed, -f should be added.

**Review by behlendorf — APPROVED** [review]

**Comment by behlendorf** [comment]
@gyakovlev would you mind rebasing this against the `zfs-0.8.7-staging` branch and updating the PR.

**Comment by gyakovlev** [comment]
@behlendorf done, opened https://github.com/openzfs/zfs/pull/11456

closing this one

**Pull request closed without merging**
