### PR TITLE
Linux 5.18 compat: __set_page_dirty_nobuffers replaced with filemap_dirty_folio

### PR DESCRIPTION
**Pull request by satmandu**
Upstream-commit: https://github.com/torvalds/linux/commit/6b1f86f8e9c7f9de7ca1cb987b2cf25e99b1ae3a
Authored by: Satadru Pramanik <satadru@gmail.com>
Closes: #13325

This tries to port from the page to the folio interface, which appears to be required for Kernel 5.18.

### Motivation and Context

This patch allows zfs to work correctly on 5.18-rc4.

Fixes: https://github.com/openzfs/zfs/issues/13325

### Description

This patch is largely cribbed from https://github.com/openzfs/zfs/commit/1c24bf966c373009f2be77438e8696aabf50a7e7 after looking at https://github.com/torvalds/linux/commit/6b1f86f8e9c7f9de7ca1cb987b2cf25e99b1ae3a

### How Has This Been Tested?

Have run this against 2.1.4 (with the other 5.8 patches from [zfs-2.1.5-staging](https://github.com/openzfs/zfs/tree/zfs-2.1.5-staging)) on 5.18-rc4 on two x86_64 machines running Ubuntu 22.04.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by satmandu** [comment]
Style question.... Should 
```
#if defined(HAVE_VFS_SET_PAGE_DIRTY_NOBUFFERS) || defined(HAVE_VFS_FILEMAP_DIRTY_FOLIO)
```
be changed to this to pass the checkstyle filter?
```
#if defined(HAVE_VFS_SET_PAGE_DIRTY_NOBUFFERS) || \
    defined(HAVE_VFS_FILEMAP_DIRTY_FOLIO)
```
?

**Comment by behlendorf** [comment]
@satmandu yes, that will sort out the style warning.  You can always run `make checkstyle` locally to check before updating the PR.

**Review by behlendorf — COMMENTED** [review]
We have one other caller of `__set_page_dirty_nobuffers()` in `zfs_putpage()`.  Right now it appears there's a wrapper function which maps it to `filemap_dirty_folio()` but we should switch it to the new folio interface.  There's no telling how long the kernel will keep that compatibility wrapper around, better to address it now.  Something like:

```c
#ifdef HAVE_VFS_FILEMAP_DIRTY_FOLIO
                filemap_dirty_folio(page_mapping(pp), page_folio(pp));
#else
                __set_page_dirty_nobuffers(pp);
#endif
```

**Comment by satmandu** [comment]
`make checkstyle` fails for me, but I'm not at all sure that's due to my doing...

**Comment by rincebrain** [comment]
It seems to be disgruntled that 496c02e0c0ee7e1957e9cf688894b758c81b7131 lacks a Signed-off-by.

**Comment by satmandu** [comment]
> It seems to be disgruntled that 496c02e0c0ee7e1957e9cf688894b758c81b7131 lacks a Signed-off-by.

Thanks.  I'll squash the commits.

**Comment by satmandu** [comment]
Shrunk the title of the commit message...

**Review by behlendorf — APPROVED** [review]
Looks good.  Thanks for  the PR.

**Review by tonyhutter — APPROVED** [review]

**Comment by ckane** [comment]
Thanks, I'm pretty sure I had been encountering this on 5.18 as well, and it wasn't clear that ZFS was possibly the culprit until I took a closer look today. Trying again with the latest code from master and will update with results.

**Comment by ckane** [comment]
Yep, this fixed it on my system (Arch w/ linux-mainline AUR kernel) too

**Pull request merged**
