### PR TITLE
Use _Noreturn (C11; GNU89) properly

### PR DESCRIPTION
**Pull request by alejandro-colomar**
A function that returns with no value is a different thing from a
function that doesn't return at all.  Those are two orthogonal
concepts, commonly confused.

pthread_create(3) expects a pointer to a start routine that has a
very precise prototype:

    void *(*start_routine)(void *);

Providing a different one is incorrect, and has only been working
because the ABIs happen to produce a compatible function for

    void (*incorrect)(void *);

And since it never returns, the return type isn't being used.  The
code has been using a cast to tell the compiler we know better.
It's been using 'void' instead of 'void *' because it never
returns a pointer, since it always calls pthread_exit(3) (or
similar).  However, 'noreturn' not only admits 'void' functions,
but any type of function.  And therefore, we can use the correct
function signature and just add 'noreturn' to mark it as never
returning.  Using it allows us to use 100% defined behavior as far
as ISO C is concerned, and so we don't risk finding an ABI that
silently produces a bug for the incorrect function signature.  The
correct signature for a non-returning start routine is:

    noreturn void *start_routine(void *);

This commit reverts:
a215c3e83445 "libzpool: kernel: silence unrelated-function-pointer cast warning"

Link: <https://github.com/openzfs/zfs/pull/13110#discussion_r808450136>
Link: <https://software.codidact.com/posts/285972>
Signed-off-by: Alejandro Colomar <alx.manpages@gmail.com>
Cc: @nabijaczleweli
Cc: @behlendorf

### Motivation and Context

A recent PR (https://github.com/openzfs/zfs/pull/13110) opened a discussion about the correctness of the code regarding function pointer casts.  While we concluded that it was probably defined behavior thanks to the ABI and to the fact that translation unit boundaries are opaque to the compiler, it's still not ideal to rely on the ABI.

### Description

Use C11 syntax to have a much more stable and portable solution.

### How Has This Been Tested?

I built the repository with `--enable-debug`.  Didn't run it or run tests, though.  CI, help me there :)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -
It shouldn't.
- [x] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv) -
Not sure about this one.  There are a few extern functions which have changed the prototype: `__thread_exit()` and `zk_thread_create()`.
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions). - AFAIK
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md). - Briefly
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied. - CI, run it for me, please.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
Maybe you prefer to use __attribute__((noreturn)) for compatibility with systems without <stdnoreturn.h>?

**Comment by alejandro-colomar** [comment]
Since I've seen the following CI error, I'm going to use `_Noreturn` instead, which is a real keyword, and requires no header file:

```

  CC      fs/zfs/spl/../os/linux/spl/spl-generic.o
In file included from ./include/zfs/os/linux/spl/sys/taskq.h:33:0,
                 from ./include/zfs/os/linux/spl/sys/kmem_cache.h:27,
                 from fs/zfs/spl/../os/linux/spl/spl-generic.c:30:
./include/zfs/os/linux/spl/sys/thread.h:31:10: fatal error: stdnoreturn.h: No such file or directory
 #include <stdnoreturn.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:288: recipe for target 'fs/zfs/spl/../os/linux/spl/spl-generic.o' failed
make[3]: *** [fs/zfs/spl/../os/linux/spl/spl-generic.o] Error 1
scripts/Makefile.build:550: recipe for target 'fs/zfs/spl' failed
make[2]: *** [fs/zfs/spl] Error 2
scripts/Makefile.build:550: recipe for target 'fs/zfs' failed
make[1]: *** [fs/zfs] Error 2
Makefile:1831: recipe for target 'fs' failed
make: *** [fs] Error 2
```

**Comment by alejandro-colomar** [comment]
Cc: @nabijaczleweli
Cc: @behlendorf

**Comment by alejandro-colomar** [comment]
Hmm, there's a deep problem here:

pthread_create(3) and kproc_kthread_add(9) expect a different start routine signature, but the same functions are being passed to both of them, which means one of them will get a pointer to a function different than what it expects.

```
int pthread_create(pthread_t *restrict thread,
                   const pthread_attr_t *restrict attr,
                   void *(*start_routine)(void *),
                   void *restrict arg);

int kproc_create(void (*func)(void *),
                   void *arg,
                   struct proc **newpp,
                   int flags,
                   int pages,
                   const char *fmt, ...);
```

**Comment by behlendorf** [comment]
Indeed.  Perhaps one way we clean this up is by adding a generic wrapper function which can be passed to `pthread_create()`.  We could pass it the function it needs to invoke and the args.  Not ideal, but it seems it would at least be 100% defined behavior.

**Comment by nabijaczleweli** [comment]
This is what I wanted to do [here](https://github.com/openzfs/zfs/pull/13110#discussion_r808404748) but decided against it because this is part of, seemingly, some precise stack depth limiting machinery – or does it only appear precise?

**Comment by behlendorf** [comment]
We have very limited stack depth on the kernel side (~16k), but this isn't really an issue when building the code in user space.  We can always bump up the stack size if needed in user space, just not in the kernel.  Still we do try and limit the stack in user space to make it more representative of the kernel environment when testing.  But since we're talking about the user space thread wrappers here, adding another stack frame would be fine.

**Comment by nabijaczleweli** [comment]
This is probably the diff you're looking for to round this out, applies to your HEAD:
```diff
diff --git a/include/sys/zfs_context.h b/include/sys/zfs_context.h
index 8430d5608..9d99388be 100644
--- a/include/sys/zfs_context.h
+++ b/include/sys/zfs_context.h
@@ -243,7 +243,7 @@ extern struct proc p0;
 
 #define	PS_NONE		-1
 
-extern kthread_t *zk_thread_create(void *(*func)(void *), void *arg,
+extern kthread_t *zk_thread_create(void (*func)(void *), void *arg,
     size_t stksize, int state);
 
 #define	issig(why)	(FALSE)
diff --git a/lib/libzpool/kernel.c b/lib/libzpool/kernel.c
index 864342a62..6b29d6d39 100644
--- a/lib/libzpool/kernel.c
+++ b/lib/libzpool/kernel.c
@@ -75,12 +75,28 @@ struct proc p0;
 #define	TS_STACK_MIN	MAX(PTHREAD_STACK_MIN, 32768)
 #define	TS_STACK_MAX	(256 * 1024)
 
+struct zk_thread_wrapper {
+	void (*func)(void *);
+	void *arg;
+};
+
+static void *
+zk_thread_wrapper(void *arg)
+{
+	struct zk_thread_wrapper ztw;
+	memcpy(&ztw, arg, sizeof (ztw));
+	free(arg);
+	ztw.func(ztw.arg);
+	return (NULL);
+}
+
 kthread_t *
-zk_thread_create(void *(*func)(void *), void *arg, size_t stksize, int state)
+zk_thread_create(void (*func)(void *), void *arg, size_t stksize, int state)
 {
 	pthread_attr_t attr;
 	pthread_t tid;
 	char *stkstr;
+	struct zk_thread_wrapper *ztw;
 	int detachstate = PTHREAD_CREATE_DETACHED;
 
 	VERIFY0(pthread_attr_init(&attr));
@@ -117,7 +133,10 @@ zk_thread_create(void *(*func)(void *), void *arg, size_t stksize, int state)
 	VERIFY0(pthread_attr_setstacksize(&attr, stksize));
 	VERIFY0(pthread_attr_setguardsize(&attr, PAGESIZE));
 
-	VERIFY0(pthread_create(&tid, &attr, func, arg));
+	VERIFY(ztw = malloc(sizeof (*ztw)));
+	ztw->func = func;
+	ztw->arg = arg;
+	VERIFY0(pthread_create(&tid, &attr, zk_thread_wrapper, ztw));
 	VERIFY0(pthread_attr_destroy(&attr));
 
 	return ((void *)(uintptr_t)tid);
```

**Comment by alejandro-colomar** [comment]
> +struct zk_thread_wrapper {
> +	void (*func)(void *);
> +	void *arg;
> +};
> +
> +static void *
> +zk_thread_wrapper(void *arg)
> +{
> +	struct zk_thread_wrapper ztw;
> +	memcpy(&ztw, arg, sizeof (ztw));
> +	free(arg);
> +	ztw.func(ztw.arg);
> +	return (NULL);
> +}
> +
>  kthread_t *
> -zk_thread_create(void *(*func)(void *), void *arg, size_t stksize, int state)
> +zk_thread_create(void (*func)(void *), void *arg, size_t stksize, int state)
>  {
>  	pthread_attr_t attr;
>  	pthread_t tid;
>  	char *stkstr;
> +	struct zk_thread_wrapper *ztw;
>  	int detachstate = PTHREAD_CREATE_DETACHED;
>  
>  	VERIFY0(pthread_attr_init(&attr));
> @@ -117,7 +133,10 @@ zk_thread_create(void *(*func)(void *), void *arg, size_t stksize, int state)
>  	VERIFY0(pthread_attr_setstacksize(&attr, stksize));
>  	VERIFY0(pthread_attr_setguardsize(&attr, PAGESIZE));
>  
> -	VERIFY0(pthread_create(&tid, &attr, func, arg));
> +	VERIFY(ztw = malloc(sizeof (*ztw)));
> +	ztw->func = func;
> +	ztw->arg = arg;
> +	VERIFY0(pthread_create(&tid, &attr, zk_thread_wrapper, ztw));


Do you really need to `malloc(3)`?  Why not just a local?

**Comment by nabijaczleweli** [comment]
Because the local lives until end of scope and we're literally starting a thread which outlives it?

**Comment by alejandro-colomar** [comment]
> Because the local lives until end of scope and we're starting a thread which outlives it?

Yup, I guessed that.  Just to be sure :)

**Comment by alejandro-colomar** [comment]
Do the failing tests make any sense to you?

This is supposed to not alter the behavior at all.  :/

**Comment by nabijaczleweli** [comment]
the freebsd one is expected and fixed in trunk, and the centos ones are Interesting to say the least, but I'm gonna assume it's an apt update failure (or whatever the fedora equivalent is) – conventional wisdom says rebase to kick over

**Comment by behlendorf** [comment]
That's surprising.  It appears after the change the `__thread_exit()` symbol isn't being included in the RPM packaging as a provided symbol.  Though clearly it's exported since it passed on the other Linux builders.

```
Error: Package: kmod-zfs-2.1.99-884_g1e4f7f7.el7.x86_64 (/kmod-zfs-2.1.99-884_g1e4f7f7.el7.x86_64)
           Requires: ksym(__thread_exit) = 0x00000000
```
http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20%28TEST%29/builds/19293/steps/shell_1/logs/install

We could just drop the `__thread_exit()` changes from the PR.

**Review by behlendorf — APPROVED** [review]
That'll work.  Thanks for the improvement!

**Comment by alejandro-colomar** [comment]
Huh, `__attribute__((noreturnn))` works but `_Noreturn` doesn't.  I think you should investigate that, there might be some build system problem.

**Comment by alejandro-colomar** [comment]
Should I rebase to restart the failing test?

**Comment by behlendorf** [comment]
Rebasing would restart the tests, but no need.  I went ahead and manually restarted the one which failed.

I'm not to concerned because it looks like more of an rpm packaging issue.  The change seemed to cause rpm to miss that symbol and not add dependency information for it to the kmod package, which resulted in the install failure.  The build itself looked fine.

**Comment by alejandro-colomar** [comment]
Okay.  Maybe we should report something to the rpm packaging system?  However, I have no idea how it works; Debian user here :-)

**Comment by behlendorf** [comment]
Probably, though I kind of suspect chasing corner case will be quite the time consuming diversion.  But if someone wants to take it on they're more than welcome!  For now, I'm going to go ahead and merge this as-is.

**Pull request merged**
