### PR TITLE
 zfs-2.3.0-rc4 patchset #16760 

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Initial proposed patchset for zfs-2.3.0-rc4.

### Description

Bug fixes, build fixes, ZTS updates.

### How Has This Been Tested?

Clean backports from master. Will be retested by the CI.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

### CODE REVIEW

**Review by amotin — APPROVED** [review]

**Comment by satmandu** [comment]
Could we get https://github.com/openzfs/zfs/pull/16770 in this as well??

**Comment by snajpa** [comment]
If https://github.com/openzfs/zfs/pull/16770 is going into rc4, then https://github.com/openzfs/zfs/pull/16817 should too, sorry about that :(

**Comment by AllKind** [comment]
@snajpa https://github.com/openzfs/zfs/pull/16770 is already in the 2.2.7 patchset, so you probably should comment there too.

**Comment by jlsalvador** [comment]
Tested 2.3.0-rc4 on Buildroot with GLIBC, MUSL, and UCLIBC. Everything seems to be working correctly! 👏

**Pull request merged**
