### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by binho1991**
### Motivation and Context

Compilation error when ZFS_DEBUG is not enabled.
### Description

zr_owner only exists when ZFS_DEBUG macro is enabled.
https://github.com/openzfs/zfs/blob/f2c027bd6a003ec5793f8716e6189c389c60f47a/module/zfs/zrlock.c#L52-L61
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by klebertarcisio** [comment]
Hi @behlendorf, thank you very much for the feedback.

Is it valid that ZFS_DEBUG is defined and NDEBUG is not defined? I think i compiled with ZFS_DEBUG defined and NDEBUG not defined.

If we look at lines 139, 140 and 141 this seems to be valid.

https://github.com/openzfs/zfs/blob/772c69d230b34bab1aaab800b1f95010e237862f/include/os/freebsd/spl/sys/ccompile.h#L122-L141

**Comment by behlendorf** [comment]
> Is it valid that ZFS_DEBUG is not defined and NDEBUG is not defined?

@klebertarcisio the original intent was that `ZFS_DEBUG == !NDEBUG`, but it looks like you found at least one case where that's not handled quite right.  We've been gradually removing the remaining places where NDEBUG is used, then we can just use ZFS_DEBUG internally.  The best fix for this would probably be to finish that work, it looks like there are only a couple places left.

@mattmacy may know offhand if this would cause any complications on FreeBSD.  For Linux, there shouldn't be any issue.  And it would be nice to remove this source of confusion.

**Comment by mattmacy** [comment]
@klebertarcisio Does this still apply with all the intervening churn?

**Comment by behlendorf** [comment]
Thanks for suggesting this change, however I'm going to close this PR out because I believe what we really want to do here is use `ZFS_DEBUG` consistently throughout the code base and remove the usage of `NDEBUG`.

**Pull request closed without merging**
