### PR TITLE
Modernise all (most) remaining .TH manpages

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
What if manpages, but stronger?

### Description
See individual messages for what happened beside that.

One thing that might be of particular import is that I moved
> Developed at Lawrence Livermore National Laboratory (LLNL\-CODE\-403049)

in zed.8 from the trailer to the comment at the top.
Not sure what the laboratory's requirements on this stanza are.

These are left:
* man/man5/spl-module-parameters.5: I don't think most (any?) of these are actually correct. `spl_kmem_cache_obj_per_slab_min` and `spl_kmem_cache_expire` return just that page and a single comment – is it time to yeet it?
* man/man5/zfs-module-parameters.5: way too long for today
* man/man5/zpool-features.5: likewise
* man/man8/mount.zfs.8: #12111
* man/man8/zfs-mount-generator.8.in: I touch it in #11917, will modernise later

### How Has This Been Tested?
Looked at'em

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
Here's a fun test: `find man -type f -name '*[1-9]*' -exec mandoc -Tlint {} \+`
I'm not sure if any of that relates to your changes, it's quite a list though 😅

**Comment by nabijaczleweli** [comment]
I was about to say that it's weird and it passes mancheck for me, but apparently mancheck is only run on man8 :v

**Comment by nabijaczleweli** [comment]
Fixed my new pages (mostly minor things that didn't affect rendered output much if at all, it's not as bad as you'd think from the error log, heh) and widened mancheck to catch all of man (and the test runner), seems that all other pages were already clean; thanks for the heads-up!

**Comment by behlendorf** [comment]
It looks like the `mancheck` target is setting `-Werror` as well and only checking for errors.  Is seems there's a bunch of additional STYLE and WARNING issues reported as well.  Well, one step at a time it'll be nice to check all the manages for ERRORS.

**Comment by nabijaczleweli** [comment]
Ah, hm. Good point; I'll beat down the warnings down to the default level on the all-new pages, we can drop the minimum level on the existing ones later (but it's gonna be very dirty, considering the main WARNING is "new sentence, new line").

**Comment by nabijaczleweli** [comment]
Okay, beside outdated mandoc.db and referenced manual not found, these are the WARNINGs that remain:
```
mandoc: man/man1/zhack.1:35:2: WARNING: sections out of conventional order: Sh SYNOPSIS
mandoc: man/man8/zinject.8:38:2: WARNING: sections out of conventional order: Sh SYNOPSIS
```
Since they use a subcommand-forward layout. I've added them to the head comments, and will make use of those in an improved variant of mancheck.

**Comment by freqlabs** [comment]
Please s/sexoin/section/ in one of the commit messages.

**Comment by nabijaczleweli** [comment]
Done

**Review by behlendorf — APPROVED** [review]
I've read through the updated pages and they look good.  Thanks for modernizing these, and the other bit of cleanup mixed in.  I'll get this merged so you can rebase the second round of fixes on these.

**Pull request closed without merging**
