### PR TITLE
Fix tracepoints definitions for Linux 6.10

### PR DESCRIPTION
**Pull request by snajpa**
### Motivation and Context

Should fix https://github.com/openzfs/zfs/issues/16475

### Description
New kernels define `__assign_str()` with only 1 parameter, using the source specified when defining the string field of a tracepoint.

There's one commit of a configure test from @tonyhutter made from this https://github.com/openzfs/zfs/issues/16475#issuecomment-2311100310 comment, it's without a sign-off, so that will probably need @tonyhutter's ack.

Not sure about the best placement (or name) for `__assign_str_impl`, I've put it into `types.h` as that was included in `trace_dbuf.h` so it was the simplest to put it in there and make sure it's included in `trace_dbgmsg.h` too.

### How Has This Been Tested?
Changed META to make tracing available + tested on 6.10, 6.9, 6.8, 5.10, 4.19 kernels.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by snajpa** [comment]
I have a related question to these particular tracepoint definitions - are they even necessary at all? The kernel supports dynamic tracing, a function can be traced at its offset dynamically, with no preexisting static definitions.

Personally, I've never used the predefined probes, I'm always using the dynamic probes on function entry/exit, which require no code to support them from the ZFS side.

Are there any users of the static tracepoints at all? Does it still make sense to carry the definitions around?

I have no idea honestly.

**Review by tonyhutter — APPROVED** [review]

**Comment by tonyhutter** [comment]
@snajpa I don't know who uses them either...

**Comment by wmmur** [comment]
@robn planned to remove DECLARE_EVENT_CLASS, but @behlendorf decided not to remove DECLARE_EVENT_CLASS. If compilation for kernel linux-rt worked in <=zfs-2.2.6 as it does in zfs-master, no one would notice this error.

**Comment by behlendorf** [comment]
> Are there any users of the static tracepoints at all? Does it still make sense to carry the definitions around?

That's a good point.  We've been carrying this code debugging functionality around for a while, and from what I can tell it's lightly used at best.  Let's go ahead and merge this compatibility fix to resolve the immediate build issue.  Then we can revisit removing it entirely if the consensus is nobody will miss this functionality.

**Review by behlendorf — APPROVED** [review]

**Comment by intelfx** [comment]
Can this be backported onto 2.2.x please?

**Pull request merged**
