### PR TITLE
zfs-2.0-release wishlist

### PR DESCRIPTION
**Pull request by freqlabs**
Staging PR for things I'd like to see in the next RC

### CODE REVIEW

**Comment by mjguzik** [comment]
Every single FreeBSD "catch up" commit is necessary to keep zfs even building on that platform.

**Comment by freqlabs** [comment]
Yeah that's why I changed my mind and decided to batch this all into one PR instead of separate PRs. Now I'm busy backporting commits that don't apply cleanly so this PR is a bit nonsense at the moment.

**Comment by freqlabs** [comment]
In the end I abandoned everything that didn't cherry-pick cleanly.

**Comment by behlendorf** [comment]
Closing.  I've pulled these commits in to the zfs-2.0-release branch for the next release candidate.

**Pull request closed without merging**
