### PR TITLE
DRAFT: Potential workaround for #11679

### PR DESCRIPTION
**Pull request by rincebrain**
Sometimes with encryption enabled, (notably during recv), particularly on
slower systems, you could wind up with dbuf_read and dbuf_write interweaving
such that the bonus buffer for a dnode wound up with its buffers temporarily
freed in dbuf_write while dbuf_read was in the midst of using them.

I believe the fact that that can happen and that the hash_lock is not
sufficient to stop that is a bug, but for now, taking the buf's
b_evict_lock ensures if we enter dbuf_write after dbuf_read, when it
inevitably travels down the arc_release codepath, it'll block until
we're out of arc_buf_fill.

PS: I'm not convinced this actually resolves the race entirely so much as
makes it much more impractical to trigger, since arc_write will happily
clobber those buffers if we could weave things such that we entered dbuf_write,
got past dbuf_release_bp, then dbuf_read started, and we happily go barreling
along into arc_write's destructive hands. But locking there is somewhat delicate,
since you'd need to resolve it in arc_write_done or dbuf_write_done, and there's
a number of other mutexes in flight between here and there.

I haven't been able to make it happen on purpose yet, so I might be happy
enough with recommending this as a mitigation until, as I said, someone runs
down why, precisely, you can end up with this case uniquely unhelped by
existing locking.

### Motivation and Context
#11679

### Description
Above.

### How Has This Been Tested?
Handed it to the Github runners hours ago, it passed sanity and functional while failing checkstyle.

Been running it in a loop on my reproducer sparc64 box, and on top of my use-sleeps-in-the-code-to-reproduce branch on x86 and aarch64. (All Linux; I admit I did not think to leave FreeBSD running in a loop, as the only report I've seen of it happening there is from me, trying it.)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by lheckemann** [comment]
I'm now running this on the machine that exhibited the issue most often. Will let you know if it helps :)

**Comment by lheckemann** [comment]
This is working reliably for me so far, even if it just pushes the corner case further into the corner.

**Comment by lheckemann** [comment]
First time I've had an issue since applying this patch:

```
Feb 05 15:10:08 madeye kernel: VERIFY3(0 == dmu_bonus_hold_by_dnode(dn, FTAG, &db, flags)) failed (0 == 5)
Feb 05 15:10:08 madeye kernel: PANIC at dmu_recv.c:1798:receive_object()
Feb 05 15:10:08 madeye kernel: Showing stack for process 687465
Feb 05 15:10:08 madeye kernel: CPU: 1 PID: 687465 Comm: receive_writer Tainted: P          IO      5.10.91 #1-NixOS
Feb 05 15:10:08 madeye kernel: Hardware name: FUJITSU D3402-B1/D3402-B1, BIOS V5.0.0.11 R1.13.0 for D3402-B1x                    02/19/2016
Feb 05 15:10:08 madeye kernel: Call Trace:
Feb 05 15:10:08 madeye kernel:  dump_stack+0x6b/0x83
Feb 05 15:10:08 madeye kernel:  spl_panic+0xd4/0xfc [spl]
Feb 05 15:10:08 madeye kernel:  ? dbuf_rele_and_unlock+0x4a7/0x660 [zfs]
Feb 05 15:10:08 madeye kernel:  ? dbuf_read+0x114/0x5d0 [zfs]
Feb 05 15:10:08 madeye kernel:  ? dnode_hold_impl+0x4e9/0xef0 [zfs]
Feb 05 15:10:08 madeye kernel:  ? _cond_resched+0x16/0x40
Feb 05 15:10:08 madeye kernel:  ? dnode_rele_and_unlock+0x5c/0xc0 [zfs]
Feb 05 15:10:08 madeye kernel:  receive_object+0xa74/0xc80 [zfs]
Feb 05 15:10:08 madeye kernel:  ? dmu_object_next+0xd6/0x120 [zfs]
Feb 05 15:10:08 madeye kernel:  ? dnode_rele_and_unlock+0x5c/0xc0 [zfs]
Feb 05 15:10:08 madeye kernel:  ? receive_freeobjects+0x95/0xf0 [zfs]
Feb 05 15:10:08 madeye kernel:  ? _cond_resched+0x16/0x40
Feb 05 15:10:08 madeye kernel:  receive_writer_thread+0x1cc/0xad0 [zfs]
Feb 05 15:10:08 madeye kernel:  ? set_next_entity+0x70/0xb0
Feb 05 15:10:08 madeye kernel:  ? set_next_task_fair+0x6b/0xa0
Feb 05 15:10:08 madeye kernel:  ? set_user_nice.part.0+0x140/0x240
Feb 05 15:10:08 madeye kernel:  ? receive_process_write_record+0x160/0x160 [zfs]
Feb 05 15:10:08 madeye kernel:  ? thread_generic_wrapper+0x6f/0x80 [spl]
Feb 05 15:10:08 madeye kernel:  thread_generic_wrapper+0x6f/0x80 [spl]
Feb 05 15:10:08 madeye kernel:  ? __thread_exit+0x20/0x20 [spl]
Feb 05 15:10:08 madeye kernel:  kthread+0x11b/0x140
Feb 05 15:10:08 madeye kernel:  ? __kthread_bind_mask+0x60/0x60
Feb 05 15:10:08 madeye kernel:  ret_from_fork+0x22/0x30
```

**Comment by rincebrain** [comment]
Hm, someone also  reported something similar in #11679, though they could trigger it very reliably on the same dataset send/recv every time - can you do that too, do you know, or is it a rare race loss?

I've not yet found a way to reproduce it on my end. :/

**Pull request closed without merging**
