### PR TITLE
zfs-2.2.3 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Support 6.7 kernel and various other fixes.

### Description
Proposed patchset for zfs-2.2.3

### How Has This Been Tested?
ZTS will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by mmatuska** [comment]
Please backport 07e95b4670dc421ec726a2b4efa97a22fe572005 (#15716), it fixes FreeBSD users space build after #15662

**Comment by tonyhutter** [comment]
@mmatuska thanks for that!  I included it in my latest push.

**Comment by tonyhutter** [comment]
Looks like everything is passing except some FreeBSD block cloning tests (http://build.openzfs.org/builders/FreeBSD%20stable%2F13%20amd64%20%28TEST%29/builds/1548).  I'll see if I can reproduce those failures in a VM.

**Comment by Vlad1mir-D** [comment]
May I ask to also include #15842?
Thanks for considering!

**Comment by tonyhutter** [comment]
@Vlad1mir-D yes, we'll pull that in after it's merged to master.

**Comment by Vlad1mir-D** [comment]
> @Vlad1mir-D yes, we'll pull that in after it's merged to master.

Thanks a lot!

**Comment by usaleem-ix** [comment]
@tonyhutter can you please include https://github.com/openzfs/zfs/pull/15843?

**Comment by shumvgolove** [comment]
*another request*

May I ask to consider including https://github.com/openzfs/zfs/pull/15584? I'll understand if this out of scope of this minor version bump 🫠

Thanks!

**Comment by mmatuska** [comment]
The newly posted #15874 is an important BRT fix as well

**Comment by mmatuska** [comment]
Please note #15883 was opened as well

**Comment by Vlad1mir-D** [comment]
2.2.3 is going to be such a great!

**Comment by tonyhutter** [comment]
@mmatuska thanks, I'll pull those two in once they're merged.

**Comment by tonyhutter** [comment]
All the builders are failing `cp_files_002_pos`.  I'm looking into it.

**Comment by tonyhutter** [comment]
> All the builders are failing cp_files_002_pos

It was failing because zfs_bclone_enabled=0 by default on the 2.2.x branch.  I just added a commit to enable it when running the tests.

**Review by behlendorf — APPROVED** [review]

**Comment by Vlad1mir-D** [comment]
Release! Release! :clap:

**Comment by tonyhutter** [comment]
Looks like we're passing on everything except FreeBSD, which is failing on the block cloning tests:
```
Tests with results other than PASS that are unexpected:
    FAIL bclone/bclone_crossfs_data (expected PASS)
    FAIL bclone/bclone_diffprops_all (expected PASS)
    FAIL bclone/bclone_diffprops_checksum (expected PASS)
    FAIL bclone/bclone_diffprops_compress (expected PASS)
    FAIL bclone/bclone_diffprops_copies (expected PASS)
    FAIL bclone/bclone_diffprops_recordsize (expected PASS)
    FAIL bclone/bclone_prop_sync (expected PASS)
    FAIL bclone/bclone_samefs_data (expected PASS)
    FAIL block_cloning/block_cloning_clone_mmap_cached (expected PASS)
    FAIL block_cloning/block_cloning_clone_mmap_write (expected PASS)
    FAIL block_cloning/block_cloning_copyfilerange (expected PASS)
    FAIL block_cloning/block_cloning_copyfilerange_cross_dataset (expected PASS)
    FAIL block_cloning/block_cloning_copyfilerange_fallback (expected PASS)
    FAIL block_cloning/block_cloning_copyfilerange_partial (expected PASS)
    FAIL block_cloning/block_cloning_cross_enc_dataset (expected PASS)
    FAIL block_cloning/block_cloning_lwb_buffer_overflow (expected PASS)
    FAIL block_cloning/block_cloning_replay (expected PASS)
    FAIL block_cloning/block_cloning_replay_encrypted (expected PASS)
```
https://build.openzfs.org/builders/FreeBSD%20stable%2F13%20amd64%20%28TEST%29/builds/1584

**Comment by tonyhutter** [comment]
Released: https://github.com/openzfs/zfs/releases/tag/zfs-2.2.3

**Pull request merged**
