### PR TITLE
Linux 6.11 compatibility

### LINKED ISSUE #16396: Kernel 6.11.0-rc1 ‘struct request_queue’ has no member named ‘backing_dev_info’
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| Noble/24.04
Kernel Version	| 6.11.0-rc1
Architecture	| x86_64
OpenZFS Version	| 2.2.4

### Describe the problem you're observing
Failure to build 2.2.x on Kernel 6.11.0-rc1.

### Include any warning/errors/backtraces from the system logs

Using my own build of 2.2.4 plus patches (to almost get to 2.2.5) I see this:
```
In file included from /var/lib/dkms/zfs/2.2.5~rc7/build/include/os/linux/spl/sys/uio.h:31,
                 from /var/lib/dkms/zfs/2.2.5~rc7/build/include/os/linux/spl/sys/sunddi.h:28,
                 from /var/lib/dkms/zfs/2.2.5~rc7/build/module/os/linux/spl/spl-generic.c:42:
/var/lib/dkms/zfs/2.2.5~rc7/build/include/os/linux/kernel/linux/blkdev_compat.h: In function ‘blk_queue_set_write_cache’:
/var/lib/dkms/zfs/2.2.5~rc7/build/include/os/linux/kernel/linux/blkdev_compat.h:93:2: error: #error "Unsupported kernel"
   93 | #error "Unsupported kernel"
      |  ^~~~~
/var/lib/dkms/zfs/2.2.5~rc7/build/include/os/linux/kernel/linux/blkdev_compat.h: In function ‘blk_queue_set_read_ahead’:
/var/lib/dkms/zfs/2.2.5~rc7/build/include/os/linux/kernel/linux/blkdev_compat.h:105:10: error: ‘struct request_queue’ has no member named ‘backing_dev_info’
  105 |         q->backing_dev_info.ra_pages = ra_pages;
      |          ^~
```

I suspect that this is, at a minimum, due to changes from the following commits:

https://github.com/torvalds/linux/commit/b9947297d00b9c75b271db88165e39c0208bec2e
https://github.com/torvalds/linux/commit/73781b3b81e76583708a652c853d54d03dce031d

### PR DESCRIPTION
**Pull request by robn**
### Motivation and Context

One must imagine Sisyphus happy.

Closes #16396.

### Description

See individual commits.

Note that most of this is applying block queue API changes to zvol. However, since the code is getting very complex, I've done a bit of cleanup in a way that will change when and how some queue settings are applied. That has the potential to break things that already work on older kernels. I doubt any fallout will be significant, but do take care on review and testing.

### How Has This Been Tested?

Compiled and passed basic sanity check (create, fio, export, import, scrub, unload) on kernels:

- 4.9.337
- 4.14.336
- 5.10.217
- 6.1.94
- 6.4.16
- 6.6.31
- 6.8.10
- 6.9.1
- 6.10.0-rc1
- 6.11.0-rc1

Full ZTS run on 6.11.0-rc1 currently in progress; should be finished by the morning. I'll update this post when its done.

Update: test suite passed (within normal flakiness bars of my setup).

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by tonyhutter — APPROVED** [review]
Thanks @robn, I was able to build this against 6.11rc1 without issue.

> One must imagine Sisyphus happy.

:laughing: :laughing: :laughing:

**Comment by satmandu** [comment]
@robn I was also able to build this on top of the 2.2.5 patchset in https://github.com/openzfs/zfs/pull/16359 against 6.11.0-rc1 but I'm seeing some memcpy messages about `module/zfs/zfs_log.c` in dmesg when booted on 6.11-rc1 but not 6.10.0. I have sent you an email about it just in case this is specific to how I'm building this.

**Comment by satmandu** [comment]
When I build this against the [zfs-2.2.5 patchset ](https://github.com/openzfs/zfs/pull/16359) I see memcpy warnings in the dmesg on 6.11.0-rc1:
```
sudo dmesg | grep memcpy
[   29.145783] memcpy: detected field-spanning write (size 28) of single field "xattrstart" at /var/lib/dkms/zfs/2.2.5~rc12/build/module/zfs/zfs_log.c:817 (size 0)
[   29.784994] memcpy: detected field-spanning write (size 15) of single field "(char *)(lr + 1)" at /var/lib/dkms/zfs/2.2.5~rc12/build/module/zfs/zfs_log.c:514 (size 0)
[   29.879852] memcpy: detected field-spanning write (size 82) of single field "(char *)(lr + 1) + snamesize" at /var/lib/dkms/zfs/2.2.5~rc12/build/module/zfs/zfs_log.c:515 (size 0)
[   30.276174] memcpy: detected field-spanning write (size 82) of single field "lr + 1" at /var/lib/dkms/zfs/2.2.5~rc12/build/module/zfs/zfs_log.c:425 (size 0)
[   40.155294] memcpy: detected field-spanning write (size 8) of single field "lr + 1" at /var/lib/dkms/zfs/2.2.5~rc12/build/module/zfs/zfs_log.c:461 (size 0)
[   49.231905] memcpy: detected field-spanning write (size 3) of single field "(char *)(lr + 1)" at /var/lib/dkms/zfs/2.2.5~rc12/build/module/zfs/zfs_log.c:593 (size 0)
[   49.234481] memcpy: detected field-spanning write (size 3) of single field "(char *)(lr + 1) + snamesize" at /var/lib/dkms/zfs/2.2.5~rc12/build/module/zfs/zfs_log.c:594 (size 0)
```

**Comment by robn** [comment]
Yeah, I saw these too in the ZTS run. As far as I can tell they're part of the kernel FORTIFY stuff; we're `memcpy()`'ing into a region that the compiler can't prove is big enough. Though 6.10 had this check as well, and I don't recall it making noise, so maybe there's something deeper (like, does the kernel now enable FORTIFY for rc builds?).

I suggest they're probably worth looking into, but separately - they're static analysis warnings, and need to be assessed and fixed or silenced as appropriate. They're not part of this patch set _as such_.

**Comment by robn** [comment]
I understand what the warnings are about now.

When built with CONFIG_FORTIFY_SOURCE, 6.11 is checking that the destination for memcpy has enough room. The various lr_XX_t structs usually have extra allocation and data after them, but this isn't visible to the compiler, so it reports the target memory regions as too small.

I have a couple of prototype patches to address this. Mostly, it's adding flex arrays to structs that have an extra allocation after them, but some rework is required for lr_create_t and lr_rename_t, as Clang doesn't support flex arrays anywhere but at end of struct. There's also some code change required, because so many places do raw pointer math to get past the end of struct, and that doesn't always work out exactly the same with the necessary type changes.

Fortunately there's no actual bugs (assuming our existing math is right, which I assume it is), it's just log noise. Still needs fixing to avoid bug reports (and also a little extra rigor doesn't hurt), but no real issue here.

Hopefully I can post a patch that isn't too horrible in the next few days.

**Comment by greg-hydrogen** [comment]
I am getting an error when trying to compile with this patch on fedora 39
make[7]: *** No rule to make target '/tmp/zfs-build-greg-EkU79TuP/BUILD/zfs-kmod-2.2.99/_kmod_build_6.11.0-rc1/module/os/linux/spl/spl-atomic.o', needed by '/tmp/zfs-build-greg-EkU79TuP/BUILD/zfs-kmod-2.2.99/_kmod_build_6.11.0-rc1/module/spl.o'.  Stop

**Comment by ascendbeing** [comment]
I just tried this patch set. I used 6.11rc2, never tried rc1.
When trying to power off my PC, it's unresponsive. It's off the network but it's not letting me do magic sysrq s u b to safely shutdown. And it's not shutting down further if I press the button etc.
So @robn maybe take a quick look over if 6.11rc2 changed anything of note? Lijus made some particular comments in the release snnounce that indicate something like that could have been done (removing "noise").
I have been using HEAD with 6.10. It powered off fine there with gentoo and xanmod patch sets. Going to have to not use this one until it's matured a bit.

**Comment by satmandu** [comment]
> I just tried this patch set. I used 6.11rc2, never tried rc1. When trying to power off my PC, it's unresponsive.

I have had success using this patch with both 6.11.0-rc1 and 6.11.0-rc2 (using my own locally built kernels on x86_64 machines) using Ubuntu 24.04, with my own customized release which is the 2.2.5-staging PR with this PR on top of it: https://launchpad.net/~satadru-umich/+archive/ubuntu/zfs-experimental/

I am not having problems with a shutdown. Reboots are working just fine for me.

**Comment by ascendbeing** [comment]
> I have had success using this patch with both 6.11.0-rc1 and 6.11.0-rc2 (using my own locally built kernels on x86_64 machines) using Ubuntu 24.04, with my own customized release which is the 2.2.5-staging PR with this PR on top of it: 
> I am not having problems with a shutdown. Reboots are working just fine for me
I guess I'll have to try what you did except I'll base it on zfs-2.2.5-hutter. I didn't think to do this because the 6.10 patch set just worked.

**Comment by robn** [comment]
@ascendbeing any interesting console output when this happens? What if you export the pool then unload the zfs module before reboot?

I built against -rc2 this morning. My very first bench check run suspended the pool during scrub, but half a dozen runs since have been fine. I don't really trust my bench check for this, it is .. quirky, and this isn't unheard of behaviour for it. But, coincidences and all that.

I'm yet to self-review this PR, but I'll do it soon, and review the rc1->rc2 changes at the same time.

**Comment by ascendbeing** [comment]
> @ascendbeing any interesting console output when this happens? What if you export the pool then unload the zfs module before reboot?
> 
I have 3 pools. My rootfs being one of them. I am using openrc not systemd so if there's any mechanism short of installing systemd to grab the output (I use metalog I think? with stock config basically), I'm willing to try it.

What specifically is happening is I issue a poweroff command and then instead of fully shutting down, monitor turns off and won't turn back on, and PC won't turn off, won't respond to magic sysrq (I have it 0x1 enabled), only way to turn it off is hard power off. Doesn't respond to additional button presses, no network connectivity.

**Comment by wmmur** [comment]
since kernel linux 6.10.0 there has been a change of #define __assign_str(dst, src) /* kernel linux <6.10.x*/ to:
#define __assign_str(dst) /* kernel linux >=6.10.0*/ in the file kernel linux
"include/trace/stages/stage6_event_callback.h". this change affects:
"zfs-2.2.5/include/os/linux/zfs/sys/trace_dbgmsg.h" and on 
"zfs-2.2.5/include/os/linux/zfs/sys/trace_dbuf
.h"
 this prevents compilation of linux kernel >=6.10.x on Debian.

**Comment by robn** [comment]
@ascendbeing I mean, your system logs the kernel messages somewhere presumably?

Not much we can do to debug this without a console. From your description that's getting extremely late in the shutdown process, to the extent that the keyboard handler can't invoke sysrq operations? A serial console might be the go.

I'm not saying its not OpenZFS at fault, but it would be extremely low-level, like, it hasn't released some resource somewhere. I can't off the top of my head think what that would be.

**Comment by robn** [comment]
@wmmur you've already opened #16433 about this. This PR is about 6.11 compatibility on the master branch, not about 6.10 or 2.2.5. If you've got a failing build with this PR against a 6.11-rc kernel, please provide more information. Otherwise I suggest its probably off-topic.

**Comment by wmmur** [comment]
I understand, but the problem is related to linux kernel 6.11.x. while reviewing the 6.11.rc kernel code (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/trace/stages/stage6_event_callback.h) I found a change, which also appeared in kernel linux 6.10.
3 and prevents kernel compilation! I believe this is important information for zfs compatibility with Linux kernel 6.11.x

**Comment by robn** [comment]
I understand, however, I'm definitely able to build on 6.11-rc2, and that file has not changed on the

**Comment by robn** [comment]
@wmmur I understand, however this PR is building fine for me on 6.11-rc2 and that file on the 6.11 branch has not changed since May. So clearly there's more going on, and its probably the same thing that is causing your 6.10 build to fail too. So, unless you have new information specific to 6.11, lets just keep it over there for the moment, otherwise we'll end up with bits of conversation in both places, which gets confusing.

**Comment by ascendbeing** [comment]
>I can't off the top of my head think what that would be.

I recently added "reboot=efi,warm mce=bootlog" to my boot arguments. Shuts down fine on 6.10. I also have power profiles daemon broken(crashes on startup somehow) if that matters.

I have a raspberry 3b if that can be used to do stuff like acquire really late messages etc. or I could connect via 2.5GbE Ethernet if that works. not to pcie or tb, just to another 2.5GbE port 

If I have to I can snapshot the rootfs and install systemd

**Comment by robn** [comment]
@ascendbeing sorry, you've got a lot more going on there than I know anything about, so I'm not really able to help much more. Divide and conquer is the game from here; try to find out if OpenZFS is the cause or something else.

(With the root on OpenZFS, if it were me I'd be trying to set up a live USB with this kernel and try to reproduce the situation that way, where there's a reasonable chance I can unload `zfs.ko` safely while the system is still up. But any of your ideas might work if you know how to do them).

**Comment by satmandu** [comment]
Using this patch on top of 2.2.5, things are looking fine for me with kernel 6.11.0-rc3 on both Ubuntu 24.04 and Ubuntu 24.10/dev.

**Comment by ascendbeing** [comment]
@robn The crash on shutdown doesn't occur on 6.10. It happens on HEAD and zfs-2.2.5-hutter w/ original version patch when used with 6.11. The original version of this patch doesn't affect shutting down with 6.10. Probably only with rootfs.

**Comment by robn** [comment]
@ascendbeing yep, if you can find out anything at all I can look into it, but right now its very much looking like something strange in your particular setup.

If its useful, here's this patch series atop the released 2.2.5 tag: https://github.com/robn/zfs/commits/linux-6.11-compat-2.2.5/. I've compiled it but not run it, ymmv.

**Comment by wmmur** [comment]
@robn  as of 2020 there is an unresolved issue #11097 "FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol " in kernel-rt. for 4 years, the only solution has been to modify CDDL->GPL in the META file. this solution worked until kernel-6.10.0 because the #define __assign_str(dst,src) macro was not fixed in zfs-2.2.5 -
> #define __assign_str(dst). if you cannot solve the source of the problem, i.e. #11097 "FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol " in kernel-rt, then fix the macro #define __assign_str(dst,src) -> #define __assign_str (dst).

**Comment by robn** [comment]
@wmmur I already said that your build issue is unrelated to this PR. Please stop.

**Review by behlendorf — APPROVED** [review]
Looks good.  Thanks for pushing this boulder a little bit father!

**Comment by ascendbeing** [comment]
@robn just gonna leave you and all a thank you because I can report (over last few days I've confirmed, w/ final release) that 6.11 reboot hang is gone. My configuration has drifted a good deal, but I had tried changing my .config kinda radically, and now it just works.

**Comment by robn** [comment]
@ascendbeing well I'm glad to hear it!

**Comment by ishitatsuyuki** [comment]
Did this miss a META update? I'm seeing

```
configure:20826: error: 
        *** Cannot build against kernel version 6.11.0-arch1-1.
        *** The maximum supported kernel version is 6.10.
```

**Comment by behlendorf** [comment]
There are still [some areas](https://github.com/openzfs/zfs/issues/16541) which need to be wrapped up for full 6.11 support.  We'll bump the META version once everything is integrated and tested with the final 6.11 release kernel.

**Pull request closed without merging**
