### PR TITLE
zfs-2.2.7 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
- Fully support 6.11 kernel
- Add QEMU github runners for testing

### Description
Proposed zfs-2.2.7 patchset.  Support 6.11 kernel and github QEMU runners.

### How Has This Been Tested?
Runners will test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by robn** [comment]
@tonyhutter I would like to include:
- #16335 #16692
- #16667
-  #16687 (still gated by `zfs_vdev_disk_classic=0`)
-  #16583 (6.11 support)

If you agree, I've pulled these in and fixed conflicts: https://github.com/robn/zfs/tree/zfs-2.2.7-staging

**Comment by tonyhutter** [comment]
@robn @AllKind thanks for the suggestions, I'll try to pull in as many as I can.

**Comment by tonyhutter** [comment]
I got everything in with the exception of these commits, which were either already merged or were related to a feature not present in 2.2.x:
2e4e09282 Fix dependency install on Debian 11 (#16683)
a9851ea3d Fix compile-time warnings caused by duplicate struct typedefs
efeb60b86 FreeBSD: ignore some includes when not building kernel
ab777f436 Return boolean_t in inline functions of lib/libspl/include/sys/uio.h
c59d5495f contrib/debian: add new manpages to installation list

@robn I eneded up "reverting the revert" (https://github.com/openzfs/zfs/pull/16720/commits/be0980f4552541612f8df8a929c76096dabb2237) to pull in https://github.com/openzfs/zfs/pull/16720/commits/ee40c21bd4a7f788de4bbe3b30805ddc731c804d

**Comment by robn** [comment]
@tonyhutter you don't need ee40c21 (orig aefc2da8a); it was only there until the proper fix went in, and was reverted in 3c650bec1.

You do need e7425ae62 to go with c25bf7a (orig 63bafe60e), or it'll corrupt memory pretty hard.

I'm not sure about be0980f; istr it made things worse for the classic IO submission (#15533), and since that's the default for 2.2 it seems likely that it's gonna immediately blow up again?

**Comment by tonyhutter** [comment]
@robn thanks, I just did the following in my latest push:

Remove:
 ee40c21 Workaround issue of Linux vdev_disk.c, (#16678)
 be0980f Reapply "Tune zio buffer caches and their alignments"

Add: 
 e7425ae6248db21240049df859630d5044dcd58a vdev_disk: move abd return and free off the interrupt handler

Can you double check that I have it correct now?

**Comment by robn** [comment]
@tonyhutter looks right to the naked eye, I'm putting it through some stress tests now.

**Review by robn — APPROVED** [review]
Yep, this should be good!

**Review by mcmilk — APPROVED** [review]
LGTM

**Comment by shodanshok** [comment]
Can I ask about https://github.com/openzfs/zfs/pull/15457 and https://github.com/openzfs/zfs/pull/15451 ?
Thanks.

**Comment by AllKind** [comment]
As far as I can tell "Read prefetched buffers from L2ARC https://github.com/openzfs/zfs/pull/15451" made it into 2.2.1.
But "Increase L2ARC write rate and headroom" 887a3c533b94a4b70075e310f15c45b9dee19410 didn't make it into a 2.2 release.

**Comment by Harry-Chen** [comment]
It doesn't build on freebsd now:

```
  --- zfs_prop.o ---
  /usr/home/zfs/zfs/module/zcommon/zfs_prop.c:1065:28: error: too many arguments provided to function-like macro invocation
   1065 | extern void simd_stat_init(void);
        |                            ^
  /usr/home/zfs/zfs/include/os/freebsd/spl/sys/simd.h:53:9: note: macro 'simd_stat_init' defined here
     53 | #define simd_stat_init()        do {} while (0)
        |         ^
  /usr/home/zfs/zfs/module/zcommon/zfs_prop.c:1066:28: error: too many arguments provided to function-like macro invocation
   1066 | extern void simd_stat_fini(void);
        |                            ^
  /usr/home/zfs/zfs/include/os/freebsd/spl/sys/simd.h:54:9: note: macro 'simd_stat_fini' defined here
     54 | #define simd_stat_fini()        do {} while (0)
        |         ^
  2 errors generated.
```

Looks like we need https://github.com/openzfs/zfs/commit/f9d4f1b480beaaa67373a9cdff6652cff255fea8 to fix.

**Comment by tonyhutter** [comment]
@shodanshok @AllKind @Harry-Chen I will pull those in.  Right now I'm trying to get the 6.12 kernel patches pulled in, but there's a lot of dependencies to resolve (like https://github.com/openzfs/zfs/pull/16479)

**Comment by robn** [comment]
@tonyhutter do you want a hand?

**Comment by tonyhutter** [comment]
@robn my latest push includes all the dependencies and builds locally.  We'll see what the test suite says...

**Comment by amotin** [comment]
@tonyhutter Since you seem to be not on Slack let me repeat here: In context of https://github.com/openzfs/zfs/pull/16720#issuecomment-2460466442 could you check that we don't have "Tune zio buffer caches and their alignments" there unless we disable the "classic" Linux vdev code?  I may be wrong, but seems like we may get broken combination.  Ron asked to not include `Reapply "Tune zio buffer caches and their alignments"`, but I don't see the revert commit here either.

**Comment by robn** [comment]
@tonyhutter guess it depends if your intent was to bump Linux min to 4.18 on this release? I was guessing not, but I don't know the rules for stable series. My offer was more, if you want 6.12 support, do you want me to work out a smaller patch set that also doesn't remove and reorganise a bunch of stuff?

I'll re-review my other stuff here too, mostly those userspace changes. I had not wanted them on 2.2.x mostly out of abundance of caution. istr there were some followup fixes too, I'll see what shakes out.

**Comment by tonyhutter** [comment]
@amotin thanks for catching that  - I unwittingly pulled 847c0fc35 in to resolve a merge conflict, but you're right it shouldn't be in there.  I'll take it out.

> guess it depends if your intent was to bump Linux min to 4.18 on this release? I was guessing not, but I don't know the rules for stable series. 

@robn I think it makes sense to pull in your big commit list and deprecate support for kernels < 4.18 on the 2.2.x branch.  We're not doing any automated testing against kernels < 4.18, so we can't really claim to support those older kernels.  Also, there's been so much churn with the deprecation commits, that if we don't pull them in now, we're just going to be fighting merge conflicts on future 2.2.x releases.  Sure, 2.3.x is coming soon, but we historically still do a few releases for the older branch even after the new branch is released.

**Review by 3dRikal — APPROVED** [review]
No issues here

**Comment by robn** [comment]
@tonyhutter You want 80645d658.

**Comment by tonyhutter** [comment]
@robn thanks, I included it in my latest push.

**Comment by mabod** [comment]
Do you want to add 6.12 compatibility with PR https://github.com/openzfs/zfs/pull/16793

**Comment by AllKind** [comment]
@tonyhutter I think it would be great to have 38c0324c0fb6b53286f00b7e36d1edca70d863d8 included, as a lot of 2.2 users experience the underlying issue.

**Comment by tonyhutter** [comment]
@mabod @AllKind @amotin thanks, I included those commits in my latest push.

**Comment by AllKind** [comment]
For full 6.11+ kernel compatibility I guess we'd also need https://github.com/openzfs/zfs/pull/16805 - once it's merged....

**Comment by snajpa** [comment]
And also please https://github.com/openzfs/zfs/pull/16817 because of the negative side effect of https://github.com/openzfs/zfs/pull/16770

**Comment by AllKind** [comment]
@allddd Already included: https://github.com/openzfs/zfs/pull/16720/commits/a6e1cd1838080424784517651dfa82e0a46e1506

**Comment by n0xena** [comment]
@allddd I run 2.3.0-rc3 on 6.12.1 right now - https://github.com/n0xena/archzfs/releases

**Comment by robn** [comment]
@tonyhutter great work, thank you :bow:

(release nit: min FreeBSD is 13.0-RELEASE).

**Comment by tuffnatty** [comment]
Thank you! On the release page, "Supported platforms" contradicts "Changes" on the matter of minimal supported FreeBSD version.

**Comment by tonyhutter** [comment]
@robn thanks, I updated the release notes page.

**Pull request merged**
