### PR TITLE
dbuf: Set dr_data when unoverriding after clone

### PR DESCRIPTION
**Pull request by amotin**
Block cloning normally creates dirty record without dr_data.  But if the block is read after cloning, it is moved into DB_CACHED state and receives the data buffer.  If after that we call dbuf_unoverride() to convert the dirty record into normal write, we should give it the data buffer from dbuf and release one.

Fixes: #15654 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by amotin** [comment]
@pjd @oromenahar @robn Please take a look.

**Review by oromenahar — APPROVED** [review]
based on your explanation and the code I think it makes sense. Thanks :)

**Comment by kevans91** [comment]
To be clear; is this just an accounting error, or would we have effectively dropped the dirtied contents on the floor (and retained the cloned block?) by not transitioning it into `dr_data`?

**Comment by amotin** [comment]
@kevans91 I haven't tried to reproduce it beyond the triggered assertion to observe other possible effects, but I'd think that missing arc_release() call may result in in-memory modification of snapshots, while empty `dr_data` in dirty record I'd expect to cause NULL-dereference during the transaction sync attempt, at least I don't see the NULL checks.

**Review by behlendorf — APPROVED** [review]

**Comment by robn** [comment]
@amotin well done!

**Pull request merged**
