### PR TITLE
[zfs-2.1.15] Misc backports 

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Backports to zfs-2.1.15-staging.

### Description
Backport some low-risk features and ZTS updates to zfs-2.1.15-staging.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by robn** [comment]
@tonyhutter do you want 6.6/6.7/6.8 compat patches for 2.1.15? I don't mind either way, I don't need them, but I'd be happy to backport them if you want them.

**Comment by tonyhutter** [comment]
@robn thanks, but I don't think we'll need them.  We really only build 2.1.x for EL7-9 now.

**Comment by rincebrain** [comment]
I would personally suggest including the compat patches, not because I particularly plan on using them myself directly, but because it'd be very helpful to be able to keep saying "can you try 2.1.x" a while longer if any more bugs in 2.2.x come up.

I'll also happily do the backports, if need be, I don't think any of them looked exciting, but that's my $0.02.

**Comment by tonyhutter** [comment]
@rincebrain it's ok with me if developers want to backport compat commits into `zfs-2.1.15-staging`.  They can just open a backport PR and we can get them approved pretty quick.  Note that don't build Fedora RPMs for 2.1.x anymore, so those users will need to build from source.

This particular PR is just a backport for some ZED and ZTS commits that I would like to see in zfs-2.1.15-staging.

**Comment by m-ueberall** [comment]
> @tonyhutter do you want 6.6/6.7/6.8 compat patches for 2.1.15? I don't mind either way, I don't need them, but I'd be happy to backport them if you want them.
Given that kernel 6.6 is a long-term support version, that'd be great! I'd imagine that this would allow a number of people to delay the switch from 2.1.x to 2.2.x if need be.

**Comment by AllKind** [comment]
I'd like to propose 9ce567c6fffd39e4bdf0cfe93f04a008de876b48 and 95b68eb693ba5b4785b260d592d8b5094f4c9576 again.
Since their inclusion into 2.2+ there have been no new error reports in that regard (except one, which is a follow up problem from the previous code).
Also someone else opened a PR for those already (can't find the now though) and @behlendorf proposed it for this upcoming 2.1 release.

**Comment by behlendorf** [comment]
@AllKind thanks for the reminder, these have already been included in the [staging branch](https://github.com/openzfs/zfs/commits/zfs-2.1.15-staging/) and will be part of 2.1.15.

**Comment by mmatuska** [comment]
Please backport https://github.com/openzfs/zfs/commit/07e95b4670dc421ec726a2b4efa97a22fe572005 (https://github.com/openzfs/zfs/pull/15716), it fixes FreeBSD userspace build after https://github.com/openzfs/zfs/pull/15662
This is the same for 2.1.x

**Comment by tonyhutter** [comment]
@mmatuska sorry I missed that one!  I included it in my latest push.

**Review by behlendorf — APPROVED** [review]

**Pull request merged**
