### PR TITLE
config: Linux 5.18: detect 4-argument `bio_alloc()`, genhd.h removal

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29/builds/44753/steps/shell_1/logs/make:
```
In file included from ./include/linux/umh.h:4:0,
                 from ./include/linux/kmod.h:9,
                 from ./include/linux/module.h:17,
                 from ./include/zfs/os/linux/spl/sys/atomic.h:27,
                 from ./include/zfs/sys/zfs_context.h:45,
                 from fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:29:
fs/zfs/zfs/../os/linux/zfs/vdev_disk.c: In function ‘__vdev_disk_physio’:
./include/linux/gfp.h:329:18: warning: passing argument 1 of ‘bio_alloc’ makes pointer from integer without a cast [-Wint-conversion]
 #define GFP_NOIO (__GFP_RECLAIM)
                  ^
fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:630:29: note: in expansion of macro ‘GFP_NOIO’
   dr->dr_bio[i] = bio_alloc(GFP_NOIO, bio_max_segs(
                             ^~~~~~~~
In file included from ./include/linux/blkdev.h:17:0,
                 from ./include/zfs/os/linux/spl/sys/uio.h:30,
                 from ./include/zfs/os/linux/spl/sys/sunddi.h:28,
                 from ./include/zfs/sys/zfs_context.h:68,
                 from fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:29:
./include/linux/bio.h:423:27: note: expected ‘struct block_device *’ but argument is of type ‘unsigned int’
 static inline struct bio *bio_alloc(struct block_device *bdev,
                           ^~~~~~~~~
fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:630:19: error: too few arguments to function ‘bio_alloc’
   dr->dr_bio[i] = bio_alloc(GFP_NOIO, bio_max_segs(
                   ^~~~~~~~~
In file included from ./include/linux/blkdev.h:17:0,
                 from ./include/zfs/os/linux/spl/sys/uio.h:30,
                 from ./include/zfs/os/linux/spl/sys/sunddi.h:28,
                 from ./include/zfs/sys/zfs_context.h:68,
                 from fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:29:
./include/linux/bio.h:423:27: note: declared here
 static inline struct bio *bio_alloc(struct block_device *bdev,
                           ^~~~~~~~~
In file included from ./include/linux/umh.h:4:0,
                 from ./include/linux/kmod.h:9,
                 from ./include/linux/module.h:17,
                 from ./include/zfs/os/linux/spl/sys/atomic.h:27,
                 from ./include/zfs/sys/zfs_context.h:45,
                 from fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:29:
fs/zfs/zfs/../os/linux/zfs/vdev_disk.c: In function ‘vdev_disk_io_flush’:
./include/linux/gfp.h:329:18: warning: passing argument 1 of ‘bio_alloc’ makes pointer from integer without a cast [-Wint-conversion]
 #define GFP_NOIO (__GFP_RECLAIM)
                  ^
fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:709:18: note: in expansion of macro ‘GFP_NOIO’
  bio = bio_alloc(GFP_NOIO, 0);
                  ^~~~~~~~
In file included from ./include/linux/blkdev.h:17:0,
                 from ./include/zfs/os/linux/spl/sys/uio.h:30,
                 from ./include/zfs/os/linux/spl/sys/sunddi.h:28,
                 from ./include/zfs/sys/zfs_context.h:68,
                 from fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:29:
./include/linux/bio.h:423:27: note: expected ‘struct block_device *’ but argument is of type ‘unsigned int’
 static inline struct bio *bio_alloc(struct block_device *bdev,
                           ^~~~~~~~~
fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:709:8: error: too few arguments to function ‘bio_alloc’
  bio = bio_alloc(GFP_NOIO, 0);
        ^~~~~~~~~
In file included from ./include/linux/blkdev.h:17:0,
                 from ./include/zfs/os/linux/spl/sys/uio.h:30,
                 from ./include/zfs/os/linux/spl/sys/sunddi.h:28,
                 from ./include/zfs/sys/zfs_context.h:68,
                 from fs/zfs/zfs/../os/linux/zfs/vdev_disk.c:29:
./include/linux/bio.h:423:27: note: declared here
 static inline struct bio *bio_alloc(struct block_device *bdev,
                           ^~~~~~~~~
scripts/Makefile.build:288: recipe for target 'fs/zfs/zfs/../os/linux/zfs/vdev_disk.o' failed
make[3]: *** [fs/zfs/zfs/../os/linux/zfs/vdev_disk.o] Error 1
scripts/Makefile.build:550: recipe for target 'fs/zfs/zfs' failed
make[2]: *** [fs/zfs/zfs] Error 2
scripts/Makefile.build:550: recipe for target 'fs/zfs' failed
make[1]: *** [fs/zfs] Error 2
Makefile:1831: recipe for target 'fs' failed
make: *** [fs] Error 2
make: *** Waiting for unfinished jobs....
```

### Description
In 07888c665b405b1cd3577ddebfeb74f4717a84c4 ("block: pass a block_device and opf to bio_alloc")
```c
bio_alloc(gfp_t gfp_mask, unsigned short nr_iovecs)
```
became
```c
bio_alloc(struct block_device *bdev, unsigned short nr_vecs, unsigned int opf, gfp_t gfp_mask)
```
and
> NULL/0 can be passed, both for the
> passthrough case on a raw request_queue and to temporarily avoid
> refactoring some nasty code.

### How Has This Been Tested?
Not.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – none apply
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
hm, oddly, the CI log now says
```
fs/zfs/zfs/../os/linux/zfs/zvol_os.c: In function ‘zvol_os_create_minor’:
fs/zfs/zfs/../os/linux/zfs/zvol_os.c:1116:3: warning: ignoring return value of ‘add_disk’, declared with attribute warn_unused_result [-Wunused-result]
   add_disk(zv->zv_zso->zvo_disk);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
but the code in question is
```c
#ifdef HAVE_ADD_DISK_RET
		error = add_disk(zv->zv_zso->zvo_disk);
#else
		add_disk(zv->zv_zso->zvo_disk);
#endif
```
and the kernel header is 
```
include/linux/blkdev.h:static inline int __must_check add_disk(struct gendisk *disk)
```
so?

**Comment by nabijaczleweli** [comment]
Ah:
```
commit 322cbb50de711814c42fb088f6d31901502c711a
Author: Christoph Hellwig <hch@lst.de>
Date:   Mon Jan 24 10:39:13 2022 +0100

    block: remove genhd.h

    There is no good reason to keep genhd.h separate from the main blkdev.h
    header that includes it.  So fold the contents of genhd.h into blkdev.h
    and remove genhd.h entirely.
```
included

**Comment by nabijaczleweli** [comment]
Yeah, this is all for today's merge window it seems.

**Review by behlendorf — APPROVED** [review]
Thanks for the quick patch for these kernel changes.

**Review by tonyhutter — APPROVED** [review]

**Pull request closed without merging**
