### PR TITLE
zed: Remove dead code from statechange-led.sh

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Fixes: #11934

### Description
`statechange-led.sh` calls `process_pool()` if either `$ZEVENT_VDEV_ENC_SYSFS_PATH` or `$ZEVENT_VDEV_STATE_STR` are not set by zed.  That should never happen, and thus `process_pool()` will never get called.  Furthermore, `process_pool()` is
totally broken (#11934).  This patch removes `process_pool()`.

### How Has This Been Tested?
Ran `zpool offline -f <tank> <vdev>` and saw the fault LED go on.  Ran `zpool clear <pool>` and saw fault LED go off.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Are you sure? This script is linked from `pool_import-led.sh`, `vdev_attach-led.sh`, and `vdev_clear-led.sh`, and these two 
```
$ git grep ESC_ZFS_VDEV_ATTACH
include/sys/sysevent/eventdefs.h:#define        ESC_ZFS_VDEV_ATTACH             "vdev_attach"
module/zfs/spa.c:       spa_event_notify(spa, newvd, NULL, ESC_ZFS_VDEV_ATTACH);
$ git grep ESC_ZFS_VDEV_CLEAR
include/sys/fs/zfs.h: * ESC_ZFS_VDEV_CLEAR
include/sys/sysevent/eventdefs.h:#define        ESC_ZFS_VDEV_CLEAR              "vdev_clear"
module/zfs/vdev.c:              spa_event_notify(spa, vd, NULL, ESC_ZFS_VDEV_CLEAR);
```
pass the vdev, but
```
$ git grep ESC_ZFS_POOL_IMPORT
include/sys/sysevent/eventdefs.h:#define        ESC_ZFS_POOL_IMPORT             "pool_import"
module/zfs/spa.c:               spa_event_notify(spa, NULL, NULL, ESC_ZFS_POOL_IMPORT);
module/zfs/spa.c:       spa_event_notify(spa, NULL, NULL, ESC_ZFS_POOL_IMPORT);
```
does not.

By necessity, then, in `zfs_event_create()`, `if (vd) {`, and, hence, 
```c
VERIFY0(nvlist_add_uint64(resource,
    FM_EREPORT_PAYLOAD_ZFS_VDEV_STATE, vd->vdev_state));
// ...
if (vd->vdev_enc_sysfs_path != NULL)
	VERIFY0(nvlist_add_string(resource,
	    FM_EREPORT_PAYLOAD_ZFS_VDEV_ENC_SYSFS_PATH,
	    vd->vdev_enc_sysfs_path));
```
are only hit on those two events, as indicated in point 2. in the script header (I would comment there, but this proves impossible for GitHub).

So this would break LED updates on pool import (which I don't see a test for in the How Was This Tested sexion).

**Comment by tonyhutter** [comment]
@nabijaczleweli I forgot about `pool_import-led.sh`, thanks for pointing that out.  Yea, you're probably right that it's not going to work.   There is a `zpool status -c fault_led` that might help for those case.  Let me look into that.

**Comment by nabijaczleweli** [comment]
That already does what my patch in #11935 does, except without writing the path, which you'll find is rather inadequate.

**Comment by tonyhutter** [comment]
Yep, closing in favor of: https://github.com/openzfs/zfs/pull/11935

**Pull request closed without merging**
