### PR TITLE
Silence used-uninitialized warning

### PR DESCRIPTION
**Pull request by lundman**
In the default: case.

clang compilation stop due to warning.

### Motivation and Context

Removes a warning.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
Weird, why doesn't the __NORETURN attribute on panic() prevent this? 🤔

**Comment by lundman** [comment]
panic?

**Comment by freqlabs** [comment]
Oh I see, unused must be the key there. That's a weird warning.

**Comment by lundman** [comment]
Hmm we probably don't have a __NORETURN on panic, let me try that too

**Comment by lundman** [comment]
Sweet, not needed

**Pull request closed without merging**
