### PR TITLE
Added test for being able to read various variants of zstd

### PR DESCRIPTION
**Pull request by rincebrain**
As detailed in #12022 and #12008, it turns out the current zstd implementation
is quite nonportable, and results in various configurations of ondisk header
that only each platform can read.

So I've added a test which contains a dataset with a file written by
Linux/x86_64, and one written by FBSD/ppc64.

~~(Note that **for obvious reasons, this PR will currently always fail the testbots if I implemented it correctly.**)~~ Nah, #12022 landed.

### Motivation and Context
#12022

### Description
Added a test, compression/compress_zstd_bswap, which untars a premade sparse pool file containing 2 datasets, with different "variants" of zstd encoding used on the single file on each.

It then tries copying the files off of each dataset and dies if any of them error out.

I also added it to the "sanity" runfile.

### How Has This Been Tested?
I ran it on an otherwise unmodified git master-running system, verified that it successfully copied the x86_64 file and failed the test when it EIOed on the ppc64_fbsd file.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rincebrain** [comment]
Well, the improbable existence of the third byte layout kept bothering me, so I tried to reproduce it with vanilla(...plus the trivial patch for sparc64) git, and found that Linux/sparc64, Linux/ppc64, and FBSD/ppc64 wrote identical encodings, so I'm forced to conclude I accidentally generated the Linux/sparc64 dataset with one of my WIP patchsets that encoded things wrong.

**Comment by rincebrain** [comment]
Well, #12022 got merged, so...

**Comment by behlendorf** [comment]
Thanks for to reminder, this should be good but can you rebase it on master so we can get a fresh CI run.

**Review by behlendorf — APPROVED** [review]

**Comment by rincebrain** [comment]
Sure, off it goes.

**Review by jwk404 — APPROVED** [review]

**Pull request merged**
