### PR TITLE
Accumulated fixes for 5.10 kernel-introduced build breakages

### PR DESCRIPTION
**Pull request by ckane**
### Motivation and Context
The latest pulls ahead of the Linux 5.10 release cycle introduced some API changes that break the build. In particular `check_disk_change()` and `revalidate_disk()` have been removed, and the "count" variable for the `percpu_ref` data structure has now been moved into a child data structure of type `percpu_ref_data`.

### Description
1. I have replaced `revalidate_disk()` with `revalidate_disk_size()` where the former is unavailable, as the context in which it is called within the driver suggests that the latter is the appropriate function to call.
2. `check_disk_change()` was a combination of checking for the change and also forcing revalidation of the device. The new preferred function is `bdev_check_media_change()` which does the check, but doesn't force a revalidation, which is now left up to the caller if it wants to. To preserve the old behavior, I have created a wrapper function when `check_disk_change()` doesn't exist that will call `bdev_check_media_change()` and then also perform the revalidate call before returning. It may be worth revisiting whether this behavior is needed in all cases where the code is used.
3. The `vdev_blkg_tryget()` function implements a local version of function calls that are implemented in GPL'd Linux code. The API changes break our version, and the solution to address this was just to switch `ref->count` to using `ref->data->count` instead. The underlying change helps reduce memory usage where local copies of `struct percpu_ref` are created, so that the underlying metadata only links to a single instance, which also now remains consistent across all copies of the `struct percpu_ref` instance.

### How Has This Been Tested?

So far I have compiled on 5.10 (Linus' tree), 5.9.0, and 5.8.14 and the build worked fine. I have not yet run-time tested this version of the module, which will take some more time to do. I wanted to get the PR up here so that all the build/test automation you've got can take a crack at it in parallel with me testing it.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [X] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [X] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [X] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [X] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ckane** [comment]
Rebased this with `master` on 2020-10-27 in to determine if the buildbot test errors are affected by other code in master or not. The ZFS tests mostly work for me when run in a VM, but there are a handful that seem to be failing which seem also outside of the scope of these changes, and I am unsure if these were introduced by my changes or not. Going to do a zfstest comparison between "old kernel w/ 2020-10-27 master" and "new kernel w/ my changes" to see what the test suite says.

**Comment by ckane** [comment]
Running `zfs-tests.sh` with & without my patches produced the following failures. Since this indicates that there's no regressions and the code responsible for test failures is outside of these patches, I'm going to mark this as passing the tests in my VM environment:
```
Tests with results other than PASS that are unexpected:
    FAIL casenorm/insensitive_formd_delete (expected PASS)
    FAIL casenorm/insensitive_formd_lookup (expected PASS)
    FAIL casenorm/insensitive_none_delete (expected PASS)
    FAIL casenorm/insensitive_none_lookup (expected PASS)
    FAIL casenorm/mixed_none_delete (expected PASS)
    FAIL casenorm/mixed_none_lookup (expected PASS)
    FAIL casenorm/sensitive_none_delete (expected PASS)
    FAIL casenorm/sensitive_none_lookup (expected PASS)
    FAIL cli_root/zfs_share/zfs_share_005_pos (expected PASS)
    FAIL cli_root/zpool_events/zpool_events_duplicates (expected PASS)
    FAIL delegate/zfs_allow_001_pos (expected PASS)
    FAIL delegate/zfs_allow_002_pos (expected PASS)
    FAIL delegate/zfs_allow_006_pos (expected PASS)
    FAIL delegate/zfs_allow_007_pos (expected PASS)
    FAIL delegate/zfs_allow_010_pos (expected PASS)
    FAIL slog/slog_replay_fs_001 (expected PASS)
    FAIL xattr/xattr_004_pos (expected PASS)
```

**Comment by ckane** [comment]
As no new functionality is added and no behavioral changes are expected, I checked the "added tests" box, but there were no new tests to add. Similarly, the documentation in the source code I added should be sufficient documentation for these changes.

**Comment by ckane** [comment]
Ok I'm running these changes on main now (patched against the 2.0.0rc4 sources)

**Comment by Ornias1993** [comment]
@behlendorf and @ahrens I think this one requires a review and removal of the WIP tag.

@ckane You might at least squash the style fixes (or even better: cherrypick and squash them into their respective commits)

**Review by behlendorf — APPROVED** [review]
@ckane thanks for putting together these fixes.  They look good and work correctly for me with the latest mainline kernel.  I'll squash them accordingly when merging.

**Comment by behlendorf** [comment]
Merged and squashed.

**Comment by tonyhutter** [comment]
These would be nice to have backported to the `zfs-0.8.6-staging` branch.   If someone is interested in doing that, please open a PR against that branch, and we'll try to pull it in.

**Pull request closed without merging**
