### PR TITLE
libshare cleanup, NFS path escaping

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
The way libshare handled dispatch was honestly so weird. Also, the libzfs protocol that handles every function as _nfs and _smb is kinda insane and won't scale so I replaced it.

Also, #13153 and #13324

### Description
See individual commit messages.

~~Currently on top of #13259.~~

### How Has This Been Tested?
These were made:
```
  1 # !!! DO NOT EDIT THIS FILE MANUALLY !!!
  2
  3 /mnt/filling/machine/1200-S121 *(sec=sys,rw,no_subtree_check,mountpoint,crossmnt,no_subtree_check,no_root_squash,async)
  4 /spac\040ed\040out *(sec=sys,rw,no_subtree_check,mountpoint,crossmnt)
  5 /spaced\040out *(sec=sys,rw,no_subtree_check,mountpoint,crossmnt)
  6 /hupa\011#hehe\040\134\134epsko\040\134053\040\040\015 *(sec=sys,rw,no_subtree_check,mountpoint,crossmnt)
  7 /hupa\011#hehe\040\134\134epsko\040\134053\040\040\015\040достопримечательности *(sec=sys,rw,no_subtree_check,mountpoint,crossmnt)
```

From these:
```
nabijaczleweli@tarta:~/store/code/zfs$ sudo cmd/zfs/zfs create 'tarta-zoot/spaced out' -o sharenfs=on
nabijaczleweli@tarta:~/store/code/zfs$ sudo cmd/zfs/zfs create 'tarta-zoot/spa ced out' -o sharenfs=on  -o mountpoint='/hupa    #hehe \\epsko \053  ^M'
nabijaczleweli@tarta:~/store/code/zfs$ sudo cmd/zfs/zfs create 'tarta-zoot/spa ced out  ' -o sharenfs=on  -o mountpoint='/hupa  #hehe \\epsko \053  ^M достопримечательности'
```

And then consequently removed as the datasets were deleted.

They were also exported fine. Well, mostly. [Turns out `exportfs` recursively parses backslash escapes.](https://twitter.com/nabijaczleweli/status/1498358452795715588) – reported upstream [here](https://lore.kernel.org/linux-nfs/20220228193235.2g2uvf7fphj4jdy5@tarta.nabijaczleweli.xyz/T/)

I had a different way for parsing:
```c
static int
nfs_process_exports(const char *exports, const char *mountpoint,
    boolean_t (*cbk)(void *userdata, char *line, boolean_t found_mountpoint),
    void *userdata)
{
	int error = SA_OK;
	boolean_t cont = B_TRUE;

	FILE *oldfp = fopen(exports, "re");
	if (oldfp != NULL) {
		char *buf = NULL, *sep, *dename = NULL;
		size_t buflen = 0, mplen = strlen(mountpoint);

		while (cont && getline(&buf, &buflen, oldfp) != -1) {
			if (buf[0] == '\n' || buf[0] == '#')
				continue;

			boolean_t found = B_FALSE;
			if ((sep = strpbrk(buf, " \t\n")) != NULL) {
				size_t rawlen = sep - buf;
				if (rawlen >= mplen) {
					char *nm = buf;
					if (memchr(buf, '\\', rawlen)) {
						nm = dename = realloc(dename, rawlen);
						if (!dename) {
							error = SA_NO_MEMORY;
							goto err;
						}
						size_t outlen = 0;
						for (char *c = buf, *oc = dename; c < buf + rawlen; ++c, ++outlen)
							if (*c == '\\' && c + 3 < buf + rawlen && isdigit(c[1]) && isdigit(c[2]) && isdigit(c[3])) {
								*oc = c[1] - '0';
								*oc = (*oc << 3) | (c[2] - '0');
								*oc = (*oc << 3) | (c[3] - '0');
								++oc;
								c += 3;
							} else
								*oc++ = *c;
						rawlen = outlen;
					}
					fprintf(stderr, "%zu == %zu; cmp(%.*s, %.*s) = %d\n", rawlen, mplen, (int)rawlen, nm, (int)mplen, mountpoint, strncmp(nm, mountpoint, mplen));
					found = rawlen == mplen && strncmp(nm, mountpoint, mplen) == 0;
				}
			}
			cont = cbk(userdata, buf, found);
		}
err:
		free(buf);
		free(dename);

		if (ferror(oldfp) != 0)
			error = ferror(oldfp);

		if (fclose(oldfp) != 0) {
			fprintf(stderr, "Unable to close file %s: %s\n",
			    exports, strerror(errno));
			error = error != SA_OK ? error : SA_SYSTEM_ERR;
		}
	}

	return (error);
}
```
but it's more fragile (but, hardly), slower, and worse than just doing it this way. If we just agree on the escaped charset and stick to it, it won't be a problem.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – ~~TODO~~ yeah. got carried away a bit, too
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
ABI summary:
```
11 Removed functions:

  [D] 'function void zfs_commit_nfs_shares()'    {zfs_commit_nfs_shares}
  [D] 'function void zfs_commit_shares(const char*)'    {zfs_commit_shares}
  [D] 'function void zfs_commit_smb_shares()'    {zfs_commit_smb_shares}
  [D] 'function boolean_t zfs_is_shared_nfs(zfs_handle_t*, char**)'    {zfs_is_shared_nfs}
  [D] 'function boolean_t zfs_is_shared_smb(zfs_handle_t*, char**)'    {zfs_is_shared_smb}
  [D] 'function int zfs_share_nfs(zfs_handle_t*)'    {zfs_share_nfs}
  [D] 'function int zfs_share_smb(zfs_handle_t*)'    {zfs_share_smb}
  [D] 'function int zfs_unshare_nfs(zfs_handle_t*, const char*)'    {zfs_unshare_nfs}
  [D] 'function int zfs_unshare_smb(zfs_handle_t*, const char*)'    {zfs_unshare_smb}
  [D] 'function int zfs_unshareall_nfs(zfs_handle_t*)'    {zfs_unshareall_nfs}
  [D] 'function int zfs_unshareall_smb(zfs_handle_t*)'    {zfs_unshareall_smb}

5 Added functions:

  [A] 'function void zfs_commit_shares_proto(const sa_protocol*)'    {zfs_commit_shares_proto}
  [A] 'function boolean_t zfs_is_shared_proto(zfs_handle_t*, char**, sa_protocol)'    {zfs_is_shared_proto}
  [A] 'function int zfs_share_proto(zfs_handle_t*, const sa_protocol*)'    {zfs_share_proto}
  [A] 'function int zfs_unshare_proto(zfs_handle_t*, const char*, const sa_protocol*)'    {zfs_unshare_proto}
  [A] 'function int zfs_unshareall_proto(zfs_handle_t*, const sa_protocol*)'    {zfs_unshareall_proto}

6 functions with some indirect sub-type change:

  [C] 'function void sa_commit_shares(const char*)' at libshare.c:89:1 has some indirect sub-type changes:
    parameter 1 of type 'const char*' changed:
      entity changed from 'const char*' to 'enum sa_protocol' at libshare.h:76:1
      type size changed from 64 to 32 (in bits)
      type alignment changed from 0 to 32

  [C] 'function int sa_disable_share(const char*, char*)' at libshare.c:69:1 has some indirect sub-type changes:
    parameter 2 of type 'char*' changed:
      entity changed from 'char*' to 'enum sa_protocol' at libshare.h:76:1
      type size changed from 64 to 32 (in bits)
      type alignment changed from 0 to 32

  [C] 'function int sa_enable_share(const char*, const char*, const char*, char*)' at libshare.c:57:1 has some indirect sub-type changes:
    parameter 4 of type 'char*' changed:
      entity changed from 'char*' to 'enum sa_protocol' at libshare.h:76:1
      type size changed from 64 to 32 (in bits)
      type alignment changed from 0 to 32

  [C] 'function boolean_t sa_is_shared(const char*, char*)' at libshare.c:79:1 has some indirect sub-type changes:
    parameter 2 of type 'char*' changed:
      entity changed from 'char*' to 'enum sa_protocol' at libshare.h:76:1
      type size changed from 64 to 32 (in bits)
      type alignment changed from 0 to 32

  [C] 'function int sa_validate_shareopts(char*, char*)' at libshare.c:98:1 has some indirect sub-type changes:
    parameter 2 of type 'char*' changed:
      entity changed from 'char*' to 'enum sa_protocol' at libshare.h:76:1
      type size changed from 64 to 32 (in bits)
      type alignment changed from 0 to 32

  [C] 'function int zfs_unshareall_bytype(zfs_handle_t*, const char*, const char*)' at libzfs_mount.c:888:1 has some indirect sub-type changes:
    parameter 3 of type 'const char*' changed:
      in pointed to type 'const char':
        'const char' changed to 'const sa_protocol'

1 Added variable:

  [A] 'const char* const sa_protocol_names[2]'    {sa_protocol_names}
```

**Comment by nabijaczleweli** [comment]
During the porting process I've followed the style by adding ones that take a protocol list with `_proto()` at the end; however, they *all* do now, so in `s?: libzfs share functions: _proto() -> nothing` I've stripped it off again, and, looking at the total diff on GitHub, it ends up pretty slick, so I think we should squish it in (and just bump abiver as normal to prevent problems from same function names but different arguments).

For an overview of sum API changes see libzfs.h and libshare.h.

**Comment by nabijaczleweli** [comment]
Oh, it seems i hastily misread the manual; there's just no way to escape share paths on FreeBSD :)  That being said, I think we should still try (which is the case in the current code) since the errors make much more sense:
```
nab@freebsd:~ % sudo mountd -rS /etc/zfs/exports
Mar  5 22:54:19 freebsd mountd[972]: bad exports list line '/testpool/spaced': symbolic link in export path or statfs failed
```
vs
``
nab@freebsd:~ % sudo mountd -rS /etc/zfs/exports
Mar  5 22:54:49 freebsd mountd[979]: bad exports list line '/testpool/spaced\040out': symbolic link in export path or statfs failed
```
and we're not gonna pollute other lines for shares with newlines in the path.

**Comment by nabijaczleweli** [comment]
And on Illumos (this is Tribblix, uh, 5.11/-m25):
image
image

it..just doesn't work. `zfs share` shares via share(1M) and yields `/literal path	-	nfs	rw` in /e/d/st (which is sharefs? apparently), but share(1M).. lists it as `/literal`? and mounting it uh, yeah lol
image

I was hoping to rig comprehensive tests for all platforms (now that I've, uh, enabled us actually.. running them? on all platforms), but, well.

**Comment by nabijaczleweli** [comment]
> 24 days ago
> 19 days ago

lads, i've spent the past 3(?) weeks in the mines. and lost the last week entirely, i genuinely thought i posted #13224 like this monday. *but* i found #13215 (activated herein) and #13250 (fixed herein) and cleaned up the test suite so it's not a horrible eyesore (incl. building the helpers together, so it parallelises) – my personal recommendation is to compare trunk `get_conf_section` from tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps.kshlib:
https://github.com/openzfs/zfs/blob/427fad7f247d8ef0975e6038587d954bd771fa63/tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps.kshlib#L20-L41
with what it's trying to say:
```ksh
function get_conf_section # regex conf
{
        typeset regex="$1"
        typeset conf="$2"

        awk -v r="$1" '$0 ~ r, 0 {if($0 ~ r) next; if(/children\[/) exit; print}' "$conf"
}
```

I've tortured this in a loop in a mostly-finalised form for a couple days now (first on FreeBSD 13-STABLE, then also on sid amd64, asan+ubsan), and, unless something Exciting happens on CI, I think the non-libshare bit is ready to go as-is. The libshare bit needs to get the `s:` commit squashed but is otherwise tested more than ever before on more platforms than ever before (i.e. not just Linux).

@behlendorf would you like to cleave this? I tried to make it cleavable somewhere along the "tests: standardise on no-arg uname with *) case for illumos" case with, I think, one hold-back of the unshare_008 adition, but, y'know

**Comment by nabijaczleweli** [comment]
Hm. It seems that all is well, except, on all linux buildds (and GHA 18.04),
```
Tests with results other than PASS that are unexpected:
    FAIL cli_root/zfs/zfs_002_pos (expected PASS)
    FAIL cli_root/zpool/zpool_002_pos (expected PASS)
```
which is weird since I made core collection.. more reliable. Well, maybe closer to "good" since it should be as reliable as it was but also correctly clean up system state afterward. Works on sid, oddly, so hm.

FreeBSD trunk fails with
```
Tests with results other than PASS that are unexpected:
    FAIL casenorm/mixed_create_failure (expected PASS)
```
which is as-expected. Maybe it wants to get marked as known?

**Comment by nabijaczleweli** [comment]
Oh, %f coredump pattern was added in 5.8+; %e works, though; lessee.

**Comment by nabijaczleweli** [comment]
An unprecedented success, everything's green. And in half the time (4 hours) it takes my asan+ubsan builds (8 hours).

**Comment by nabijaczleweli** [comment]
With #13259 in, this should be g2g

**Comment by nabijaczleweli** [comment]
2-week bump!

**Comment by nabijaczleweli** [comment]
Once more.

**Review by behlendorf — APPROVED** [review]
This all looks reasonable to me, although it does need a rebase and updated ABI files.

@don-brady @grwilson @jwk404 my understanding is you guys rely pretty heavily on this functionality, so if you have any feedback please comment.  I'd like to merge this next week if possible, so please take a look before then if possible.

**Comment by nabijaczleweli** [comment]
Rebased

**Pull request closed without merging**
