### PR TITLE
Misc zevent improvements

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

Fixing some issues that were identified while looking into zevent handling.

### Description

ratelimit_dropped isn't protected by a lock. We must atomically read and clear the value.

Use a fixed default value for zfs_zevent_len_max rather than scaling by CPUs. The lower bound was too low and the upper bound was too high. 512 is a reasonable default value.

### How Has This Been Tested?

ZTS sanity

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by behlendorf — APPROVED** [review]

**Comment by h1z1** [comment]
@freqlabs did you test clearing thousands of events as part of this?  Ran into an issue last week where a system was pausing for some reason.  Turned out a user set zfs_deadman_ziotime_ms  _way_ too low (10ms), which was spamming events.   Clearing them (60k+) alone completely froze the host.

**Comment by freqlabs** [comment]
I'm not sure how you would have thousands of events queued when this sets the max queue length to 512?

**Comment by h1z1** [comment]
It shouldn't, question was did you run into that as well and would it be resolved along with this change.   Spose either way events shouldn't cause the freezing.

**Comment by freqlabs** [comment]
No I didn't test clearing thousands of events. I don't think these changes will help whatever is going on there, but it will help ensure the reported number of dropped events due to rate limiting is accurate.

**Pull request closed without merging**
