### PR TITLE
Linux: Set spl_kmem_cache_slab_limit when page size !4K

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

It was observed on systems using a 64k page size that running
`zpool scrub` could exhaust memory and trigger the OOM killer.
This should never be possible.

Issues #11429 #11574 #12150

### Description

For small objects the kernel's slab implemention is very fast and
space efficient. However, as the allocation size increases to
require multiple pages performance suffers. The SPL kmem cache
allocator was designed to better handle these large allocation
sizes. Therefore, on Linux the kmem_cache_* compatibility wrappers
prefer to use the kernel's slab allocator for small objects and
the custom SPL kmem cache allocator for larger objects.

This logic was effectively disabled for all architectures using
a non-4K page size which caused all kmem caches to only use the
SPL implementation. Functionally this is fine, but the SPL code
which calculates the target number of objects per-slab does not
take in to account that __vmalloc() always returns page-aligned
memory. This can result in a massive amount of wasted space when
allocating tiny objects on a platform using large pages (64k).

To resolve this issue we set the spl_kmem_cache_slab_limit cutoff
to PAGE_SIZE on systems using larger pages. Since 16,384 bytes
was experimentally determined to yield the best performance on
4K page systems this is used as the cutoff. This means on 4K
page systems there is no functional change.

This particular change does not attempt to update the logic used
to calculate the optimal number of pages per slab. This remains
an issue which should be addressed in a future change.

### How Has This Been Tested?

Locally compiled but it has not yet been tested on a system
using a large page size.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by AttilaFueloep** [comment]
Wouldn't it be better to make this a runtime selection rather than a compile time one? AFAIK AArch64 Linux supports 4k and 16K pages as well.

**Comment by behlendorf** [comment]
@AttilaFueloep 4k, 16k, and 64k pages are all supported for aarch64, but a specific page size needs to be selected when compiling the kernel.  So there shouldn't be an issue setting this at compile time.

```
    CONFIG_<ARCH>_4K_PAGES
    CONFIG_<ARCH>_16K_PAGES
    CONFIG_<ARCH>_64K_PAGES
```

**Comment by AttilaFueloep** [comment]
Yes, but what happens if you compile the module on a box with a 4K page sized kernel and then load it on a box with a 64k kernel? Then there is a discrepancy between the compile time and the running on page sizes. Or am I missing something here?

**Comment by AttilaFueloep** [comment]
I think we should at least detect page size mismatches and refuse to load the module if so.

**Comment by omarkilani** [comment]
@AttilaFueloep nothing bad should happen because the "default" 16k value works fine on the 64k page size kernel:

https://github.com/openzfs/zfs/issues/12150#issuecomment-850754587

**Comment by omarkilani** [comment]
> I think we should at least detect page size mismatches and refuse to load the module if so.

Maybe it could just be some printk warning? Like...

```
ZFS: Loaded module v2.1.0-rc6, ZFS pool version 5000, ZFS filesystem version 5
ZFS: Module built for kernel with PAGE_SIZE page size, but running on a DYNAMIC_PAGE_SIZE page size kernel. You may need to adjust spl_kmem_cache_slab_limit or use a module compiled for DYNAMIC_PAGE_SIZE page size.
```

If the only thing affected is spl_kmem_cache_slab_limit...

**Comment by behlendorf** [comment]
> I think we should at least detect page size mismatches and refuse to load the module if so.

I believe this should already be the case even without additional changes.  Though I'm not having much luck finding any documentation to confirm this.

**Comment by behlendorf** [comment]
@omarkilani thanks for the testing, I opted for setting the cutoff at the page size because the kernel's slab implementation(s) should allocate a single page per slab.  As long as the object size is less than the page size I'd expect the kernel's slab to be both faster and more space efficient since it's highly optimized.  Your testing seems to back that up.  Where that story changes is a bit when allocations start requiring multiple pages.

**Comment by AttilaFueloep** [comment]
> I believe this should already be the case even without additional changes. Though I'm not having much luck finding any documentation to confirm this.

Yeah, I couldn't find any documentation either and even grepping the Linux and kmod sources didn't brought up something revealing. Unfortunately I don't have a box supporting multiple page sizes to test this on. So I'll take this for granted,  it seems to be quite a corner case anyway. 

As a side note, not directly related to your change, the mixed usages of `PAGESIZE` and `PAGE_SIZE` I see in the sources puzzles me a bit. Skimming the sources my understanding is that `PAGESIZE` is defined as `PAGE_SIZE` if in [kernel space](https://github.com/openzfs/zfs/blob/45516b4a0a1908299f2f88aa4ef8c65f95abecb3/include/os/linux/spl/sys/sysmacros.h#L108) and as `sysconf(_SC_PAGESIZE)` if in [user space](https://github.com/openzfs/zfs/blob/45516b4a0a1908299f2f88aa4ef8c65f95abecb3/lib/libspl/include/os/linux/sys/param.h#L65) (`ztest`).  If that's true, wouldn't using `PAGE_SIZE` outside of `#ifdef _KERNEL` blocks defeat that approach and  shouldn't  `PAGESIZE` always be preferred over `PAGE_SIZE`? Further I don't see the same handling for `PAGE_SHIFT` in user space outside of [abd_os.c](https://github.com/openzfs/zfs/blob/45516b4a0a1908299f2f88aa4ef8c65f95abecb3/module/os/linux/zfs/abd_os.c#L490). I'm not sure if all of this could lead to some obscure `ztest` failures in the page size mismatch case.

**Comment by behlendorf** [comment]
> the mixed usages of PAGESIZE and PAGE_SIZE I see in the sources puzzles me a bit.

The mixed usages comes from the fact that `PAGESIZE` is what was used on illumos, and so you're right that's the portable interface which should be used in all the common code.  We could add the same wrappers for `PAGESHIFT` but it turns out there were never any existing consumers in the common code so they never got added.

In the platform specific code (`module/os/<platform>/`) there really isn't any issue with using the native interfaces in the right contexts.  In general, that's what we've tried to do but we don't have a hard and fast rule about it.  In this case I opted for `PAGE_SIZE` since this is platform specific code which is only used by the kernel.

**Comment by AttilaFueloep** [comment]
I see, thanks for the thorough explanation. No reason to change anything then.

**Comment by ahrens** [comment]
@behlendorf 
>  I opted for setting the cutoff at the page size because the kernel's slab implementation(s) should allocate a single page per slab. As long as the object size is less than the page size I'd expect the kernel's slab to be both faster and more space efficient since it's highly optimized.

FYI that isn't true for caches with entries >=256 bytes, at least on PAGESIZE=4K systems:
```
sdb> slabs -o name,entry_size,entries_per_slab
name                        entry_size entries_per_slab
--------------------------- ---------- ----------------
kmalloc-96                          96               42 (1 page per slab)
kmalloc-128                        128               32 (1 page per slab)
kmalloc-192                        192               21 (1 page per slab)
kmalloc-256                        256               32 (2 pages per slab)
kmalloc-512                        512               32 (4 pages per slab)
kmalloc-1k                        1024               32 (8 pages per slab)
kmalloc-2k                        2048               16 (8 pages per slab)
kmalloc-4k                        4096                8 (8 pages per slab)
kmalloc-8k                        8192                4 (8 pages per slab)
```

Given the possibility of fragmentation, this aspect of the kernel's slab implementation seems like a bad design decision to me.

**Comment by behlendorf** [comment]
@ahrens yes, upon re-reading what I wrote I clearly left out more than a few important qualifiers.  Looking at this again, I wonder if it wouldn't be preferable to simply set the cutoff at 16k for all architectures.  Based on @omarkilani's testing any performance impact seems negligible.  Thoughts?

**Comment by omarkilani** [comment]
This is probably a dumb question but how does one run the `slabs -o name,entry_size,entries_per_slab` command?

Googling `sdb` is about as helpful as you'd expect.

**Comment by ahrens** [comment]
@omarkilani `sudo sdb -k`: https://github.com/delphix/sdb

**Comment by omarkilani** [comment]
I spent most of the day rebuilding kernels and dependencies to get `drgn` working and then I realised... I could just `cat /proc/slabinfo`. lol.

```
slabinfo - version: 2.1
# name            <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab>
kmalloc-128k          28     28 131072    4    8
kmalloc-64k          144    144  65536    8    8
kmalloc-32k          272    272  32768   16    8
kmalloc-16k         2944   2944  16384   32    8
kmalloc-8k           608    608   8192   32    4
kmalloc-4k          3072   3072   4096   32    2
kmalloc-2k          3072   3072   2048   32    1
kmalloc-1k         25490  25536   1024   64    1
kmalloc-512        19741  23424    512  128    1
kmalloc-256        20647  21248    256  256    1
kmalloc-128       613203 613376    128  512    1
```

I did some more tests with `pgbench` and `zpool scrub` while monitoring `/proc/slabinfo` at 16k and 64k.

In both cases nothing above `kmalloc-4k` gets used. And that only gets used during a `zpool scrub`. During `pgbench` nothing above `kmalloc-1k` gets used.

`pgbench` averages ~15,500tps at 64k and 15,000tps at 16k.

I ran `pgbench` 10 times under each limit setting and the better performance using 64k is small but reproducible.

IMHO, 16k is probably fine for a default setting if you're worried about fragmentation. I'm not sure it's the "optimal" setting for all workloads, but nothing bad's going to happen and people can just up the limit for Postgres or whatever.

Anything's better than `0` and certain OOM/crash.

**Review by tonynguien — APPROVED** [review]
Change looks good. Thanks for fixing the issue.

**Comment by behlendorf** [comment]
I've gone ahead and updated the PR to always use a 16K cutoff..  This keeps the behavior the same across platforms add should help mitigate any issues we might otherwise end up seeing with fragmentation.

**Review by tonynguien — APPROVED** [review]

**Review by ahrens — APPROVED** [review]

**Pull request merged**
