### PR TITLE
Always enable -Werror, even in non-debug builds

### PR DESCRIPTION
**Pull request by pzakha**
This change sets `-Werror` unconditionally in the build, thus guaranteeing that warnings always trigger errors, regardless of whether this is a debug build or not.

### How Has This Been Tested?
- Checked that the latest code compiles without errors as expected.
- Checked that warnings now trigger errors even when `--with-debug` is not set.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by prakashsurya — APPROVED** [review]
LGTM.

@behlendorf can you comment on why we don't (prior to this change) use `-Werror` always?

**Review by ahrens — APPROVED** [review]

**Comment by behlendorf** [comment]
> can you comment on why we don't (prior to this change) use -Werror always?

Sure.  My concern is that making `-Werror` the default will unnecessarily break the build in some environments.  For example, it's not unheard of for the kernel build system to add another `-W` option to their defaults, or for a new version of `gcc` to change what's include in `-Wall`, or to get new warnings when compiling on different architecture.  All of which would cause the build to needlessly fail and are largely outside our control.  My feeling is it's better to tolerate warnings in non-debug build.  Otherwise we risk breaking existing working systems since many OpenZFS users build from source via DKMS and are not developers.

I understand the desire to make this the default, but I don't think it's a good idea.  Perhaps we could do something else so it's always enabled in your environment but not by default.

**Comment by ahrens** [comment]
@behlendorf Are we building with `-Werror` in the buildbots?

**Comment by behlendorf** [comment]
@ahrens yes they all build with `-Werror`, but that's still really only a handful of test environments.

**Comment by prakashsurya** [comment]
I think those are valid concerns (not controlling the GCC version, and building with DKMS being good example); based on that, I'd be OK closing this and only adopting it downstream.

**Comment by pzakha** [comment]
Closing due to Brian's concerns.

**Pull request closed without merging**
